### ISSUE TITLE
Search support for identifier references (logical references)

### ISSUE THREAD

**Issue by johaneltes** [jamesagnew/hapi-fhir#1001]
I have problems to find Observations based on Subject when the Subject is a logical reference (identifier reference). Does hapi support search expressions for logical references (identifiers)?

**Comment by johaneltes** [comment]
Just learned that DSTU doesn't have a search expression for identifier-based references, which should explain why hapi doesn't support it for DSTU3 either:)

**Comment by patrick-werner** [comment]
searching identifier references works in R4, hasn't been specified in STU3.

**Comment by MattMorgis** [comment]
Has this stopped working? See #2866, I am seeing the same issue.
