### ISSUE TITLE
Bundle constraint bdl-7 is incomplete

### ISSUE THREAD

**Issue by lawley** [jamesagnew/hapi-fhir#1011]
The error message below is produced when validating a batch-response type `Bundle` with resources and no fullUrl values (because they're transient OperationOutcomes). I believe this is because `parent::f:Bundle/f:entry[f:fullUrl/@value=$entry/f:fullUrl/@value` evaluates to true even when the values are "null".

`
[error] in /*:Bundle[namespace-uri()='http://hl7.org/fhir'][1] @ Bundle bdl-7: FullUrl must be unique in a bundle, or else entries with the same fullUrl must have different meta.versionId Test=count(for $entry in f:entry[f:resource] return $entry[count(parent::f:Bundle/f:entry[f:fullUrl/@value=$entry/f:fullUrl/@value and ((not(f:resource/*/f:meta/f:versionId/@value) and not($entry/f:resource/*/f:meta/f:versionId/@value)) or f:resource/*/f:meta/f:versionId/@value=$entry/f:resource/*/f:meta/f:versionId/@value)])!=1])=0
`

**Comment by jamesagnew** [comment]
I believe this should be resolved by #1355. Checking in a test to confirm.
