### ISSUE TITLE
gzip compression needs to be configurable

### ISSUE THREAD

**Issue by joshm-zen** [jamesagnew/hapi-fhir#1014]
Currently, gzip compression is on by default and configuration to disable it is not currently supported.
According to the JPA server documentation, it is optional. This needs to be a configurable option somewhere so that developers can choose whether or not they want that functionality.

**Comment by jamesagnew** [comment]
This is where the GZip happens: https://github.com/jamesagnew/hapi-fhir/blob/32e1feb48459be695629e940b900336d1d02f177/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/BaseHapiFhirDao.java#L1265

**Comment by jamesagnew** [comment]
LIkely a setting in the DaoConfig should be added to set a default

**Comment by deganmee** [comment]
Current code base shows that there is a resourceEncoding setting in DaoConfig with default set to JSONC. There is a setter that allows you to change encoding to JSON.

default set here: https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/DaoConfig.java#L121

I submitted a PR to add JavaDoc to the getter/setter for resourceEncoding in DaoConfig.

If this doesn't address the issue, please clarify the ask here.
