### ISSUE TITLE
_filter parameter not working for different parameters

### ISSUE THREAD

**Issue by anthonys123** [jamesagnew/hapi-fhir#1016]
We need to perform OR queries across different parameters for a resource.  In a Zulip chat below, Grahame Grieve instructed me to use the **_filter** parameter.  Unfortunately, it doesn't work in HAPI.  I've attached a zip file containing a PostgreSQL database for testing.  The following URL returns all 36 Patient resources present in the database instead of zero (none match the query):

http://127.0.0.1:8080/hapi/baseDstu3/Patient?_filter=_id eq 218 or _lastUpdated co 2018-04-26

Zulip chat for reference:

https://chat.fhir.org/#narrow/stream/4-implementers/topic/OR.20queries.20across.20parameters.3F

[postgreSQL_backup_for_OR_issue.zip](https://github.com/jamesagnew/hapi-fhir/files/2143225/postgreSQL_backup_for_OR_issue.zip)

**Comment by jamesagnew** [comment]
_filter is not yet implemented.

Help definitely appreciated.

sent from my phone.

**Comment by anthonys123** [comment]
Thanks for the quick reply James.  Feel free to assign the issue to me and I'll start work on it.

**Comment by jamesagnew** [comment]
Done

**Comment by patrick-werner** [comment]
very nice to see that there is somebody working on getting filters running. @anthonys123 how is the progress on this issue?

**Comment by anthonys123** [comment]
I submitted the PR in December or January.  James indicated to me several weeks ago that it will be merged for the next release.

**Comment by jamesagnew** [comment]
Yup- I'm slowly chipping away at merging this. It's unfortunately such a fundamental set of changes to a fast-changing and core part of HAPI FHIR JPA (the SearchBuilder) that it's a difficult merge. I've pushed my progress up into the public repo here: https://github.com/jamesagnew/hapi-fhir/pull/1220

Definitely intending to land this for 3.8.0
