### ISSUE TITLE
Conversion error /min to /hour

### ISSUE THREAD

**Issue by Al-Pena** [jamesagnew/hapi-fhir#1019]
I tried the ucum utilities to convert some units into others and bumped into a problem when converting "/min" into "/h".
The precision used by Decimal seems to truncate a bit too aggressively: the code below prints 911 instead of 15 * 60 = 900. 
(Not sure if i should report the bug here or on https://github.com/FHIR/Ucum-java ) 
Using ca.uhn.hapi.fhir:hapi-fhir-utilities:3.3.0

To fix this on my end, I quickly changed the Decimal.java class to keep a double as value and not a String. The current tests still pass, the code below returns correctly 900.0 and after some benchmarking, it ran 10times faster. Was there any reason to keep the value as a String with precision ?

    ClassLoader classLoader = getClass().getClassLoader();

    try (InputStream inputStream = classLoader.getResourceAsStream("ucum_essence.xml");
         InputStream bis = new BufferedInputStream(inputStream)) {

        UcumEssenceService ucumService = new UcumEssenceService(bis);
        Decimal result = ucumService.convert(new Decimal("15"), "/min", "/h");
        System.out.println(result.asDecimal()); // Prints 911
    }

As a side note, equals is defined but not with the signature of Object, resulting in Assert.assertEquals failing, nor is hashcode defined

**Comment by patrick-werner** [comment]
The correct place to report the bug would be the UCUM-java project. Feel free to submit the issue there again. As you already have tinkered around the problem you could do a pull request there as well.

**Comment by Al-Pena** [comment]
Ok, reported it at https://github.com/FHIR/Ucum-java/issues/6
I cannot pull request for now though
Thanks
