### ISSUE TITLE
Display name of Patient marital status is not supported

### ISSUE THREAD

**Issue by jacksonjesse** [jamesagnew/hapi-fhir#102]
The only API methods available for setting the `MaritalStatus` of a `Patient` are `setMaritalStatus(MaritalStatusCodesEnum)` and `setMaritalStatus(BoundCodeableConceptDt<MaritalStatusCodesEnum>)`.

Nether of these methods supports addition of the `<display>` element that can be added to a `<coding>` element. The XML I am looking to generate is as follows:
```
<maritalStatus>
    <coding>
        <system value="http://hl7.org/fhir/v3/MaritalStatus"/>
        <code value="M"/>
        <display value="Married"/>
    </coding>
</maritalStatus>
```

**Comment by jamesagnew** [comment]
Hi Jackson,
You can actually add additional content to the CodeableConcept.conding value after setting it using the enum if you need to. After reviewing the documentation on our site, I would say it's pretty weak in this area so I've spent a bit of time beefing it up. Here's a sample showing exactly what you're trying to do (pulled from the rewritten documentation).

      // Set the CodeableConcept's first coding to use the code
      // and codesystem associated with the M value.
      patient.setMaritalStatus(MaritalStatusCodesEnum.M);
      
      // If you need to set other fields (such as the display name) after
      // using the Enum type, you may still do so.
      patient.getMaritalStatus().getCodingFirstRep().setDisplay("Married");
      patient.getMaritalStatus().getCodingFirstRep().setPrimary(true);
      patient.getMaritalStatus().getCodingFirstRep().setVersion("1.0");

**Comment by jacksonjesse** [comment]
Ahh my apologies, had not spotted that one! Thanks for your assistance, can definitely close this one off now given it's entirely possible.
