### ISSUE TITLE
Problem with searching resources

### ISSUE THREAD

**Issue by karkaletsis** [jamesagnew/hapi-fhir#1020]
I am using 3.4.0 version of FHIR Server and I am having some issues with the search operation. I do the following steps
1. Create a resource programmatically 
2. Search for this resource with some criteria
3. The result is empty

In order to make it work I have to go from the UI of JPA Server and do an update on a resource and after that this resource is appearing in search results. 

Do you have any idea how to resolve this issue? Is there any configuration for that?

**Comment by jamesagnew** [comment]
Hi @karkaletsis ,

Can you please create a concise code snippet showing how to reproduce this issue? (Note that this should be as concise as possible- please remove any code that is not required in order to demonstrate the issue)

**Comment by karkaletsis** [comment]
**Create consent**
 try {
            Consent consent = new Consent();
            consent.setDataPeriod(BuilderUtils.buildPeriod(fromdate,todate));

            consent.setPatient(BuilderUtils.buildResourceReference("Patient/1","Patient/1"));
            consent.setStatus(Consent.ConsentState.ACTIVE);
            Consent.ConsentActorComponent consentActorComponent = new Consent.ConsentActorComponent();
            resp = ReaderUtils.readPractitioner(ourClient, doctorId);
            String doctorId_ = resp.getDescription();
            consentActorComponent.setReference(BuilderUtils.buildResourceReference(doctorId_, doctorId_));
            consent.getActor().add(consentActorComponent);
            resp = client.createResource_(consent);
            resp.setStatus(HelperUtil.RESPONSE_OK);
            resp.setDescription(consent.getId());
        } catch (Exception e) {
            resp.setStatus(HelperUtil.RESPONSE_ERROR);
        }

**Search Consents**
 List<Consent> consents = new ArrayList<>();

        try {
            IUntypedQuery q = ourClient.search();
            IQuery<Bundle> b = q.forResource(Consent.class);
            //ICriterion crit1= new TokenClientParam("status").exactly().code("active");

            ICriterion crit1 = new ReferenceClientParam("patient").
                    hasId(patientId_);
            IQuery crit = b.where(crit1);
 org.hl7.fhir.dstu3.model.Bundle bundle_ = (org.hl7.fhir.dstu3.model.Bundle) crit
                    .returnBundle(org.hl7.fhir.dstu3.model.Bundle.class)
                    .prettyPrint()
                    .execute();

            for (org.hl7.fhir.dstu3.model.Bundle.BundleEntryComponent be : bundle_.getEntry()) {

                Consent consent_ = (Consent) be.getResource();
                LOG.info(consent_.getPatient().getReference());
                consents.add(consent_);
            }

You can check yourself here in our public server
**List of consents**
http://ehealthpass.gnomon.com.gr/hapi-fhir-jpaserver4/search?serverId=home&pretty=true&resource=Consent&param.0.qualifier=&param.0.0=&param.0.name=_language&param.0.type=string&sort_by=&sort_direction=&resource-search-limit=

**Search for consents from UI**
http://ehealthpass.gnomon.com.gr/hapi-fhir-jpaserver4/search?serverId=home&pretty=true&resource=Consent&param.0.0=&param.0.1=Patient%2F1&param.0.name=patient&param.0.type=reference&sort_by=&sort_direction=&resource-search-limit=

As you can see the results are only two, but if you open all the consents you will see that all have reference to the same patient "Patient/1" but the search returns 2 instead of 7

**Comment by jamesagnew** [comment]
This code contains fields and class references that don't exist. Unfortunately I can not run it. In addition, the formatting is very strange (you have some blocks of the code highlighted as code snippets and other blocks not highlighted).

Again, please create a concise demonstration of the issue if you would like to increase the chances of a solution. In as few lines of code as possible, with no external dependencies, please show how to reproduce this issue.

**Comment by karkaletsis** [comment]
I think you can check it only from UI without any code. It is the same behaviour

You can check yourself here in our public server
**List of consents**
http://ehealthpass.gnomon.com.gr/hapi-fhir-jpaserver4/search?serverId=home&pretty=true&resource=Consent&param.0.qualifier=&param.0.0=&param.0.name=_language&param.0.type=string&sort_by=&sort_direction=&resource-search-limit=

**Search for consents from UI**
http://ehealthpass.gnomon.com.gr/hapi-fhir-jpaserver4/search?serverId=home&pretty=true&resource=Consent&param.0.0=&param.0.1=Patient%2F1&param.0.name=patient&param.0.type=reference&sort_by=&sort_direction=&resource-search-limit=

As you can see the results are only two, but if you open all the consents you will see that all have reference to the same patient "Patient/1" but the search returns 2 instead of 7

**Comment by jamesagnew** [comment]
Without being able to reproduce the issue locally on my own database, I will not be able to help unfortunately.

**Comment by karkaletsis** [comment]
I think you can try to add a consent between a patient and a practirioner and try to search from the ui the consents with reference to a patient

**Comment by jamesagnew** [comment]
Please reopen if you are able to supply a code snippet that allows me to reproduce this issue. Unfortunately you have not supplied enough detail to allow me to reproduce this issue locally and it can not be fixed as such.

**Comment by karkaletsis** [comment]
Ok, it is not possible to send code snippet as it has methods from other classed. I think that you can reproduce it if you try to add consent and then search for it. It is searchable only after you make a manual update on the consent resource. But anyway, I will try to investigate myself. Thanks for your time!

**Comment by karkaletsis** [comment]
I have debugged it a bit and can see that the search returns only the resources having resource version 2. Can you imagine where is the problem. I runned it with xrebel in order to find out the queries made in db

**Comment by jamesagnew** [comment]
That does sound like the initial version isn't getting indexed correctly.

Unfortunately there isn't a way for me to see how it's being indexed unless I have a way of recreating it on a database I can look at.It may take some trial-and-error to come up with a code snippet that does the same thing as your closed source application.
