### ISSUE TITLE
FHIR BUNDLE PROCESS

### ISSUE THREAD

**Issue by Rokshan2016** [jamesagnew/hapi-fhir#1024]
Hi,

I am trying to do this :

1. I have a FHIR bundle, I resolve the bundle and get 42 separate resource. I want to show this all resource in a GRAPH (tree structure). What can be the best way to do it

Added json for reference
[patient.txt](https://github.com/jamesagnew/hapi-fhir/files/2181619/patient.txt)

**Comment by jamesagnew** [comment]
Hi @Rokshan2016 : Please see the HAPI FHIR wiki for instructions on how to ask for help: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
