### ISSUE TITLE
Error storing empty strings

### ISSUE THREAD

**Issue by anthonys123** [jamesagnew/hapi-fhir#1046]
I created a Practitioner resource in HAPI (refer to attached file) with empty strings for family and given names.  When I retrieve the resource, the data elements populated with the empty strings are missing (refer to attached).

The FHIR spec says an empty string is valid, so I would expect to see it retrieved.

[practitioner.txt](https://github.com/jamesagnew/hapi-fhir/files/2246452/practitioner.txt)

![retrieval](https://user-images.githubusercontent.com/15097189/43476405-861cae96-94c6-11e8-9864-233fe4d70ea2.jpg)

**Comment by jamesagnew** [comment]
Do you have a reference for empty strings being valid? At least the last time I looked that was not the case, although presumably it has changed?

**Comment by anthonys123** [comment]
Thanks for the fast reply.  The regex is cited in the spec:

   http://hl7.org/fhir/2018May/datatypes.html#string

An empty string is validated by that regex.  I used the regex tester at https://regex101.com/

Also, the validator accepts empty strings for those values and doesn't flag any issues.

**Comment by jamesagnew** [comment]
Ah, that is superceded by this: http://hl7.org/fhir/json.html

> String property values can never be empty. Either the property is absent, or it is present with at least one character of content

**Comment by anthonys123** [comment]
Thanks for the clarification, but shouldn't the validator flag empty strings?  Would that be a bug to be logged against the validator?

**Comment by jamesagnew** [comment]
Yup, I'd say so...
