### ISSUE TITLE
FhirInstanceValidator::validate() not looking in meta/profile section of request prior to calling InstanceValidator::validate()

### ISSUE THREAD

**Issue by anthonys123** [jamesagnew/hapi-fhir#1048]
When a StructureDefinition is loaded on demand by FhirInstanceValidator::validate(), the code should inspect the meta/profile section in the request to see if profile(s) are specified.  If so, then the meta.profile value should be used instead of the resource name to pass to InstanceValidator::validate().

Also, multiple profiles can be specified in that section, which would mean all profiles have to be validated.

Our profiles are named differently from the standard FHIR ones, this is how we hit the problem.  For instance, our practitioner profile is named "ocp-practitioner".  The current code sends the FHIR validator the resource type name, "practitioner", which means that the "ocp-practitioner" profile is never retrieved by the validator.

I've tested a fix in FhirInstanceValidator::validate() for the JSON processing of a single profile.  With the changes below, the FHIR validator picks up our "ocp-practitioner" profile and validates the request correctly.  Later this week I'll re-factor this to handle multiple profiles in the meta section.  I'll also implement and test the fix for XML.  Initial JSON fix below:

		} else if (theEncoding == EncodingEnum.JSON) {
			Gson gson = new GsonBuilder().create();
			JsonObject json = gson.fromJson(theInput, JsonObject.class);

			String resourceName = null;
			try {
				String[] components = json.getAsJsonObject("meta").get("profile").getAsString().split("/");
				resourceName = components[components.length - 1];
			} catch (Exception e) {
				resourceName = json.get("resourceType").getAsString();
			}
			StructureDefinition profile = findStructureDefinitionForResourceName(theCtx, resourceName);
			if (profile != null) {
				try {
					v.validate(null, messages, json, profile.getUrl());
				} catch (Exception e) {
					throw new InternalErrorException("Unexpected failure while validating resource", e);
				}
			}
		} else {
			throw new IllegalArgumentException("Unknown encoding: " + theEncoding);
		}

**Comment by anthonys123** [comment]
James - feel free to assign this one to me.

**Comment by jamesagnew** [comment]
Sounds good!

**Comment by anthonys123** [comment]
Hi James - created pull request this morning.  Thanks.

**Comment by anthonys123** [comment]
Hi James - I just realized that there are two more FhirInstanceValidator.java files I need to commit these changes to also.  I'll do that now and create another pull request.

**Comment by anthonys123** [comment]
Hi James - while build-testing these fixes in 3.4.0, I noticed that one of the unit tests failed an assertion pertaining to defect #824.  I'll investigate.

**Comment by anthonys123** [comment]
Hi James - I've made the changes to resolve the unit test issues for defect #824.  As part of those changes, I'm now enforcing that any URL specified for a custom StructureDefinition has to contain the text "StructureDefinition" per the FHIR spec:

https://www.hl7.org/fhir/structuredefinition.html#resource

"If the structure describes a base Resource or Type, the URL has to start with "http://hl7.org/fhir/StructureDefinition/" and the tail must match the id"

Doing this broke another unit test that tries to use "http://foo/myprofile" as its structure definition per below.  I can remove the "StructureDefinition" text check in the URL or I can modify those unit tests.  Let me know what I should do.

[INFO] Running org.hl7.fhir.dstu3.hapi.validation.FhirInstanceValidatorDstu3Test

[ERROR] Tests run: 46, Failures: 0, Errors: 1, Skipped: 7, Time elapsed: 80.344
s <<< FAILURE! - in org.hl7.fhir.r4.validation.FhirInstanceValidatorR4Test
[ERROR] testValidateResourceContainingProfileDeclarationDoesntResolve(org.hl7.fh
ir.r4.validation.FhirInstanceValidatorR4Test)  Time elapsed: 0.001 s  <<< ERROR!

ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Structure definition
URL must contain the text, "StructureDefinition", URL=http://foo/myprofile
        at org.hl7.fhir.r4.validation.FhirInstanceValidatorR4Test.testValidateRe
sourceContainingProfileDeclarationDoesntResolve(FhirInstanceValidatorR4Test.java
:918)

[INFO] Running org.hl7.fhir.dstu3.hapi.validation.ResourceValidatorDstu3Test
[WARNING] Tests run: 13, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 122.5
4 s - in org.hl7.fhir.dstu3.hapi.validation.ResourceValidatorDstu3Test
[INFO] Running org.hl7.fhir.dstu3.utils.FhirPathEngineTest
[ERROR] Tests run: 44, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 155.631
 s <<< FAILURE! - in org.hl7.fhir.dstu3.hapi.validation.FhirInstanceValidatorDst
u3Test
[ERROR] testValidateResourceContainingProfileDeclarationDoesntResolve(org.hl7.fh
ir.dstu3.hapi.validation.FhirInstanceValidatorDstu3Test)  Time elapsed: 0.176 s
 <<< ERROR!
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Structure definition
URL must contain the text, "StructureDefinition", URL=http://foo/myprofile
        at org.hl7.fhir.dstu3.hapi.validation.FhirInstanceValidatorDstu3Test.tes
tValidateResourceContainingProfileDeclarationDoesntResolve(FhirInstanceValidator
Dstu3Test.java:854)

**Comment by anthonys123** [comment]
Hi James - I'll modify the affected profile-based unit tests to use a URL of "http://foo/StructureDefinition/myprofile".

**Comment by anthonys123** [comment]
All unit tests now run properly in the hapi-fhir-validation project.  All files committed and pushed to the change request.  Hoping this can make it into 3.5.0.

**Comment by eevaturkka** [comment]
I noticed this due to the mention of #824 (reported from our project), and are you refrencing this constraint by mentioning requiring the StructureDefinition in the url? Because the logical identifier in SDs allows URIs, and I think that would be ok in case of constraint profiles. I'm just worried about our validation that loads custom profiles using ValidationSupport and has thus far worked just fine with any urls for the custom profiles, will it keep working after this?

sdf-7: If the structure describes a base Resource or Type, the URL has to start with "http://hl7.org/fhir/StructureDefinition/" and the tail must match the id (expression : (derivation = 'constraint') or (kind = 'logical') or (url = 'http://hl7.org/fhir/StructureDefinition/'+id))

**Comment by anthonys123** [comment]
All of the unit tests pass with my changes, including a test specifically written earlier for issue #824.  The scenario presented in that issue would have been tested by that unit test.

I'm not entirely sure what you're asking, but I'll try to answer.  Per my comments above, "As part of those changes, I'm now enforcing that any URL specified for a custom StructureDefinition has to contain the text "StructureDefinition" per the FHIR spec:

https://www.hl7.org/fhir/structuredefinition.html#resource

"If the structure describes a base Resource or Type, the URL has to start with "http://hl7.org/fhir/StructureDefinition/" and the tail must match the id"

I enforce the "StructureDefinition" text having to be present, but I'm not enforcing the second part of the rule stating that "the tail must match the id".  I was concerned that enforcing the "tail" part would be onerous.

Be aware that no enforcement of the specification rule was present in earlier HAPI versions.

- Anthony

**Comment by eevaturkka** [comment]
I'm asking because the rule you point to in the spec is:
"sdf-7: If the structure describes a base Resource or Type, the URL has to start with "http://hl7.org/fhir/StructureDefinition/" and the tail must match the id (expression : (derivation = 'constraint') or (kind = 'logical') or (url = 'http://hl7.org/fhir/StructureDefinition/'+id))"

The url  constraint has two ors that reference other fields inside the StructureDefinition, the derivation (that for normal custom profiles is "constraint") and the kind field. To my understanding the expression that is more precice than natural language would not constrain urls of such profiles. I wanted to know if your change would affect using such profiles?

**Comment by anthonys123** [comment]
All I'm looking for is the "StructureDefinition" text in the URL.  Case insensitive.  Everything else in the URL is allowed to be arbitrary.
