### ISSUE TITLE
hapi-fhir-server-resourceproviders-dev.xml should be renamed in web.xml

### ISSUE THREAD

**Issue by mochaholic** [jamesagnew/hapi-fhir#106]
This causes the following in the latest snapshot: 
"
IOException parsing XML document from class path resource [hapi-fhir-server-resourceproviders-dev.xml]; nested exception is java.io.FileNotFoundException: class path resource [hapi-fhir-server-resourceproviders-dev.xml] cannot be opened because it does not exist
"
It should probably be renamed to hapi-fhir-server-resourceproviders-dstu2.xml consistent with the recent changes.

**Comment by jamesagnew** [comment]
Closing bugs that were fixed but not closed out. This should be resolved.
