### ISSUE TITLE
Error message Shouldn’t response with “not a com.google.gson.JsonNull” but rather just “null” when resource JSON contains NULL values

### ISSUE THREAD

**Issue by timirahikainen** [jamesagnew/hapi-fhir#1069]
We are sending POST Observation and resource content is in JSON format with some NULL values

POST {
    "resourceType":"Observation",
    "meta":{
    	"versionId": NULL,
"lastUpdated": NULL

  },
  
    "status": NULL,
  "category": NULL,
    "identifier": [            {
               
               "system": "urn:ietf:rfc:3986",
               "value": "20170808TR0001"              
            }],  
    "code": NULL,
    "subject":{
        "reference": "Patient/ABC"
    },
  "effectiveDateTime": "2018-08-27",
  "issued": "2018-08-27T13:15:59.961+02:00",
  "performer": [{
    "reference": "Patient/ACB"
  }],  
    "valueQuantity":{
        "value":93,
        "unit":"cm",
		"system":"http://unitsofmeasure.org",
		"code":"cm"
		
    }
}

We are getting following errors in response and they shouldn’t response with “not a com.google.gson.JsonNull” but rather just “null”, as the former reveals details about underlying implementation in the error message.

HTTP/1.1 422 Undefined
X-Powered-By: Servlet/3.1
X-Content-Type-Options: nosniff
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
X-Powered-By: HAPI FHIR 3.2.0 REST Server (FHIR Server; FHIR 3.0.1/DSTU3)
Content-Type: application/json+fhir
Content-Language: en-US
Transfer-Encoding: chunked
Date: Mon, 27 Aug 2018 10:32:34 GMT
Set-Cookie: BIGipServerphr2.ke_pool=555107594.31011.0000; path=/; Httponly; Secure
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=16070400

{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "This property must be an simple value, not a com.google.gson.JsonNull",
      "location": [
        "/Observation/meta/versionId"
      ]
    },
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "This property must be an simple value, not a com.google.gson.JsonNull",
      "location": [
        "/Observation/meta/lastUpdated"
      ]
    },
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "This property must be an simple value, not a com.google.gson.JsonNull",
      "location": [
        "/Observation/status"
      ]
    },
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "This property must be an Array, not a com.google.gson.JsonNull",
      "location": [
        "/Observation/category"
      ]
    },
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "This property must be an Object, not a com.google.gson.JsonNull",
      "location": [
        "/Observation/code"
      ]
    },

  ]
}

**Comment by patrick-werner** [comment]
NULL ist not a valid value. See:
https://www.hl7.org/fhir/conformance-rules.html#cardinality

> Note that when present, elements cannot be empty - they SHALL have a value attribute, child elements, or extensions.

You can omit the null elements (if a profile enforces a min. cardinality of 1 you could use the https://www.hl7.org/fhir/extension-data-absent-reason.html Extension instead of a value)
