### ISSUE TITLE
Search with count 0 does not work as according to standard

### ISSUE THREAD

**Issue by timirahikainen** [jamesagnew/hapi-fhir#1074]
We are sending Search request with count = 0 (http://hapi.fhir.org/baseDstu3/Observation?_count=0&_lastUpdated=2018-09-19)

standard says "if _count has the value 0, this shall be treated the same as _summary=count: the server resturns a bundle that reports the total number of resources that match in Bundle.total, but with no entries, and no prev/next/last links. Note that the Bundle.total only include the total number of matching resources. It does not count extra resources such as OperationOutcome or included resources that may also be returned." (https://www.hl7.org/fhir/search.html#count)

Expected response: (same as http://hapi.fhir.org/baseDstu3/Observation?_summary=count)
{
  "resourceType": "Bundle",
  "id": "7628f71a-97e1-4a15-9267-a1293c62f196",
  "total": 10000
}

Actual response: 

{
  "resourceType": "Bundle",
  "id": "c479ced6-0225-4064-961d-2d4d050b2c1a",
  "meta": {
    "lastUpdated": "2018-09-19T11:44:30.857+00:00"
  },
  "type": "searchset",
  "total": 10000,
  "link": [
    {
      "relation": "self",
      "url": "http://hapi.fhir.org/baseDstu3/Observation?_count=0&_lastUpdated=2018-09-19"
    },
    {
      "relation": "next",
      "url": "http://hapi.fhir.org/baseDstu3?_getpages=c479ced6-0225-4064-961d-2d4d050b2c1a&_getpagesoffset=20&_count=20&_pretty=true&_bundletype=searchset"
    }
  ],
  "entry": [
    {
      "fullUrl": "http://hapi.fhir.org/baseDstu3/Observation/6131780",
      "resource": {
        "resourceType": "Observation",
        "id": "6131780",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2018-09-19T00:00:01.936+00:00"
        },
        "status": "preliminary",
        "category": [
          {
            "text": "vital-signs"
          }
        ],
        "code": {
          "coding": [
            {
              "system": "http://dcx.fhir-test.com/fhir/",
              "code": "NIBPS",

**Comment by ThomK** [comment]
see also https://github.com/jamesagnew/hapi-fhir/issues/981
