### ISSUE TITLE
Karaf Hapi-Fhir 3.5.0 is missing in Maven Central

### ISSUE THREAD

**Issue by oscerd** [jamesagnew/hapi-fhir#1076]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Describe the bug**
Karaf Hapi-Fhir 3.5.0 is missing in Maven Central

**To Reproduce**
http://repo2.maven.org/maven2/ca/uhn/hapi/fhir/karaf/hapi-fhir/

**Expected behavior**
It should be there.

**Comment by jamesagnew** [comment]
Thanks for pointing this out! Fixed
