### ISSUE TITLE
Missing spring boot releases for version 3.5.0

### ISSUE THREAD

**Issue by bratwurzt** [jamesagnew/hapi-fhir#1086]
I've tried to upgrade my project to hapi.version=3.5.0 and noticed that hapi-fhir-spring-boot-autoconfigure is missing among other spring boot release jars. Is this intentional?

**Comment by janverhoeckx** [comment]
I also would like to update my Spring boot, but the HAPI starter is not yet compatible.. Can we expect this in the future?
