### ISSUE TITLE
Oudated java-hamcres dependency.

### ISSUE THREAD

**Issue by mochaholic** [jamesagnew/hapi-fhir#109]
Seems like the old version of java-hamcres dependency in the pom file of oauth2 subproject is no longer available in the maven repository and causes an error. It worked fine when I fixed the version to 2.0.0.0.

**Comment by jamesagnew** [comment]
Thanks for reporting! This got fixed in commit a3be361e40f09d201e0eaf8e198981956d58488d but I just noticed this bug wasn't closed, so I'm closing it now.
