### ISSUE TITLE
HAPI converters don't offer  support for AllergyIntolerance resources

### ISSUE THREAD

**Issue by josemolmomillan** [jamesagnew/hapi-fhir#1091]
HAPI converters don't offer support for AllergyIntolerance resource in DSTU2 or DSTU3

- https://github.com/jamesagnew/hapi-fhir/blob/v3.5.0/hapi-fhir-converter/src/main/java/org/hl7/fhir/convertors/VersionConvertor_10_30.java#L12824

- https://github.com/jamesagnew/hapi-fhir/blob/v3.5.0/hapi-fhir-converter/src/main/java/org/hl7/fhir/convertors/VersionConvertor_10_40.java#L12086

**Comment by grahamegrieve** [comment]
No. Maintaining those converters is a huge job, and we only commit to do it for the conformance resources. But if you contributed something, we'd be happy to add it.

**Comment by josemolmomillan** [comment]
Thanks Graham for the info.

But yes, we are migrating data for our fhir/xds DSTU2 implementation to export to Google Cloud Healthcare API STU3, and we need to export Health Records with a lot of AllergyIntolerance. I am going to analyze it to introduce some issue in the next sprints of my team. Surely, I will have some question about the converter architecture .

Thanks again
