### ISSUE TITLE
Plea to eliminate checked exceptions

### ISSUE THREAD

**Issue by mdgeek** [jamesagnew/hapi-fhir#1108]
Not exactly a bug, but a major annoyance nonetheless.  It is frustrating to have to explicitly handle every FHIRException.  If we could make it a runtime exception my code would be drastically simplified and I would be much HAPIer.

**Comment by lawley** [comment]
Please do not. If you don't want to handle the exception, let your IDE add in the throws declarations and have it propagate up (just as a RuntimeException would).

The throws declarations then act as useful (albeit somewhat minimal) documentation on where errors may flow from.

**Comment by jamesagnew** [comment]
I always love how contentious Java's checked exceptions are. Lots of good opinions on both sides. :)

I have to be honest, I'd lean towards making HL7Exception unchecked personally. Most of HAPI FHIR already uses unchecked exceptions (BaseServerResponseException and its entire hierarchy being the best example of this).

The main spot where HL7Exception happens is when calling getters for choice[x] types on the datamodel, and having a checked exception for something that will literally never happen as long as you are writing good defensive code is a bit of a pain.

**Comment by restevez-chs** [comment]
@jamesagnew i'm hoping to contribute to this repo. i'm reading the conversation on this issue and see two opposing viewpoints. would you consider this issue as unworkable at this point and pending more discussion? thanks -- ricky

**Comment by restevez-chs** [comment]
Hopefully more discussion in this ticket can clear confusion...

`HL7Exception` is in another GitHub project: [hapifhir/hapi-hl7v2](https://github.com/hapifhir/hapi-hl7v2/blob/master/hapi-base/src/main/java/ca/uhn/hl7v2/HL7Exception.java)

And, yep, it is a _checked_ exception.

Question 1 to @jamesagnew: if a change might be needed to make `HL7Exception` an unchecked exception, that will be a change in another repo hapifhir/hapi-hl7v2 right?

Summary
* `FHIRException` in HAPI-FHIR, 3.0.0-SNAPSHOT is a [checked exception](https://github.com/jamesagnew/hapi-fhir/blob/be5c5ebecde889e5e91784e300c943a35d50c253/hapi-fhir-base/src/main/java/org/hl7/fhir/exceptions/FHIRException.java#L24)
* `FHIRException` in latest HAPI-FHIR, 3.7.0-SNAPSHOT is an [unchecked exception](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-utilities/src/main/java/org/hl7/fhir/exceptions/FHIRException.java#L3)
* Noteworthy: the other [custom exceptions](https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-fhir-utilities/src/main/java/org/hl7/fhir/exceptions) themselves extend FHIRException, so they are also unchecked (`RuntimeException`)

Question 2 to @mdgeek, so everything is good to go, right? going to latest version 3.7.0-SNAPSHOT might be all you need

**Comment by mdgeek** [comment]
Yes, I am a HAPI camper!

**Comment by restevez-chs** [comment]
@mdgeek that's great. sounds like this issue is close-able then.
