### ISSUE TITLE
mvn install failed (version: 3.6.0)

### ISSUE THREAD

**Issue by kj142857** [jamesagnew/hapi-fhir#1115]
**Describe the bug**
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project hapi-fhir-jpaserver-base: There are test failures.

**To Reproduce**
1. Go to "releases" -> HAPI FHIR 3.6.0 (Food) 
2. Download source code (zip)
3. In the root directory 

```
$ mvn install
```

Output:
```
...
[ERROR] Errors: 
[ERROR] ca.uhn.fhir.jpa.subscription.r4.WebsocketWithSubscriptionIdR4Test.createObservationThatDoesNotMatch(ca.uhn.fhir.jpa.subscription.r4.WebsocketWithSubscriptionIdR4Test)
[ERROR]   Run 1: WebsocketWithSubscriptionIdR4Test.before:67->BaseResourceProviderR4Test.before:152 » Bind
[ERROR]   Run 2: WebsocketWithSubscriptionIdR4Test.afterCloseWebsocket:61 NullPointer
[INFO] 
[INFO] 
[ERROR] Tests run: 2160, Failures: 0, Errors: 1, Skipped: 70
...
...
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:04 min
[INFO] Finished at: 2018-11-14T10:11:20-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project hapi-fhir-jpaserver-base: There are test failures.
...
```

**Expected behavior**
Build Success.

**Screenshots**
Not applicable.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 3.6.0 (Food)
 - OS: MacOS 10.13.6
 - Maven version: Apache Maven 3.5.4
 - Java version: 10.0.2, vendor: Oracle Corporation

**Comment by Romanow88** [comment]
@kj142857 can you please provide the stack traces for the failed tests?
