### ISSUE TITLE
Please list server URL in hapi-fhir-jpaserver-example/README.md when running inside Docker

### ISSUE THREAD

**Issue by tmielke** [jamesagnew/hapi-fhir#1122]
hapi-fhir-jpaserver-example/README.md has good instructions on how to run the server inside Docker. 
However from these instructions its not clear what is the right server URL in order to access this server (or push data to it). 

The part 
https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-fhir-jpaserver-example#running-hapi-fhir-jpaserver-example-in-tomcat-from-intellij

mentions the URL http://localhost:8080/hapi/base/Patient but that does not work in Docker. 
For the server running inside Docker the right URL seems to be http://localhost:8080/baseDstu3/Patient and that URL should be documented.

Or ideally, reconfigure the docker image to use the same URL as when running  in Tomcat from IntelliJ (or vice versa).

**Comment by patrick-werner** [comment]
fixed through #297cf3e
