### ISSUE TITLE
ca.uhn.fhir.context.ConfigurationException: hapi-fhir-client does not appear to be on the classpath

### ISSUE THREAD

**Issue by arabin-android** [jamesagnew/hapi-fhir#1132]
when I tried Step 3: Upload your basic Patient.
I got this error. Can anyone help me with this issue?

Exception in thread "main" ca.uhn.fhir.context.ConfigurationException: hapi-fhir-client does not appear to be on the classpath
	at ca.uhn.fhir.context.FhirContext.getRestfulClientFactory(FhirContext.java:528)
	at Main.main(Main.java:30)

Here is my code : 

import ca.uhn.fhir.context.FhirContext;
import ca.uhn.fhir.parser.DataFormatException;
import ca.uhn.fhir.parser.IParser;
import ca.uhn.fhir.rest.api.MethodOutcome;
import ca.uhn.fhir.rest.client.api.IGenericClient;
import org.hl7.fhir.dstu3.model.*;

import java.io.IOException;

public class Main {

    public static void main(String[] args) throws IOException {
        // context - create this once, as it's an expensive operation
        // see http://hapifhir.io/doc_intro.html
        FhirContext ctx = FhirContext.forDstu3();
        String serverBaseUrl = "http://sqlonfhir-stu3.azurewebsites.net/fhir";

        Patient ourPatient = new Patient();

        // you can use the Fluent API to chain calls
        // see http://hapifhir.io/doc_fhirobjects.html
        ourPatient.addName().setUse(HumanName.NameUse.OFFICIAL)
                .addPrefix("Mr").setFamily("Fhirman").addGiven("Sam");
        ourPatient.addIdentifier()
                .setSystem("http://ns.electronichealth.net.au/id/hi/ihi/1.0")
                .setValue("8003608166690503");

        // increase timeouts since the server might be powered down
        // see http://hapifhir.io/doc_rest_client_http_config.html
        ctx.getRestfulClientFactory().setConnectTimeout(60 * 1000);
        ctx.getRestfulClientFactory().setSocketTimeout(60 * 1000);

        // create the RESTful client to work with our FHIR server
        // see http://hapifhir.io/doc_rest_client.html
        IGenericClient client = ctx.newRestfulGenericClient(serverBaseUrl);

        System.out.println("Press Enter to send to server: " + serverBaseUrl);
        System.in.read();

        try {
            // send our resource up - result will be stored in 'outcome'
            // see http://hapifhir.io/doc_rest_client.html#Create_-_Type
            MethodOutcome outcome = client.create()
                    .resource(ourPatient)
                    .prettyPrint()
                    .encodedXml()
                    .execute();

            IdType id = (IdType) outcome.getId();
            System.out.println("Resource is available at: " + id.getValue());

            IParser xmlParser = ctx.newXmlParser().setPrettyPrint(true);
            Patient receivedPatient = (Patient) outcome.getResource();
            System.out.println("This is what we sent up: \n"
                    + xmlParser.encodeResourceToString(ourPatient)
                    + "\n\nThis is what we received: \n"
                    + xmlParser.encodeResourceToString(receivedPatient));
        } catch (DataFormatException e) {
            System.out.println("An error occurred trying to upload:");
            e.printStackTrace();
        }

        System.out.println("Press Enter to end.");
        System.in.read();
    }
}

**Comment by jamesagnew** [comment]
Is hapi-fhir-client on your classpath?

sent from my phone.

**Comment by arabin-android** [comment]
could you please suggest me how to add "hapi-fhir-client" on my classpath? I am using IntelliJ IDE thanks.

**Comment by arabin-android** [comment]
I added the "hapi-fhir-client" on my classpath. however, i am getting the following error on step3. Can anyone help me, please.

Exception in thread "main" java.lang.ClassCastException: ca.uhn.fhir.rest.client.apache.ApacheRestfulClientFactory cannot be cast to ca.uhn.fhir.rest.client.api.IRestfulClientFactory
	at ca.uhn.fhir.context.FhirContext.getRestfulClientFactory(FhirContext.java:526)
	at Main.main(Main.java:32)

**Comment by jamesagnew** [comment]
Hi @arabin-android - Please see [this link](https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help) for information on how to ask questions about HAPI FHIR.

As for this question, it looks to me like you have a version mismatch between your hapi-fhir-base and your hapi-fhir-client JARs.
