### ISSUE TITLE
@Override public IBaseExtension<?> newExtension()

### ISSUE THREAD

**Issue by mochaholic** [jamesagnew/hapi-fhir#114]
This method has been added to FhirDev, FhirDstu1 and FhirDstu2 in the Tinder Plugin (latest commit) and bears the annotation @Override but it doesn't exist in the parent interface IFhirVersion. This is  causing a compile fail.
I commented out the annotation in these three classes and I could build the project (moving the method up to the interface breaks some other implementers of the interface).

**Comment by jamesagnew** [comment]
Thanks for letting me know Mohammad,

This has been fixed. Our project Jenkins server had stopped building for
some reason, so I've put that back up too.

Cheers,
James
