### ISSUE TITLE
Getting exception while calling DSTU3 server using IBasicClient interface 

### ISSUE THREAD

**Issue by shayaanmunshi** [jamesagnew/hapi-fhir#1163]
Exception in thread "main" ca.uhn.fhir.parser.DataFormatException: Unknown resource name "Conformance" (this name is not known in FHIR version "DSTU3")
	at ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:369)
	at ca.uhn.fhir.rest.client.impl.RestfulClientFactory.validateServerBase(RestfulClientFactory.java:305)
	at ca.uhn.fhir.rest.client.impl.RestfulClientFactory.validateServerBaseIfConfiguredToDoSo(RestfulClientFactory.java:264)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:210)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:203)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:199)
	at ca.uhn.fhir.rest.client.impl.ClientInvocationHandler.invoke(ClientInvocationHandler.java:62)
	at com.sun.proxy.$Proxy15.getResourceById(Unknown Source)

**Version:**
 - HAPI FHIR Version 3.6.0
 - OS:  Windows 7

**Java Client:**
public interface IRestfulClient extends IBasicClient {
	@Read()
	public Patient getResourceById(@IdParam IdType theId);
}

 IRestfulClient client = ctx.newRestfulClient(IRestfulClient.class, serverBase);
Patient patient = client.getResourceById(new IdType("1234"));

**DSTU3 server capability Stmt**
{
  "resourceType": "CapabilityStatement",
  "status": "active",
  "date": "2019-01-09T16:17:08-05:00",
  "publisher": "Not provided",
  "kind": "instance",
  "software": {
    "name": "FHIR Server",
    "version": "V2"
  },
  "fhirVersion": "3.6.0",
  "acceptUnknown": "?",
  "format": [
    "application/fhir+xml",
    "application/fhir+json"
  ],
..........

**Comment by shayaanmunshi** [comment]
I tried changing the Client using IGenericClient implementation and still getting the same exception 

IGenericClient client = ctx.newRestfulGenericClient(serverBase);
Bundle results = client.search().forResource(Patient.class).where(Patient.FAMILY.matches().value("duck"))
				.returnBundle(Bundle.class).execute();

**Comment by jamesagnew** [comment]
Are you sure you are accessing a DSTU3 base URL? That looks like you're
pointer at a DSTU2 url.

sent from my phone.

**Comment by shayaanmunshi** [comment]
Yes I am sure i am pointing to DSTU3 Server. 
Strange thing is it is fixed after setting acceptUnknown to "no" on CapabilityStatement

  "acceptUnknown": "?",
   ca.uhn.fhir.parser.DataFormatException: Unknown resource name "Conformance" (this name is not known in FHIR version "DSTU3")
   
  **"acceptUnknown": "no",**
  No Exceptions...Successfully able to query the resource followed by metadata call

**Comment by jamesagnew** [comment]
Is your server somewhere that I can try replicating this? I'm not seeing
this locally.

sent from my phone.

**Comment by jamesagnew** [comment]
Alternately, can you attach a debugger and trace where the string
"conformance" is actually coming from?

sent from my phone.

**Comment by shayaanmunshi** [comment]
You can try this base URL test Server:
https://smartonfhirstagingsrv.eclinicalweb.com/FHIRServer/fhir/test/
This is DSTU3 FHIR Server

**Comment by jamesagnew** [comment]
FYI I have been able to replicate locally. Thanks for providing.

The issue is that "?" is not a valid value for that field. HAPI then has a
bug where it's not correctly floating the actual error up to the user.

**Comment by jamesagnew** [comment]
This is fixed. Thanks again for reporting and providing access to your system demonstrating the issue!

**Comment by shayaanmunshi** [comment]
Thanks James !
