### ISSUE TITLE
HAPI FHIR public test server down

### ISSUE THREAD

**Issue by goku0** [jamesagnew/hapi-fhir#1171]
It seems the server is down again, getting a 502 gateway error when I try to go to:

http://hapi.fhir.org/baseDstu3
http://fhirtest.uhn.ca/baseDstu3
http://hapi.fhir.org/baseDstu2

**Comment by jamesagnew** [comment]
Should be back up now. Thanks for the heads up.

**Comment by goku0** [comment]
It's up! Quick fix! Thanks for maintaining this service James

**Comment by Kunalrk1** [comment]
Hello,
It seems FHIR Test server is down again. I am getting following error - "504 Gateway Time-out" since last couple of days.

**Comment by RikeEl** [comment]
Hey, guess it's down again, I get runtime error.

**Comment by jamesagnew** [comment]
Please see the announcement here: https://groups.google.com/u/1/g/hapi-fhir/c/jMY934Fgf8w

The server has temporarily moved to http://test.hapifhir.io

**Comment by cdimas1** [comment]
https://hapi.fhir.org/baseR4/swagger-ui/ 
Server is down  again https://prnt.sc/IAoEXryPbHXI

**Comment by SahilBhardwaj4** [comment]
Hi Team,
https://hapi.fhir.org/baseR4/swagger-ui/
Server is down again.
