### ISSUE TITLE
[Android] MinSdk Requirement really high, necessity?

### ISSUE THREAD

**Issue by KsgPhellow** [jamesagnew/hapi-fhir#1173]
Hello,
I have used hapi fhir on java before and was extremely satisfied.
Now I wanted to use it with our new Android App but the minSdk required to run hapi-fhir android is 24 which is a no-go for me, since it exludes large parts of the distribution.

Is a minSdk that high really necessary for hapi fhir ? 
And what are the differences between hapi fhir android and the java hapi fhir client? 
Could I reasonably use the hapi fhir client on android to circumvent the minSdk requirements?

**Comment by patrick-werner** [comment]
Android < API level 24 isn't supported by Google anymore -> gets no security updates.
Building a healthcare related app on a non supported base seems like a bad idea.

**Comment by KsgPhellow** [comment]
I'm aware of that, but we would exlude most of our target group if we went with >= API level 24.
So the question still stands I'm afraid.

**Comment by KsgPhellow** [comment]
Then your patients are drastically different from ours, but this really is besides the point.

**Comment by jamesagnew** [comment]
What version of Java does Android 23 support?

HAPI FHIR has a minimum of Java 8 (and that's definitely not going back) -
It's been a while now but I seem to recall that this was the main driver
for moving up to 24.

**Comment by KsgPhellow** [comment]
okay, I can understand that.
I'll see if i'll be able to use hapi anyway or have to look for an alternative.

Thanks for the responses.
