### ISSUE TITLE
Occurrence parameter not working on CommunicationRequest & ProcedureRequest on DSTU3

### ISSUE THREAD

**Issue by contactkuchi** [jamesagnew/hapi-fhir#1188]
We have created  couple of CommunicationRequests on the Hapi Server and we are trying to fetch them using the occurrence parameter

The resources created are:
http://hapi.fhir.org/baseDstu3/CommunicationRequest/fm-solicit

The url we are trying to fetch them using the url:
http://hapi.fhir.org/baseDstu3/CommunicationRequest?occurrence=ge2015-08-10T11:33:00-04:00

It seems that the occurrence parameter works if the occurrenceDateTime is used but if occurrencePeriod/occurrenceTiming is used it does not 

Thanks
Ravi Kuchi

**Comment by jamesagnew** [comment]
Hi @contactkuchi - After digging into this, it looks like the system is actually working as expected. For whatever reason, the [CommunicationRequest:occurrence](http://hl7.org/fhir/communicationrequest.html#search) search parameter uses the path:

```
(CommunicationRequest.occurrence as dateTime)
```

This means it specifically does not index `CommunicationRequest.occurrencePeriod`. You could work around this by modifying this search parameter's definition to use the path `CommunicationRequest.occurrence` instead and this would make things work.

I've filed a tracker with the FHIR spec to clarify this: 
https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemBrowse&feedback=Successfully+added+%5B%2320517%5D&tracker_id=677
