### ISSUE TITLE
how to build and run this project locally

### ISSUE THREAD

**Issue by samir-ware** [jamesagnew/hapi-fhir#1198]
Hello 
I could build this project locally (mvn clean install) . Although can someone please help me to understand how should I run it locally ? I could not find my war file anywhere even after project got build successfully. 
Thanks
Samir

**Comment by jamesagnew** [comment]
Hi @samir-ware . 

Please see this wiki page for information on how to get help: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
