### ISSUE TITLE
Coding comparison should not consider display and userSelected

### ISSUE THREAD

**Issue by okkokauh** [jamesagnew/hapi-fhir#1201]
The standard states: _"If two codings have the same system, version and code then they have the same meaning."_

However, HAPI also considers display and userSelected fields in equality comparisons. The bug can be reproduced as follows:
```

        Coding a = new Coding().setCode("1").setSystem("http://system").setDisplay("123");
        Coding b = new Coding().setCode("1").setSystem("http://system");
        System.out.println("Result: " + a.equalsShallow(b));
```
We use display texts in multiple languages for codes.  We implemented our own comparison, but it would be nice to have this also in HAPI.

**Comment by grahamegrieve** [comment]
java equals should not be confused with 'have the same meaning'. I think it should be a different operation

**Comment by okkokauh** [comment]
True, after giving more thought to this, it is not a bug. In a strict sense, the Java objects are not equal for different display and userSelected values.

However, we haven't yet encountered a situation where the display values would be of relevance in Coding comparisons. Coding comparisons are needed very often and the comparison has always been by the meaning of the code (as described in the standard). 

The correct place for such a comparison method would be a utility class. CodingUtilities already has it for R4 structures.  Maybe this could be added for stu3 Coding objects also. I could make a pull request once I have time.

Thank you.
