### ISSUE TITLE
Google Analytics Tracking Script

### ISSUE THREAD

**Issue by jtwolgamott** [jamesagnew/hapi-fhir#1207]
In the hapi-fhir-3.6.0-jpaserver-example, I see that the `tmlp-footer.html` file has a Google Analytics tracking script with what I assume is the project creators tracking ID. Please remove, or provide a notice that the project has a Google Analytics tracking script that will log usage data to a Google Analytics account not accessible to general consumers of this project.

**Comment by patrick-werner** [comment]
especially important with GDPR regulations.

**Comment by jamesagnew** [comment]
Pull request gladly accepted on this, I'm assuming this is just legacy from
when the project was forked from our reference server long ago.

Really people should be using the jpaserver-starter project though

J

sent from my phone.

**Comment by patrick-werner** [comment]
> Really people should be using the jpaserver-starter project though
I totally agree. To force people to do so would you accept a PR removing everything from JPA-example just leaving a markdown note to point to the new repo for the JPA Starter?

**Comment by jtwolgamott** [comment]
> > Really people should be using the jpaserver-starter project though
> 
> I totally agree. To force people to do so would you accept a PR removing everything from JPA-example just leaving a markdown note to point to the new repo for the JPA Starter?
> edit: also made a PR to the new JPA Starter which also includes analytics.

@patrick-werner @jamesagnew  Is this the recommended starter project --> https://github.com/hapifhir/hapi-fhir-jpaserver-starter? Could we push forward on the recommendation to remove everything in JPA-example and replace with a markdown note pointing to this repo? I would also be happy to submit a PR if this is in fact the direction we're going.

**Comment by jamesagnew** [comment]
@jtwolgamott Sure thing, that would be great. I think we're ready to remove the other project a this point.

**Comment by jtwolgamott** [comment]
@patrick-werner I would like to contribute a commit/PR with the aforementioned changes, but I don't currently have the required access level to this repo, can you please assist or point me in the right direction regarding how I might contribute to this project?

**Comment by patrick-werner** [comment]
@jtwolgamott you can fork this repo, apply the changes and then make a PR. But i already started working on implementing the required changes. Currently only left is the migration of the elasticsearch config.

**Comment by jtwolgamott** [comment]
@patrick-werner Glad to hear it, thanks for the info.
