### ISSUE TITLE
Can not link to versioned resource (versionID)

### ISSUE THREAD

**Issue by mmreith** [jamesagnew/hapi-fhir#1224]
Hey,

i tried to link a ressource to a versioned resource, which should be allowed in DSTU3 http://hl7.org/fhir/STU3/references.html -> regex literal references
 
so i sent the following bundle to a HAPI 3.6.0 Server
```xml
<Bundle xmlns="http://hl7.org/fhir">
    <type value="transaction"/>
      <entry> 
    <fullUrl value="http://example.org/fhir/Observation/12"/> 
    <resource> 
      <Observation> 
        <id value="12"/>  
<status value="final"/>  
         <code>  
          <coding>  
            <system value="http://loinc.org"/>  
            <code value="15074-8"/>  
            <display value="Glucose [Moles/volume] in Blood"/>  
          </coding>  
        </code>  
        <subject> 
          <!--    this is reference to the first patient above    -->
          <reference value="Patient/2/_history/1"/> 
        </subject> 
      </Observation> 
    </resource> 
            <request>
         <method value="POST"/>
      </request>
  </entry>
</Bundle>
```
this observation is linked to Patient/2/_history/1/
two versions of this Patient are available on this server...but the resource on the server points to:
```xml
<subject> 
<reference value="Patient/2"/> 
</subject> 
```

**Comment by jamesagnew** [comment]
You need to enable versioned references on the context. See: http://hapifhir.io/doc_resource_references.html#_toc_versioned_references

(Note, please ask questions on our Google Group. [See here for details](https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help))
