### ISSUE TITLE
stu3 InstanceValidator

### ISSUE THREAD

**Issue by KevinMayfield** [jamesagnew/hapi-fhir#1235]
With STU3 Validation, getting the following error https://chat.fhir.org/#narrow/stream/179166-implementers/topic/HAPI.20validator.20error.20-.20traversing.20bundles

Issue is with STU3 InstanceValidator function  **private void checkAllInterlinked**

it has a TODO to check other resources point to referenced resources. Fix has been done for R4 (same function name) see line 3301 https://github.com/jamesagnew/hapi-fhir/blob/73dda18f5971abdb362ca220703604cc3493d50a/hapi-fhir-validation/src/main/java/org/hl7/fhir/r4/validation/InstanceValidator.java

**Comment by jamesagnew** [comment]
Closing old bugs that are no longer relevant. We now use the R5 validator for R3/4/5 validation, so this should now be fixed. Please feel free to comment if you feel that this is not fixed.
