### ISSUE TITLE
Resource references shouldn't include version when they are encoded

### ISSUE THREAD

**Issue by jamesagnew** [jamesagnew/hapi-fhir#124]
..and maybe they should omit the server base too if it matches the one being encoded?

**Comment by jamesagnew** [comment]
Reopening, per email from Tomas Stæhr Berg on the HAPI list. We should allow encoding references with versions if they are supplied.

**Comment by jalbertof** [comment]
Hello Hapi guys, any news about this issue? How I could implement a Hapi Server that is able to handle references with a specific version of the resource?

**Comment by jamesagnew** [comment]
This is a stale ticket. See: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/hapi-fhir/PPmzTOldI1Y/eo2GsM7gEgAJ

Closing, although a corresponding PR in hapi-fhir-jpaserver-starter may be needed.
