### ISSUE TITLE
_summary parameter not yet supported

### ISSUE THREAD

**Issue by jamesagnew** [jamesagnew/hapi-fhir#125]
We should automatically honour this param. Might be nice to let the user get a copy and do their own definition too, if they want to return a different subset of the resource instead of FHIR's defined one

**Comment by lawley** [comment]
+1 for this, but also the _elements parameter

**Comment by jamesagnew** [comment]
As luck would have it, I'll be committing and deploying a fix to this today which implements support for both _summary and _elements per the new DSTU2 specs
