### ISSUE TITLE
RiskAssessment doesn't have a `note` attribute as per FHIR specs

### ISSUE THREAD

**Issue by hzitoun** [jamesagnew/hapi-fhir#1257]
**Describe the bug**
In `FHIR` Specs, a `RiskAssessment` resource has a [`note` attribute ](https://www.hl7.org/fhir/riskassessment-definitions.html#RiskAssessment.note) to put a comment about the evaluation. Which is not the case in the java implementation.

I guess that the corresponding attribute is [`comment` ](http://hapifhir.io/apidocs-dstu3/org/hl7/fhir/dstu3/model/RiskAssessment.html#setComment-java.lang.String-).

**To Reproduce**
- No steps, just by reading FHIR Specs vs HAPI Implementation of `RiskAssessment`

**Expected behavior**
Expected to have the same attribute name unless I'm missing something.

**Screenshots**
No Screenshots

**Environment (please complete the following information):**
 - HAPI FHIR 3.6.0 (even with 3.7.0)
 - OS: doesn't matter
 - Browser: doesn't matter

**Additional context**
Nothing

**Comment by hzitoun** [comment]
It was related to the version of FHIR specs. The attribute has been renamed to `note` from version 3 to version 4.

**Comment by jamesagnew** [comment]
hi @hzitoun can this be closed then?
