### ISSUE TITLE
Observation.setInterpretation should accept CodeableConceptDt instead of BoundCodeableConceptDt

### ISSUE THREAD

**Issue by steve1medix** [jamesagnew/hapi-fhir#126]
ObservationInterpretationCodesEnum doesn't contain any values, therefore the Observation.setInterpretation should accept a CodeableConceptDt similar to HL7's API.

**Comment by RJFoster** [comment]
Similarly `DiagnosticServiceSectionCodesEnum` is empty so `DiagnosticReport.setServiceCategory()` can't do anything

**Comment by jamesagnew** [comment]
Ah, thanks for the reminder. I've had a fix ready for this for ages, and needed a push to put it in. Will commit now.
