### ISSUE TITLE
Missing "Total" property in Bundle responses

### ISSUE THREAD

**Issue by flovogt** [jamesagnew/hapi-fhir#1265]
Hi Team,

following issue detected by myself:
The "total" property is missing on the public R4 server http://hapi.fhir.org/baseR4/ for Resource Type patient. I know, this is a performance mechanism, but a server should return for the same request, the same result. So many applications have dependencies to the "total" property, like counters of resource entities.

1. Go to http://hapi.fhir.org/baseR4/Patient
2. No total property is placed in the bundle

**Expected behavior**
A server should return for the same request, the same result. So many applications have dependencies to the "total" property, like counters of resource entities.

Best Regards

**Comment by jamesagnew** [comment]
The `_total` parameter can be used to force the total to be calculated, even for larger search results.

Be warned that this will impact performance though on larger search results, since the database has to perform an additional count(*) query.

E.g.

http://hapi.fhir.org/baseR4/Patient?_total=accurate

**Comment by estani** [comment]
Is this supposed to be working with `_summary` too?
(this is internal, so no access from the outside)
`https://test.fhir-stage.teamedio.com/fhir/Communication?_summary=count&_total=accurate`
returns
```
{
	"resourceType": "Bundle",
	"id": "066ea719-93e5-425b-8385-a4d7f75a6083",
	"meta": {
		"lastUpdated": "2022-10-13T09:34:07.215+00:00",
		"tag": [
			{
				"system": "http://terminology.hl7.org/CodeSystem/v3-ObservationValue",
				"code": "SUBSETTED",
				"display": "Resource encoded in summary mode"
			}
		]
	},
	"type": "searchset"
}
```

I'm missing a `"_total": 0` at least (even though that's not the case)
