### ISSUE TITLE
on Immunization resource some status values are coming out in CAPS

### ISSUE THREAD

**Issue by shayaanmunshi** [jamesagnew/hapi-fhir#1292]
On Immunization resource some status values are coming out in Capital letters

Sample test resource :
{
      "resource": {
        "resourceType": "Immunization",
        "id": "b7747b4e-3604-3298-9c53-a374ed5c9688",
        "text": {
          "status": "generated",
          "div": "<table border = \"1\" width = \"100%\" xmlns=\"http://www.w3.org/1999/xhtml\"><thead><tr><th>Patient Name</th><th>Vaccine</th><th>Route</th><th>Administration Date</th><th>Status</th></tr></thead><tbody><tr><td>Alice Newman</td><td ID = \"immunization12\">influenza intradermal, quadrivalent, preservative free</td><td>Unknown</td><td>20171205170200</td><td>Refused</td></tr></tbody></table>"
        },
        **"status": "STOPPED",**
        "date": "2017-12-05T17:02:00+05:30",
        "vaccineCode": {
          "coding": [
            {
              "system": "http://hl7.org/fhir/sid/cvx",
              "code": "166",
              "display": "influenza intradermal, quadrivalent, preservative free"
            }
          ],
          "text": "influenza intradermal, quadrivalent, preservative free"
        },
        "patient": {
          "reference": "Patient/1",
          "display": "Alice Newman"
        },
        "wasNotGiven": true,
        "reported": false
      }
    }
 {
      "resource": {
        "resourceType": "Immunization",
        "id": "09c6d742-2de4-3a9a-b202-86de310b95ea",
        "text": {
          "status": "generated",
          "div": "<table border = \"1\" width = \"100%\" xmlns=\"http://www.w3.org/1999/xhtml\"><thead><tr><th>Patient Name</th><th>Vaccine</th><th>Route</th><th>Administration Date</th><th>Status</th></tr></thead><tbody><tr><td>Alice Newman</td><td ID = \"immunization14\">tetanus and diphtheria toxoids</td><td>Unknown</td><td>20120104170100</td><td>Administered</td></tr></tbody></table>"
        },
        **"status": "COMPLETED",**
        "date": "2012-01-04T17:01:00+05:30",
        "vaccineCode": {
          "coding": [
            {
              "system": "http://hl7.org/fhir/sid/cvx",
              "code": "106",
              "display": "tetanus and diphtheria toxoids"
            }
          ],
          "text": "tetanus and diphtheria toxoids"
        },
        "patient": {
          "reference": "Patient/1",
          "display": "Alice Newman"
        },
        "wasNotGiven": false,
        "reported": true
      }
    }

 - HAPI FHIR Version: 3.7.0 (Gale)

**Comment by jamesagnew** [comment]
Hi @shayaanmunshi, can you please show a code snippet that reproduces this problem?

**Comment by shayaanmunshi** [comment]
It's working fine....!
Looks like there is no enum defined for Immunization status. Ended up using some other enum .name() in CodeDt object which probably converted the case.

		Immunization obj = new Immunization();
		obj.setStatus(new CodeDt("completed"));				
		String jsonresponseTotest = FhirContext.forDstu2().newJsonParser().setPrettyPrint(true).encodeResourceToString(obj);
		System.out.println(jsonresponseTotest);
{
  "resourceType": "Immunization",
  "status": "completed"
}
