### ISSUE TITLE
Error - HAPI STU3 / R3 - returned HTTP status was 200(Ok) - should be 201(Created)

### ISSUE THREAD

**Issue by Interopguy** [jamesagnew/hapi-fhir#1299]
**Describe the bug**
While testing HAPI with Touchstone - Test Script 

Test Script: /FHIR3-0-1-Basic/A-C/AllergyIntolerance/Client Assigned Id/AllergyIntolerance-client-id-xml

Test System: http://fhirtest.uhn.ca/baseDstu3

Error message below

Operation | updateCreate AllergyIntolerance
Status HTTP/1.1 200 OK
Resource AllergyIntolerance  ID gJsx-TxRLA6JQA

**To Reproduce**
1. Go to Touchstone / Login
2. Select Test Definition / FHIR3-0-1-Basic  
3. Expand A-C, AllegryIntolerance
4. Select Check-box /FHIR3-0-1-Basic/A-C/AllergyIntolerance/Client Assigned Id/AllergyIntolerance-client-id-xml
5. Create Test Setup
6. Destination (FHIR) Server:  James Agnew - HAPI / UHN STU3
7. Execute

Expected behavior**
Status:  HTTP/1.1 201 Created

**Screenshots**

**Comment by patrick-werner** [comment]
just had a look at the testscript. This is a test using UPDATE to create a resource with a given ID.
I tried the test with an empty server -> works as expected, return value = 201.

The testscript reuses the ID in every test and deletes the generated resource after the creation. During the next test run this deleted resource is updated to be not deleted anymore. This is considered as an update by hapi so the returned status code = 200.
I think this behaviour is fine as a deleted resource is updated.
@jamesagnew your thoughts on this?

**Comment by jamesagnew** [comment]
Innnnnteresting.

@patrick-werner I agree with your assessment.

@Interopguy Are you guys able to modify the test to delete the resource first if it already exists?

**Comment by patrick-werner** [comment]
@jamesagnew the resource is already deleted before the test starts, but as it isn't expunged. So hapi already knows this id.

**Comment by jamesagnew** [comment]
Ohhhhh.... In that case I kinda think this is a HAPI FHIR bug after all.
This is a pretty niche edge case but I think it's fair to say that updating
a previously deleted resource counts as a create and should return a 201.

This is mostly personal opinion of course, but I think it makes sense..

**Comment by Interopguy** [comment]
Hello Patrick,

  We enjoy the conversation(s) - thanks for the feedback …  James - yes, we do delete prior to the next run (I think that is what Patrick is reporting) while the resource is present it is in a deleted status.  So, if you create/update against an existing resource (which is in a sense an Update and not a Create) - does the status of the resource i.e. "Deleted" change the operation outcome to an Update (200-ok) or should it be a Create (201-Created, due to it being in a delete status) -

  I like Innnnnteresting :)

  I see the order of the test script executions makes it appear that XML is only affected.  I see why it happens with the XML Client-Assigned ID test script execution, and not when I run the JSON test script - I receive the 201(Created) as expected.

  I have added Richard Ettema (AEGIS - FHIR guy) to the conversation for situational awareness, and comment.

Thanks,
Mario



________________________________

**Comment by jamesagnew** [comment]
Ok, this is fixed.
