### ISSUE TITLE
Narrative generator generates schema-non-compliant narrative for resources that don't have an html specified

### ISSUE THREAD

**Issue by wdebeau1** [jamesagnew/hapi-fhir#130]
In at least some cases, seeing Condition with a narrative like this:
	<text>
		<status value="generated"/>
	</text>
But the schema requires that narrative has a div present

**Comment by jamesagnew** [comment]
I think there is some text in this report missing.. :)

**Comment by wdebeau1** [comment]
Odd, it was there when I pasted it.
Basically, what I'm seeing is a narrative that has a <status value="generated" />
But no <div
section

**Comment by jamesagnew** [comment]
Lol, it happened again! I think GitHub is treating your resource tags as HTML content..
Try putting \`\`\` around your examples, e.g. (ignore the backslashes in the example below)
```
\`\`\`
<Patient blah/>
\`\`\`
```

Any chance you are able to reproduce in a code snippet?

**Comment by jamesagnew** [comment]
Closing. FIxed by https://github.com/jamesagnew/hapi-fhir/commit/c7558c77802e2d694d9779564a0a92db54e270f8
