### ISSUE TITLE
DateParam can't serialize hapi-fhir-osgi-core-2.0 

### ISSUE THREAD

**Issue by Nilsaw** [jamesagnew/hapi-fhir#1307]
Hello, 

I am using hapi-fhir-osgi-core-2.0 for making client service calls to the FHIR server and
I want to make date range queries but they do not seem to work.

Can someone guide me on making the right query call if I am doing something wrong here?

 - HAPI FHIR Version  - hapi-fhir-osgi-core-2.0 

Only a single date query works for dates greater than the required date
Here are my queries which work.

http://server:port/context/fhir/Task?status=completed&created=gt2019-05-06&_include=*
http://server:port/context/fhir/Task?status=completed&created=>2019-05-06&_include=*

Here are the queries and the errors I experience for a less than date query:
Query:  
http://server:port/context/fhir/Task?status=completed&created=lt2019-05-06&_include=*
http://server:port/context/fhir/Task?status=completed&created=<2019-05-06&_include=*
Error: can't serialize class ca.uhn.fhir.rest.param.DateParam

Here are the queries and the errors I experience for a date range query which I have created:
Query:  
http://server:port/context/fhir/Task?status=completed&created=lt2019-05-06gt2019-05-10&_include=*
http://server:port/context/fhir/Task?status=completed&created=>2019-05-06<2019-05-10&_include=*

Error: 
110 - hapi-fhir-osgi-core - 2.0.0 | Failure during REST processing: ca.uhn.fhir.parser.DataFormatException: Invalid date/time format: "2019-05-06gt2019-05-10": Expected character 'T' at index 10 but found g
ca.uhn.fhir.parser.DataFormatException: Invalid date/time format: "2019-05-06gt2019-05-10": Expected character 'T' at index 10 but found g
	at ca.uhn.fhir.model.primitive.BaseDateTimeDt.throwBadDateFormat(BaseDateTimeDt.java:469)[110:hapi-fhir-osgi-core:2.0.0]

**Comment by jamesagnew** [comment]
HAPI FHIR 2.0 is an ancient version of the software, so you really shouldn't be reporting issues against it unless you have verified that they still occur in the latest build. You can use current builds (3.7.0) in an OSGI container without requiring a special OSGI build. I'd recommend testing with that version.

That said, your query is not valid. You can't combine two dates into a single value.

I.e. this is not valid:

`&created=>2019-05-06<2019-05-10`

Instead you should be doing the following:

`&created=gt2019-05-06&created=lt2019-05-10`

**Comment by Nilsaw** [comment]
Thanks for the really quick response :). We are moving this application to Smart on FHIR in the next couple of months.
