### ISSUE TITLE
AuthenticationException in IServerInterceptor

### ISSUE THREAD

**Issue by romvlvs** [jamesagnew/hapi-fhir#1309]
Most methods of IServerInterceptor.java thrown AuthenticationException with http code 401. According to https://tools.ietf.org/html/rfc7235#section-3.1, " The 401 (Unauthorized) status code indicates that the request has not been applied because it lacks valid authentication credentials for the target resource."
In practice we want to use other BaseServerResponseException type, for example ForbiddenOperationException. I suggest changing AuthenticationException to BaseServerResponseException in IServerInterceptor.java

**Comment by jamesagnew** [comment]
I'm not sure I understand this request. IServerInterceptor is an interface, it doesn't throw any exceptions on its own.. and you are welcome to throw any of HAPI's standard exceptions from any method you implement in an interceptor, depending on the logic you're trying to convey.

AuthenticationException is specifically called out in the javadocs a few times as it has special processing, if that's what you're referring to?

**Comment by romvlvs** [comment]
Thank you for your answer. I can explain more clearly:
In the interface definition the method `incomingRequestPostProcessed` throws only `AuthenticationException`. Our subclass wants to thrown other `BaseServerResponseException` type, for example `ForbiddenOperationException`.  
According to the definition basically we shouldn't throw other Exception in implementation of `incomingRequestPostProcessed` other than `AuthenticationException`.

**Comment by jamesagnew** [comment]
FYI all of the BaseServerResponseException classes are unchecked so it is
possible to throw any of them from any interceptor method.

Will update the docs to be more clear on that fact.
