### ISSUE TITLE
Write a resource with its id and make it searchable

### ISSUE THREAD

**Issue by Yohan-Bismuth** [jamesagnew/hapi-fhir#1315]
**Describe the issue**
We are trying to migrate data from a hapi-fhir backend 3.2.0 to a new one upgraded in 3.7.0. We have two constraints: 
-no down time of the api or almost (which means we cannot lock the tables for upgrade)
-a same resource must keep the same id between the two databases

For that, we're trying to read resources in 3.2.0, encode them to json, and send them to the new backend in 3.7.0 using the generic fhir client. In that process, we use the "update" method of the client so we can specify an id that is taken into account in the payload. 

From what I understand, the new backend will populate a HFJ_FORCED_ID table and map the forced_id with the actual res_id in the db. This works fine for us until we try to use the SearchBuilder to loadResourcesByPid, which calls doLoadPids. If we pass a list of forced_id to this method, no resource is found.

It seems the call to myResourceSearchViewDao.findByResourceIds(thePids) doesn't find any of the forced_id we pass.
```
private void doLoadPids(List<IBaseResource> theResourceListToPopulate, Set<Long> theIncludedPids, boolean theForHistoryOperation, EntityManager theEntityManager, FhirContext theContext, IDao theDao, Map<Long, Integer> thePosition, Collection<Long> thePids) {

		// -- get the resource from the searchView
		Collection<ResourceSearchView> resourceSearchViewList = myResourceSearchViewDao.findByResourceIds(thePids);
```

I believe this happens because 
```
public interface IResourceSearchViewDao extends JpaRepository<ResourceSearchView, Long> {
	@Query("SELECT v FROM ResourceSearchView v WHERE v.myResourceId in (:pids)")
	Collection<ResourceSearchView> findByResourceIds(@Param("pids") Collection<Long> pids);
}
```
this query looks for v.myResourceId in the view.

Do you have any idea how I could make it work ? 

**Environment (please complete the following information):**
 - HAPI FHIR Version: 3.7.0
 - OS: ubuntu 4.18.0-18-generic
 - Browser: chrome

**Comment by jamesagnew** [comment]
Hi @Yohan-Bismuth -

(FYI, this should really be discussed in the Google Group as it is not a bug. Please see [this page](https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help) for info on getting help with HAPI FHIR)

You can probably solve this using HAPI FHIR 3.8.0-SNAPSHOT by setting the Client ID Strategy to "ANY". That will allow you to assign numeric client IDs via the external REST interface, and will allow purely numeric forced IDs. These are not supported in previous versions of HAPI FHIR.

This is the setting you're looking for:
https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/DaoConfig.java#L1619
