### ISSUE TITLE
Searchset Bundle includes response

### ISSUE THREAD

**Issue by chrisgrenz** [jamesagnew/hapi-fhir#1328]
GET http://hapi.fhir.org/baseR4/Organization

Returned searchset bundle includes entries including:

{
...resource here...
},
"search": {
  "mode": "match"
},
"response": {
  "status": "200 OK",
  "etag": "W/\"2\""
}

the inclusion of response makes the bundle invalid by bdl-4

**Comment by chrisgrenz** [comment]
Sorry - looks like a duplicate of #1250

**Comment by jamesagnew** [comment]
Closing for duplicate, but thanks for reporting :)
