### ISSUE TITLE
Problem: Project Problem: Parent POM file is not accessible. Project might be improperly setup., resolvable by: org.netbeans.modules.maven.problems.ProblemReporterImpl$MavenProblemResolver@475e5a82 unresolved

### ISSUE THREAD

**Issue by kkatsoulas** [jamesagnew/hapi-fhir#133]
The parent POM with id org.sonatype.oss:oss-parent:9 was not found in sources or local repository. Please check that <relativePath> tag is present and correct, the version of parent POM in sources matches the version defined. 
If parent is only available through a remote repository, please check that the repository hosting it is defined in the current POM.

**Comment by jamesagnew** [comment]
Hi there,
According to Maven that POM exists in the central repo: http://search.maven.org/#artifactdetails|org.sonatype.oss|oss-parent|9|pom

Is this still happening? Does it happen if you build via the command line as well, or just in Netbeans?

Cheers, James

**Comment by jamesagnew** [comment]
No response, closing.

**Comment by AkhilCasey** [comment]
Non-resolvable parent POM: Failure to find com.sample:sample-master-parent:pom:3.0.4 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 3, column 10 ->

im getting this issue . need help
