### ISSUE TITLE
performance testing

### ISSUE THREAD

**Issue by wanghaisheng** [jamesagnew/hapi-fhir#134]
is there any plan about performance testing
XML JSON  seriliazation and deseriliazation is the most time consuming part

**Comment by jamesagnew** [comment]
Definitely agreed, we should do some performance work on the parsers soon. We did a bunch of profiling on the startup time in the last round, and made some improvements but haven't gotten to the parsers yet. I'm marking this as helpwanted in case anyone wants to get to it first.

I'm thinking a likely place to start would be BaseRuntimeDeclaredChildDefinition.java, which is where all of the field reflection happens. We should investigate using ASM or Javassist or something to speed this up. Another possibility would be to use code-genned helper methods to replace some of the reflection (we use this strategy in HAPI for HL7v2 and it had a dramatic effect actually).
