### ISSUE TITLE
Spring Boot Sample: Invalid hapi.fhir.server.path makes server respond invalid path

### ISSUE THREAD

**Issue by longnguyen2306** [jamesagnew/hapi-fhir#1340]
**Describe the bug**
The bug can be reproduced by clone the repo at https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-fhir-spring-boot/hapi-fhir-spring-boot-samples/hapi-fhir-spring-boot-sample-server-jpa and run the Spring Application. Server will always responds with a small "*" in the response's url. For example searching all Patients with `http://localhost:8080/fhir/Patient` will return:

```json
{
"resourceType": "Bundle",
"id": "be9cb1c5-f810-413c-bbd6-59f37d602d9b",
"meta": {
"lastUpdated": "2019-06-09T10:34:19.579+02:00"
},
"type": "searchset",
"total": 0,
"link": [
  {
"relation": "self",
"url": "/fhir/*/Patient"
}
],
}
```

Take a look at the url /fhir/*/Patient. This url is not valid.

**To Reproduce**
1. Go to https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-fhir-spring-boot/hapi-fhir-spring-boot-samples/hapi-fhir-spring-boot-sample-server-jpa
2. Click on application.yml
3. Scroll down to 
```
hapi:
  fhir:
    version: dstu3
    server:
      path: /fhir/*
```

**Expected behavior**
I expect the server to response with a valid url. For example: 
```json
{
"resourceType": "Bundle",
"id": "be9cb1c5-f810-413c-bbd6-59f37d602d9b",
"meta": {
"lastUpdated": "2019-06-09T10:34:19.579+02:00"
},
"type": "searchset",
"total": 0,
"link": [
  {
"relation": "self",
"url": "/fhir/Patient"
}
],
}
```

Specs:

* Java 12
* Hapi Fhir 3.8.0, latest version directly clone from master

**Comment by hc1jgniffke** [comment]
I am running into the same issue.  What was the fix?

**Comment by flyaruu** [comment]
@longuyen97 Did you do anything special to resolve this? I got the same issue.

**Comment by longuyen97** [comment]
@flyaruu I had to stop using the Spring Boot version and used instead https://github.com/hapifhir/hapi-fhir-jpaserver-starter

**Comment by frostmarked** [comment]
I think this issue should be reopened. It seems like the FhirAutoConfiguration uses the property hapi.fhir.server.path for two different purposes. 
1. Url-mappings in servlet bean, therefore wildcard
[https://github.com/hapifhir/hapi-fhir/blob/b27559caa4e0a4735f11ba67bdbd578e7d7c4c66/hapi-fhir-spring-boot/hapi-fhir-spring-boot-autoconfigure/src/main/java/ca/uhn/fhir/spring/boot/autoconfigure/FhirAutoConfiguration.java#L150](url)
2. Probably as the actual base-path, when generating urls
[https://github.com/hapifhir/hapi-fhir/blob/b27559caa4e0a4735f11ba67bdbd578e7d7c4c66/hapi-fhir-spring-boot/hapi-fhir-spring-boot-autoconfigure/src/main/java/ca/uhn/fhir/spring/boot/autoconfigure/FhirAutoConfiguration.java#L163](url)

Maybe something as simple as
```
String urlMapping = this.properties.getServer().getPath() + "/*";
ServletRegistrationBean registration = new ServletRegistrationBean(this, urlMapping);
```
would resolve this

**Comment by esbakker** [comment]
I ended up implementing a FhirRestfulServerCustomizer that removes the `/*` from the serverAddressStrategy:

```java
@Component
public class ServerAddressStrategyCustomizer implements FhirRestfulServerCustomizer {

    @Override
    public void customize(RestfulServer server) {
        HardcodedServerAddressStrategy serverAddressStrategy = (HardcodedServerAddressStrategy) server.getServerAddressStrategy();
        serverAddressStrategy.setValue(serverAddressStrategy.getValue().replace("/*", ""));
    }
}
```
