### ISSUE TITLE
Consider removing Eclipse artifacts from project

### ISSUE THREAD

**Issue by mdgeek** [jamesagnew/hapi-fhir#135]
The inclusion of Eclipse artifacts (.settings, .project, .classpath) is a bit of a pain when doing pulls as they always trigger a merge.  We routinely exclude these from our commits for that reason.  This is a gentle request to remove them.

**Comment by jamesagnew** [comment]
This seems reasonable, we probably should have done so long ago.
In the old days, Eclipse's Maven support was awful and checking in your eclipse files made it a bit less painful to deal with.. but these days that just doesn't seem to be the case any more.

**Comment by XcrigX** [comment]
I still see .project, .settings, .classpath files/folders sprinkled all throughout the project. 

If you do want to attempt to remove them, here is a recipe I follow:

First add/commit any current changes, obviously. 

Then update the root .gitignore file, I use https://www.gitignore.io to assist generating gitignore files. Pretty handy.. 

You can use this command to then see the files in the project that correspond to ignored files:
git ls-files -i --exclude-from=.gitignore

And this to remove them from git tracking without removing them from your local disk:
git rm --cached 'git ls-files -i --exclude-from=.gitignore'

Source:
https://stackoverflow.com/questions/13541615/how-to-remove-files-that-are-listed-in-the-gitignore-but-still-on-the-repositor
