### ISSUE TITLE
Consider publishing a BOM POM

### ISSUE THREAD

**Issue by srdo** [jamesagnew/hapi-fhir#1351]
**Describe the issue**
HAPI FHIR consists of a decent number of modules at this point. Users need to repeatedly specify the same version when declaring a dependency on HAPI FHIR. In addition, user projects may include HAPI FHIR and also use other projects that themselves use HAPI FHIR (e.g. Camel's [camel-fhir](https://github.com/apache/camel/tree/c3da2b0d3bb5fb8d3c2803d8bef4fc6258d7470f/components/camel-fhir) module)

It is inconvenient to have to repeatedly specify the same version number in your POM/gradle file, and it is easy to accidentally mix up HAPI FHIR versions in the same project. For example, if your project uses `hapi-fhir-structures-dstu3:3.7.0`, and you include `camel-fhir`, you end up with the following jars on the classpath:

```
hapi-fhir-structures-dstu3:3.7.0
hapi-fhir-base:3.7.0
hapi-fhir-client:3.5.0
hapi-fhir-structures-dstu2:3.5.0
```

It would be better if I could declare a dependency on a BOM POM in version 3.7.0, and ensure that all HAPI FHIR jars are the same version.

A BOM POM is a POM that lists all the modules published by a project, in a `dependencyManagement` section. The idea is that users can import this POM in their own POM/Gradle file, which will cause all HAPI FHIR dependencies to resolve to the version defined in the BOM.

Here's an example of how a user would use the BOM (Gradle has a similar mechanism):
```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-bom</artifactId>
            <version>4.0.0</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>   
    </dependencies>
</dependencyManagement>
```
This will cause any HAPI FHIR module in that project to lock to version 4.0.0.

Examples of other multimodule projects that use BOMs:
Jackson https://github.com/FasterXML/jackson-bom
JUnit https://junit.org/junit5/docs/current/user-guide/#dependency-metadata-junit-bom
Camel https://github.com/apache/camel/blob/master/bom/camel-bom/pom.xml

**Comment by jamesagnew** [comment]
Cool! I was unaware of this concept.. All of my own internal projects just use the root hapi-fhir POM as the parent pom, which sort-of accomplishes the same thing, but this seems like a nicer way of doing it.

**Comment by srdo** [comment]
Great. I'll try to put up a PR for a BOM in the next few days.
