### ISSUE TITLE
Failed to call access method: java.lang.NullPointerException in case of bundle entry without resource

### ISSUE THREAD

**Issue by lytvynenko-dmitriy** [jamesagnew/hapi-fhir#1355]
**Describe the bug**
Failed to call access method: java.lang.NullPointerException in case of bundle entry without resource

**To Reproduce**
1. Create fhir.bundle.xml with a body:
```
<Bundle xmlns="http://hl7.org/fhir">
 <entry>
      <request>
         <method value="POST"/>
         <url value="CarePlan"/>
      </request>
   </entry>
</Bundle>
```
2. Run:

`curl -X POST -H "Content-Type: application/xml" -d @fhir.bundle.xml  http://localhost:8080/R4`

The issue is also reproduced on http://hapi.fhir.org/baseR4:

`curl -X POST -H "Content-Type: application/xml" -d @fhir.bundle.xml  http://hapi.fhir.org/baseR4`

3. Find next in the response:
```
<OperationOutcome xmlns="http://hl7.org/fhir">
   ...
   <issue>
      <severity value="error"/>
      <code value="processing"/>
      <diagnostics value="Failed to call access method: java.lang.NullPointerException"/>
   </issue>
</OperationOutcome>
```

**Expected behavior**
Clear description of what's wrong with the Bundle.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 3.7.0
 - Data models: R4

**Comment by jamesagnew** [comment]
Thanks for reporting! Fix checked in.

**Comment by pramodmurthy** [comment]
I am getting the same error with the attached bundle when I post it to the HAPI fhir public test server. Any suggestion would be appreciated..
[FHIRoutput.zip](https://github.com/hapifhir/hapi-fhir/files/14167251/FHIRoutput.zip)
