### ISSUE TITLE
Use POST in place of GET for reading resources in HAPI Server?

### ISSUE THREAD

**Issue by snimmagadda1** [jamesagnew/hapi-fhir#1365]
**Describe the issue**
For reasons that I cannot go into, I have the requirement to not support GET requests in my FHIR application. I'm looking to use the HAPI JPA server to expose FHIR resources i.e CRUD. Is it possible to instead use POST for reads i.e POST to /Patient/1 or POST to /Patient/read instead of the traditional GET to /Patient/{id}

**Environment (please complete the following information):**
 - HAPI FHIR Version: 3.8.0
 - OS: NA
 - Browser: NA

**Comment by jamesagnew** [comment]
HI @snimmagadda1 - Please see this page for information on where to get help with HAPI FHIR: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Comment by snimmagadda1** [comment]
Ah @jamesagnew apologies. Thanks!

**Comment by jamesagnew** [comment]
No worries!
