### ISSUE TITLE
I am trying to connect a simple app to the hapi fhir, however the class I imported such as AsyncTask and Activitity.java seems to include errors. How can I fix it because it seems that the libraries are recognised but not their path.

### ISSUE THREAD

**Issue by Imane81** [jamesagnew/hapi-fhir#1374]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version

**Additional context**

**Comment by jamesagnew** [comment]
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
