### ISSUE TITLE
Add ServerAddressStrategy that deals with proxied requests

### ISSUE THREAD

**Issue by wdebeau1** [jamesagnew/hapi-fhir#138]
If an incoming request goes through a proxy server, IncomingAddressStrategy will use the final address in any urls it makes. This will normally result in resource references and ids that aren't readable to the client, since presumably the final server is behind a firewall somewhere.

It'd be useful to have an address strategy that uses x-forarded-host to determine whether a request had been proxied, and if so, use the host as specified by the client.

**Comment by jamesagnew** [comment]
Just wanted to comment: this is really nicely done, what a good idea.

**Comment by jvitrifork** [comment]
just what I needed
