### ISSUE TITLE
After the resource is created, it cannot be queried immediately.

### ISSUE THREAD

**Issue by navyflower** [jamesagnew/hapi-fhir#1389]
- HAPI FHIR Version 3.8.0

Query by identifier, if it exists, update it, if it does not exist, create resource.
Create a resource with identifier by using the following code:

FhirContext fhirContext = FhirContext.forR4();
client = fhirContext.newRestfulGenericClient("http://xxxxxxxxxx/baseR4");
client.setPrettyPrint(true);
client.setEncoding(EncodingEnum.JSON);
client.create().resource(baseResource).execute()
IIdType resId = entity.getId();

After the creation is successful, the query is performed by identifier, but it is not queried. After waiting for a few seconds, it can be found. Why is this happening? The code is as follows:

IUntypedQuery search = client.search();
IQuery query = search.forResource(xxxclass);
Class<? extends IBaseBundle> bundleType;
bundleType = (Class<? extends IBaseBundle>) client.getFhirContext().getResourceDefinition("Bundle").getImplementingClass();
IQuery<?> queryTyped = query.returnBundle(bundleType);
Bundle bundle = null;
query.where(new TokenClientParam("identifier").exactly().systemAndCode("system value", "code value"));
bundle = (Bundle)queryTyped.execute();

Performed the following test again:
Do not search first, create resources directly, and then search,  retrieve data immediately

**Comment by jamesagnew** [comment]
This sounds like you're just experiencing the query cache.

Some information here: http://hapifhir.io/doc_jpa.html#_toc_search_result_caching

And much more detail here: https://smilecdr.com/docs/current/fhir_repository/performance_and_caching.html

**Comment by navyflower** [comment]
> This sounds like you're just experiencing the query cache.
> 
> Some information here: http://hapifhir.io/doc_jpa.html#_toc_search_result_caching
> 
> And much more detail here: https://smilecdr.com/docs/current/fhir_repository/performance_and_caching.html

Thank you very much, according to your prompt, add the following code when querying, no problem.

query.withAdditionalHeader("Cache-Control", "no-cache");

thank you again
