### ISSUE TITLE
Bulk data API support: Type fhir+ndjson

### ISSUE THREAD

**Issue by citizenrich** [jamesagnew/hapi-fhir#1411]
**Describe the issue**

This is just a little issue to track support for newline-delimited JSON (ndjson) in HAPI for export and import. Mime type `fhir+ndjson` is the preferred data structure for the emerging Bulk Data API https://github.com/hl7/bulk-data

**Environment (please complete the following information):**
 - HAPI FHIR Version: 3.8
 - OS: macOS 10.14.6
 - Any

**Comment by citizenrich** [comment]
Landed in master in September. Closing. Thanks!

https://github.com/jamesagnew/hapi-fhir/commit/4a751cbfc5a43f28bc0f70e765731fcc525ae6cc

**Comment by jamesagnew** [comment]
Ah awesome, thanks for closing!
