### ISSUE TITLE
Invalid DateTime e.g. 2015-02-30, 2015-04-32 will be translated to 2015-03-02, 2015-05-02 automatically

### ISSUE THREAD

**Issue by chelseag** [jamesagnew/hapi-fhir#142]

**Comment by xinanz** [comment]
Are there any plans to address this issue?

**Comment by SarenCurrie** [comment]
According to the Fhir standard, dates should follow this regex:
`-?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1]))?)?`

Which means that 2017-03-32 is not a valid date, but 2017-02-29 is.

>Dates SHALL be a valid date

https://www.hl7.org/fhir/datatypes.html

**Comment by jamesagnew** [comment]
This was actually addressed in HAPI 2.2, but this bug never got closed. Sorry!

Closing it now. I've added a unit test for the specific example in the title too.
