### ISSUE TITLE
Missing method: Encounter hasServiceProviderTarget()

### ISSUE THREAD

**Issue by svenhaag** [jamesagnew/hapi-fhir#1423]
hapi-fhir-structures-dstu3
version: 3.7.0

org.hl7.fhir.dstu3.model.Encounter is missing the method `hasServiceProviderTarget()`.

**Comment by jamesagnew** [comment]
The getFooTarget() methods are actually being deprecated as they are duplicates of the equivalent method on resource. I'd recommend migrating to using
```encounter.getServiceProvider().getResource()```
