### ISSUE TITLE
How to pass Keystore datails while making a bundle call through IGeneric client

### ISSUE THREAD

**Issue by ArunKalvapalli** [jamesagnew/hapi-fhir#1426]

**Comment by ArunKalvapalli** [comment]
Patient p = null;
FhirContext ctx = FhirContext.forDstu3();
IRestfulClientFactory clientFactory = new ApacheRestfulClientFactory(ctx);

// KeyStore & TrustStore
System.setProperty("javax.net.ssl.keyStoreType", keyStoreType);
System.setProperty("javax.net.ssl.keyStoreAlias", keyStoreAlias);
 System.setProperty("javax.net.ssl.keyStore", keyStore);
 System.setProperty("javax.net.ssl.keyStorePassword", keyStorePassword);
 System.setProperty("javax.net.ssl.trustStore", trustStore);
System.setProperty("javax.net.ssl.trustStorePassword", trustStorePassword);
 System.setProperty("javax.net.ssl.trustStoreType", trustStoreType);
 System.setProperty("javax.net.debug", "ssl");
		
// Register Interceptor 
InterceptorClass interceptor = new InterceptorClass();		
client.registerInterceptor(interceptor);
	
logger.trace("TIMER for fhir server calls to fetch Patient details begin...");
Stopwatch timer1 = Stopwatch.createStarted();
for (int i = 0; i < numRetries; ++i) {
	logger.trace("Fhir server call for mrn "+ mrn+ " for trial "+ i);
	try {
	      Bundle b = client.search()
		    			.forResource(Patient.class)
		    			.where(ca.uhn.fhir.model.dstu2.resource.Patient.IDENTIFIER
		    						.exactly()
		    						.systemAndCode(oid, mrn))
		    			.and(ca.uhn.fhir.model.dstu2.resource.Patient.LINK.hasId(Long.toString(userId)))		    			
		    			.returnBundle(Bundle.class)
		    			.execute();
				List<BundleEntryComponent> entries = b.getEntry();
}
catch (Exception e) {
				// TODO: Log exception
				logger.trace("Exception cause : cause " + e.getCause().getCause());
				logger.trace("Exception cause : Message " + e.getCause().getMessage());
				logger.trace("Exception cause : StackTrace " + e.getCause().getStackTrace());
				logger.trace("Exception cause : Suppressed " + e.getCause().getSuppressed());	
				
				logger.trace("Exception detail message : " + e.getMessage());
				logger.trace("Exception's stck trace :: " + e.getStackTrace());
				e.printStackTrace();				
				logger.error(e);
				if (i == numRetries) throw new BundleParseException();
			}
		}		
		// Unregister the interceptor
		client.unregisterInterceptor(interceptor);
		return p;

**Comment by ArunKalvapalli** [comment]
Am I missing any thing in this. Is this the right approach??

**Comment by jamesagnew** [comment]
Hi @ArunKalvapalli . Please see [this wiki page](https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help) for information on where to get help with HAPI FHIR.
