### ISSUE TITLE
R4 FhirInstanceValidator ends up using R5 InstanceValidator

### ISSUE THREAD

**Issue by sdatchley** [jamesagnew/hapi-fhir#1427]
Exploring loading us core ig pack using R4 and noticed during my testing that org.hl7.fhir.r4.hapi.validation.FhirInstanceValidator.validate returns a org.hl7.fhir.common.hapi.validation.ValidatorWrapper which in it's validate specifically creates a org.hl7.fhir.r5.validation.InstanceValidator.InstanceValidator instead of the R4 version. Just wanted to check if this is intended since the R5 version uses a number of R5 classes. 

I'm using 4.0.0 btw.

Thanks!
Dean

**Comment by jamesagnew** [comment]
This is intentional. The latest version of the validator (currently R5) is the only one that is seriously maintained, and it is able to validate all versions of FHIR, so it's the one we use for validating DSTU3 and up (DSTU2 has some complications because of the old HAPI structures).
