### ISSUE TITLE
Allow externalized Query Cache

### ISSUE THREAD

**Issue by jamesagnew** [jamesagnew/hapi-fhir#1440]
This is a ticket to track the the separation of the JPA server query cache into its own service, so that it can be left intact or subbed out with an alternate implementation.

The initial alternate implementation will be the InfiniSpan cache.

- [x] Split the query cache into its own service. This service should have the exact same semantics as the existing implementation, so it is just a refactoring of existing DAO code out of the DAO.
- [x] Bonus: Make sure that we don't hammer the DB with updates to the "Search last used" time if a seach is reused frequently (we do this currently)

**Comment by jvitrifork** [comment]
Are there any current problems with an InfiniSpan cache?

**Comment by jamesagnew** [comment]
Nope- I just jumped the gun on this ticket a bit. Infinispan grid cache support is a Smile CDR feature. This ticket is a dependency to that feature, but more importantly includes direct HAPI FHIR performance improvements, hence the renaming.
