### ISSUE TITLE
hapi-fhir-utilities 4.0.0 not published?

### ISSUE THREAD

**Issue by johngrimes** [jamesagnew/hapi-fhir#1456]
**Describe the bug**

All of the HAPI Maven artifacts on Maven Central seem to have been updated to 4.0.0, except `hapi-fhir-utilities`. It is still at 3.8.0.

**To Reproduce**

Check out: https://search.maven.org/search?q=g:ca.uhn.hapi.fhir%20AND%20a:hapi-fhir-utilities&core=gav
And: https://search.maven.org/search?q=g:ca.uhn.hapi.fhir

**Expected behavior**

I would expect all of the 4.0.0 versions of the modules to be published.

I would also expect `hapi-fhir-utilities` to still be a dependency for all HAPI projects, as it says it is here: http://hapifhir.io/download.html

**Comment by johngrimes** [comment]
I got it to work by using ca.uhn.hapi.fhir:org.hl7.fhir.utilities:4.0.0.

`¯\_(ツ)_/¯`

**Comment by jamesagnew** [comment]
The `hapi-fhir-utilities` module was discontinued, as it is completely superceded by `org.hl7.fhir.utilities`. Any HAPI FHIR modules that needed the former now automatically import the latter via Maven, so I had assumed this would be an invisible change. 

Is there something out there depending explicitly on the old module?

**Comment by johngrimes** [comment]
The only one I know of is `XhtmlNode`.

This is used in the public API, e.g. `org.hl7.fhir.dstu3.model.Narrative.setDiv(XhtmlNode value)`.

**Comment by jamesagnew** [comment]
XhtmlNode can be found in `org.hl7.fhir.utilities` though, which is explicitly imported by the POM of the hapi-fhir-structures-dstu3 project as of HAPI FHIR 4.0.0, so I'm not clear on how this would cause issues?

**Comment by johngrimes** [comment]
I noticed this in cerner/bunsen, in their bunsen-core module, which does not explicitly depend upon the hapi-fhir-structures. 

I think for this library the user opts in to STU3 or R4 by depending upon an additional module which is FHIR version specific.

**Comment by jamesagnew** [comment]
A note has been added to the download page about the removal of this module
