### ISSUE TITLE
_history can be used to check existence of foreign tenant resources

### ISSUE THREAD

**Issue by der-brecher** [jamesagnew/hapi-fhir#1484]
HAPI v4.0.0

If you have multple tenants configured and create a resource, e.g. Patient/1, as tenant a and you access Patient/1/_history as tenant b you get an empty history indicating that the guessed resource exists for another tenant. Actually, the correct reaction is to return an HTTP-404 for this very resource. This happens if a specific version is requested by tenant b, e.g., Patient/1/_history/1 returns a 404 which is perfectly fine.

This could be used for security attacks.

This is how the empty history looks like for Observation/1702/_history as a foreign tenant:

```
{
  "resourceType": "Bundle",
  "id": "7eb9c188-2648-4fb0-963e-c06c0666e682",
  "meta": {
    "lastUpdated": "2019-09-12T13:57:37.933+02:00"
  },
  "type": "history",
  "link": [
    {
      "relation": "self",
      "url": "http://localhost:8080/hapi-fhir-jpaserver/b/Observation/1702/_history"
    }
  ]
}
```

**Comment by der-brecher** [comment]
Yes, I used a UrlBaseTenantIdentificationStrategy and customized RPs to delegate the tenant ids to the resources' meta data. Using a ConsentInterceptor I filter for the tenant id on retrieval. I was just wondering whether this foreign tenant resource lookup could be used for some attack or at least to spy data

**Comment by jamesagnew** [comment]
This sounds like an issue with your tenancy implementation.. What are you requesting we fix in this bug?

**Comment by der-brecher** [comment]
I think an HTTP-404 should arrise for a GET on a _history of an existing resource of a foreign tenant. 

As I tried, this already works for _specific_ _history/<version>s but not for the whole _history, i.e., <foreign tenant resource>/_history gives you an empty history which indicates the existence of the resource on which the requester does not have access to but this should be an HTTP-404. Whereas <foreign tenant resource>/_history/<specific version> works fine and reports a 404.

**Comment by der-brecher** [comment]
Or do you think, I miss something in the tenancy implementation? How can I invalidate the request to a foreign tenant resource's history? For access control, I use the AuthorizationInterceptor which appends the tenant id for each request.

**Comment by jamesagnew** [comment]
Maybe I'm misunderstanding the issue here, but if the JPA server doesn't support multitenancy, and you add it yourself and it's not working, I don't understand how we could fix that...

Are you able to submit a unit test that demonstrates the issue against HAPI?

**Comment by jamesagnew** [comment]
Closing this, as it hasn't had any follow up.

@der-brecher Please leave a comment if you feel that this is an error. I do want to address any potential security issues in HAPI, but it's not clear to me how we could address (or even reproduce) this one.
