### ISSUE TITLE
Unicode Entities converted to HTML entities in Narrative

### ISSUE THREAD

**Issue by beichhor** [jamesagnew/hapi-fhir#1488]
**Describe the bug**
When using HAPI as a client, Resource.text.div is parsed Unicode entities are parsed and converted to HTML entities producing invalid XML.

**To Reproduce**
1. Using HAPI as a client have HAPI call:
    - https://fhir-open.sandboxcerner.com/r4/0b8a0111-e8e6-4c26-a91c-5069cbc6b1ca/Device/15575768

**Expected behavior**
The Narrative content does not have unicode characters converted to HTML entities.

**Screenshots**
![Screen Shot 2019-09-16 at 12 48 22 PM](https://user-images.githubusercontent.com/8973530/64980840-5382b800-d880-11e9-9069-50aee069764c.png)

**Environment (please complete the following information):**
 - HAPI FHIR Version: 4.0.0
 - OS: Mac OS 10.14.6
 - Browser: Chrome

**Additional context**
Using Cerner's public sandbox, making a request to https://fhir-open.sandboxcerner.com/r4/0b8a0111-e8e6-4c26-a91c-5069cbc6b1ca/Device/15575768 produced this error. The narrative for the Device contains the `&#174;` unicode entity. Based upon the screenshot above though the Narrative contains the HTML entity instead `&reg;` which causes the parsing of the Narrative to fail.

**Comment by beichhor** [comment]
@jamesagnew that is correct, I've tried it on multiple Unicode Entities with the same result.

**Comment by jamesagnew** [comment]
This turned out to be a bug in the Xhtml datatype. Fixed it there, will propagate to HAPI FHIR by the next release.
