### ISSUE TITLE
Search _include parameter with :iterate modifier

### ISSUE THREAD

**Issue by j-fbriere** [jamesagnew/hapi-fhir#1494]
**Describe the issue**
According to the FHIR R4 v4.0.0 Search resource documentation, in the _include parameter section:
[FHIR R4 v4.0.0 Search _include](https://www.hl7.org/fhir/search.html#include)
It is written:
> The inclusion process can be iterative, if (and only if) the modifier :iterate is included.

But the HAPI 4.0.0 version uses instead the older modifier :recurse, see the FHIR R4 v3.3.0 documentation:
[FHIR R4 v3.3.0 Search _include](http://hl7.org/fhir/2018May/search.html#include)
Where it is written:
> The inclusion process can be recursive, if the modifier :recurse is included.

The HAPI implementation should at least add the :iterate modifier or replace the :recurse modifier with it.

**Environment (please complete the following information):**
 - HAPI JPA server 4.0.0 using FHIR R4 resources

**Note**
As a quick fix, I decided to simply add the :iterate modifier, so that either _include:iterate or _include:recurse will do the same thing. Here is the patch:
[add_iterate_modifier_for_include_search_parameter.patch.txt](https://github.com/jamesagnew/hapi-fhir/files/3632932/add_iterate_modifier_for_include_search_parameter.patch.txt)

**Comment by jamesagnew** [comment]
@j-fbriere did you forget to fill the template?

**Comment by jamesagnew** [comment]
Oops- Didn't mean to close this issue, typed the wrong ticket number in a commit message for #1495
