### ISSUE TITLE
NullPointerException in RuleBuilder$RuleBuilderFinished.withTester(RuleBuilder.java:177)

### ISSUE THREAD

**Issue by ttntrifork** [jamesagnew/hapi-fhir#1495]
**Describe the bug**
NullPointerException in RuleBuilder$RuleBuilderFinished.withTester(RuleBuilder.java:177)

**To Reproduce**
Make the following sequence of calls on a RuleBuilder: 
```java
var ruleBuilder = new RuleBuilder().allow().metadata().andThen();
ruleBuilder.allow().createConditional().resourcesOfType("anystring").withTester(writeAccessTester).andThen();
```
where 'writeAccessTester' is any non-null IAuthRuleTester object

**Expected behavior**
No NullPointerException

**Environment (please complete the following information):**
 - HAPI FHIR Version: 4.0.0
 - OS: [e.g. iOS]: Windows 10

**Comment by jamesagnew** [comment]
Thanks for reporting! Fix coming up.
