### ISSUE TITLE
Device.serialNumber cannot be searched on

### ISSUE THREAD

**Issue by der-brecher** [jamesagnew/hapi-fhir#1508]
HAPI v4.0.0

As already supported by HAPI is the attribute "serialNumber" of Device. But you cannot search of filter for it.

GET /Device?serialNumber=123 produces:

`{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Unknown search parameter \"serialNumber\". Value search parameters for this search are: [_id, _language, device-name, identifier, location, manufacturer, model, organization, patient, status, type, udi-carrier, udi-di, url]</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Unknown search parameter \"serialNumber\". Value search parameters for this search are: [_id, _language, device-name, identifier, location, manufacturer, model, organization, patient, status, type, udi-carrier, udi-di, url]"
    }
  ]
}`

**Comment by patrick-werner** [comment]
The FHIR Spec doesn't include a serialNumber SearchParameter: https://www.hl7.org/fhir/device.html#search

You have to create a custom SearchParameter and Upload it to your hapi instance to enable searching for serialNumber:
https://blog.smilecdr.com/2017/02/08/custom-search-parameters-in-hapi-fhir/

and/or you can discuss the adding that parameter to Device on chat.fhir.org in the Implementers stream: https://chat.fhir.org/#narrow/stream/179166-implementers

Closing, as this is not a hapi issue.

**Comment by der-brecher** [comment]
Alright, thanks!
