### ISSUE TITLE
[enhancement] Read server interceptors as spring beans (TestRestfulServer.java 166-173)

### ISSUE THREAD

**Issue by mochaholic** [jamesagnew/hapi-fhir#151]
This will make it possible to configure other loggers or interceptors without recompiling the code.

**Comment by mochaholic** [comment]
Created a pull-request for this:
https://github.com/jamesagnew/hapi-fhir/pull/153

**Comment by jamesagnew** [comment]
Closing this as the pull request has been merged. Thanks again!
