### ISSUE TITLE
	4.0.0 _has search not working?

### ISSUE THREAD

**Issue by seanmcilvenna** [jamesagnew/hapi-fhir#1521]
**Describe the bug**

In my 3.7.0 installation of HAPI, the following search query worked as expected:
https://base-fhir-server/fhir/CodeSystem?_sort=name&_summary=true&_count=10&_has:ImplementationGuide:resource:_id=test-ig-id
This search should return any code systems that are referenced by the implementation guide with id "test-ig-id".
Yesterday, I upgraded to HAPI 4.0.0, and the same search is no longer returning any results. I have confirmed that the implementation guide "test-ig-id" does have a reference to a code system, so I'm not sure why the code system is not being returned in the above search...

**To Reproduce**
1. Create a Structuredefinition resource
2. Associate that resource (as a reference) to an ImplementationGuide
3. Perform a reverse search on StrucDef that returns only resources associated with the IG via the _id of the IG using the _has parameter.
4. Notice that no resources are returned when there is in fact resources associated with the IG that SHOULD be returned.

**Expected behavior**
Using _has for ImplementationGuide._id should return resources referenced by the IG.

**Environment (please complete the following information):**
 - HAPI FHIR Version 4.0.0
 - OS: linux
 - Browser chrome

**Comment by jamesagnew** [comment]
This was fixed in  #1525
