### ISSUE TITLE
Unable to run mvn install with package ca.uhn.fhir.jpa.search.elastic error 

### ISSUE THREAD

**Issue by ievans01** [jamesagnew/hapi-fhir#1532]
Hello,
I am trying to setup a fhir server for testing and running into a issue getting maven to run. I am on a rhel vm on aws. Forgive me if I am missing something simple but I am just starting out on this and only have been playing around for a few days. 

cd hapi-fhir
cd hapi-fhir-jpaserver-example
mvn install

![Capture](https://user-images.githubusercontent.com/56274714/66429652-74a17900-e9e6-11e9-944b-f27cb73542a6.PNG)

java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T15:06:16Z)
Maven home: /opt/downloads/maven
Java version: 1.8.0_221, vendor: Oracle Corporation, runtime: /opt/downloads/jdk1.8.0_221/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-80.4.2.el8_0.x86_64", arch: "amd64", family: "unix"

**Comment by jamesagnew** [comment]
If you're looking to test the JPA server, this is the best project to use:

https://github.com/hapifhir/hapi-fhir-jpaserver-starter
