### ISSUE TITLE
Bulk Delete for Resource History

### ISSUE THREAD

**Issue by joshm-zen** [jamesagnew/hapi-fhir#1534]
Would it be possible to implement a bulk/mass delete for the history of a resource?
Currently, I believe the user has to make a DELETE call on each history version for each patient resource.

I'd love to have a single operation that deletes a resource AND it's history.

**Comment by jamesagnew** [comment]
HI @joshm-zen - This is the purpose of the $expunge operation. See this page for information on how it works: https://smilecdr.com/docs/fhir_repository/deleting_data.html#the-expunge-operation

Please feel free to comment for re-opening if this operation is not meeting your use case in any way.
