### ISSUE TITLE
CacheControlDirective is not used 

### ISSUE THREAD

**Issue by jvitrifork** [jamesagnew/hapi-fhir#1537]
In the 4.1.0 snapshot (and probably earlier versions as well) the Cache HTTP header (parsed by CacheControlDirective) is not used when invoking calls to the /metadatadata endpoint. The consequence is that clients are unable to state whether they would like a cached capability statement or not.

**Comment by jamesagnew** [comment]
I am not sure I understand the intent. When would a client want or not want a cached metadata endpoint?

I guess you could implement this as an interceptor if there was some kind of expensive calls happening in your CapabilityStatementProvider that you wanted to give the client control over...

**Comment by jvitrifork** [comment]
The ConformanceMethodBinding provides a nonconfigurable default cache for 60 seconds. So far so good - even if the the Cache HTTP header is set. As part of generating the capabilitytstatement, the server base is also set - in respect to the client that invoked the call.

In my setup, we use the /metadata endpoint to figure out if our service is running. The /metadata endpoint is continuously called by our istio proxy - every 10 seconds. The istio service is a sidecar to all of our services in our kubernetes cluster. As it is invoked every 10 seconds from the istio service located in the same kubernetes pod, 'localhost' will always be set as serverbase.

Now, we would like to continue with this setup, but let istio call the /metadata endpoint without having this stored in the cache - effectively letting it be up to the client when the cache should be used - by eg. letting a client (in this particular case istio) set the no-cache header.

(FYI - we also use the JPA stuff with some extra extensions)

**Comment by jvitrifork** [comment]
as in https://github.com/trifork/fut-hapi-fhir/commit/ff52dfba665fa9d5927c29eb4a839bc34a33557d

**Comment by jamesagnew** [comment]
Hmm.. Well, the commits you link to would certainly allow for the caching to be more controllable which is a good thing.

If you add test coverage I'd be happy to accept that as a PR.

**Comment by jamesagnew** [comment]
That is a very different PR. This has a much higher chance of speedy merge if it isn't a change buried in an unrelated PR.

**Comment by jvitrifork** [comment]
I agree

**Comment by jvitrifork** [comment]
See PR https://github.com/jamesagnew/hapi-fhir/pull/1541

**Comment by jamesagnew** [comment]
Closing this, as #1541 was merged
