### ISSUE TITLE
Redundant search parameters in generated includeParam

### ISSUE THREAD

**Issue by jvitrifork** [jamesagnew/hapi-fhir#1546]
Looking at the tool-generated resource providers in the JPA package, it looks like there is room for refinement when looking at the search parameters generated for the includeParam. Below you'll see what is contained in eg. ca.uhn.fhir.jpa.rp.dstu3.AppointmentResourceProvider

"Appointment:actor" , 					"Appointment:incomingreferral" , 					"Appointment:location" , 					"Appointment:patient" , 					"Appointment:practitioner" , 						"Appointment:actor" , 					"Appointment:incomingreferral" , 					"Appointment:location" , 					"Appointment:patient" , 					"Appointment:practitioner" , 						"Appointment:actor" , 					"Appointment:incomingreferral" , 					"Appointment:location" , 					"Appointment:patient" , 					"Appointment:practitioner" , 						"Appointment:actor" , 					"Appointment:incomingreferral" , 					"Appointment:location" , 					"Appointment:patient" , 					"Appointment:practitioner" , 						"Appointment:actor" , 					"Appointment:incomingreferral" , 					"Appointment:location" , 					"Appointment:patient" , 					"Appointment:practitioner" 					, "*"

- it looks like there is some redundancy here

**Comment by jamesagnew** [comment]
Thanks for pointing this out. Looks like we had an extra for loop in the generator!
