### ISSUE TITLE
org.hl7.fhir.core compile error(s) against hapi-fhir  4.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by bdenton** [jamesagnew/hapi-fhir#1549]
**Describe the bug**
After changing the org.hl7.fhir.core dependency on hapi-fhir to 4.1.0-SNAPSHOT, I get the following error during "mvn install":
`[ERROR] C:\Projects\git\github\bdenton\org.hl7.fhir.core\org.hl7.fhir.utilities\src\main\java\org\hl7\fhir\utilities\xhtml\XhtmlNode.java:[66,7] error: XhtmlNode is not abstract and does not override abstract method setUserData(String,Object) in IBase
`

The readme on org.hl7.fhir.core seems to indicate that this project and hapi-fhir would remain compatible at the minor version level but this does not seem to be the case currently

**To Reproduce**
1. Make the following changes to `org.hl7.fhir.core/pom.xml`:
```
	<properties>
		<hapi_fhir_version>4.1.0-SNAPSHOT</hapi_fhir_version>
	</properties>
```
2. Run `mvn clean install` on org.hl7.fhir.core
3. Observe the compile error

**Expected behavior**
Changes to HAPI basic interfaces (such as `IBase` in this case) should be implemented in all referencing implementation classes in all projects

**Additional context**
The change in dependency was done to make sure to pick up the HAPI v4.1 OSGi bundles during testing..

**Comment by grahamegrieve** [comment]
@jamesagnew I don't understand this error - is it some kind of maven set up error? (I don't get it... - my IBase doesn't have setUserData()

**Comment by bdenton** [comment]
The setUserData() method was added to IBase in hapi-fhir v4.1.0-SNAPSHOT on 19-September (commit 2be63a1650893ee673f4fa60d1a5a5e0b41c1de5)

**Comment by jamesagnew** [comment]
I haven't synced core to the latest hapi recently, I generally resolve this
kind of issue when I do that.

Switching versions of dependencies in either projects pom is not a
supported thing, im not surprised it caused issues.

sent from my phone.
