### ISSUE TITLE
any plan or thoughts in combination with FHIRBASE

### ISSUE THREAD

**Issue by wanghaisheng** [jamesagnew/hapi-fhir#156]

**Comment by jamesagnew** [comment]
No plans in the short term although I would agree that this would be great.

If anyone wants to volunteer to give this a shot, awesome!

**Comment by niquola** [comment]
+1

May be we will find some time to do this integration.

We already have integration with .NET spark api -
https://github.com/fhirbase/fhirbase-net
It was quite simple.

73's nicola

**Comment by wanghaisheng** [comment]
@jamesagnew  pls Count me in

**Comment by jamesagnew** [comment]
@wanghaisheng Excellent! I guess the first big question is whether such a project belongs as a module within HAPI FHIR, or a module within Fhirbase, or a standalone project. (All three seem fine to me, I'd certainly be happy for it to live within HAPI assuming we could document it consistently with the rest of the library.. or I'm happy to help support an external effort in any way I can)

@niquola Any opinions?

**Comment by wanghaisheng** [comment]
just like hapi-fhir-jpaserver-uhnfhirtest is ok for me

**Comment by niquola** [comment]
All options are ok :)

We just have to be confident about libraries & FHIR versioning strategy.

Now in fhirbase we are working on edge (i.e. directly with github master of
FHIR spec),
but we surely have to switch to more pragmatic  strategy.

I'm sure @jamesagnew has a solid point of view on this!

73's nicola

**Comment by myungchoi** [comment]
Anyone doing this?
