### ISSUE TITLE
Retrieving Extension Values documentation error

### ISSUE THREAD

**Issue by larry-s** [jamesagnew/hapi-fhir#1617]
**Describe the bug**
Some comments in the documentation for Retrieving Extension Values are incorrect.
On https://hapifhir.io/doc_extensions.html#_toc_retrieving_extension_values , for both DTS2 and DTS3, the third comment is incorrect. The comment should be "Get all modifier extensions regardless of URL"

**Comment by jaferkhan** [comment]
Thank you for pointing this out, @larry-s 

I've submitted a pull request against this issue that closes it.
