### ISSUE TITLE
Override HAPI FAHIR Search functionality in provider

### ISSUE THREAD

**Issue by madlbtt** [jamesagnew/hapi-fhir#1619]
I am trying to override a search functionality in my class which extends to OrganizationProvider to get organization (Healthcare provider) which we have already saved in the database, but it is not working, request related to search always hitting the default implementation rather than which I have overrided in my class which is extending Organization Provider.

Below is a code from my application where I am overriding Search functionality.

Any help would be appreciated

public class FhirOrganizationProvider extends OrganizationResourceProvider {

    @Autowired
    private ApplicationService applicationService;

    public FhirOrganizationProvider(IFhirResourceDao<Organization> dao){
        super();
        setDao(dao);
    }

    @Search()
    public Organization getPatient(@RequiredParam(name = Organization.SP_IDENTIFIER) StringParam identifier) {

        Organization theResource = new Organization();
        SorOrganizationResponse response = getApplicationService().getOrganization(identifier.getValue());
        SorOrganizationToFhirMapping.fromMap(response.getResponseMessage(), theResource);

        return theResource;

    }
}

**Comment by jamesagnew** [comment]
Hi @madlbtt - Please see this page for details on where to ask questions about HAPI FHIR: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
