### ISSUE TITLE
Error in description of idempotent REST operations

### ISSUE THREAD

**Issue by awesome-manuel** [jamesagnew/hapi-fhir#1620]
The description of _idempotency_ in http://hapifhir.io/doc_rest_operations.html#_toc_idempotent_operations__handling_http_get is incorrect.

Quote from Wikipedia: "The GET method is safe, meaning that applying it to a resource does not result in a state change of the resource (read-only semantics). The GET, PUT and DELETE methods are idempotent, meaning that applying them multiple times to a resource result in the same state change of the resource as applying them once, though the response might differ."

https://en.wikipedia.org/wiki/Representational_state_transfer#Relationship_between_URI_and_HTTP_methods

**Comment by jamesagnew** [comment]
Hi @awesome-manuel  - We're in the process of rewriting the docs, oddly enough.

Are you satisfied with the description in the new page (which is not yet published but should be within weeks): https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/docs/server_plain/rest_operations_operations.md

**Comment by awesome-manuel** [comment]
Hi @jamesagnew - thanks for the fast reply, the updated documentation seems reasonable.
