### ISSUE TITLE
Can't instantiate a `Verdict` object inside an `IAuthRule` implementation

### ISSUE THREAD

**Issue by jaferkhan** [jamesagnew/hapi-fhir#1621]
**Describe the issue**

I would like to write a class (that extends IAuthRule) to implement my custom rule but I can't return an instance of `Verdict` from the function because its constructor is package-private. Shouldn't this be public, or is this by design?

Furthermore, I noticed that this constructor was public prior to the release of HAPI's version 3.5.0.

If this is an issue then I would be glad to submit a pull request for it.

**Environment (please complete the following information):**
 - HAPI FHIR Version 3.5.0
 - OS: Windows

**Comment by jamesagnew** [comment]
Pull request gladly accepted - Ideally with a test that actually
instantiates from another package so as to avoid this happening again :)

**Comment by jaferkhan** [comment]
Thank you so much for your response, @jamesagnew 

One more thing, I noticed that there is no @Test annotation mentioned above the method inside this class. Would you like me to add it?
https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-server/src/test/java/ca/uhn/fhir/rest/server/interceptor/auth/VerdictTest.java

**Comment by jamesagnew** [comment]
Hah, good catch. Yes please. :)
