### ISSUE TITLE
search interaction

### ISSUE THREAD

**Issue by wanghaisheng** [jamesagnew/hapi-fhir#164]
Put  http://fhirtest.uhn.ca/baseDstu2/Organization?name=Central is ok
but  
POST   http://fhirtest.uhn.ca/baseDstu2/Organization?name=Central
Content-Type   application/x-www-form-urlencoded
body:name=Central
return 500

**Comment by wanghaisheng** [comment]
http://fhirtest.uhn.ca/baseDstu2/Organization?active:missing=false is ok
but  http://fhirtest.uhn.ca/baseDstu2/Organization?partof:missing=false return 404
```

{
    "resourceType":"OperationOutcome",
    "text":{
        "status":"generated",
        "div":"<div><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">error</td><td>[]</td><td><pre>Resource false is not known</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
    },
    "issue":[
        {
            "severity":"error",
            "details":"Resource false is not known"
        }
    ]
}
```

**Comment by jamesagnew** [comment]
It should be noted that what you're doing there is invalid. To do a search using a POST you need to POST to the URL [base]/[Resource Type]/_search

So for example in the first example you should be doing a POST to:
http://fhirtest.uhn.ca/baseDstu2/Organization/_search

That error message is not helpful though, I'll investigate that.

**Comment by jamesagnew** [comment]
For the second part, you're right. The :missing qualifier wasn't working on the public server (or in our JPA module). I've fixed it and I'm about to push a commit.

I'm going to leave the bug open though, as I won't be able to redeploy the public server until later. Will close this bug when that happens. Thanks for reporting!

**Comment by jamesagnew** [comment]
Hi @wanghaisheng - Ok, the server should now support :missing. Do you mind to test?

**Comment by wanghaisheng** [comment]
http://fhirtest.uhn.ca/baseDstu2/Organization?partof:missing=false  is ok 
still  http://fhirtest.uhn.ca/baseDstu2/Organization?partof:missing=true return 
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
    <head>
        <title>502 Proxy Error</title>
    </head>
    <body>
        <h1>Proxy Error</h1>
        <p>The proxy server received an invalid
response from an upstream server.
            <br />
The proxy server could not handle the request 
            <em>
                <a href="/baseDstu2/Organization">GET&nbsp;/baseDstu2/Organization</a>
            </em>.
            <p>
Reason: 
                <strong>Error reading from remote server</strong>
            </p>
        </p>
        <hr>
            <address>Apache/2.2.15 (Red Hat) Server at fhirtest.uhn.ca Port 80</address>
        </body>
    </html>
```

**Comment by jamesagnew** [comment]
Ok! I believe this is now solved! The last error was due to a timeout between our Apache server the backend app server. It turns out that there was a performance issue that needed solving.

Do you mind to test again?

**Comment by wanghaisheng** [comment]
yeah  ok now
