### ISSUE TITLE
Possible renaming of "myEntityManagerFactory"?

### ISSUE THREAD

**Issue by mochaholic** [jamesagnew/hapi-fhir#167]
This is a possible minor configuration improvement.
While trying to add some entities to the database using the existing EntityManagerFactory, I noticed that renaming the object to entityManagerFactory will better fit autowiring of JPA Repositories if one wants to define new entities. 
I renamed this manually in the config file and things went well but I thought it might be a good idea to rename this in the main branch.

**Comment by jamesagnew** [comment]
I'm not sure I understand the benefit. All of the spring beans that ship with hapi-fhir-jpaserver-base use the naming convention of "my[Foo]", so I think if we change entityManagerFactory, we'd want to change everything else. I mean, I'm not in any way attached to the myFoo naming style (I'm not even sure why I did them that way to be honest) but I feel like that's a pretty sweeping change..

**Comment by mochaholic** [comment]
I understand. Like I said this is not a big deal really since one can easily change the names.
The issue is when you use the tag @Repository you can autowire the corresponding JpaRepository --which results in a much cleaner code-- and that will trigger spring to look for a bean named "entityManagerFactory".
This might be configurable in Spring but the default behavior is as such.

**Comment by jamesagnew** [comment]
This seems reasonable enough. I'll make the switch now.
