### ISSUE TITLE
remove transient fields from migration task hashCode() and equals()

### ISSUE THREAD

**Issue by fil512** [jamesagnew/hapi-fhir#1674]
e.g. We need to remove both `myIsOkayIfNeitherColumnExists` and 
`myDeleteTargetColumnFirstIfBothExist` from `RenameColumnTask.hashCode()` and `RenameColumnTask.equals()`.

Only those fields directly pertinent to what's being migrated should be included in the hashCode.  Flyway uses this hashCode to validate the migration hasn't been "tampered with" since it was last run.

**Comment by jamesagnew** [comment]
ooh good call.

I guess we should get a rush on this since it will be a nuisance to implement once 4.2.0/2020.02 are out.

**Comment by fil512** [comment]
Thanks for doing this @jaferkhan !

**Comment by jaferkhan** [comment]
@fil512 You're most welcome ^_^
