### ISSUE TITLE
Add an exception for HTTP 403 Forbidden error

### ISSUE THREAD

**Issue by joel-costigliola** [jamesagnew/hapi-fhir#169]
I haven't found an exception to express a HTTP 403 Forbidden error.
Is it possible to add one ?
Would `ForbiddenOperationException` be a good name for it ?

I'm willing to do a PR if you agree.

Cheers !

**Comment by jamesagnew** [comment]
Hi Joel,

Pull requests always welcome and I promise a speedy merge if you are
willing :)

Otherwise I'm happy to add one too.

James

sent from my phone.

**Comment by joel-costigliola** [comment]
Will send a PR this week end, thanks for the quick feedback
