### ISSUE TITLE
custom search parameters not working as expected

### ISSUE THREAD

**Issue by sajithdil** [jamesagnew/hapi-fhir#1706]
Hi,

I am trying to get a custom search parameter working using HAPI. I downloaded the latest hapi-fhir-jpaserver-starter, and ran it using 'mvn jetty:run'.

Once the server was up I did a POST to 'http://localhost:8888/hapi-fhir-jpaserver/fhir/SearchParameter'
with the body

`<SearchParameter xmlns="http://hl7.org/fhir">
	<id value="au-searchparameter-receivingfacility-namespace-id"/>
	<meta>
		<lastUpdated value="2017-09-08T06:22:39.374+00:00"/>
	</meta>
	<url value="http://hl7.org.au/fhir/pd/SearchParameter/au-searchparameter-receivingfacility-namespace-id"/>
	<version value="2.0.1"/>
	<name value="Search Endpoint Receiving Facility Extension Namespace Id"/>
	<status value="draft"/>
	<date value="2019-09-05T01:09:02+00:00"/>
	<description value="Find a matching receiving facility namespace id"/>
	<code value="au-receivingfacility-namespace-id"/>
	<base value="Endpoint"/>
	<type value="string"/>
	<expression value="Endpoint.extension('http://hl7.org.au/fhir/StructureDefinition/au-receivingfacility').extension('namespace-id').value"/>
	<modifier value="exact"/>
	<modifier value="missing"/>
</SearchParameter>`

This returned a 201 created response
I presumed the above was what needed to be done based on comments posted [here](https://groups.google.com/d/msg/hapi-fhir/-SbSx1QGoQc/NlTIY96GBgAJ)

However when I tried to do a GET request to 'http://localhost:8888/hapi-fhir-jpaserver/fhir/Endpoint?au-receivingfacility-namespace-id=test'

I receive:
`<OperationOutcome xmlns="http://hl7.org/fhir">
    <text>
        <status value="generated"/>
        <div xmlns="http://www.w3.org/1999/xhtml">
            <h1>Operation Outcome</h1>
            <table border="0">
                <tr>
                    <td style="font-weight: bold;">ERROR</td>
                    <td>[]</td>
                    <td>
                        <pre>Unknown search parameter &quot;au-receivingfacility-namespace-id&quot;. Value search parameters for this search are: [_id, _language, connection-type, identifier, name, organization, payload-type, status]</pre>
                    </td>
                </tr>
            </table>
        </div>
    </text>
    <issue>
        <severity value="error"/>
        <code value="processing"/>
        <diagnostics value="Unknown search parameter &quot;au-receivingfacility-namespace-id&quot;. Value search parameters for this search are: [_id, _language, connection-type, identifier, name, organization, payload-type, status]"/>
    </issue>
</OperationOutcome>`

Is there a step that I am missing?

regards

**Comment by jamesagnew** [comment]
Hi @sajithdil! Please post questions on our Google Group. Instructions here: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

In this case, your search parameter isn't working because it has a status of `draft` and not `active`.
