### ISSUE TITLE
Collection Pool ShutDown

### ISSUE THREAD

**Issue by sagarmarkalappex** [jamesagnew/hapi-fhir#1707]
PFA screenshot
![image (2)](https://user-images.githubusercontent.com/60346615/74151184-3a80f780-4bd1-11ea-9eb8-0bbf2bde3586.png)

NOTE: Before filing a ticket, please see the following URL:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version

**Additional context**

**Comment by jamesagnew** [comment]
Server is back up. Thanks for the heads up.
