### ISSUE TITLE
Search broken in Hapi docs

### ISSUE THREAD

**Issue by MattMorgis** [jamesagnew/hapi-fhir#1714]
**Describe the bug**
The search feature on the Hapi docs returns broken links

**To Reproduce**
1. Visit https://hapifhir.io/hapi-fhir/docs/
2. Type anything in the search bar. Examples: "bulk export", "cluster"
3. Click any link returned in the search results 
4. It nearly always says: `Unknown chapter ID: database_administration`

**Expected behavior**
The link should open to the corresponding page

**Screenshots**
![Screen Shot 2020-02-13 at 2 10 57 PM](https://user-images.githubusercontent.com/4664374/74469401-95814b80-4e6a-11ea-93a7-75e2ebf1a9fb.png)

**Environment (please complete the following information):**
 - Browser: Safari

**Comment by tadgh** [comment]
Thanks for the report, I'll have a look at this

**Comment by tadgh** [comment]
Heya, this has been fixed! Going to close this now :) Thanks again for the heads up!
