### ISSUE TITLE
R3/R4 conversion

### ISSUE THREAD

**Issue by manasvi22sharma** [jamesagnew/hapi-fhir#1720]
I transformed a JSON file from STU 3 for to R4

Using the following code to transform :
org.hl7.fhir.r4.model.Patient temp= converter.convertPatient(p1);

this program is converting the version but the urls like the system

"identifier": [
    {
      "use": "usual",
      "type": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/v2/0203",
            "code": "MR"
          }
        ]
      }

are the same so the response is failing the validation test of the FHIR validator
I cant seem to find any code regarding the transformation of urls
do we need to change the urls? and how we do it?

**Comment by jamesagnew** [comment]
Hi @manasvi22sharma , please see this wiki page for details on where to ask for help with HAPI FHIR:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
