### ISSUE TITLE
4.2.0 release artifacts missing?

### ISSUE THREAD

**Issue by mistydemeo** [jamesagnew/hapi-fhir#1745]
**Describe the bug**
For previous releases (like 4.1.0), there are standard distribution and CLI ZIP/tarball build artifacts available from the [GitHub releases tab](https://github.com/jamesagnew/hapi-fhir/releases). It looks like these are missing for 4.2.0; only the GitHub generated tarballs are available.

**Comment by chenrui333** [comment]
Any update on this?

relates to https://github.com/Homebrew/homebrew-core/pull/50989

**Comment by tadgh** [comment]
Heya, sorry for the delay on this. [I've added the tarball/zip](https://github.com/jamesagnew/hapi-fhir/releases/tag/v4.2.0) of the release. Let me know if this resolves it!

**Comment by issyl0** [comment]
Thanks for this, @tadgh - it builds perfectly now.

**Comment by tadgh** [comment]
Glad to hear it!
