### ISSUE TITLE
HTML Entities converted during parsing, but not restored during serializing

### ISSUE THREAD

**Issue by nickkitto** [jamesagnew/hapi-fhir#175]
In XMLUtil the VALID_ENTITY_NAMES allows for entities to be converted to their values during parsing. However they are not converted back during serialization.

For example, having a resource with a text>div tag like so

    <div xmlns="http://www.w3.org/1999/xhtml">&sect;</div>

and running it through the xml parser

    IParser parser = fhirContext.newXmlParser();
    IResource res = parser.parseResource(...);
    String output = parser.encodeResourceToString(res);

Results in the following text instead of the input text.

    <div xmlns="http://www.w3.org/1999/xhtml">§</div>

Is this expected? I expected it to return the same value as the input, since this effectively changes the value.

Note: This is on HAPI-FHIR 0.7. Apologies if this is no longer applicable, but having a brief look at the code it seems to be.

**Comment by nickkitto** [comment]
I think the easiest solution to this problem is to either test if the namespace is xhtml, or for that specific element, and use a different StringEscapeUtils escape method (maybe escapeHtml4).

**Comment by jamesagnew** [comment]
Hi Nick,

This behaviour is sort of by design. Entities such as &amp;sect; are valid in HTML/XHTML but not in XML by default, and since a FHIR document is not an XHTML document (even if it contains parts that are) it is not valid to use entities outside of [what's allowable in XML](http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML)

We had some complaints about HTML that was parsed in containing &amp;sect; entities failing to validate with XML validators when the entites were preserved so we coded it to unescape these. Given that FHIR requires the use of UTF-8, this seemed like a safe thing to do.

Is this causing issues on your end? I'm definitely not against changing this behaviour if you have specific issues it's causing, although I don't know what the right behaviour would be..

**Comment by nickkitto** [comment]
It isn't causing issues at the moment, but we can see how it would if someone had those tags in their html values. Since it is an edge case it won't have any noticeable benefit to us if it is fixed.

With regards to your answer, would this be invalid in XML? Should that div tag inside the xml actually be

    <div xmlns="http://www.w3.org/1999/xhtml">&amp;sect;</div>

That probably makes more sense, and then should be resolved in this case. Now that I am revisiting this it seems like if what you are saying is accurate than the xml document itself is invalid.

**Comment by grahamegrieve** [comment]
I believe the existing functionality is correct. Since this is an error commonly made by implementers, it's useful for HAPI to read html entities, but it should not produce them

**Comment by nickkitto** [comment]
Reopening this issue as this fails in one of our examples.
A bit of info of our usage: we are leveraging HAPI-FHIR to convert from XML->JSON and JSON->XML.

Looking through the examples for DSTU1 there is the v3-codesystems. In the examples it has the entity '&trade;' in the JSON and in the symbol '™' in the XML. However using the HAPI-FHIR library this element is dropped as it does not exist in the mapping table.

**Comment by jamesagnew** [comment]
Hi Nick,

Thanks for the info. It does look like we're missing some entities, including &trade. 

I'm completely unable to reproduce what you're seeing though. How are you doing the parsing? For reference I came up with the following unit test, but it fails on the parse step with an exception about there being an unknown entity (which is what I'd expect).

```java
	@Test
	public void testParseTextWithUnknownEntity() {
		String msg = "<Patient xmlns=\"http://hl7.org/fhir\"><text><status value=\"generated\"/>"
				+ "<div xmlns=\"http://www.w3.org/1999/xhtml\">Trade &trade;</div></text></Patient>";
		Patient pt = ourCtx.newXmlParser().parseResource(Patient.class, msg);

		ourLog.info(pt.getText().getDiv().getValueAsString());
		assertThat(pt.getText().getDiv().getValueAsString(), containsString("Trade ™"));
		
		String enc = ourCtx.newXmlParser().encodeResourceToString(pt);
		ourLog.info(enc);
		assertThat(enc, containsString("Trade ™"));

	}
```

**Comment by nickkitto** [comment]
Hey James,
Our test has it being parsed from JSON, then being encoded into XML.

So the input would be something like

    "{\"resourceType\":\"Supply\",\"text\":{\"status\":\"generated\",\"div\":\"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">&trade;</div>\"}}"

And using the JSON parser. This then throws the exception (but this is valid, as v3-codesystems.json has this). This then shouldn't throw the exception and this should be added to the list of entities.

I think it was dropped due to some minor modifications we made to the library to get around this problem, so ignore that. Reverting to the vanilla library it throws the exception which is what you said.

**Comment by grahamegrieve** [comment]
actually, just because v3-codesystems.json has it doesn't make it valid.
And I don't think it is; it's an html entity, not valid in xhtml.





On Fri, Jun 5, 2015 at 7:58 AM, Nick Kitto <notifications@github.com> wrote:

> Hey James,
> Our test has it being parsed from JSON, then being encoded into XML.
>
> So the input would be something like
>
> "{\"resourceType\":\"Supply\",\"text\":{\"status\":\"generated\",\"div\":\"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">&trade;</div>\"}}"
>
> And using the JSON parser. This then throws the exception (but this is
> valid, as v3-codesystems.json has this). This then shouldn't throw the
> exception and this should be added to the list of entities.
>
> I think it was dropped due to some minor modifications we made to the
> library to get around this problem, so ignore that. Reverting to the
> vanilla library it throws the exception which is what you said.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jamesagnew/hapi-fhir/issues/175#issuecomment-109068094>
> .
>



-- 
-----
http://www.healthintersections.com.au / grahame@healthintersections.com.au
/ +61 411 867 065

**Comment by jamesagnew** [comment]
Perfect, I'll add an update list of entities to convert.
