### ISSUE TITLE
Support chained Parameters inside of a Reverse Chained parameter

### ISSUE THREAD

**Issue by tadgh** [jamesagnew/hapi-fhir#1752]
**Describe the issue**
Currently, performing a search  with a `_has` SearchParameter, which itself includes a chained parameter, does not behave as expected, and throws InvalidRequestException when attempted.

Here is an example query which works: 
`GET Patient?_has:Observation:subject:device=Device/1234`

Here is an example of a query which does not work: 

`GET Patient?_has:Observation:subject:device.identifier=urn:system|DEVICEID`

**Environment**
 - HAPI FHIR Version 4.2
 - OS: Manjaro 18

**Comment by j-fbriere** [comment]
Had the same problem. Solved it with the following patch : 
[search_with_has_and_chained_parameters.patch.txt](https://github.com/jamesagnew/hapi-fhir/files/4308990/search_with_has_and_chained_parameters.patch.txt)
(after download but before applying this patch, remove the .txt extension)

**Comment by tadgh** [comment]
This was closed by #1760 !
