### ISSUE TITLE
Where can I find a table schema definition? Or Access to the raw data

### ISSUE THREAD

**Issue by osacn** [jamesagnew/hapi-fhir#1757]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Describe the issue**
I would like to access the raw data of the resources where for example, I can pull all patients including all their attributes. I combed through the tables in an export of the data of my local server, and while I've found some values that seem to be indexed, I don't seem to be able to find the full set of the data. I presume there is some sort of json-based or at least noSQL based storage format. How can I get access to that data?

**Environment (please complete the following information):**
 - HAPI FHIR Version

**Additional context**

**Comment by tadgh** [comment]
Heya!

If you follow the getting help link in the issue you posted, it will lead you to the [google group](https://groups.google.com/forum/#!forum/hapi-fhir), which is a better location to get queries answered.
