### ISSUE TITLE
Invalid response when using _summary=count

### ISSUE THREAD

**Issue by Legi429** [jamesagnew/hapi-fhir#1763]
Hi :)
I've been trying to have the server give me the total number of results for a given search. I noticed that the Bundle I get as a response does not include the `type` key which is required based on the FHIR standard:
https://www.hl7.org/fhir/bundle-definitions.html#Bundle.type

**Describe the bug**
Sending a request with _summary=count returns a Bundle without a type key.
The most appropriate type appears to be "searchset". When I use _summary with all the other valid options, that's the type I get in the response.

**To Reproduce**
Send a request with any resource type (Observation, Media ...) using _summary=count.
For example: `http://hapi.fhir.org/baseR4/Media?_summary=count`

**Expected behavior**
I expect to get a Bundle including the type key with the value "searchset".

**Environment (please complete the following information):**
 - Happened with both HAPI FHIR 4.1.0 and 4.3.0
 - I get this response I posted above both in the browser (link) and when using an actual FHIR client implementation. In this case: https://github.com/smart-on-fhir/Swift-SMART

**Additional context**
As an example of a response I get without the type key:
`http://hapi.fhir.org/baseR4/Media?_summary=count` gives me:
```json
{
  "resourceType": "Bundle",
  "id": "9aaf1d79-4c1a-4c9c-a3db-ea5b119653b6",
  "meta": {
    "lastUpdated": "2020-03-16T12:02:17.484+00:00",
    "tag": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationValue",
        "code": "SUBSETTED",
        "display": "Resource encoded in summary mode"
      }
    ]
  },
  "total": 1705
}
```

I have opened another issue here (wasn't sure where it applied): https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/88

**Comment by jamesagnew** [comment]
Thanks for reporting! A fix has been submitted.
