### ISSUE TITLE
What type should the  'context' parameter take in ValueSet search?

### ISSUE THREAD

**Issue by pgwilliams** [jamesagnew/hapi-fhir#1768]
Hi there!  I've got a ValueSetProvider and I'm implementing the search function.  See my code here:  https://github.com/IHTSDO/snowstorm/blob/feature/fhir/src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProvider.java#L121

The spec says that the "context" parameter is a Coding, but I find I'm unable to use either the Coding or TokenParam types because that causes the following exception:

```
ConfigurationException: Unknown search parameter type: class ca.uhn.fhir.rest.param.TokenParam
	at ca.uhn.fhir.rest.server.method.SearchParameter.setType(SearchParameter.java:318)
```

I suspect I should be using SearchParameter in a more general way, rather than specifying each parameter separately?

**Comment by jamesagnew** [comment]
The "context" search parameter on ValueSet is a fhir search "token" type,
so TokenParam should work there.

Does it not? What is the full stack trace you see?

(And is this with current HAPI 4.2.0?)

Cheers,
James

**Comment by pgwilliams** [comment]
Apologies James, I switched from HAPI 4.1.0 to 4.2.0 and the problem vanished.    I switched back to 4.1.0 to check I'm not crazy was unable to reproduce the error so the jury is still out on me being crazy.   Thanks for confirming that TokenParam should work - perhaps I picked up a wrong import package or something.
