### ISSUE TITLE
ava.lang.NoSuchMethodError when building the SQL files in hapi-fhir-jpaserver-base maven install

### ISSUE THREAD

**Issue by pogo61** [jamesagnew/hapi-fhir#177]
I'm suddenly getting this error when building a new version of the hapi-fhir-jpaserver-base jar:
[ERROR] Failed to execute goal de.juplo:hibernate4-maven-plugin:1.0.5:export (o10g) on project hapi-fhir-jpaserver-base: Execution o10g of goal de.juplo:hibernate4-maven-plugin:1.0.5:export failed: An API incompatibility was encountered while executing de.juplo:hibernate4-maven-plugin:1.0.5:export: java.lang.NoSuchMethodError: org.hibernate.cfg.beanvalidation.TypeSafeActivatorAccessor.applyRelationalConstraints(Ljavax/validation/ValidatorFactory;Ljava/util/Collection;Ljava/util/Properties;Lorg/hibernate/dialect/Dialect;)V

I've changed no code.

**Comment by jamesagnew** [comment]
Hi @pogo61 ,

Weird! That type of error has showed up before when we've changed Hibernate versions and not kept the hibernate4-maven-plugin up to date with the changes but I wouldn't expect it could just happen randomly.

Are you using the latest master codebase from Git, or a branch?

Attach a debug log from the build of that module to this bug?

e.g.:
```
cd hapi-fhir-jpaserver-base
mvn -X install > build.log
```

**Comment by pogo61** [comment]
Hi James,
I'm using the latest from the Git trunk.

I managed to remove the error by:
Creating a new project in Eclipse and deleting and re-creating the local maven repository.

You can close this, but I think it was an eclipse/maven issue.

PP

**Comment by jamesagnew** [comment]
Thanks for letting me know, glad it worked out.

-James
