### ISSUE TITLE
Error message when parsing JSON with empty attribute value does not include attribute name

### ISSUE THREAD

**Issue by jwalter** [jamesagnew/hapi-fhir#1793]
**Describe the bug**
When RestfulServer receives a request with JSON content to a provider method with a ResourceParameter and the JSON encoded resource has an attribute with an empty value, an error will we thrown or logged depending on the error handler. The error message given to the error handler by ParserState does not include the attribute name which makes the message less informative than it could be.

**Expected behavior**
The message given to the error handler includes at least the attribute name but IParseLocation would be even better.

**Environment**
 - HAPI FHIR Version 4.2.0

**Comment by jamesagnew** [comment]
Thanks for the report. Fix coming up.
