### ISSUE TITLE
DocumentReference.custodian

### ISSUE THREAD

**Issue by qagwaai** [jamesagnew/hapi-fhir#181]
INFO  c.u.f.r.m.BaseOutcomeReturningMethodBinding [BaseOutcomeReturningMethodBinding.java:162] Exception during method invocation: Resource Organization/org.hl7.fhir.instance.model.Organization@5d47865a not found, specified in path: DocumentReference.custodian (this is an invalid ID, must be numeric on this server)

I am getting this during the Argonaut anonymized data.  All other datasets have loaded successfully and the referential integrity seems to work very well with the above message when an Organization reference is not found.  When the RI failed with other data, this message contained a real Organization ID.

if I am reading this right, BaseFhirDao creates this exception message on line 222 of the 1.1-SNAPSHOT code (below)

```java
throw new InvalidRequestException("Resource " + resName + "/" + id + " not found, specified in path: " + nextPathsUnsplit + " (this is an invalid ID, must be numeric on this server)");
```
the id is assign as ```String id = nextValue.getReference().getIdPart();```

that would mean the the getIdPart() is returning an Organization?

**Comment by jamesagnew** [comment]
Hi @qagwaai ,

That error message is a bit misleading, I need to fix that. We used to require numeric IDs but the server does support textual ones now.

Unfortunately Github mangled the error a bit, but presumably there is a resource in the bundle you're trying to upload that has a reference to an observation that has an ID that's long and alphanumeric? (e.g. "5d47865")

Does this ID exist either on the server already, or elsewhere in the bundle? Are you able to share a copy of the code you're using to load the data? (I know you can't share the data itself, but I've requested a copy)

**Comment by qagwaai** [comment]
i believe this is not an ID, but a Java Object toString() method:

https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html

```
getClass().getName() + '@' + Integer.toHexString(hashCode())
```
which makes things even more strange.

below is the c# code to do the loading - I am going to try a java client to do the same
```csharp

                    Resource resource = null;
                    try
                    {
                        resource = FhirParser.ParseResourceFromXml(resourceFile.ToString());
                    }
                    catch (Exception e)
                    {
                        log.Error("Error on [" + fileName + "]:" + e.Message);
                    }
                    if (resource != null)
                    {
                        try
                        {
                            client.Update<Resource>(resource);
                            success++;
                        }
                        catch (Exception e)
                        {
                            if (e.Message.IndexOf("expected a body but none was returned") > 0)
                            {
                                success++;
                            }
                            else
                            {
                                log.Error("Server Call Error on [" + fileName + "]:" + e.Message);
                            }
                        }
                    }
```

**Comment by qagwaai** [comment]
silly me... turns out it is in the data:

```
  <custodian>
    <reference value="Organization/org.hl7.fhir.instance.model.Organization@46ace11e"/>
  </custodian>
```
