### ISSUE TITLE
References within bundles starting from an extended resource are not resolved

### ISSUE THREAD

**Issue by ohr** [jamesagnew/hapi-fhir#1817]
**Describe the bug**
When I parse a bundle with _included entries, references contained in extended resources pointing to another resource in the bundle are not resolved properly anymore. Calling `getResource()` on such a reference returns null. 
This worked in 4.1.0, but not in 4.2.0 anymore.

**To Reproduce**
* Parse a bundle containing a resource with an extension profile.  that is referenced by another resources in this bundle. See attached demo.

**Expected behavior**
getResource() should return the resource of the referenced bundle entry.

**Environment (please complete the following information):**
 - HAPI FHIR Version 4.2.0
 - OS: Windows 10

**Additional context**

Something in the optimization in https://github.com/jamesagnew/hapi-fhir/commit/39ff698dd2ec210e5d757045090f178fc17f37f3#diff-3e59bfdf0ae7820aba4280d7b8299825 probably broke this.

**Comment by ohr** [comment]
[This demonstrates the issue](https://github.com/jamesagnew/hapi-fhir/files/4539751/bug.zip). Change the HAPI FHIR version between 4.1.0 and 4.2.0 to see the difference.

**Comment by ohr** [comment]
About to provide a PR...

**Comment by jamesagnew** [comment]
Fixed by #1848
