### ISSUE TITLE
JSON unicode decoding issue

### ISSUE THREAD

**Issue by Lord-Overkirk** [jamesagnew/hapi-fhir#1818]
**Description of the bug**
When receiving a response from the FHIR-client, some unicode characters are decoded incorrectly. As shown below the character "ë" is shown as the null character (�). The JSON response is utf-8 encoded which should be correct.

**The issue**
When sending a request to our FHIR-client it shows a response which contains the null character instead of the correct character. When checking the request Headers, we can observe that the encoding is UTF-8.

**Expected behavior**
Expected is the correct unicode character.

**Screenshots**
![image](https://user-images.githubusercontent.com/45995519/80475463-326f6300-8949-11ea-9929-8f6555d41b00.png)

**Attempted solutions**
When printing the console after the data has passed the FHIR-client the screenshot from above is shown. So, the null character is shown.

Next, a `curl` request to the corresponding FHIR-server has been made. The following xml has been received (non-essential parts are left out):
```
<?xml version="1.0" encoding="UTF-8"?>
<Bundle>
...
<Organization>
    ...
    <name value="Diëtist Krokant"/>
    ...
</Bundle>
...
</Organization>

```

The data from the server is interpreted in a correct way (no null character). Only when this data has passed the client the null character is shown. This is why I suspect the issue is caused by the client and not the server.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 3.8.0
 - OS: Docker tomcat image
 - Browser: FireFox/Insomnia for sending requests.

**Comment by jamesagnew** [comment]
Hi @Lord-Overkirk, can you please provide a code snippet showing how to replicate this issue using a publicly available test server? (e.g. http://hapi.fhir.org )

**Comment by jarimayenburg** [comment]
Hi James. I work together with @Lord-Overkirk on this project. We've tried uploading our Organization resource to the public test server. When connecting a HAPI FHIR client to this server, the results look fine! The Unicode character appears correctly, as shown in the attached screenshot.

![image](https://user-images.githubusercontent.com/11874892/80493335-8daf4e80-8965-11ea-8f4b-8ee22cdc4ab3.png)

So we went to take a look at the difference in raw FHIR data when querying both FHIR servers using `curl`. What we noticed is that our FHIR server prepends a `<?xml version="1.0" encoding="UTF-8"?>` tag to the XML response, while the public test server doesn't. Do you think that might be a reason?

Our FHIR server
```
<?xml version="1.0" encoding="UTF-8"?>
<Bundle xmlns="http://hl7.org/fhir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <type value="searchset">
  </type>
  <total value="9">
  </total>
...
```

The public test server
```
<Bundle xmlns="http://hl7.org/fhir">
   <id value="9f090115-cae5-4215-909f-d8b85d04b4b0"/>
   <meta>
      <lastUpdated value="2020-04-28T13:29:17.807+00:00"/>
   </meta>
   <type value="searchset"/>
   <total value="1"/>
...
```

**Comment by jamesagnew** [comment]
It's possible, but I feel like this would have been more widespread if that
caused an issue on its own. Is your server actually outputting UTF-8, and
does it correctly specify this in the content-type?

**Comment by jarimayenburg** [comment]
Hi James, to be sure I've performed both requests again using `curl` and it appears that our FHIR server does not specify utf-8 as its charset in the Content-Type header, while the public test server does.

Our server
```
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Content-Type: application/fhir+xml
< Transfer-Encoding: chunked
< Date: Tue, 28 Apr 2020 17:13:06 GMT
< 
{ [8853 bytes data]
```

Public test server
```
< HTTP/1.1 200 OK
< Server: nginx/1.14.0 (Ubuntu)
< Date: Tue, 28 Apr 2020 17:14:52 GMT
< Content-Type: application/fhir+xml;charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: HAPI FHIR 5.0.0-SNAPSHOT REST Server (FHIR Server; FHIR 3.0.2/DSTU3)
< X-Request-ID: 2mG2LeuP4l0QNcJv
< Last-Modified: Tue, 28 Apr 2020 17:14:52 GMT
< 
{ [3840 bytes data]
```

Do you think that might be the culprit?

**Comment by jamesagnew** [comment]
I'm almost certain of it. If your server doesn't state UTF-8 in the content
type header, the client has to assume ISO-8859-1 (US-ASCII) per the HTTP
spec.

**Comment by jarimayenburg** [comment]
Ok great! Thanks so much for your time! I'll get the server administrators to include the charset in the Content-Type header. I think we can close this issue for now.
