### ISSUE TITLE
Sources of org.hl7.fhir.convertors artifact missing?

### ISSUE THREAD

**Issue by Thopap** [jamesagnew/hapi-fhir#1823]
The converters modul (https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-fhir-converter) reference a maven artifact named "org.hl7.fhir.convertors", but I was not able to locate the sources of this artifact in this git project. 
Can someone assist where to find the sources?

**Comment by jamesagnew** [comment]
Hi @Thopap - Please direct questions to our Google Group. You can find more info on where to ask questions about HAPI FHIR here: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

The convertors sources can be found here: https://github.com/hapifhir/org.hl7.fhir.core/tree/master/org.hl7.fhir.convertors
