### ISSUE TITLE
java.lang.IllegalStateException: Could not find any HAPI-FHIR structure JARs on the classpath

### ISSUE THREAD

**Issue by pogo61** [jamesagnew/hapi-fhir#183]
James,
this is quite a confusing error.

I'm getting this when loading the OSGi bundles I've created (both hapi-fhir-base and hapi-fhir-jpaserver-base are now bundles).

This error is being thrown on the start of hapi-fhir-base. Here is the relevant part:
Caused by: java.lang.IllegalStateException: Could not find any HAPI-FHIR structure JARs on the classpath. Note that as of HAPI-FHIR v0.8, a separate FHIR strcture JAR must be added to your classpath (or project pom.xml if you are using Maven)
at ca.uhn.fhir.context.FhirContext.<init>(FhirContext.java:130)
at ca.uhn.fhir.context.FhirContext.<init>(FhirContext.java:108)
at ca.uhn.fhir.context.FhirContext.<init>(FhirContext.java:96)
at ca.uhn.fhir.rest.server.RestfulServer.<init>(RestfulServer.java:109)

Where RestfulServer.java:109 is:
/**
* Constructor
*/
public RestfulServer() {
this(new FhirContext());
}

Where the constructor for FhirContext is:
private FhirContext(FhirVersionEnum theVersion, Collection<Class<? extends IBaseResource>> theResourceTypes) {
if (theVersion != null) {
if (!theVersion.isPresentOnClasspath()) {
throw new IllegalStateException(getLocalizer().getMessage(FhirContext.class, "noStructuresForSpecifiedVersion", theVersion.name()));
}
myVersion = theVersion.getVersionImplementation();
} else if (FhirVersionEnum.DSTU1.isPresentOnClasspath()) {
myVersion = FhirVersionEnum.DSTU1.getVersionImplementation();
} else if (FhirVersionEnum.DSTU2.isPresentOnClasspath()) {
myVersion = FhirVersionEnum.DSTU2.getVersionImplementation();
} else if (FhirVersionEnum.DSTU2_HL7ORG.isPresentOnClasspath()) {
myVersion = FhirVersionEnum.DSTU2_HL7ORG.getVersionImplementation();
} else if (FhirVersionEnum.DEV.isPresentOnClasspath()) {
myVersion = FhirVersionEnum.DEV.getVersionImplementation();
} else {
throw new IllegalStateException(getLocalizer().getMessage(FhirContext.class, "noStructures"));
}

ourLog.info("Creating new FHIR context for FHIR version [{}]", myVersion.getVersion().name());

scanResourceTypes(toElementList(theResourceTypes));
}

This matches the exception being thrown.

But the question is, why is something in hapi-fhir-base have a dependency of these packages, given that these packages have a dependency on hapi-fhir-base? I've noticed in the latest hapi-fhir-base POM the dependencies for the dstu and dstu2 jars have been removed - I suspect for this reason.

So, how would this work normally if this was just in a normal App Server? Would it just rely on a shared class loader?

PP

**Comment by jamesagnew** [comment]
Hi Paul,

This is basically done by design: The hapi-fhir-base JAR has the main HAPI library code, and the hapi-fhir-structures-XXX JARs have different versions of the model. The idea is that applications using HAPI need to depend on both of those things, but only need to pick one of the various model versions in order to save space. They can also include multiple model versions if they need their app to suport multiple versions of FHIR.

This does seem to cause a challenge in OSGi environments, since you have two JARs depending on each other. FWIW we use the same setup in the [HAPI-HL7v2 library](http://hl7api.sourceforge.net/) and the dev who put together the OSGi bundle for that library did it by creating a specific OSGi JAR with all versions of the model. I don't know if there is a better way than that (possibly the model JARs need something in their manifest?) but it would be cool if there was...

**Comment by pogo61** [comment]
So is there an OSGi guide for the HL7 library? If so, can you point me to it, please?
I'm thinking that the only way to go is to split the base jar into two bundles. One that relies on the structure-xxx bundles, and the other that the structure-xxx bundles rely on. 
I'll look more deeply into that and the HL7 OSGi guide if I can. 
PP

Please excuse my fat fingers, as I'm using my iPhone 




On Tue, Jun 9, 2015 at 5:05 AM -0700, "James Agnew" <notifications@github.com> wrote:












Hi Paul,



This is basically done by design: The hapi-fhir-base JAR has the main HAPI library code, and the hapi-fhir-structures-XXX JARs have different versions of the model. The idea is that applications using HAPI need to depend on both of those things, but only need to pick one of the various model versions in order to save space. They can also include multiple model versions if they need their app to suport multiple versions of FHIR.



This does seem to cause a challenge in OSGi environments, since you have two JARs depending on each other. FWIW we use the same setup in the HAPI-HL7v2 library and the dev who put together the OSGi bundle for that library did it by creating a specific OSGi JAR with all versions of the model. I don't know if there is a better way than that (possibly the model JARs need something in their manifest?) but it would be cool if there was...

**Comment by jamesagnew** [comment]
Unfortunately there isn't. You could have a look though at how the hapi-osgi-base project gets built (this is the non-fhir version of HAPI, and this project bundles the base as well as all of the structures into a single JAR for OSGi)

http://sourceforge.net/p/hl7api/code/HEAD/tree/trunk/hapi-mvn/hapi-osgi-base/

**Comment by pogo61** [comment]
Ok. Thanks James. 

Please excuse my fat fingers, as I'm using my iPhone 




On Tue, Jun 9, 2015 at 7:02 AM -0700, "James Agnew" <notifications@github.com> wrote:












Unfortunately there isn't. You could have a look though at how the hapi-osgi-base project gets built (this is the non-fhir version of HAPI, and this project bundles the base as well as all of the structures into a single JAR for OSGi)



http://sourceforge.net/p/hl7api/code/HEAD/tree/trunk/hapi-mvn/hapi-osgi-base/
