### ISSUE TITLE
Question: Why is the Spring Boot autoconfiguration for FhirRestfulServerConfiguration conditional on a AbstractJaxRsProvider?

### ISSUE THREAD

**Issue by jrahhali** [jamesagnew/hapi-fhir#1840]
This is not an issue, but a question.

**Project**: hapi-fhir-spring-boot-autoconfigure (v4.2.0)
**Class**: FhirAutoConfiguration
**Code snippet in question**:

	@Configuration
	@ConditionalOnClass(AbstractJaxRsProvider.class)
	@EnableConfigurationProperties(FhirProperties.class)
	@ConfigurationProperties("hapi.fhir.rest")
	@SuppressWarnings("serial")
	static class FhirRestfulServerConfiguration extends RestfulServer {
        ...
       }

**Question:I** was just wondering the reasoning behind why an autoconfiguration of a RestfulServer (Servlet based) is @ConditionalOnClass(AbstractJaxRsProvider.class) (A JAX-RS Server based class)?

If I don't include hapi-fhir-jaxrsserver-base, then my fhir server fails to start (as expected).  Is this the intended behaviour?

Thanks.

**Comment by jamesagnew** [comment]
Hi @jrahhali - Please see this wiki page for details on where to ask questions about HAPI FHIR: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
