### ISSUE TITLE
Odd results for StructureDefinition search without parameters

### ISSUE THREAD

**Issue by brianalind** [jamesagnew/hapi-fhir#1855]
When doing a query from Postman for all the StructureDefinition resources in a HAPI version 5 server, the response bundle contains a mostly empty resource instead of a list of existing resources.

For example: **GET http://hapi.fhir.org/baseR4/StructureDefinition** returns the following.

`  
{
    "resourceType": "Bundle",
    "id": "3d3cca18-1fb2-4440-a1c1-8a1c9e02420f",
    "meta": {
        "lastUpdated": "2020-05-20T17:40:24.694+00:00"
    },
    "type": "searchset",
    "total": 1,
    "link": [
        {
            "relation": "self",
            "url": "http://hapi.fhir.org/baseR4/StructureDefinition"
        }
    ],
    "entry": [
        {
            "fullUrl": "http://hapi.fhir.org/baseR4/StructureDefinition/verificationresult",
            "resource": {
                "resourceType": "StructureDefinition",
                "id": "verificationresult"
            }
        }
    ]
}
`

The resource http://hapi.fhir.org/baseR4/StructureDefinition/verificationresult doesn't actually exist.
I have to do something like **GET http://hapi.fhir.org/baseR4/StructureDefinition?status=active** to get any resources at all.

When doing the same search against my locally deployed HAPI 5.0.0 jpaserver is see the same results, but a different invalid resource is returned. 

**GET http://localhost:8080/hapi-fhir-jpaserver/fhir/StructureDefinition**

`{
    "resourceType": "Bundle",
    "id": "5b9001b6-e42a-46a4-9543-9aba37177713",
    "meta": {
        "lastUpdated": "2020-05-20T12:56:35.462-05:00"
    },
    "type": "searchset",
    "total": 1,
    "link": [
        {
            "relation": "self",
            "url": "http://localhost:8080/hapi-fhir-jpaserver/fhir/StructureDefinition"
        }
    ],
    "entry": [
        {
            "fullUrl": "http://localhost:8080/hapi-fhir-jpaserver/fhir/StructureDefinition/examplescenario",
            "resource": {
                "resourceType": "StructureDefinition",
                "id": "examplescenario"
            }
        }
    ]
}`

**Comment by jkiddo** [comment]
We are seeing the same issue.

**Comment by MattMorgis** [comment]
Is this deployed? I'm running HAPI Server v5.0.2 and seeing this issue

**Comment by MattMorgis** [comment]
Ah - I see this listed in the [v5.1.0](https://smilecdr.com/hapi-fhir/docs/introduction/changelog.html#change5.1.0-0) release notes
