### ISSUE TITLE
java.lang.AssertionError:  Expected: a string containing "\"identifier\":" in ca.uhn.fhir.rest.server.ServerFeaturesTest

### ISSUE THREAD

**Issue by pogo61** [jamesagnew/hapi-fhir#186]
James, 
after refreshing hapi-fhir-structures-dstu from the trunk repo I'm getting this error:
Running ca.uhn.fhir.rest.server.ServerFeaturesTest
Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.651 sec <<< FAILURE! - in ca.uhn.fhir.rest.server.ServerFeaturesTest
testAcceptHeaderWithMultiple(ca.uhn.fhir.rest.server.ServerFeaturesTest)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: a string containing "\"identifier\":"
     but: was "<Patient xmlns="http://hl7.org/fhir"><identifier><use value="official"/><system value="urn:hapitest:mrns"/><value value="00001"/></identifier><name><family value="Test"/><given value="PatientOne"/></name><gender><text value="M"/></gender></Patient>"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at ca.uhn.fhir.rest.server.ServerFeaturesTest.testAcceptHeaderWithMultiple(ServerFeaturesTest.java:155)

If I change line 155 to:
assertThat(responseContent, StringContains.containsString("identifier"));
it passes.

I'm assuming that you are only looking for the identifier element?

**Comment by jamesagnew** [comment]
Can you please sync again? This was actually the unit test catching a
problem with a recent commit.

**Comment by pogo61** [comment]
yep..it's gone now. ;-)

thanks
