### ISSUE TITLE
class file for ca.uhn.fhir.model.primitive.BoundCodeableConceptDt not found in ca.uhn.fhir.jpa.provider.ResourceProviderMultiVersionTest

### ISSUE THREAD

**Issue by pogo61** [jamesagnew/hapi-fhir#187]
James,
I'm getting this error:
/Users/paulpog/Documents/workspace/hapi-fhir/hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/ResourceProviderMultiVersionTest.java:47: error: cannot access BoundCodeableConceptDt
		p.getGender().setValueAsEnum(AdministrativeGenderCodesEnum.M);
		           ^
  class file for ca.uhn.fhir.model.primitive.BoundCodeableConceptDt not found

but that class does not exist in the base source code. It's in either the structure.dstu or structure.dstu2 source

PP

**Comment by jamesagnew** [comment]
Is this on a clean Git pull of HAPI, or on your fork? If the latter, can
you please push the changes you've made?

**Comment by pogo61** [comment]
It’s a pull of HAPI for any source changes. these source changes were updated into my fork.

I’ve just pushed the changes to the fork

**Comment by jamesagnew** [comment]
Hmm, ok if I try to build this fork locally I get a bunch of compile issues related to slf4j. I take it this doesn't happen for you?

```[ERROR] /Users/t3903uhn/git/paulhapi/hapi-fhir/hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/method/DynamicSearchMethodBinding.java:[113,38] incompatible types: java.lang.String cannot be converted to org.slf4j.Marker```

**Comment by pogo61** [comment]
No. However, I know we have a different implementation of SLF4J in our container, than that specified by HAPI

**Comment by jamesagnew** [comment]
Hmm, ok I see it too.

Unfortunately I am stumped as to why. It doesn't happen on the non fork build, so it's definitely something to do with the changes you have made, but I don't know enough about the OSGi stuff to be able to begin to guess.

This really just reinforces my view though that it would make sense to add a new submodule with dependencies on everything you want to include and make sure that no changes happen to the rest of the build. I think as long as there are all of these dependency changes to the core library we wouldn't be able to merge this back into the core anyhow so it's not something we'll ever be able to keep current with....

**Comment by jamesagnew** [comment]
Here is how this is done for the other HAPI library: http://sourceforge.net/p/hl7api/code/HEAD/tree/trunk/hapi-mvn/hapi-osgi-base/

That way there are no OSGi dependencies in the core or structures libraries and the unit tests don't break. This design is known to work.

**Comment by pogo61** [comment]
OK.
Let me have a look at this and re-evaluate.

I take your point re supporting these changes. Although, All I have done is:
1. created my own servlet that will work in our container (created a WAB out of something like the hapi-fhir-jpaserver-example just didn’t work)
2. change the POM’s of the base, structure and jpa-server jars, to create bundles
3. add additional non-container jars into a separate library and add that library to the base bundle classpath.

PP

**Comment by jamesagnew** [comment]
Closing old bugs that appear solved, please re-open if issue persist.
