### ISSUE TITLE
Error after upgrading from 4.2 to 5.0

### ISSUE THREAD

**Issue by seanmcilvenna** [jamesagnew/hapi-fhir#1876]
**Describe the bug**
I was under the impression that as of 4.1, HAPI would be able to automatically upgrade itself... So, we recently changed our installation of hapi-fhir-jpaserver from 4.2 to 5.0, and are now getting this error on all resources:

`Field 'SEARCH_LAST_RETURNED' doesn't have a default value`

**To Reproduce**
1. Install 4.2 of HAPI with MySQL database
2. Swap out installation with 5.0 without touching MySQL database
3. Perform any search request, such as /fhir/Observation or /fhir/Practitioner

**Expected behavior**
Should return search results without error.

**Environment (please complete the following information):**
 - HAPI FHIR Version 4.2 -> 5.0
 - OS: Ubuntu, MySQL
 - Browser Chrome

**Comment by jamesagnew** [comment]
Hi 
@seanmcilvenna - Have you run the migrator? https://hapifhir.io/hapi-fhir/docs/server_jpa/upgrading.html

**Comment by seanmcilvenna** [comment]
No. I had thought you said a couple months ago that this happens automatically now when the server starts...

**Comment by jamesagnew** [comment]
Ah, sorry that was just misspeaking (already answered in the Zulip thread but answering here too in case others are following along).

One or 2 releases ago I did mention that the migrator wasn't needed anymore on a release webinar. What I meant to say was that manual SQLs no longer have to be run.
