### ISSUE TITLE
How should Tags be added to resources as codings

### ISSUE THREAD

**Issue by nsking** [jamesagnew/hapi-fhir#189]
I need to add a tag to an allergy intolerance. The [ResourceMetadataKeyEnum] (https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/model/api/ResourceMetadataKeyEnum.java) supports adding tags as a [Tag] (https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/model/api/Tag.java). I was under the impression the tag should be a coding (see [here] (http://www.hl7.org/FHIR/2015May/resource.html#Meta)). Note that I am wanting to support DSTU2.

**Comment by jamesagnew** [comment]
Hi @nsking , you should be able to do the same thing as in DSTU1 [described here](http://jamesagnew.github.io/hapi-fhir/doc_tags.html) in DSTU2 code. The tags are codings, but HAPI's parser automatically converts from the TagList format into the codings used in DSTU2.
