### ISSUE TITLE
Snapshot Generation Fails Due to DefinitionException Caused by Alleged Wrong Slicing

### ISSUE THREAD

**Issue by npwynands** [jamesagnew/hapi-fhir#1908]
**Bug Description**
The creation of a snapshot from the profile https://simplifier.net/medizininformatikinitiative-modulperson/patientin fails due to a `DefinitionException`. The `DefinitionException` is raised in `org.hl7.fhir.r4.conformance.ProfileUtilities` in line 875. According to the surrounding commentary and the debug context at raise time, the differential setup a slice for `"Patient.identifier:versicherungsnummer_gkv.type.coding"` but hasn't defined it. To me, the condition (`if` statement) of the `DefinitionException` and the exception itself is incomprehensible. I don't see any mistake in the profile definition, so I assume a bug on the HAPI FHIR side.

**To Reproduce**
I'm using the following method to generate the `snapshot` from the given `differential` and `profileWebURL`:

```java
private StructureDefinition generateSnapshot(StructureDefinition differential, String profileWebURL) throws DefinitionException {

    DefaultProfileValidationSupport defaultSupport = new DefaultProfileValidationSupport(this.fhirContext);
    SnapshotGeneratingValidationSupport snapshotSupport = new SnapshotGeneratingValidationSupport(this.fhirContext);

    String profileCanonicalURL = differential.getUrl();
    String profileName = differential.getName();

    StructureDefinition snapshot = (StructureDefinition) snapshotSupport.generateSnapshot(defaultSupport,
            differential, profileCanonicalURL, profileWebURL, profileName);

    return snapshot;
}
```
	
The FHIR context is set to R4. The `differential` of the profile mentioned above is queried via the SIMPLIFIER REST endpoint at https://fhir.simplifier.net/r4/StructureDefinition/d82d0a1f-bf79-47b5-9641-fd198ff66b1a. This address is also selected for the `profileWebURL` parameter.

**Expected behavior**
I assume that the authors validated their profiles with SIMPLIFIER's profiling tools, further their profiles are no drafts anymore, so it should be possible to create a snapshot from of their differential definitions.
I also tested my function with the profiles https://simplifier.net/medizininformatikinitiative-modulperson/observation-vitalstatus and https://simplifier.net/medizininformatikinitiative-modulperson/probantin, which both work fine.

**Environment**
 - HAPI FHIR 5.0.2
 - Server: Tomcat 9.0.35
 - Java: 8u231
 - OS: Windows 10

**Comment by jamesagnew** [comment]
FYI I've duplicated this ticket on the org.hl7.fhir.core repository where the associated codebase lives.

See https://github.com/hapifhir/org.hl7.fhir.core/issues/235
