### ISSUE TITLE
StructureDefinition snapshots are not always generated during $validate operation causing errors

### ISSUE THREAD

**Issue by dusty2020** [jamesagnew/hapi-fhir#1914]
I'm calling the $validate operation to validate a resource using a profile. The StructureDefinition for that profile inherits from another StructureDefinition that doesn't have a snapshot attribute specified. Before upgrading to HAPI 5.0.2 this operation was working. After upgrading I get this error: 

```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[AuditEvent, Line 1, Col 2]</td><td><pre>StructureDefinition has no snapshot - validation is against the snapshot, so it must be provided</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "StructureDefinition has no snapshot - validation is against the snapshot, so it must be provided",
            "location": [
                "AuditEvent",
                "Line 1, Col 2"
            ]
        }
    ]
}
```

The 4.2.0 version of the code handled this by generating a snapshot after fetching StructureDefinition resources if they didn't have a snapshot. See https://github.com/jamesagnew/hapi-fhir/blob/6b019492feab501adba6c97bb5aec5a987eb6172/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/validation/JpaValidationSupportChainR4.java#L72

This code didn't seem to make it into the non-version specific [JpaValidationSupportChain](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/validation/JpaValidationSupportChain.java). 

**To Reproduce**
1. Create a StructureDef that extends a FHIR resource (don't include snapshot attribute)
2. Create a second StructureDef that extends the first (don't include snapshot attribute)
3. Call the $validate operation on a resource using the second structure def as a profile

**Comment by jamesagnew** [comment]
Hi @dusty2020 - Are you able to create a reprodcible test case on hapi.fhir.org?

**Comment by dusty2020** [comment]
I created StructureDefinition/test-parent and StructureDefinition/test-child but I couldn't figure out how to run a request like 
/AuditEvent/$validate
with body
```
{
  "resourceType" : "AuditEvent",
  "id" : "log-event-ex",
  "meta": {
    "profile": [
      "http://test.com/fhir/structuredefinition/test-child"
    ]
  },
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><b>Log Event:</b> Debug Test Message<br />Customer: sound<br />debugType: debug<br /><br /></div>"
  },
  "recorded" : "2020-02-11T16:06:37.777-05:00",
  "agent" : [
    {
      "who" : {
          "reference" : "Organization/1199128"
      },
      "requestor" : true
    }
  ],
  "type" : {
    "code" : "1234"
  },
  "source" : {
    "observer" : {
      "reference" : "Organization/1199128"
    }
  },
  "entity" : [
    {
      "detail" : [
        {
          "type" : "message",
          "valueString" : "Debug Test Message"
        },
        {
          "type" : "customer",
          "valueString" : "sound"
        },
        {
          "type" : "debugType",
          "valueString" : "debug"
        }
      ]
    }
  ]
}
```
It's putting the id in the url and responding with a 404.

**Comment by dusty2020** [comment]
I used Postman to verify. I'm not getting the error.

**Comment by jamesagnew** [comment]
Sounds good- Closing this ticket then.
