### ISSUE TITLE
Android / Signed APK/Bundle causes MissingResourceException

### ISSUE THREAD

**Issue by mmacagno** [jamesagnew/hapi-fhir#1916]
Hello.
We have an app in Android, using HAPI-FHIR just to parse and manage FHIR entities from JSON strings.
Targets and runs on API 29.

gradle:

`implementation 'ca.uhn.hapi.fhir:hapi-fhir-structures-r4:4.1.0`

(tried to add as well:
    implementation "ca.uhn.hapi.fhir:hapi-fhir-android:4.1.0"
    implementation "ca.uhn.hapi.fhir:hapi-fhir-base:4.1.0"
but no changes)

The debug version works fine.
The release/signed APK or Bundle will fail on this instruction:

`FhirContext ctx = FhirContext.forR4();`

with this exception:

$MissingResourceException, Can't find bundle for base name c.a.a.b.hapi-messages, locale en_US
    , [java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1561), java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1384), java.util.ResourceBundle.getBundle(ResourceBundle.java:771), c.a.a.b.a.a(HapiLocalizer.java:163), c.a.a.b.a.<init>(HapiLocalizer.java:53), c.a.a.b.a.<init>(HapiLocalizer.java:48), ca.uhn.fhir.context.g.<init>(FhirContext.java:89), ca.uhn.fhir.context.g.<init>(FhirContext.java:145), ca.uhn.fhir.context.g.k(FhirContext.java:944), io.sensoria.ahora.activities.QrCodeScannerActivity.a(QrCodeScannerActivity.java:477), io.sensoria.ahora.application.w.l(SensoriaIOClient.java:175), io.sensoria.ahora.application.b.run(Unknown Source:4), android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641), java.lang.Thread.run(Thread.java:919)]

Not sure how to fix it - any help appreciated.
thanks

**Comment by mmacagno** [comment]
It looks like some issue with proguard.
If I disable minification in the build, it works. I haven't been able to find the right setting in proguard to make it work though.

**Comment by mmacagno** [comment]
The "less" stringent rules in proguard that solve the issue are:

`-keep class ca.uhn.**
-keep class org.hl7.fhir.**`

**Comment by ajithmemana** [comment]
Is there a proper settings for proguard to use? So that the file size is reduced.
