### ISSUE TITLE
CodeSystem/$lookup does not return designations even when query param property=designation is used

### ISSUE THREAD

**Issue by ttntrifork** [jamesagnew/hapi-fhir#1919]
**To Reproduce**
I have created a CodeSystem with a concept that has a designation with a language value
http://hapi.fhir.org/baseDstu3/CodeSystem/2724187
```
{
  "resourceType": "CodeSystem",
  "id": "2724187",
  "meta": {
    "extension": [ {
      "url": "http://hapifhir.io/fhir/StructureDefinition/resource-meta-source",
      "valueUri": "#70s3yjiJZFw3nzKd"
    } ],
    "versionId": "1",
    "lastUpdated": "2020-06-12T11:01:17.527+00:00"
  },
  "url": "urn:uuid:3e6a6206-79cc-4cab-aa90-45f678f31960",
  "identifier": {
    "system": "TEST_SYSTEM",
    "value": "TEST_IDENTIFIER_VALUE"
  },
  "name": "some code system",
  "status": "active",
  "content": "example",
  "concept": [ {
    "code": "TEST_CODE_WITH_DANISH_VALUE",
    "display": "My display text",
    "designation": [ {
      "language": "da",
      "value": "Rundbarbering"
    } ]
  }, {
    "code": "TEST_CODE_WITHOUT_DANISH_VALUE",
    "display": "My display text"
  } ]
}
```

However, when I do a $lookup to get the designation then it is not included in the response even though I ask for it in the query parameters:
http://hapi.fhir.org/baseDstu3/CodeSystem/$lookup?code=TEST_CODE_WITH_DANISH_VALUE&system=urn:uuid:3e6a6206-79cc-4cab-aa90-45f678f31960&property=designation

However, if I do the same type of request on a different FHIR implementation it seems to work: 
https://stu3.ontoserver.csiro.au/fhir/CodeSystem/$lookup?code=12915011000036104&system=http://snomed.info/sct&property=designation

**Expected behavior**
I expect the designations of the found concept to be included in the body of the response of $lookup

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.1.0-SNAPSHOT
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
I found the working other server stu3.ontoserver.csiro.au in https://chat.fhir.org/#narrow/stream/179166-implementers/topic/CodeSystem.20Lookup

**Comment by ttntrifork** [comment]
After a grueling debugging session, I have realized that my code system does not get stored in the `trm_codesystem` tabel because it has `"content": "example` as checked here: [TermCodeSystemStorageSvcImpl#258](https://github.com/jamesagnew/hapi-fhir/blob/v5.0.2/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/TermCodeSystemStorageSvcImpl.java#L258)

This means that it is not the `TermReadSvcDstu3#lookupCode that is used when calling Codesystem/$lookup (which does return designations), but instead it is InMemoryTerminologyServerValidationSupport#lookupCode that is used, which does not return designations!

@jamesagnew is this intentional? It was well confusing for me!
However, as things are working (when using the right CodeSystem content value), I will close this issue

**Comment by jvitrifork** [comment]
maybe a PR that returns designations on the inmem would be appropriate

**Comment by jvitrifork** [comment]
That also could look like a bug waiting to happen. With the current code CodeSystem supplements, are not stored in the term tables. Is that really intentional?
