### ISSUE TITLE
ValueSet$expand with filter and offset parameters needs to be enhanced.

### ISSUE THREAD

**Issue by dmuylwyk** [jamesagnew/hapi-fhir#1946]
I've identified an issue with ValueSet$expand on pre-expanded ValueSets (stored in the terminology tables) where a filter param is combined with offset and count params.

What we're presently doing:

- Offset and count provide paging support. We default to 0 and 1000 respectively. Expanding a ValueSet with 100,000 concepts with these default values would mean 100 pages of concepts.
- Offset and count are considered _before_ applying a filter. Offset is the starting index (concept, not page), and is in consideration of the total number of concepts. Count is the number of concepts returned per page.
- Filter constrains the returned results based on a concept's display, case-insensitive.
- If the value being filtered on doesn't appear until the 99,001th concept, the first 99 pages will be empty.

This seems wrong to me, and ultimately confusing to clients. Ideally, the filter should be applied first, and then the offset and count ought to be applied to the subset of concepts such that if there are fewer matched concepts than the value of count, they will all be returned when the offset is 0 - regardless of where they appear among the total count of concepts.

@jamesagnew has suggested the following:

> i think it might also be reasonable to just say you can't combine filter and offset (and for us to have a check to that effect)
> 
> i'd say it should just return the first page (say 1000 results) max... if someone needed more, they should just create a valueset that includes the filter and pre-expand it

If filtering on the entire ValueSet returns more than 1000 results, we should simply prompt the client to refine their search.

These changes are non-trivial so I've captured this in a ticket to revisit later.

**Comment by dmuylwyk** [comment]
Some screenshots to demonstrate the issue:

![Screenshot from 2020-06-26 12-39-05](https://user-images.githubusercontent.com/3145704/85892949-dea1be80-b7bf-11ea-8262-69e2b51b77a0.png)
![Screenshot from 2020-06-26 12-39-28](https://user-images.githubusercontent.com/3145704/85892950-df3a5500-b7bf-11ea-918c-ada477b0d477.png)
![Screenshot from 2020-06-26 12-39-49](https://user-images.githubusercontent.com/3145704/85892952-dfd2eb80-b7bf-11ea-967b-0c99cef9bb35.png)

**Comment by mohammadfarooqi** [comment]
I've investigated this issue further and here are my findings.

we are trying to search for the term "mixed". 
![image](https://user-images.githubusercontent.com/10905290/99851668-72986c00-2b4d-11eb-91ba-2bf64529880f.png)


we can see here that at least 1 result should come up:
![image](https://user-images.githubusercontent.com/10905290/99851726-8e9c0d80-2b4d-11eb-8bde-8f7b4b95488f.png)



and we verify the codesystem has it as well:
![image](https://user-images.githubusercontent.com/10905290/99851758-a07db080-2b4d-11eb-85b6-0fa2b32b5b57.png)



we also verify that the $expand?filter= does give back some "selective" results. for example here:
![image](https://user-images.githubusercontent.com/10905290/99851916-ef2b4a80-2b4d-11eb-8e91-953f9784daa6.png)
