### ISSUE TITLE
Got Android HAPI Fhir working with some hacking and hasle

### ISSUE THREAD

**Issue by botunge** [jamesagnew/hapi-fhir#199]
I was looking into using the Hapi Fhir android client for an android app.

I downloaded the "selfcontained" hapi fhir android jar hapi-fhir-android-1.1.jar and hapi-fhir-structures-dstu2-1.1.jar and tried finding all patient resources on a dstu2 server.

<pre><code>FhirContext fc = FhirContext.forDstu2();
IGenericClient gc = fc.newRestfulGenericClient("http://&lt;&lt;some server&gt;&gt;"); //$NON-NLS-1$
gc.setEncoding(EncodingEnum.JSON);
ca.uhn.fhir.model.api.Bundle bundle = gc.search().forResource(Patient.class).execute();
</code></pre>

This gave me some errors, first of all the following slf4j files needs to be added:
<i>slf4j-android-1.7.12.jar
slf4j-api-1.7.12.jar</i>
Inside hapi-fhir-android-1.1.jar the following folder is required but missing:
<i>ca\uhn\fhir\model\dstu</i>. I just copied the 5 enums with anonymous classes from the base jar <i>hapi-fhir-base-1.1.jar</i>
After that I was missing  <i>commons-io-2.4.jar</i>
And finally i was hit by <code>Caused by: ca.uhn.fhir.repackage.javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.MXParserFactory not found</code>
This was fixed by adding the following two lines in the code before using <i>FhirContext.forDstu2();</i>

<pre><code>System.setProperty("javax.xml.stream.XMLInputFactory", "com.ctc.wstx.stax.WstxInputFactory")
System.setProperty("ca.uhn.fhir.repackage.javax.xml.stream.XMLInputFactory", "com.ctc.wstx.stax.WstxInputFactory")
</code></pre>

I suspect you need to do that for all files specified in <i>hapi-fhir-android-1.1.jar\META-INF\services</i>

But after these changes i was able to retrieve a list of patients on my server.
I used the following permission in AndoirdManifest.xml for the above code.

<pre><code>&lt;uses-permission android:name="android.permission.INTERNET" /&gt;
&lt;uses-permission android:name="android.permission.READ_LOGS" /&gt;
&lt;uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /&gt;
&lt;uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" /&gt;</code></pre>

I hoped that by setting <code>gc.setEncoding(EncodingEnum.JSON);</code> i could do without XML but that was not the case.

**Comment by jamesagnew** [comment]
Hi @botunge , this is great information. Thanks for providing it!

I'd like to try and incorporate fixes to these issues into a new snapshot. Are you in a position to test snapshot builds?

Also, what issues did you encounter when you tried to use JSON encoding? I believe this should work, although I'm not 100% sure.

**Comment by botunge** [comment]
I can verify the change if you make them.
The problem with Json is that it still complains about the stax parser. Insted of e.g. encoding/decoding using google gson. Android (google) has decided that jaxb etc should not be natively supported. So a pure google gson version would be better on android. It looks like the .net api by ewout kramer only requires a json lib.
Also i only tried reading, after you change the code i'll try writing a resource.

**Comment by wurstnudl** [comment]
I had the same problem. I'm not totally sure at the moment, but if I
remember what did work though was shadowing the javax.xml.stream and
javax.json packages in the pom.xml and building the jar via maven. I think
this is a slightly better solution than setting the system properties, but
probably that's a matter of opinion.

I did this with hapi-fhir 0.9.

The entry in the pom.xml (be careful with that includes though I might have
modified them for my needs. The important part are the "relocations"):


<plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <version>2.3</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <createDependencyReducedPom>true</createDependencyReducedPom>
              <artifactSet>
                <includes>
                  <include>commons-codec:commons-codec</include>
                  <include>commons-io:commons-io</include>
                  <include>ca.uhn.hapi.fhir:hapi-fhir-base</include>

<include>ca.uhn.hapi.fhir:hapi-fhir-structures-dstu</include>
                  <include>org.glassfish:javax.json</include>
                  <include>org.codehaus.woodstox:woodstox-core-asl</include>
                  <include>javax.xml.stream:stax-api</include>
                  <include>org.codehaus.woodstox:stax2-api</include>
                  <include>org.apache.commons:*</include>
                  <include>org.apache.httpcomponents:*</include>
                  <include>org.glassfish:javax.json</include>
                </includes>
              </artifactSet>
              <relocations>
                <relocation>
                  <pattern>javax.xml.stream</pattern>

<shadedPattern>ca.uhn.fhir.repackage.javax.xml.stream</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>javax.json</pattern>

<shadedPattern>ca.uhn.fhir.repackage.javax.json</shadedPattern>
                </relocation>
              </relocations>
              <filters>
                <filter>
                  <artifact>ca.uhn.hapi.fhir:hapi-fhir-base</artifact>
                  <excludes>
                    <exclude>ca/uhn/fhir/model/dstu/valueset/**</exclude>
                    <exclude>**/*.java</exclude>
                  </excludes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>




I can't upgrade the hapi fhir library at the moment, but maybe somebody can
confirm this.




2015-07-24 21:12 GMT+02:00 Thomas Andersen <notifications@github.com>:

**Comment by wurstnudl** [comment]
Oh I'm totally sorry I think I can remember now. Those are probably even
the default entries, my bad ;-)

I had to add this entry in the relocations:

<relocation>
  <pattern>com.bea.xml.stream.MXParserFactory</pattern>
  <shadedPattern>com.ctc.wstx.stax.WstxInputFactory</shadedPattern>
</relocation>


So this might even be a different problem.

2015-07-29 9:59 GMT+02:00 J. Bachmann <bachmajo@gmail.com>:
