### ISSUE TITLE
Internal Server error 500 (Failed to call access method) while trying to post QuestionnaireAnswer

### ISSUE THREAD

**Issue by gansoper** [jamesagnew/hapi-fhir#201]
Hello,

I tried to post  a questionnaire answer to the public HAPI server - http://fhirtest.uhn.ca/

```xml
<QuestionnaireAnswers xmlns="http://hl7.org/fhir">
   <identifier>
      <value value="4772"/>
   </identifier>
   <questionnaire>
      <reference value="Questionnaire/4772"/>
   </questionnaire>
   <subject>
      <reference value="Organization/4769"/>
   </subject>
   <authored value="2015-07-29T20:39:17+04:00"/>
   <group>
      <title value="Main Group"/>
      <group>
         <text value="Common"/>
         <question>
            <linkId value="Link0"/>
            <text value="What is your name?"/>
            <answer>
               <valueString value="swewe"/>
            </answer>
         </question>
         <question>
            <linkId value="Link1"/>
            <text value="What is your age?"/>
            <answer>
               <valueInteger value="1"/>
            </answer>
         </question>
         <question>
            <linkId value="Link2"/>
            <text value="Do you smoke?"/>
            <answer>
               <valueBoolean value="false"/>
            </answer>
         </question>
         <question>
            <linkId value="Link3"/>
            <text value="What is your age?"/>
            <answer>
               <valueInteger value="23"/>
            </answer>
         </question>
         <question>
            <linkId value="Link4"/>
            <text value="Do you smoke?"/>
            <answer>
               <valueBoolean value="false"/>
            </answer>
         </question>
      </group>
   </group>
</QuestionnaireAnswers>'''


but got the "Failed to call access method" error. Can you please have a look?

**Comment by jamesagnew** [comment]
This is a great test case for the new QuestionnaireAnswersValidator. FYI when you post a QuestionnaireAnswers to our server and it references a questionnaire, it will be validated against that questionnaire.

There was a bug in the validator which was causing it to crash. That has now been fixed, so posting that questionnaire doesn't crash. However, the validator doesn't support "questionnaire-deReference" questions so it still won't accept that QuestionnaireAnswers.

It probably should, but I can't find any examples of this anywhere, other than the one you are posting.... Where is this defined?

**Comment by gansoper** [comment]
Hello James,

Thank you for your answer.

This example was taken from our own demo solution. Test case is following

1) User creates Questionnaire and saves it to sever
2) Other user takes the questionnaire  (application renders it to
appropriate usable form) and answers questions
3) Application creates QuestionnaireAnswer entity and post it to server as
well. Thus there should be connection between Questionnaire and
QuestionnaireAnswer which I implemented with help of reference.


I followed description that is provided here :

http://hl7.org/fhir/2015May/questionnaireanswers.html

As yo can see there is the link to Questionnnaire in QuestionnnaireAnswers.


We already had this demo workable (with references) about one or two months
ago and everything was fine then. I'm not sure why it stopped working.

From your explanation I understood that reference is not working, so I can
not place it to QuestionnareAnswer - right?

Thanks,
Andrew


2015-07-29 22:59 GMT+03:00 James Agnew <notifications@github.com>:

**Comment by jamesagnew** [comment]
Hi Andrew,

Just to be clear, there is nothing wrong with your QuestionnaireAnswers (at least I don't think there is). 

We recently added a validator so that answers get validated when they are posted, and the issue you're having is with the validator itself. It's half fixed now, but I'll fix it completely later today. You don't need to do anything. :)

**Comment by wanghaisheng** [comment]
@gansoper   are your solution something like IHE RFC or ONC  SDC?

**Comment by jamesagnew** [comment]
This is fixed! Still don't have validation on dereferenced elements, as there are no canonical examples of this yet but you can once again post your example and it will be validated.

**Comment by gansoper** [comment]
Hello,

It seems that  ONC SDC will be the correct answer:)

Thanks,
Andrew

2015-07-30 15:54 GMT+03:00 wanghaisheng <notifications@github.com>:

**Comment by wanghaisheng** [comment]
@gansoper  thx bro

**Comment by gansoper** [comment]
Hello guys,

Could you please review the issue #203 - this is really weird - delete of
QuestionAnswers does not work at all...

2015-08-03 10:06 GMT+03:00 wanghaisheng <notifications@github.com>:
