### ISSUE TITLE
Can't get custom search parameters of type SearchParamTypeEnum.NUMBER working

### ISSUE THREAD

**Issue by edclement** [jamesagnew/hapi-fhir#2023]
**Describe the bug**
I'm able to get custom Token/String search params working fine but Number type params don't seem to work.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 5.0.2
 - OS: Fedora 32 (running a barely custom HAPI FHIR server forked from https://github.com/hapifhir/hapi-fhir-jpaserver-starter)
 - Browser: NA

Hi, I'm having some troubles getting integer customer search param types working in HAPI FHIR with DSTU2. I'm able to get Token (String) type working fine. I was hoping someone could provide some assistance. I've spent a day debugging and can't figure out what is wrong...

**Example Code:**
```java
// This DOES NOT work - NUMBER type search param
SearchParameter numberParameter = new ca.uhn.fhir.model.dstu2.resource.SearchParameter();
numberParameter.setName("Future Appointment Count");
numberParameter.setCode("future-appointment-count");
numberParameter.setDescription("Count of future appointments for the patient");
numberParameter.setUrl("http://integer"); // not what I'm really using as the url
numberParameter.setStatus(ca.uhn.fhir.model.dstu2.valueset.ConformanceResourceStatusEnum.ACTIVE);
numberParameter.setBase(ca.uhn.fhir.model.dstu2.valueset.ResourceTypeEnum.PATIENT);
numberParameter.setType(ca.uhn.fhir.model.dstu2.valueset.SearchParamTypeEnum.NUMBER);
numberParameter.setXpathUsage(XPathUsageTypeEnum.NORMAL);
numberParameter.setXpath("Patient.extension('http://integer')"); // not what I'm really using as the url

// This DOES work - TOKEN type search param
SearchParameter tokenParameter = new ca.uhn.fhir.model.dstu2.resource.SearchParameter();
tokenParameter.setName("Eye Colour");
tokenParameter.setCode("eyecolour");
tokenParameter.setDescription("Eye colour of the patient");
tokenParameter.setUrl("http://token"); // not what I'm really using as the url
tokenParameter.setStatus(ca.uhn.fhir.model.dstu2.valueset.ConformanceResourceStatusEnum.ACTIVE);
tokenParameter.setBase(ca.uhn.fhir.model.dstu2.valueset.ResourceTypeEnum.PATIENT);
tokenParameter.setType(ca.uhn.fhir.model.dstu2.valueset.SearchParamTypeEnum.TOKEN);
tokenParameter.setXpathUsage(XPathUsageTypeEnum.NORMAL);
tokenParameter.setXpath("Patient.extension('http://token')"); // not what I'm really using as the url

IFhirResourceDao<SearchParameter> searchParamDao = daoRegistry.getResourceDao(SearchParameter.class);
searchParamDao.create(numberParameter);
searchParamDao.create(tokenParameter);

ISearchParamRegistry searchParamRegistry = appCtx.getBean(ISearchParamRegistry.class);
searchParamRegistry.forceRefresh();
```

I based this code off of the following sources:

- https://blog.smilecdr.com/2017/02/08/custom-search-parameters-in-hapi-fhir/ (a little outdated but still relevant)
- https://github.com/jamesagnew/hapi-fhir/blob/v5.0.2/hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/dstu2/FhirResourceDaoDstu2SearchCustomSearchParamTest.java#L586

**Example Patient:**
```json
{
  "resourceType": "Patient",
  "id": "Patient1",
  "meta": {
    "versionId": "4",
    "lastUpdated": "2020-08-07T15:29:19.421-04:00"
  },
  "text": {
  "status": "generated",
  "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><div class=\"hapiHeaderText\">Patient1 <b>PATIENT1 </b></div><table class=\"hapiPropertyTable\"><tbody><tr><td>Date of birth</td><td><span>01 January 1981</span></td></tr></tbody></table></div>"
  },
  "extension": [ {
    "url": "http://integer",
    "valueInteger": 1
    }, {
    "url": "http://token",
    "valueCode": "blue"
  } ],
  "active": true,
  "name": [ {
    "use": "official",
    "family": [ "Patient1" ],
    "given": [ "Patient1" ]
  } ],
  "gender": "male",
  "birthDate": "1981-01-01"
}
```

If I do the following search for the future-appointment-count:
http://localhost:8080/fhir/dstu2/Patient?future-appointment-count=gt0
... no results are returned, I've tried with the client as well and same thing

If I do a search for eyecolour:
http://localhost:8080/fhir/dstu2/Patient?eyecolour=blue
...the example patient is returned, I've tried with the client and same result (it works)

Am I doing something wrong? Thanks in advance!

**Comment by jamesagnew** [comment]
Your example is working for me: http://hapi.fhir.org/baseDstu2/Patient?future-appointment-count=gt0

One potential reason here is that there is a SearchParameter cache that lasts 1 hour, and it needs to expire before new SearchParameters are fully active (i.e. being indexed). On your server if you create a new Patient now, does the query you quote find it?

I'm working on a patch right now to reduce the time it takes for a new SP to become active.. It does seem excessive for it to take 1 hour.

**Comment by edclement** [comment]
Hi James, thanks for your response. Based on the info you provided, I deduced the problem may be related to the underlying database. I was testing this using `mvn run` and `mvn test`. I actually had a unit test to ensure this was working. when running `mvn test`, H2 is used as the database. As soon as I ran the code as we would in our dev/stagin/prod environment (using a postgres backend) everything worked as expected. I'm going to see if I can fork the hapi-fhir-jpaserver-starter project, add this custom search param, and create a unit test to demonstrate the failure when using H2. Again, thanks for taking the time to reply.

**Comment by edclement** [comment]
@jamesagnew - ok, apparently searching for numeric values greater then 0 does work. As soon as an integer parameter is greater then 0, it fails. I forked the hapi-fhir-jpaserver-starter and created a test case to show you what I am encountering. Can you pull the repo down and give it a whirl when you have a minute:
https://github.com/hapifhir/hapi-fhir-jpaserver-starter/compare/master...edclement:numberParamSearch

**Comment by jamesagnew** [comment]
Are you able to replicate this in a unit test method similar to the one I
added to this ticket by any chance?

**Comment by edclement** [comment]
I will check and let you know. I will follow up either way. Thanks!

**Comment by edclement** [comment]
@jamesagnew 
I was already adding a `searchParamRegistry.forceRefresh();` after creating the custom search param. Inside the test I added `searchParamRegistry.refreshCacheIfNecessary();` and still seeing the issue. Looking at the test I created itself:
```java
    // this PASSES
    Bundle futureAppointmentCountBundle1 = ourClient
      .search()
      .forResource(Patient.class)
      .where(new NumberClientParam("future-appointment-count").greaterThan().number(0))
      .returnBundle(Bundle.class)
      .execute();
    assertEquals(futureAppointmentCountBundle1.getTotal().intValue(), 1);
    // this passes, patient retrieved from the futureAppointmentCountBundle1 search has a future-appointment-count set to 2
    Patient searchResultPatient2 = (Patient) eyecolourBundle.getEntry().get(0).getResource();
    List<ExtensionDt> appointmentCountExtensions2 = searchResultPatient2.getUndeclaredExtensionsByUrl("http://integer");
    assertEquals(appointmentCountExtensions2.size(), 1);
    assertEquals(appointmentCountExtensions2.get(0).getValue().toString(), new IntegerDt(2).toString());

    ISearchParamRegistry searchParamRegistry = appCtx.getBean(ISearchParamRegistry.class);
    searchParamRegistry.refreshCacheIfNecessary();

    // this FAILS, even though we just proved that the patient has a future appointment count set to 2
    Bundle futureAppointmentCountBundle2 = ourClient
      .search()
      .forResource(Patient.class)
      .where(new NumberClientParam("future-appointment-count").greaterThan().number(1))
      .returnBundle(Bundle.class)
      .execute();
    assertEquals(futureAppointmentCountBundle2.getTotal().intValue(), 1);

    // this FAILS, even though we just proved that the patient has a future appointment count set to 2
    Bundle futureAppointmentCountBundle3 = ourClient
      .search()
      .forResource(Patient.class)
      .where(new NumberClientParam("future-appointment-count").exactly().number(2))
      .returnBundle(Bundle.class)
      .execute();
    assertEquals(futureAppointmentCountBundle3.getTotal().intValue(), 1);
```
... The `.where(new NumberClientParam("future-appointment-count").greaterThan().number(0))` passes. Looking at the patient record, the integer value of the extension is actually `2`. So it makes no sense that the other two search criteria would fail:
- `.where(new NumberClientParam("future-appointment-count").greaterThan().number(1))`
- `.where(new NumberClientParam("future-appointment-count").exactly().number(2))`

**Comment by edclement** [comment]
@jamesagnew I think this might warrant re-opening. There is definitely something buggy going on with numeric custom search parameters. Have you had a chance to pull down that branch and throw a few break points in the test?

**Comment by jamesagnew** [comment]
I've incorporated your test code into another test, but this one is passing for me too.

**Comment by edclement** [comment]
Can you point me to the test code you mention? I noticed the tests here: https://github.com/jamesagnew/hapi-fhir/blob/v5.0.2/hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/dao/dstu2/FhirResourceDaoDstu2SearchCustomSearchParamTest.java#L586 do not use the client but instead use the patient DAO directly which could explain the discrepancy.

**Comment by jamesagnew** [comment]
https://github.com/jamesagnew/hapi-fhir/commit/90ebaf8549aa73cbe753058badb2105b1bb836ce#diff-bc1e706e994c047edce7e006700736f4R181

**Comment by edclement** [comment]
So I recreated your test in my code quickly and it passes. So it seems to not be an issue if you persist the patient with the extension value already set. In the test code I provided, an interceptor sets the the extension value on the patient each time an appointment is created (see [here](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/compare/master...edclement:numberParamSearch#diff-fd754e34c956222667bf99de46dc47f0)). I never set the extension value directly when saving the patient. I'm not familiar with how the indexing is performed on these custom search param fields so I'm guessing that when this value is updated from the interceptor it must not be getting indexed for searches? Is there a way to trigger indexing on a custom search field manually?

**Comment by edclement** [comment]
@jamesagnew I'm trying not to be a pest but any ideas as to why updating the value using a patient DAO from an interceptor would prevent the patient from being returned in a search result when the value of the custom extension meets the search criteria?

**Comment by jamesagnew** [comment]
No idea really, it shouldn't make a difference..

Any chance you are getting cached search results? Did you perform the same
search beforehand?

Can you try to work this scenario into the unit test I linked to?
