### ISSUE TITLE
Internal Server error 500 (Failed to call access method) while trying to delete QuestionnaireAnswer

### ISSUE THREAD

**Issue by gansoper** [jamesagnew/hapi-fhir#203]
Hello, 

I think that this issue somehow connected with the #201 

I tired to delete QuestionnaireAnswer with no connection to Questionnaire , and got 

HTTP/1.1 500 Internal Server Error  - Failed to call access method 

try this:
DELETE http://fhirtest.uhn.ca/baseDstu2/QuestionnaireAnswers/10048 

Thanks,
Andrew

**Comment by gansoper** [comment]
Hello Guys,

I undestand that this is some test server - but could you take a look into this problem? Deletion of QuestionAnswers is not working...

**Comment by jamesagnew** [comment]
HI @gansoper , this is a regression caused by the validator but we have a fix already. Should have it deployed to the test server later today or possibly early tomorrow depending on time.

**Comment by jamesagnew** [comment]
This fix has now been deployed, so DELETE should now work on QuestionnaireAnswers once again.
