### ISSUE TITLE
HL7 - OBR version 2.8.1 | HAPI Columns order different from HL7 2.8.1 document

### ISSUE THREAD

**Issue by rajatshroti** [jamesagnew/hapi-fhir#2031]
There is difference between HAPI OBR Columns order for HL7 V2.8.1 and HL7 2.8.1 document. Please find below file that has columns for both.

[AsParHAPIForOBR.pdf](https://github.com/jamesagnew/hapi-fhir/files/5049322/AsParHAPIForOBR.pdf)

Please let me know why there is difference.

**Comment by jvitrifork** [comment]
@rajatshroti this git repo is related to the development of a FHIR based framework for HL7 v4 aka. FHIR, and not directly related to HL7 v2.8.1

**Comment by jamesagnew** [comment]
Please feel free to raise here: https://github.com/hapifhir/hapi-hl7v2
