### ISSUE TITLE
HAPI FHIR Documentation - Bad Link in 13.0.2 Getting The Sources

### ISSUE THREAD

**Issue by KevinDougan** [jamesagnew/hapi-fhir#2042]
Go to:
https://hapifhir.io/hapi-fhir/docs/contributing/hacking_guide.html

Scroll down to Section:
13.0.2 Getting the Sources

Notice that there is an invalid URL for the GitHub Build Status Page.
It goes to https://dev.azure.com/jamesagnew214/jamesagnew214/_apis/build/status/jamesagnew.hapi-fhir?branchName=master which is a 404.
![HAPIFHIRDocs-13 0 2-BadLink](https://user-images.githubusercontent.com/2100158/90337542-1dc6e180-dfb1-11ea-81a6-3876cdca19ed.jpg)

**Comment by jamesagnew** [comment]
Thanks for the heads up @KevinDougan ! Fixing this now.
