### ISSUE TITLE
Tag attribute does not get populated in the response

### ISSUE THREAD

**Issue by prabhSingh** [jamesagnew/hapi-fhir#205]
We are building a FHIR REST API for Encounter resource (DSTU 2) and as part of that we are trying to populate the meta tag attribute in the response (https://jamesagnew.github.io/hapi-fhir/doc_tags.html). We are creating and setting the tag in the returned resource. However, the tag does not show up in the response.

If we populate the version or lastUpdated attribute then the tag attribute appears in the response. However, we do not want to include either of these attributes.

FYI - We observed the same behaviour with the procedure resource

Sample response is 
```
{  
   "resourceType":"Bundle",
   "id":"c83ccea3-d394-40c5-986e-fdecee25e560",
   "type":"searchset",
   "base":"http://localhost:8080/fhir/dstu2",
   "total":1,
   "link":[  
      {  
         "relation":"self",
         "url":"....."
      }
   ],
   "entry":[  
      {  
         "resource":{  
            "resourceType":"Encounter",
            "id":"8ea540b2-bfb4-4d3d-8a76-2bdd0989a42e",
            "meta":{  
               "lastUpdated":"2011-01-02T11:22:33.0000Z",
               "tag":[  
                  {  
                     "system":".....",
                     "code":"generated",
                     "display":"Generated Id"
                  }
               ]
            },
            "patient":{  
             .....
            }
         }
      }
   ]
}
```
We only want to include meta -> tag attribute. But it does not appear in the response unless we populate meta -> lastUpdated or meta -> versionId attribute.

**Comment by jamesagnew** [comment]
Hi @prabhSingh , I've added a test and this seems to work for me.

What version of HAPI are you using?

**Comment by prabhSingh** [comment]
We are using version 1.0

**Comment by jamesagnew** [comment]
Can you please try it with version 1.1 of the library? I believe this is an
issue that was solved in that version.

sent from my phone.

**Comment by jamesagnew** [comment]
Closing old bug, please feel free to reopen if this is still happening with version 1.1
