### ISSUE TITLE
Connection Pool Shutdown

### ISSUE THREAD

**Issue by tanieee28** [jamesagnew/hapi-fhir#2055]
Warning!
Failed to load conformance statement, error was: ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: Connection pool shut down

Getting above error on opening home page.

Can someone help ?

**Comment by jamesagnew** [comment]
Thanks for the heads up, this is fixed!

**Comment by tanieee28** [comment]
Its up now.
Thanks @jamesagnew for quick response.
