### ISSUE TITLE
Content does not appear to be FHIR JSON, first non-whitespace character was: '[' (must be '{')

### ISSUE THREAD

**Issue by theo-m** [jamesagnew/hapi-fhir#2056]
**Describe the bug**

Bug: 
```
Exception in thread "main" ca.uhn.fhir.parser.DataFormatException: Failed to parse JSON content, error was: Content does not appear to be FHIR JSON, first non-whitespace character was: '[' (must be '{')
```

Content of the file (limited to 512kb, the actual file is 2.5mb) [on this pastebin](https://pastebin.com/HuSCAGrL) and first lines below:
```json
{
  "resourceType": "Bundle",
  "type": "transaction",
  "entry": [
    {
      "fullUrl": "urn:uuid:7e663514-8a66-bad6-0dc5-11ff003b0904",
      "resource": {
        "resourceType": "Patient",
        "id": "7e663514-8a66-bad6-0dc5-11ff003b0904",
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: master-branch-latest-8-gfad266a8\n .   Person seed: 4145537462502279  Population seed: 1598445728084</div>"
        },
```

As you can see the first non whitespace character is indeed a `{`

**To Reproduce**
1. Parse a JSON file starting with `{`

**Expected behavior**
Either the error message is wrong, but I've looked at the code: https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/json/jackson/JacksonStructure.java#L86-L106 and it seems to be doing what the error message says.

**Screenshots**

**Environment (please complete the following information):**
 - HAPI FHIR Version: 5.1.0 (happened with 4.2.0 too)
 - OS: macos

**Additional context**
The files were generated by [Synthea](https://github.com/synthetichealth/synthea) to match the FHIR format, I've used FHIR visualization tool to look at them, e.g. with [this one](https://techcommunity.microsoft.com/t5/educator-developer-blog/fhir-data-visualization/ba-p/1451780), and it didn't complain.

**Comment by theo-m** [comment]
Looks like it's because the parser doesn't handle a "bundle" resource type. 
Using the parser's `setOverrideResourceIdWithBundleEntryFullUrl` doesn't help.

Resorted to pre-parsing the json to give individual items from "entry" to HAPI's parser:
```kotlin
            val preParsed = objectMapper.readValue<Map<String, Any>>(bytes)
            val entries = preParsed["entry"] ?: throw Exception("Excepted an 'entry' key, keys are: ${preParsed.keys}")
            check(entries is Iterable<*>)
            entries.map { parser.parseResource(it.toString()) }
```

I now fail for a different reason, yay! And this time it looks like it actually comes from my json file, will ping over at Synthea!

**Comment by jamesagnew** [comment]
I'm a bit confused by this report - HAPI FHIR's parser absolutely handles
the Bundle resource type, we have probably 1000+ tests that do exactly this.

I suspect there is an issue with your source data.

**Comment by theo-m** [comment]
I've included the data in the description, I was suspecting it too but it validates as good json and is generated with FHIR standards in mind, see [e.g. this export code](https://github.com/synthetichealth/synthea/blob/master/src/main/java/org/mitre/synthea/export/FhirPractitionerExporterR4.java)
