### ISSUE TITLE
NPE Parsing contained resource 

### ISSUE THREAD

**Issue by hugosoares** [jamesagnew/hapi-fhir#207]
NPE occurs when parsing an contained resource that has wrong "resourceType" property like "resourTypezz". 
Problem is on JsonParser.java ln 1121 on the parse children object. 
You shoul either catch the expction thrown by JsonObject.getString or use getString with a default value of String.empty (wich seems like what you were expecting the result to be on the first place).

The validation outcome should then be "Missing 'resourceType' from resource"

**Comment by jamesagnew** [comment]
Thanks for reporting! Will check in a fix shortly!
