### ISSUE TITLE
How shall i add extension in questionnaire from dstu2 ?

### ISSUE THREAD

**Issue by Gaduo** [jamesagnew/hapi-fhir#208]
Hi, everyone

how shall i add extension in questionnaire from dstu2 ?

http://hl7.org/fhir/2015May/questionnaire-extensions.html

**Comment by jamesagnew** [comment]
Hi @Gaduo , you'll find some documentation on how to add extensions to resources in our documentation here: http://jamesagnew.github.io/hapi-fhir/doc_extensions.html

PS: Please post questions about how to use HAPI in our Google Group here: https://groups.google.com/d/forum/hapi-fhir

Cheers,
James
