### ISSUE TITLE
xml:lang attribute prefix gets removed during serialization

### ISSUE THREAD

**Issue by oliveregger** [jamesagnew/hapi-fhir#2111]
**Describe the bug**
When defining the language for the div element the lang attribute to be specified with lang and xml:lang for xhtml [reference](https://www.w3.org/International/questions/qa-html-language-declarations#basics) e.g.:

```xml
<div lang="fr" xml:lang="fr" xmlns="http://www.w3.org/1999/xhtml">
```
During serialization to xml or json the xml prefix is removed from the xml:lang attribute and we have two lang="fr" attributes which is invalid:

```xml
<div lang="fr" lang="fr" xmlns="http://www.w3.org/1999/xhtml">
```

**To Reproduce**
See Testcase submitted in following PR.

**Expected behavior**
The xml: prefix should not be removed.

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.2.0-SNAPSHOT
 - OS: OSX

**Comment by jamesagnew** [comment]
Closing this, as the PR was merged
