### ISSUE TITLE
ids should match [A-Za-z0-9\-\.]{1,64}

### ISSUE THREAD

**Issue by jmandel** [jamesagnew/hapi-fhir#212]
I was able to create http://fhirtest.uhn.ca/baseDstu2/Patient/bad-id:123 via

    curl -X POST --data @patient.json http://fhirtest.uhn.ca/baseDstu2/Patient/bad-id:123

Per http://hl7-fhir.github.io/datatypes#id, this should be illegal.

**Comment by jamesagnew** [comment]
Per Skype discussion, JPA server should also allow client-assigned textual IDs even if they start with a number.
