### ISSUE TITLE
Validation of Extension (4.0.0) is failing 

### ISSUE THREAD

**Issue by surajpjannu** [jamesagnew/hapi-fhir#2136]
**Describe the bug**
Validation on Extension resource is failing for R4 version.
please find the post which i raised in community channel. https://groups.google.com/g/hapi-fhir/c/9vHdEDQBxug

**To Reproduce**
1. Go to 'https://groups.google.com/g/hapi-fhir/c/9vHdEDQBxug'
2. Copy Input.json content which is an input.
3. Find the code snippet which is used in the post
4. Please find the error below.

**The extension http://hl7.org/fhir/StructureDefinition/regex is not allowed to be used at this point (allowed = e:Questionnaire.item, e:ElementDefinition.type; this element is [[StructureDefinition.snapshot.element.type.code, BackboneElement.element.type.code, ElementDefinition.type.code, Element.code, uri])"**

**Expected behavior**
Expecting validation on 4.0.0 profiles should be validated correctly. but facing an Validation Error.

**Comment by jamesagnew** [comment]
The issue is in the error message: You are not allowed to use that extension in that spot, so the validator is correctly flagging it.

That extension can be used only directly in Questionnaire.item, and in ElementDefinition.type. You've put it in ElementDefinition.type.code.
