### ISSUE TITLE
lost history path in JSON serialization of (some?) references

### ISSUE THREAD

**Issue by ericprud** [jamesagnew/hapi-fhir#2143]
**Describe the bug**
R5 examples `audit-event-example-vread.json`, `provenance-example.json`, `servicerequest-example2.json`, and `task-example1.json` don't round trip; references lose their history path, e.g.
```js
"entity": [
    { "what": {"reference": "Patient/example/_history/1"}...
```
turns into
```js
"entity": [
    { "what": {"reference": "Patient/example"}...
```
Other examples, like `bundle-references.json` and `bundle-response.json` would probably have the same issue but the JSON parser throws `Input JSON did not yield a DomainResource` when parsing them.

**To Reproduce**
1. Parse a resource from the listed example resources
2. `String serializedResource = ctx.newJsonParser().encodeResourceToString(resource)`
3. `IBaseResource parsed = ctx.newJsonParser().parseResource(<stream of serializedResource>)`
4. `((Base)parsed).equalsDeep((Base)resource)` will be false

**Expected behavior**
should serialize "Patient/example/_history/1"

**Screenshots**
N/A

**Environment (please complete the following information):**
 - HAPI FHIR from github 9e8e98b6fb and [R5 examples](https://build.fhir.org/examples-json.zip)
 - OS: Ubuntu
 - Browser: none

**Additional context**
I think `/_history/1` is getting trimmed off by a call in JsonParser.java to 
```js
preProcessValues(nextChild, theResource, values, nextChildElem, theEncodeContext)
```

**Comment by jamesagnew** [comment]
You need to configure your parser to include the versions in your serialization, by default they are stripped by that can be changed with the `setDontStripVersionsFromReferencesAtPaths` method: https://hapifhir.io/hapi-fhir/apidocs/hapi-fhir-base/ca/uhn/fhir/parser/IParser.html#setDontStripVersionsFromReferencesAtPaths(java.lang.String...)

**Comment by ericprud** [comment]
Yep, that was it. (I went with `.setStripVersionsFromReferences(false)` 'cause it only needed a boolean.) Tx!
(It's a little counter-intuitive that the default behavior doesn't round-trip, but I understand that the plurality of use cases suggest that behavior.
