### ISSUE TITLE
Is it possible to register a new resource provider dynamicly?

### ISSUE THREAD

**Issue by joedai** [jamesagnew/hapi-fhir#215]
Hi James,
    The RestfulServer that we are using works as a dispatcher and we  registered all the providers in the initialize() method.  Is it possible to register new resource providers on the fly after the servlet starts up? At the moment, in our osgi environment, we introduced ServiceListTracker which waits for all the providers to be up then starts up the servlet. How ever if any of the providers has issue the whole servlet won't startup which is against our micro service strategy. Just wondering if there is a way to register new resource provider dynamically?

Please advise 

Cheers

Joe Dai

**Comment by jamesagnew** [comment]
Hi Joe,

This capability was actually added as a part of https://github.com/jamesagnew/hapi-fhir/commit/9de81a1bd84a40d11da40cea87c0c41862a34e2c which was implemented by Bill Denton.

It will be a part of the upcoming 1.2 release. I'll note that Bill also contributed the start of an OSGi bundle of HAPI FHIR. It still needs some polishing but hopefully it will be enabled in the 1.3 devleopment cycle.
