### ISSUE TITLE
NPE when AdministrativeGender is Enumeration[null]

### ISSUE THREAD

**Issue by kristof-taveirne** [jamesagnew/hapi-fhir#2157]
Hi,

When converting from dSTU2 to STU3, I'm getting an NPE on a missing AdministrativeGender.

The resource causing the issue (coming from the Cerner Ignite sandbox) is:
` {
            "fullUrl": "https://fhir-ehr-code.cerner.com/dstu2/ec2458f2-1e24-41c8-b71b-0e701af7583d/Patient/12743884",
            "resource": {
                "resourceType": "Patient",
                "id": "12743884",
                "meta": {
                    "versionId": "0",
                    "lastUpdated": "2020-09-15T06:35:01.000Z"
                },
                "text": {
                    "status": "generated",
                    "div": "<div><p><b>Patient</b></p><p><b>Name</b>: Dawg, Joel</p><p><b>DOB</b>: Nov 11, 1991</p><p><b>Status</b>: Active</p></div>"
                },
                "identifier": [
                    {
                        "use": "usual",
                        "type": {
                            "coding": [
                                {
                                    "system": "http://hl7.org/fhir/v2/0203",
                                    "code": "MR",
                                    "display": "Medical record number",
                                    "userSelected": false
                                }
                            ],
                            "text": "MRN"
                        },
                        "system": "urn:oid:2.16.840.1.113883.6.1000",
                        "value": "7690",
                        "_value": {
                            "extension": [
                                {
                                    "url": "http://hl7.org/fhir/StructureDefinition/rendered-value",
                                    "valueString": "00000007690"
                                }
                            ]
                        },
                        "period": {
                            "start": "2020-09-15T06:35:01.000Z"
                        }
                    },
                    {
                        "use": "usual",
                        "type": {
                            "text": "Military Id"
                        },
                        "system": "urn:oid:2.16.840.1.113883.3.42.10001.100001.12",
                        "value": "10050007740",
                        "_value": {
                            "extension": [
                                {
                                    "url": "http://hl7.org/fhir/StructureDefinition/rendered-value",
                                    "valueString": "10050007740"
                                }
                            ]
                        },
                        "period": {
                            "start": "2020-09-15T06:35:01.000Z"
                        }
                    }
                ],
                "active": true,
                "name": [
                    {
                        "use": "official",
                        "text": "Dawg, Joel",
                        "family": [
                            "Dawg"
                        ],
                        "given": [
                            "Joel"
                        ]
                    }
                ],
                "telecom": [
                    {
                        "system": "phone",
                        "value": "3075557575",
                        "use": "home"
                    },
                    {
                        "system": "email",
                        "value": "amitabhp@mindfiresolutions.com",
                        "use": "work"
                    }
                ],
                "_gender": {
                    "extension": [
                        {
                            "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
                            "valueCode": "unknown"
                        }
                    ]
                },
                "birthDate": "1991-11-11"
            }
        },`

The bug appears to be in VersionConverter_10_30 on line 3869 (org.hl7.fhir.convertors-5.1.0.jar).
`            switch((org.hl7.fhir.dstu2.model.Enumerations.AdministrativeGender)src.getValue()) {
`
where src is Enumeration[null].

**Expected behavior**
The conversersion should map this to AdministrativeGender.NULL (which is the default in the switch statement).

**Screenshots**

![Screenshot 2020-11-02 153450](https://user-images.githubusercontent.com/3511273/97880113-0b8f5080-1d21-11eb-849a-367b6b291f44.png)

**Environment (please complete the following information):**
 - HAPI FHIR Version: 5.1.0
 - OS: Ubuntu

**Additional context**
N/A

**Comment by tadgh** [comment]
This issue is probably better suited for the core libs github as the file in question lives there: https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.convertors/src/main/java/org/hl7/fhir/convertors/VersionConvertor_10_30.java. 

Here is the link to their issues page: https://github.com/hapifhir/org.hl7.fhir.core/issues/

That said, looks like you're right, gender should be able to upgrade no problem: https://hl7.org/fhir/2018Jan/patient-version-maps.html

Cheers

**Comment by kristof-taveirne** [comment]
OK,

Thank you, will re-open issue there.
