### ISSUE TITLE
DSTU2 xml parsing issues

### ISSUE THREAD

**Issue by wdebeau1** [jamesagnew/hapi-fhir#216]
I've found a couple of parsing issues parsing xml files for dstu2.
In the case of identifiers, if the identifier contains
```
	<type value="MRN"/>
```
a warning should be logged, as that's not valid (type is now a codeableconcept)

In parsing MedicationStatement, attempting to parse the example at https://www.hl7.org/fhir/2015Sep/medicationstatementexample1.xml.html produces the following error:
Error on file e:\tmp\Fhir\bad\MedicationStatementExample1.xml - DataFormatException at [[row,col {unknown-source}]: [47,5]]: Unknown element 'quantityQuantity' found during parse

In parsing https://www.hl7.org/fhir/2015Sep/familymemberhistory-example.xml.html:
Error on file e:\tmp\Fhir\bad\FamilyMemberHistoryExample.xml - DataFormatException at [[row,col {unknown-source}]: [32,5]]: Unknown element 'onsetQuantity' found during parse

**Comment by jamesagnew** [comment]
The first issue is solved. Will check that in shortly.

I don't know about the other two though. The datatype is called SimpleQuantity now, but the field still seems to be called "quantityQuantity" in the spec. I've asked in the implementors chat about that...

**Comment by jamesagnew** [comment]
This wound up not being so bad after all.. Both parts are fixed.
