### ISSUE TITLE
AllergyIntolerance validation flagging erroneous ERROR 

### ISSUE THREAD

**Issue by PeterTeunissen** [jamesagnew/hapi-fhir#2163]
**Describe the bug**
When the following AllergyIntolerance json is used to create an AllergyIntolerance object and passed to the validator, we get 

`
Sample json:
{
  "resourceType": "AllergyIntolerance",
  "clinicalStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical",
        "code": "active",
        "display": "Active"
      }
    ],
    "text": "Active"
  },
  "type": "allergy",
  "category": [
    "medication"
  ],
  "criticality": "high",
  "code": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "7258",
        "display": "7258"
      }
    ],
    "text": "naproxen"
  },
  "patient": {
    "reference": "Patient/1305"
  },
  "encounter": {
    "id": "f215dc72-fe20-3b7e-a9f3-b88b360e8c3d"
  },
  "recordedDate": "2020-02-04T20:54:08.000Z",
  "note": [
    {
      "authorReference": {
        "reference": "H, A"
      },
      "time": "2020-02-04T15:54:07-05:00",
      "text": "Naproxen from SOLGM"
    }
  ],
  "reaction": [
    {
      "manifestation": [
        {
          "coding": [
            {
              "system": "http://snomed.info/sct",
              "code": "386713009",
              "display": "386713009"
            }
          ],
          "text": "Redness"
        }
      ]
    }
  ]
}
`

**To Reproduce**
The following code with above json can be used to verify:
```java
    final FhirContext ctx = FhirContext.forR4();
    final IParser p = ctx.newJsonParser();
 
    final AllergyIntolerance e = p.parseResource(AllergyIntolerance.class, js);
 
    final FhirValidator validator = ctx.newValidator();
    final FhirInstanceValidator instanceValidator = new FhirInstanceValidator();
    validator.registerValidatorModule(instanceValidator);
 
 
    final ValidationResult result = validator.validateWithResult(e);
    final boolean outcome = result.isSuccessful();
    if (!outcome) {
      log.info("The resource with id element {} did not pass validation.", e.getIdElement());
      result.getMessages()
          .forEach(singleValidationMessage -> log.info(
              " Validation severity {} - Location {} - Message {}",
              singleValidationMessage.getSeverity(), singleValidationMessage.getLocationString(),
              singleValidationMessage.getMessage()));
    }
```

Maven dependencies used:

```xml
<dependency>
   <groupId>ca.uhn.hapi.fhir</groupId>
   <artifactId>hapi-fhir-base</artifactId>
   <version>4.1.0</version>
</dependency>

<dependency>
   <groupId>ca.uhn.hapi.fhir</groupId>
   <version>4.1.0</version>
   <artifactId>hapi-fhir-structures-r4</artifactId>
</dependency>

<dependency>
   <groupId>ca.uhn.hapi.fhir</groupId>
   <version>4.1.0</version>
   <artifactId>hapi-fhir-validation</artifactId>
</dependency>

<dependency>
   <groupId>ca.uhn.hapi.fhir</groupId>
   <artifactId>hapi-fhir-validation-resources-r4</artifactId>
   <version>4.1.0</version>
</dependency>
```

**Expected behavior**
According to https://www.hl7.org/fhir/allergyintolerance-definitions.html#AllergyIntolerance.verificationStatus it is valid to not have a verificationStatus. This should not have been flagged as error.

**Environment (please complete the following information):**
 - HAPI FHIR Version: 4.1
 - OS: Windows 10
 - Browser n.a.

**Additional context**
n.a.

**Comment by jamesagnew** [comment]
That is a really old version of HAPI FHIR. Can you please verify using the current release?

**Comment by jamesagnew** [comment]
Closing this as there has been no response. Please feel absolutely free to update if this issue is still present in the current release of HAPI FHIR and we will reopen.
