### ISSUE TITLE
PARAM_PAGINGACTION "_getpages" not being recognized correctly.

### ISSUE THREAD

**Issue by granadacoder** [jamesagnew/hapi-fhir#2165]
NOTE: Before filing a ticket, please see the following URL:
https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Describe the bug**

When coding and running against the PARAM_PAGINGACTION "_getpages" query-string name like this:

```
Patient/?_getpages=aaaaaaaa-d6e3-4ab3-8665-f131941f323f&_getpagesoffset=50&_count=25&_pretty=true&_bundletype=searchset
```

Note, the above query is the result of a pagination search.

Getting postman error like this:

```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[Patient/] with parameters [[_getpages, _pretty, _count, _getpagesoffset, _bundletype]]"
        }
    ]
}
```

**To Reproduce**

Create a Patient Resource Provider (r4)

```
import org.hl7.fhir.r4.model.Patient;

public class MyPatientResourceProviderBase implements IResourceProvider {

    /**
     * The getResourceType method comes from IResourceProvider, and must be overridden to indicate what type of resource this provider supplies.
     */
    @Override
    public Class<Patient> getResourceType() {
        return Patient.class;
    }

Add this @Search  method:

import static ca.uhn.fhir.rest.api.Constants.PARAM_BUNDLETYPE;
import static ca.uhn.fhir.rest.api.Constants.PARAM_COUNT;
import static ca.uhn.fhir.rest.api.Constants.PARAM_PAGINGACTION;
import static ca.uhn.fhir.rest.api.Constants.PARAM_PAGINGOFFSET;
import static ca.uhn.fhir.rest.api.Constants.PARAM_PRETTY;


    @Search
    public IBundleProvider findPatientsByPaging(@OptionalParam(name = PARAM_PAGINGACTION) String theGetPages,
                                                 @OptionalParam(name = PARAM_PAGINGOFFSET) String thePagingOffSet,
                                                 @OptionalParam(name = PARAM_COUNT) String theCount,
                                                 @OptionalParam(name = PARAM_PRETTY) String thePretty,
                                                 @OptionalParam(name = PARAM_BUNDLETYPE) String theBundleType
    ) {

return null;

}
```

Current Version:

**Expected behavior**

PARAM_PAGINGACTION does not error out.

**Environment (please complete the following information):**

    Gradle import/hapi fhir server version

    implementation group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-server', version: '5.1.0'

**Additional context**

Note, if I change it to

```
    @Search
    public IBundleProvider findPatientsByPaging(@OptionalParam(name = "_getpagesx") String theGetPages,
                                                 @OptionalParam(name = PARAM_PAGINGOFFSET) String thePagingOffSet,
                                                 @OptionalParam(name = PARAM_COUNT) String theCount,
                                                 @OptionalParam(name = PARAM_PRETTY) String thePretty,
                                                 @OptionalParam(name = PARAM_BUNDLETYPE) String theBundleType
    ) {
```

and slightly adjust the request to:

```
Patient/?_getpagesx=aaaaaaaa-d6e3-4ab3-8665-f131941f323f&_getpagesoffset=50&_count=25&_pretty=true&_bundletype=searchset

```
It works fine.

Something about that 

PARAM_PAGINGACTION

Note sure if these being so close is an issue:

	public static final String PARAM_PAGINGACTION = "_getpages";
	public static final String PARAM_PAGINGOFFSET = "_getpagesoffset";

**Comment by jamesagnew** [comment]
HAPI FHIR paging URLs have to be executed against the base of the server, and have to come from existing search result bundles (i.e. be created by HAPI FHIR). In other words, it is not valid to create your own.

Did HAPI FHIR give you a paging URL with `Patient/?` in it?

**Comment by jamesagnew** [comment]
(Note that this is FHIR's rule, not HAPI's)

**Comment by granadacoder** [comment]
Ok, maybe I'm not understanding something then.

Here is my "regular" search...but I've added pagination.

myr4fhirserver/Patient/?

And I get back:


{
    "resourceType": "Bundle",
    "id": "5555f71b7469458cb34286e9638febf9",
    "meta": {
        "lastUpdated": "2020-11-09T17:36:50.300-05:00"
    },
    "type": "searchset",
    "total": 100,
    "link": [
        {
            "relation": "self",
            "url": "/myr4fhirserver/*/Patient/"
        },
        {
            "relation": "next",
            "url": "/myr4fhirserver/*?_getpages=aaaaaaaa-db90-46c7-8ca6-b3eb565249d5&_getpagesoffset=25&_count=25&_pretty=true&_bundletype=searchset"
        }
    ],
    "entry": [

So I don't take the "next" .. and run it through /Patient/ again?

Is that my miscue?

**Comment by granadacoder** [comment]
I have injected this into my "context" via xml

        <bean id="zzzFifoMemoryPagingProviderBean"
              class="ca.uhn.fhir.rest.server.FifoMemoryPagingProvider">
            <constructor-arg value="10"/>
        </bean>


which is the (close xml version of 

https://hapifhir.io/hapi-fhir/docs/server_plain/paging.html


      FifoMemoryPagingProvider pp = new FifoMemoryPagingProvider(10);
      pp.setDefaultPageSize(10);
      pp.setMaximumPageSize(100);
      setPagingProvider(pp);


and am calling

RestfulServer.setPagingProvider (with the above injection)

**Comment by jamesagnew** [comment]
You would just run it through / (i.e. your server base URL) again, not
[baseUrl]/Patient/.

That's really weird through that HAPI isn't already adding a base URL to
those next/self links. Are you using a custom server base URL strategy or
something?

**Comment by granadacoder** [comment]
public final class FullOrShortServerAddressStrategy implements IServerAddressStrategy {

    private boolean showFullUrl = false;

You've done it again!

Tomorrow I will see if my custom FullOrShortServerAddressStrategy is screwing things up and report back.

**Comment by granadacoder** [comment]
Ok, I temporarily removed my custom address strategy.

and now I see a "healthier" NEXT link

            "relation": "next",
            "url": "http://me.com/myr4fhirserver?_getpages=aaaaaaaa-6b26-4d81-a398-e2d154a59e09&_getpagesoffset=25&_count=25&_pretty=true&_bundletype=searchset"
        }

and now I "see" better how the _getpages is off the root.

S'oh boy.  Now I gotta tell update my teams.

It is still weird to me that it isn't off of /Patient/

**Comment by jamesagnew** [comment]
Closing this as it appears solved. But of course please feel free to comment if it is not.

**Comment by granadacoder** [comment]
Everything is ok.  I had a small bug in my IServerAddressStrategy. (That's where that "*" was coming from).
Thanks for your quick feedback.

Once again, this was not a real bug, but a lack of understanding on my part.

To finish out the conversation...here is my return payload:

and the "next" link (and later one, the "previous" links) work correctly.

{
    "resourceType": "Bundle",
    "id": "abcblahblahblah1228be50d",
    "meta": {
        "lastUpdated": "2020-11-10T16:06:18.775-05:00"
    },
    "type": "searchset",
    "total": 100,
    "link": [
        {
            "relation": "self",
            "url": "http://localhost:8080/myr4fhirserver/Patient/?_count=13"
        },
        {
            "relation": "next",
            "url": "http://localhost:8080/myr4fhirserver?_getpages=bbbbcd07-6bfe-4f0a-bc17-e5035746261a&_getpagesoffset=13&_count=13&_pretty=true&_bundletype=searchset"
        }
    ],
    "entry": [
        {
            "fullUrl": "http://localhost:8080/myr4fhirserver/Patient/14",
            "resource": {
                "resourceType": "Patient",

**Comment by granadacoder** [comment]
PS, I wrote a "PayAsYouGo" IBundleProvider.  with an injectable method to handle the "getting".
#foodForThought


```

import ca.uhn.fhir.model.primitive.InstantDt;
import ca.uhn.fhir.rest.api.server.IBundleProvider;

import org.hl7.fhir.instance.model.api.IBaseResource;
import org.hl7.fhir.instance.model.api.IPrimitiveType;

import javax.annotation.Nonnull;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.function.BiFunction;
import java.util.stream.Collectors;

/**
 * PayAsYouGoBundleProvider allows for an injected method where the method is able to get the subset of items based on fromIndex and toIndex.
 *
 * @param <R>
 */
public final class PayAsYouGoBundleProvider<R extends YouPickSomethingHereReadTheComments> implements IBundleProvider {

    private final String uuid;

    private Integer preferredPageSize;

    /* Must be the TRUE overall size of the resources. */
    private Integer overallSize;

    private IPrimitiveType<Date> publishedDate = InstantDt.withCurrentTime();

    private BiFunction<Integer, Integer, R> pagingDataRetriever;

    /**
     * @param uuid random uuid
     * @param overallItemsCount this must be the actual and true OVERALL count, not just the "current page of data" count
     * @param pagingDataRetriever a BiFunction where the "R" should be List<IBaseResource> or something that can be converted to a List<IBaseResource> 
     */
    public PayAsYouGoBundleProvider(String uuid, int overallItemsCount, BiFunction<Integer, Integer, R> pagingDataRetriever) {
        this.uuid = uuid;
        setSize(overallItemsCount);
        this.pagingDataRetriever = pagingDataRetriever;
    }

    @Override
    public IPrimitiveType<Date> getPublished() {
        return this.publishedDate;
    }

    /**
     * By default this class uses the object creation date/time (for this object)
     * to determine {@link #getPublished() the published date} but this
     * method may be used to specify an alternate date/time.
     */
    public void setPublished(IPrimitiveType<Date> newPublishedDate) {

        this.publishedDate = newPublishedDate;
    }

    @Nonnull
    @Override
    public List<IBaseResource> getResources(int fromIndex, int toIndex) {
        R rItem = this.pagingDataRetriever.apply(fromIndex, toIndex);
        List<IBaseResource> returnItems = rItem; /* OR rItem can be something translate-able to List<IBaseResource> */ 
        return returnItems;
    }

    @Override
    public String getUuid() {
        return uuid;
    }

    /**
     * Defaults to null.
     */
    @Override
    public Integer preferredPageSize() {
        return preferredPageSize;
    }

    /**
     * Sets the preferred page size to be returned by {@link #preferredPageSize()}.
     * Default is <code>null</code>.
     */
    public void setPreferredPageSize(Integer preferredPageSize) {
        this.preferredPageSize = preferredPageSize;

    }

    /**
     * Sets the total number of results, if this provider corresponds to a single page within a larger search result.
     */
    public PayAsYouGoBundleProvider setSize(Integer theSize) {
        this.overallSize = theSize;
        return this;
    }

    @Override
    public Integer size() {
        return this.overallSize;
    }
}

```
