### ISSUE TITLE
Contributing and/or development documentation

### ISSUE THREAD

**Issue by SingingTree** [jamesagnew/hapi-fhir#217]
The project currently does not have documentation targeted towards people who want to contribute and/or hack on the project. People can work through issues they might encounter, but I think it would be worthwhile to lower the barrier to entry by having information on the process (even if it's just a getting started doc).

I've got some notes/ideas I've been jotting down while getting the repo working in Eclipse and command line that I'd like to contribute (to the README.md, or a CONTRIBUTING.md, or similar), but would like to discuss what the preferred way to present such information would be before I open a pull request.

**Comment by jamesagnew** [comment]
Hi @SingingTree , having a page with "getting started hacking" instructions of some sort sounds like a really useful idea.

Ideally it would be nice to put this page on the HAPI website (which is built by Maven), so it should probably be in a format that Maven understands. There are plenty of choices there, but Markdown and XDOC are probably the best bets to be consistent with the rest of the project.

If you wanted to write an Xdoc document, you could put in [this directory](https://github.com/jamesagnew/hapi-fhir/tree/master/src/site/xdoc). Xdoc is basically XHTML with two extra tags, section and subsection for laying out the page. There are lots of examples of Xdoc in that directory.

Markdown is the other option, and could go [here](https://github.com/jamesagnew/hapi-fhir/tree/master/src/site/markdown). One thing to note, Maven uses [pegdown markdown](https://github.com/sirthias/pegdown) which is slightly different from GitHub markdown.

If you want to see how your page would render with the rest of the site, you need to execute `mvn -P SITE site` once to build the whole site. This takes forever, so after you've done this once you can just do `mvn -P ROOT site` to just build the pages. The output will be in `target/site`.

**Comment by SingingTree** [comment]
Cheers, I'll take a look and see if I can get something sorted.

**Comment by KevinMayfield** [comment]
Sounds like a great idea. I'll look at contributing also.
