### ISSUE TITLE
VersionConvertor_10_30.convertTimingRepeatComponent  causes NullPointerException if Timing.when is null

### ISSUE THREAD

**Issue by eotoole67** [jamesagnew/hapi-fhir#2181]
**Describe the bug**
If I call 
```
org.hl7.fhir.dstu3.model.Timing.TimingRepeatComponent tgt = 
    VersionConvertor_10_30.convertTimingRepeatComponent(org.hl7.fhir.dstu2.model.Timing.TimingRepeatComponent src);
```
where src.when is null 
Then any call to tgt.hasWhen causes a NullPointerException

**To Reproduce**
1. Run *Sample Code* below 
2. Expected Outcome 
tgt.when=null
3. Actual Outcome 
NullPointerException

**Sample Code**
```
public class TimingBugTest {
    
    public static void main(String[] args) {
        org.hl7.fhir.dstu2.model.Timing.TimingRepeatComponent src = new org.hl7.fhir.dstu2.model.Timing.TimingRepeatComponent();
        src.setCount(11);
        org.hl7.fhir.dstu3.model.Timing.TimingRepeatComponent tgt = VersionConvertor_10_30.convertTimingRepeatComponent(src);
        
        System.out.println("tgt.count=" + tgt.getCount());
        System.out.println("tgt.when=" + tgt.hasWhen());
        
                
    }
}
```

**Environment (please complete the following information):**
 - HAPI FHIR Version 5.1.0
 - OS: na
 - Browser: na

**To Fix**
add src.hasWhen condition
before:
```
    tgt.setWhen(Collections.singletonList(convertEventTiming(src.getWhenElement())));
    return tgt;
  }
```
after:
```
   if (src.hasWhen())
        tgt.setWhen(Collections.singletonList(convertEventTiming(src.getWhenElement())));
    return tgt;
  }
```

**Comment by tadgh** [comment]
This code actually lives in the core libs, over in this file: https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.convertors/src/main/java/org/hl7/fhir/convertors/VersionConvertor_10_30.java

Would appreciate it if you could re-open this issue over there.
