### ISSUE TITLE
Modified Practitioner as HumcPractitioner and clicking on HumcPractitioner test server. How to resolve this.

### ISSUE THREAD

**Issue by mepatil** [jamesagnew/hapi-fhir#219]
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is ca.uhn.fhir.parser.DataFormatException: Unknown resource name "HumcPractitioner" (this name is not known in FHIR version "DSTU2")
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
    org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
    org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    org.ebaysf.web.cors.CORSFilter.handleNonCORS(CORSFilter.java:437)
    org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:172)
root cause

ca.uhn.fhir.parser.DataFormatException: Unknown resource name "HumcPractitioner" (this name is not known in FHIR version "DSTU2")
    ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:273)
    ca.uhn.fhir.to.Controller.actionResource(Controller.java:335)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:483)
    org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
    org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777)
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706)
    org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
    org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
    org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
    org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    org.ebaysf.web.cors.CORSFilter.handleNonCORS(CORSFilter.java:437)
    org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:172)

**Comment by jamesagnew** [comment]
Hi @mepatil ,

Can you provide a bit more detail on what you're trying to do?

That error message means that you've used a url like [base]/HumcPractitioner

If you have created your own resource type which extends Practitioner (perhaps to add extensions or something?) you still access that via [base]/Practitioner, since that's still the FHIR resource type. Your server is welcome to return instances of HumcPractitioner in the IResourceProvider for that type.

Cheers,
James

**Comment by mepatil** [comment]
THis is my HumcPractitioner extends Practitioner Classs. 
Queries
1) How can we change the Extension to any other my own name like eg.iTotal or How can add my own interger or string with my own name?
2) When I am clicking on my test server Resources HumcPractitioner then I am getting ablove error. How can I resolve it.
http://localhost:8080/humc-server/tester/resource?serverId=example&resource=HumcPractitioner
3) MyConnector  is my own servlet class.

package com.humc.server.servlet;

import java.util.ArrayList;
import java.util.List;

import ca.uhn.fhir.context.FhirContext;
import ca.uhn.fhir.narrative.DefaultThymeleafNarrativeGenerator;
import ca.uhn.fhir.narrative.INarrativeGenerator;
import ca.uhn.fhir.rest.server.EncodingEnum;
import ca.uhn.fhir.rest.server.FifoMemoryPagingProvider;
import ca.uhn.fhir.rest.server.IResourceProvider;
import ca.uhn.fhir.rest.server.RestfulServer;

import com.humc.server.provider.OrganizationResourceProvider;
import com.humc.server.provider.PatientResourceProvider;
import com.humc.server.provider.PractitionerResourceProvider;
import com.humc.server.provider.ValueSetResourceProvider;

/**
 * This servlet is the actual FHIR server itself
 */
public class MyConnector extends RestfulServer {

	private static final long serialVersionUID = 1L;

	/**
	 * Constructor
	 */
	public MyConnector () {
		super(FhirContext.forDstu2()); // Support DSTU2
	}

	/**
	 * This method is called automatically when the servlet is initializing.
	 */
	@Override
	public void initialize() {
		
		
		 // In your initialize method, assign a DSTU2 FhirContext. This
	      // is all that is required in order to put the server
	      // into DSTU2 mode
	      setFhirContext(FhirContext.forDstu2());
	      
		/*
		 * Two resource providers are defined. Each one handles a specific type
		 * of resource.
		 */
		List<IResourceProvider> providers = new ArrayList<IResourceProvider>();
		//providers.add(new PatientResourceProvider());
		//providers.add(new OrganizationResourceProvider());
		providers.add(new PractitionerResourceProvider());
		providers.add(new ValueSetResourceProvider());
		setResourceProviders(providers);

		/*
		 * Use a narrative generator. This is a completely optional step, but
		 * can be useful as it causes HAPI to generate narratives for resources
		 * which don't otherwise have one.
		 */
		INarrativeGenerator narrativeGen = new DefaultThymeleafNarrativeGenerator();
		getFhirContext().setNarrativeGenerator(narrativeGen);

		/*
		 * This tells the server to use "browser friendly" MIME types if it
		 * detects that the request is coming from a browser, in the hopes that
		 * the browser won't just treat the content as a binary payload and try
		 * to download it (which is what generally happens if you load a FHIR
		 * URL in a browser).
		 * 
		 * This means that the server isn't technically complying with the FHIR
		 * specification for direct browser requests, but this mode is very
		 * helpful for testing and troubleshooting since it means you can look
		 * at FHIR URLs directly in a browser.
		 */
		setUseBrowserFriendlyContentTypes(true);

		/*
		 * Default to XML and pretty printing
		 */
		setDefaultPrettyPrint(true);
		setDefaultResponseEncoding(EncodingEnum.JSON);

		/*
		 * This is a simple paging strategy that keeps the last 10 searches in
		 * memory
		 */
		setPagingProvider(new FifoMemoryPagingProvider(10));

	}

}

=================================================
package com.humc.connector.provider;
import ca.uhn.fhir.model.api.annotation.Child;
import ca.uhn.fhir.model.api.annotation.Description;
import ca.uhn.fhir.model.api.annotation.Extension;
import ca.uhn.fhir.model.api.annotation.ResourceDef;
import ca.uhn.fhir.model.dstu2.resource.Practitioner;
import ca.uhn.fhir.model.primitive.StringDt;
import ca.uhn.fhir.util.ElementUtil;
/**
 * Definition class for adding extensions to the built-in
 * Patient resource type.
 */
@ResourceDef(name="HumcPractitioner")
public class HumcPractitioner extends Practitioner{

	 /**
     * Each extension is defined in a field. Any valid HAPI Data Type
     * can be used for the field type. Note that the [name=""] attribute
     * in the @Child annotation needs to match the name for the bean accessor
     * and mutator methods.
     */
    @Child(name="itotalRecordNumber") 
    @Extension(url="http://example.com/dontuse#itotalRecordNumber", definedLocally=false, isModifier=false)
    @Description(shortDefinition="The name of the Practitioner favourite itotalRecordNumber")
    private StringDt myItotalRecordNumber;
    
    
   
    @Override
    public boolean isEmpty() {
        return super.isEmpty() && ElementUtil.isEmpty(myItotalRecordNumber);
    }
     
    /********
     * Accessors and mutators follow
     *
     * IMPORTANT:
     * Each extension is required to have an getter/accessor and a stter/mutator.
     * You are highly recommended to create getters which create instances if they
     * do not already exist, since this is how the rest of the HAPI FHIR API works.
     ********/
 
    /** Getter for ItotalRecordNumber */
    public StringDt getItotalRecordNumber() {
        if (myItotalRecordNumber == null) {
        	myItotalRecordNumber = new StringDt();
        }
        return myItotalRecordNumber;
    }
 
    
    /** Setter for ItotalRecordNumber  */
    public void setItotalRecordNumber(StringDt itotalRecordNumber) {
    	myItotalRecordNumber = itotalRecordNumber;
    }
 
	
}

**Comment by mepatil** [comment]
Hi James,
I am setting Qualification in Practitioner  like below,but whenever I am testing on server the but qualification not coming in the response. What I am doing wrong here.It wolud be great if you send me example how to set all values in Practitioner and test it on test server response.



Practitioner practitioner = new Practitioner();
		if(StringUtils.isNotEmpty(pObject.getString(PractitionerConstant.EC_ID)) && StringUtils.isNotBlank(pObject.getString(PractitionerConstant.EC_ID)))
		practitioner.setId(new IdDt(pObject.getString(PractitionerConstant.EC_ID)));
		
		List<Practitioner.Qualification> qualificationList= new ArrayList<Practitioner.Qualification>();
		Qualification qualification =new  Qualification();
		
			//Certification 1
			 qualification.setElementSpecificId(pObject.getString(PractitionerConstant.Certification_1));
			 qualificationList.add(qualification);
		
			 
			 
		practitioner.setQualification(qualificationList);
		

		HumanNameDt humanNameDt = new HumanNameDt();
		humanNameDt.addFamily(pObject.getString(PractitionerConstant.Last_Name)).addGiven(
				pObject.getString(PractitionerConstant.First_Name));
		practitioner.setName(humanNameDt);

		practitioner.setBirthDateWithDayPrecision(new Date(pObject.getString(PractitionerConstant.DOB)));

		AddressDt address = new AddressDt();
		address.setCity(pObject.getString(PractitionerConstant.Office_1_City))
				.setPostalCode(pObject.getString(PractitionerConstant.Office_1_Zip))
				.setState(pObject.getString(PractitionerConstant.Office_1_State));
		practitioner.addAddress(address);

		AttachmentDt attachmentDt = new AttachmentDt();
		attachmentDt.setUrl(pObject.getString(PractitionerConstant.Photo));
		List<AttachmentDt> photos = new ArrayList<AttachmentDt>();
		photos.add(attachmentDt);
		practitioner.setPhoto(photos);
		

		return practitioner;
	}

Thanks 
Mepatil

**Comment by jamesagnew** [comment]
Hi Milind,

You probably need to adjust this line:

qualification.setElementSpecificId(pObject.getString(PractitionerConstant.Certification_1));

The elementSpecificId is actually just for when you need XML id=""
attributes, which is pretty rare and they don't get encoded unless
something refers to them.

I'm guessing you want to replace this with something like:
quelification.addIdentifier().setValue(
PractitionerConstant.Certification_1);

Cheers,
James
