### ISSUE TITLE
JPA Servers should be laxer about ContentType

### ISSUE THREAD

**Issue by wdebeau1** [jamesagnew/hapi-fhir#220]
When using tools like Poster, the default content type is text/xml. Currently, the JPA server example rejects this, saying it needs to be a fhir content type (either application/xml+fhir or application/json+fhir). 
While this can be tweaked in the tool (and presumably other tools as well), having to tweak things every time you want to send a debug message is annoying, and as long as the server can sniff out the content type reliably, this seems more restrictive than it needs to be.

Thus, please allow text/fhir, text/json, text/xml+fhir, text/json+fhir, application/xml, and application/json.

**Comment by jamesagnew** [comment]
I think this should be a config flag in RestfulServer, or... maybe even better an interceptor which tests incoming requests for their content and adjusts the content type accordingly.
