### ISSUE TITLE
Client provided UUIDs as primary identifier are completly ignored

### ISSUE THREAD

**Issue by ZuSe** [jamesagnew/hapi-fhir#2218]
**Describe the bug**
Against documentation the server is not creating respect to provided ids within the POST-Request-Body

**To Reproduce**
Download the hapi-fhir-starter
Set the ClientId-Strategy to UUID in config or JpaRestfulServer.java
Start the server
Create a Patient with a given uuid
A new Patient is created by with a different (server generated uuid)

**Expected behavior**
A client given UUID should always be accepted and treated first (see code comments). 
Only if the Id is invalid or the server is configured to NOT ACCEPT client provided ids it should generate one or better block the request.

**Screenshots**
https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/153#issuecomment-734397684

**Environment (please complete the following information):**
 - 5.2.0
 - Ubuntu 20.04
 - Postman

**Additional context**
I am not sure but I might remember that it worked some months ago.

**Comment by jamesagnew** [comment]
Client ID Strategy does not have an option of `UUID`, this is an option for the Server ID Strategy (see [here](https://smilecdr.com/docs/fhir_repository/resource_ids.html#server-assigned-ids) for a description of the options for both).

Also, are you using a POST or a PUT? With POST, the server is required by the FHIR spec to ignore any ID supplied by the client and assign its own ID.

**Comment by ZuSe** [comment]
Hi @jamesagnew  thanks a lot, using POST was my problem!
