### ISSUE TITLE
The $everything operation doesn't return Medications referenced from MedicationOrders

### ISSUE THREAD

**Issue by wdebeau1** [jamesagnew/hapi-fhir#226]
After a discussion on Skype, if $everything is executed on a Patient, and that patient has a MedicationOrder, and that MedicationOrder references a Medication, the Medication order should be returned as part of the result set ("The server also returns whatever resources are needed to support the records - e.g. linked practitioners, medications, locations, organizations etc."). Currently, it doesn't.

**Comment by jamesagnew** [comment]
Hmm, I can't reproduce this actually. I thought this wouldn't work, but it seems like it does.. Maybe it's not an issue after all? @wdebeau1 are you able to reproduce?
