### ISSUE TITLE
Internal Server error 500 (Failed to call access method) while trying to delete Appointent

### ISSUE THREAD

**Issue by gansoper** [jamesagnew/hapi-fhir#229]
Hello,

I was trying to delete appointment I had created recently and got this:

 HTTP/1.1 500 Internal Server Error - failed to call access method.

Was the deletion of the Appointments implemented on server?

Thanks,
Andrew

**Comment by jamesagnew** [comment]
Hi Andrew,

Do you mind to try again? I did a redeploy of the server, and it looks like one of the database sequences got corrupted. This should be working once again.
