### ISSUE TITLE
PUT http://fhirtest.uhn.ca/baseDstu2/Slot/23552?_format=xml&_pretty=true returns error 500

### ISSUE THREAD

**Issue by gansoper** [jamesagnew/hapi-fhir#231]
When I tried to update Slot resource - I've got the HTTP/1.1 500 Internal Server Error 

Yesterday it worked.

**Comment by gansoper** [comment]
The same picture with Appointment update
```xml
<Appointment xmlns="http://hl7.org/fhir">
   <id value="23586"/>
   <meta>
      <versionId value="1"/>
      <lastUpdated value="2015-09-24T11:26:20.049-04:00"/>
   </meta>
   <status value="booked"/>
   <start value="2015-09-25T09:00:00"/>
   <end value="2015-09-25T09:30:00"/>
   <participant>
      <actor>
         <reference value="Practitioner/23274"/>
      </actor>
   </participant>
   <participant>
      <actor>
         <reference value="Patient/23576"/>
      </actor>
      <status value="accepted"/>
   </participant>
</Appointment>
```

**Comment by jamesagnew** [comment]
HI there, same issue as #229 . Can you try it again?

**Comment by gansoper** [comment]
Hello James,

It seems service is down - I've got 503 message - 503 Service Temporarily Unavailable 

Thanks,
Andrew

**Comment by jamesagnew** [comment]
Man, what remarkable bad luck.

We've been up without any interruption for months and months, then an upgrade screws it up. Yesterday we were knocked offline for about 12 hours yet again because of a power outage in our data centre. Do you mind to try once more? :)

**Comment by gansoper** [comment]
Hello James,

Thank you for the quick turn around. I tried operations I had mentioned and it seems that everything works as needed.

Thanks,
Andrew

**Comment by gansoper** [comment]
Hello James,

Regretfully after some period of time update was broken again...I started to get 500 error. 

Thanks,
Andrew

**Comment by jamesagnew** [comment]
Argh, thanks for letting me know!

I thought I had reset the database sequence back to the correct value but it looks liike I had not. It should be fixed now.
