### ISSUE TITLE
V1.2 does not include validation-resources-dstu2 jar 

### ISSUE THREAD

**Issue by hugosoares** [jamesagnew/hapi-fhir#232]
Hi the donwload documentation for version 1.2  references a hapi-fhir-validation-resources-dstu2-[version].jar.
I cant find it anywere on the download page.

Can you please add it? I do not use gradle or maven....

**Comment by jamesagnew** [comment]
Hi @hugosoares , sorry about that! I've added the validation JAR to the GitHub release page. It will be included in the release ZIP as of the next release.
