### ISSUE TITLE
FhirContext and FhirVersion

### ISSUE THREAD

**Issue by akley** [jamesagnew/hapi-fhir#236]
On HAPI FHIR 1.2 there is no possibility to create the context for specific FHIR version like DSTU2 and a list of DSTU2 subset of resources. The right constructor to handle both is unfortunately, private!

Also strange is the fact, that the FhirContext constructor with resource calls the private constructer with version = null. This implies that the internal HAPI processing is set to DSTU1 resources independently from DSTU version of given resources list, if DSTU1 structures are present in classpath. So it is possible to set DSTU2 resources to context and the constructor set the version to DSTU1. This could be a bug!

My workaround is to rebuild HAPI-FHIR-OSGI-CORE without DSTU1 structures.

Cheers,
Alex

**Comment by wdebeau1** [comment]
Hi Alex,
There are factory methods that let you specify which version you want to create a context for, such as
FhirContext fhirContext = FhirContext.forDstu2();
Will that work for you?

**Comment by akley** [comment]
No it doesn't works for me. I've seen the static factory method and it works fine if you don't want to use only special subset of FHIR resources. 
However, this is not intended by me! What I need is, DSTU2 context with a subset of resources, like constructor for FhirContext(FhirVersionEnum, Class<? extends IBaseResource> theResourceType).
If I set these special resources for context, the FhirContext implementation assumes that these resources are DSTU1. Thats a bug - the private constructor is called with NULL as version, then logic choose DSTU1, beacuse rthe DSTU1 structure library is accessible from classpath.

**Comment by jamesagnew** [comment]
Hi Alexander,

I have to admit I'm really not clear on what you mean by this.

If you call FhirContext.forDstu2() you should get a context that will never
assume DSTU1 even if there are DSTU1 resources on the classpath. Any chance
you could post a code sample showing the issue you're having?

I'm just worried that if I just create the given constructor, others will
have the same issue you're having and we won't address the root cause..

Cheers,
James

**Comment by akley** [comment]
Hi James, hi Bill

I'm very frustrated about the fact, that I can not transfer my problems :)
I'll try it in another way. James, I have written a mail to you with more detailed information. 
For now only a  small introduction:

I hold my own FhirContext in my OSGi app. To do this i call:
-> FhirContext(Class<? extends IBaseResource> theResourceType) 
This constructor calls:
-> FhirContext(FhirVersionEnum theVersion, Collection<Class<? extends IBaseResource>> theResourceTypes)
First parameter is NULL. So: else if (FhirVersionEnum.DSTU1.isPresentOnClasspath())
is called next and check if DSTU1 structures are present in classpath. 
Because the HAPI-FHIR-OSGI-CORE includes the DSTU1, DSTU2 and HL7DSTU2 structures, the condition ist TRUE, isn't it?
Then the FhirContext runs under DSTU1 conditions. And as far as I have understood, this is my problem.

Can you understand my circumstances?

Cheers,
Alex
