### ISSUE TITLE
Send the Creation Request of Resources in Bundle

### ISSUE THREAD

**Issue by nikesh2187** [jamesagnew/hapi-fhir#243]
Hi,

In our project we need to send all the creation request in one go for e.g. If we want to create a patient and observation related to the patient it should happen in one call. Is there any provision for the same, if yes kindly share the details

**Comment by nikesh2187** [comment]
@jamesagnew Kindly help on this

**Comment by jamesagnew** [comment]
Hi Nikesh,

You can achieve the behaviour you are describing using the FHIR "transaction" operation. See the [description](http://www.hl7.org/fhir/http.html#transaction) of that operation in the FHIR specification.

Note that if you have questions on how to use HAPI, we would prefer if you could use our [google group](https://groups.google.com/forum/#!forum/hapi-fhir) for that.
