### ISSUE TITLE
BaseDateTimeDtDstu2Test fail with install command from maven

### ISSUE THREAD

**Issue by MBonini** [jamesagnew/hapi-fhir#248]
Hi,
when I use install command from maven on Hapi-Fhir project, on version 1.2 and 1.3-SNAPSHOT (never tried before), testToHumanDisplay() from BaseDateTimeDtDstu2Test fail on line 66: assertThat(human, containsString("12:00:00"));.
This is because I'm from Italy and here when you use format() (see BaseDateTimeDt line 108 and 112) on a Calendar with a FastDateFormat with getDateTimeInstance(FastDateFormat.MEDIUM, FastDateFormat.MEDIUM) (see BaseDateTimeDt line 64 and 65) the resulting String contain "12.00.00" (with dot and not with colon).
I don't know what is your politic about this problem, I mean that I don't know if you prefer to change the Test or if you prefer to change how HumanDisplay will work.

**Comment by jamesagnew** [comment]
Thanks for letting us know! Committing a fix now.
