### ISSUE TITLE
Deleting a patient via transaction while deleting all of their resources sometimes fails

### ISSUE THREAD

**Issue by wdebeau1** [jamesagnew/hapi-fhir#253]
I'm not sure whether order is important, but if you pull all of a patient's resources, then create a bundle deleting all of them, including the patient, it can fail because one of the resources being deleted references the patient.

https://www.hl7.org/fhir/http.html#transaction states that "The outcome of the processing the transaction SHALL NOT depend on the order of the resources in the transaction."

Removing the patient from the initial transaction then deleting the patient after the transaction works, so there's definitely not some lingering "other" resource holding onto the Patient.

**Comment by utkinnina** [comment]
@wdebeau1  hello!
can you please help me? I need an example of "pull all of a patient's resources" 
does hapi fhir provide an api to pull resources from different types in one querry?
