### ISSUE TITLE
MaritalStatusCodesEnum (all BoundCodeableConceptDt?) not serializable

### ISSUE THREAD

**Issue by nrpeterson** [jamesagnew/hapi-fhir#258]
I use Apache Spark to transform a whole bunch of raw data (in several CSVs/etc) into FHIR resources.  Doing this requires that resources be serializable, so that they can be transmitted between the various components of the system.

I currently use HAPI 1.2.

Resources themselves serialize well; I've only run in to one issue so far, namely MaritalStatusCodesEnum attached to Patient resources.

I'm happy to submit a PR, but wasn't sure which you would prefer:
1) Making IBoundCodeableConcept extend java.io.Serializable
2) Making IBoundCodeableConcept extends IBase (which already implements java.io.Serializable
3) Hidden option C

For reference, here's the serialization stack trace provided by Spark:

```15/11/18 21:15:16 ERROR yarn.ApplicationMaster: User class threw exception: org.apache.spark.SparkException: Job aborted due to stage failure: Task 164.0 in stage 28.0 (TID 7719) had a not serializable result: ca.uhn.fhir.model.dstu2.valueset.MaritalStatusCodesEnum$1
Serialization stack:
	- object not serializable (class: ca.uhn.fhir.model.dstu2.valueset.MaritalStatusCodesEnum$1, value: ca.uhn.fhir.model.dstu2.valueset.MaritalStatusCodesEnum$1@2de7fcc)
	- field (class: ca.uhn.fhir.model.dstu2.composite.BoundCodeableConceptDt, name: myBinder, type: interface ca.uhn.fhir.model.api.IValueSetEnumBinder)
	- object (class ca.uhn.fhir.model.dstu2.composite.BoundCodeableConceptDt, ca.uhn.fhir.model.dstu2.composite.BoundCodeableConceptDt@140303f3)
	- field (class: ca.uhn.fhir.model.dstu2.resource.Patient, name: myMaritalStatus, type: class ca.uhn.fhir.model.dstu2.composite.BoundCodeableConceptDt)
	- object (class ca.uhn.fhir.model.dstu2.resource.Patient, Patient[id=null])
	- field (class: scala.Tuple2, name: _2, type: class java.lang.Object)
	- ...```

**Comment by jamesagnew** [comment]
I'd say option A makes sense.... You'd probably also have to make `IValueSetEnumBinder` serializable for this to work. Pull request definitely welcome!

**Comment by nrpeterson** [comment]
No problem!  I'll put something together today.
