### ISSUE TITLE
Maven build requires JDK version 1.8 or higher.

### ISSUE THREAD

**Issue by joelsch** [jamesagnew/hapi-fhir#263]
When using JDK 1.7, the Maven build fails, and reports an OutOfMemoryError.  Example (Mac OS X 10.10):

	$ export MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
	$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home
	$ mvn clean install
	...
	Exception: java.lang.OutOfMemoryError thrown ...

Changing JAVA_HOME to use JDK 1.8 enables the build to succeed:

	$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
	$ mvn clean install
	...
	[INFO] BUILD SUCCESS

I'm considering creating a pull request to add something like this under &lt;plugins&gt; in pom.xml, to make the JDK 1.8 requirement more explicit:

			<plugin>
				<artifactId>maven-enforcer-plugin</artifactId>
				<executions>
					<execution>
						<id>enforce-java</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireJavaVersion>
									<version>[1.8,)</version>
									<message>
										The hapi-fhir Maven build requires JDK version 1.8 or higher.
									</message>
								</requireJavaVersion>
							</rules>
						</configuration>
					</execution>
				</executions>
			</plugin>

**Comment by shvoidlee** [comment]
I was reported similar issue at
https://groups.google.com/forum/#!topic/hapi-fhir/zfFyrWRV5O0

**Comment by jamesagnew** [comment]
It does seem like at this point the build needs JDK1.8 to proceed. We're still maintaining support for JDK1.6 in the library, but requiring JDK 1.8 to build seems reasonable.

Pull request would certainly be accepted :)

**Comment by bhattajo** [comment]
I am using java 1.8 and its throwing this when i run mvn clean install:

Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.

**Comment by jamesagnew** [comment]
HAPI FHIR now requires Java 11 or newer in order to build (JDK 8 is still
supported to use the library however, the JDK 11 requirement is only for
actually compiling HAPI FHIR itself).

Cheeers,
James

**Comment by bhattajo** [comment]
Thx! James. I upgraded to java11 and it complied fine and i am able to run using mvn jetty:run . However i am getting this warning : Failed to load conformance statement, error was: ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: HTTP 404 Not Found

Also, how to load patient resources which i generated using  SMART on FHIR Test Data Generator.
