### ISSUE TITLE
Please remove dependency on Servlet 3.0

### ISSUE THREAD

**Issue by bdenton** [jamesagnew/hapi-fhir#283]
I have noticed the following dependencies on Servlet 3.0: ServerConformanceProvider calls ServletRequest.getServletContext(). This appears in all three structures projects

**Comment by jamesagnew** [comment]
Is this an issue? Servlet 2.5 is 11 years old now (more than Java 6 even), that's some serious backward compatbilty.

We use several Servlet 3.0 features (annotation servlets and websockets being the main ones), so trying to compile with Servlet 2.5 would be challenging...

**Comment by bdenton** [comment]
That is all well and good to embrace the required level of standards to make use of more advanced featured. However, I was hoping that we could keep the core components at a lowest common denominator level.
From a purely selfish viewpoint, our product framework is still based on Jetty v7 which does not yet have servlet 3.0 support. I’m sure I don’t need to tell you what a hassle it is to get “product management” to schedule any sort of technology uplift…
