### ISSUE TITLE
Issue with DSTU2.1 and hapi-fhir-osgi-core

### ISSUE THREAD

**Issue by bdenton** [jamesagnew/hapi-fhir#284]
hapi-fhir-structures-dstu2.1 and hapi-fhir-structures-hl7org-dstu2 contain (almost) duplicate classes in the org.hl7.fhir.utilities packages and subpackages. Some of the classes nave the same package/class names but are different.

This is causing a potential issue when being combined in the hapi-fhir-osgi-core package.

**Comment by jamesagnew** [comment]
This one is known and should be cleared up soon.. I need to untangle the way we pull in classes from the RI classes. Should be done soon..
