### ISSUE TITLE
hapi fhirDSTU2 - v1.3: Cannot generate the profile for resource 

### ISSUE THREAD

**Issue by baopingle** [jamesagnew/hapi-fhir#285]
Normally we will give the URL like as GET /StructureDefinition/resourceId to get its profile. Look at the ServerProfileProvider#getProfileById, in this read method, it get the id by theId.getValue() but it will return the id value like as "StructureDefinition/id" not the "id", so the resource "StructureDefinition/id" is not known. I think to get the id should be like "theId.getIdPart()".

**Comment by jamesagnew** [comment]
Hi @baopingle : Is this the bug/fix you are referring to: https://github.com/jamesagnew/hapi-fhir/commit/ea89f3af286140bf417824ceeaffa20ad9f3ef3d
If so, it's fixed in the latest 1.4-SNAPSHOT builds and this should be released very soon.

Cheers,
James

**Comment by baopingle** [comment]
@jamesagnew, Thanks for your response at first. Then, there is another issue related it that I want your comments. The profile of DSTU1 has been replaced with StructureDefinition in DSTU2. But it could only set the id into the structureDefinition, see the code of FhirDstu2#generateProfile, not like the FhirDstu1. Is it correct or something is still in progress?

**Comment by jamesagnew** [comment]
Hello, this is still in progress unfortunately. I'm hoping we'll get this back soon, but unfortunately the profile/structure definition changed so much between DSTU1 and DSTU2 that the old code had to be scrapped. Hopefully we'll see this feature return in a new version of HAPI soon.
