### ISSUE TITLE
MYSQL 

### ISSUE THREAD

**Issue by JonaaSosa** [jamesagnew/hapi-fhir#290]
Hi, I'm trying to make time to walk the Fhir in MYSQL ago, the error I get is "org.springframework.beans.factory.BeanCreationException: Error creating bean With name 'EntityManagerFactory'" I do all replacements, but just give me that error may try to commit the MYSQL version? thx

**Comment by jonathan128** [comment]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in ca.uhn.fhirtest.config.TestDstu1Config: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean]: Factory method 'entityManagerFactory' threw exception; nested exception is java.lang.NoSuchMethodError: org.jboss.logging.Logger.debugf(Ljava/lang/String;I)

**Comment by jamesagnew** [comment]
Hi Jonathan,

The exception you list shows that an outdated version of JBoss logging is on your classpath somewhere. There is some information about this type of issue here: http://stackoverflow.com/questions/31547015/hibernate-5-java-lang-nosuchmethoderror-org-jboss-logging-logger-debugf
