### ISSUE TITLE
Need to support search by location/position/proximity in JPA

### ISSUE THREAD

**Issue by jamesagnew** [jamesagnew/hapi-fhir#294]
The JPA server doesn't currently support search by position, e.g. Location's `near` and `near-distance` search parameters.

The `ResourceIndexedSearchParamCoords` entity has been added for this purpose, but it's not yet indexed or added to search criteria.

**Comment by lcamilo15** [comment]
How can I help with this, can you point me in the right direction to start helping with this?

**Comment by sbwoodside** [comment]
Is it still the case that proximity searching is not yet implemented in HAPI FHIR?

Should the server return an error if a search is attempted using the `near` search parameter?
