### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to org.hl7.fhir.instance.model.api.IBase

### ISSUE THREAD

**Issue by hugosoares** [jamesagnew/hapi-fhir#304]
Hi James,
we are experiencing this error while serializing to json or xml:

java.lang.ClassCastException: java.lang.String cannot be cast to org.hl7.fhir.instance.model.api.IBase

the stack trace points at:
ca.uhn.fhir.parser.BaseParser.encodeResourceToString(BaseParser.java:351)

Looks like somehow the parser is expecting an IBase but is getting a String. It should be no problem with the resource that I am serializing becuase everything was fine during the instantiation process.

In this case we are serializing a Bundle with a MessageHeader and Encounter resources.

Tested on HAPI versions 1.2, 1.3 and 1.4

**Comment by jamesagnew** [comment]
Hi Hugo,

Would you be able to provide a code snippet illustrating what you're seeing?

**Comment by hugosoares** [comment]
Meanwhile I found the reason for this error was because of the name property of the patient resource.
This code is HAPI Fhir running on Javascript (Rhino, Mirth Connect).
```
var patient = new Packages.ca.uhn.fhir.model.dstu2.resource.Patient();

patient.setName(['Hugo']); //public Patient setName(List<HumanNameDt> theValue)
...
var outcomeString = parser.setPrettyPrint(true).encodeResourceToString(patient);
```
It is strange that this does not give an error while setting the name, only while encoding to string...

**Comment by jamesagnew** [comment]
Hi Hugo,

`patient.setName(['Hugo']); ` looks wrong to me. That method accepts a list of `HumanNameDt` objects, but you're passing in a list of strings. Java's generics don't enforce their types at runtime, so the error isn't caught until the parser tries to actually use the value later on.

I don't know exactly the right syntax you'd need, but presumably it would be something like
```javascript
var name = new Packages.ca.uhn.fhir.model.dstu2.composite.HumanNameDt();
name.addGiven('Hugo');
patient.setName([name]); 
```

**Comment by hugosoares** [comment]
I understand the issue with generics... Has an improvement on the parser I think you could control these encoding errors and produce a detailed error message showing exactly wich property is failling during the encoding process. 
I see this happening a lot of times during resource instantiation and it will be a pain to check each property set by hand to find the one that is causing the problem...

Keep up the great work.

**Comment by jamesagnew** [comment]
Thanks for the suggestion! Checking in a fix now.
