### ISSUE TITLE
When implementing search UriParam does not include the :above and :below qualifiers

### ISSUE THREAD

**Issue by ametke** [jamesagnew/hapi-fhir#306]
Hi James,

I am using HAPI 1.4 and implementing value set search by URL. I use the following parameter in my search implementation: 
...
@OptionalParam(name=ValueSet.SP_URL) UriParam url,
... 

I noticed that the :above and :below qualifiers are not being populated, i.e. url.getQueryParameterQualifier() returns null.

**Comment by jamesagnew** [comment]
Hi @ametke,

This has actually been addressed in the current 1.5-SNAPSHOT builds of HAPI, although that version hasn't been released yet. Are you in a position to try that build out?

**Comment by ametke** [comment]
Hi James,

Thanks. I should be able to build it.

Cheers,

Alejandro

**Comment by jamesagnew** [comment]
Closing- Please do feel free to comment or reopen if the solution doesn't meet your needs
