### ISSUE TITLE
Parser error handler is logging warn for unknown attribute url of declared extensions

### ISSUE THREAD

**Issue by matt-blanchette** [jamesagnew/hapi-fhir#308]
Warning in log:
ca.uhn.fhir.parser.LenientErrorHandler unknownAttribute: Unknown attribute 'url' found while parsing

Commit d0cffbf8c7 added overriding the attributeValue for ExtensionState (special case for url), but this is also not overridden in DeclaredExtensionState

**Comment by jamesagnew** [comment]
Thanks for reporting! Checking in a fix now.
