### ISSUE TITLE
Android build issue

### ISSUE THREAD

**Issue by aagnone3** [jamesagnew/hapi-fhir#309]
Hello,

This library (all versions) does not successfully build onto an Android device. There is a dependency issue within the javax/xml package. The thrown error is "Ill-advised or mistaken usage of a core class when not building a core library.

**Comment by jamesagnew** [comment]
Hi Anthony,

Are you using android build with the `classifier` attribute in your build file, per the example here: http://jamesagnew.github.io/hapi-fhir/doc_android.html

That library uses a relocated version of the javax.xml package, so it should avoid this problem.

**Comment by aagnone3** [comment]
[error.txt](https://github.com/jamesagnew/hapi-fhir/files/156096/error.txt)
[build.gradle.txt](https://github.com/jamesagnew/hapi-fhir/files/156097/build.gradle.txt)

Hey James,

Thanks for such a quick response. I have been using the classifier attribute in the (gradle) build file. I attached the build file and a copy of the error for your reference.

**Comment by jamesagnew** [comment]
Hi Anthony,

You may need to add some exclusions. Can you try adding the exclusions seen
in this example?

https://github.com/SynappzMA/FHIR-Android/blob/master/app/build.gradle

Cheers,
James

**Comment by aagnone3** [comment]
James,

At a glance, this seems to have fixed the issue. Thank you for the assistance!
