### ISSUE TITLE
Can we get a version that can interact with other JSON (de-) serializers?

### ISSUE THREAD

**Issue by justjanne** [jamesagnew/hapi-fhir#311]
We have situations where we receive or have to send a JSON Object with some of the values being FHIR Objects, and others being non-FHIR Objects.

Sadly, HAPI-FHIR does not allow using it together with Gson, Jackson, or any other JSON library currently, which makes this very hard (practically impossible).

We’d like to see a way to do this natively, for example by HAPI-FHIR providing typeadapters for Gson.

**Comment by jamesagnew** [comment]
Hi Janne,

I'd like for HAPI to migrate to natively using either GSON or Jackson instead of JSR 353 which it currently uses. At the time we started the project it looked like JSR 353 had a bright future but that doesn't seem like it's the case anymore.

I don't know that we have a schedule for doing this yet though- if anyone wants to have a try at this I wouldn't object. :)

Are you asking for support for multiple parsers though? I'm not sure I understand the benefit there. In my mind it probably makes more sense to go with Jackson since that's the more powerful parser.. Gson is more ubiquitous though, so that's a point in its favour. It probably wouldn't be toooo hard to support GSON and Jackson, but it would be more work for sure.

**Comment by KevinMayfield** [comment]
We have Apache camel running in front of HAPI FHIR to do conversions. Is that an option?

**Comment by justjanne** [comment]
> Are you asking for support for multiple parsers though? I'm not sure I understand the benefit there. In my mind it probably makes more sense to go with Jackson since that's the more powerful parser.. Gson is more ubiquitous though, so that's a point in its favour. It probably wouldn't be toooo hard to support GSON and Jackson, but it would be more work for sure.

No, sorry if it seemed like that.

I was just hoping for you to support either of those.

As obviously this transition won’t be done by Monday (and I need it by then) I’ll just hack something together for that uni project and add a link to this thread with some explanations on how to do it properly for the team which will take over my project next year.

**Comment by justjanne** [comment]
@jamesagnew Btw, do you have any suggestions on how to get this running with Gson or Jackson already today? Doesn’t have to be perfect, of course.

**Comment by justjanne** [comment]
@jamesagnew Sorry to bother you again, but: Could you make a tiny change (which would already improve usability with other parsers a lot) which adds 2 methods on the IParser to encode from IResource to JsonObject and deserialize from JsonObject to IResource?

**Comment by jamesagnew** [comment]
In terms of support for GSON/Jackson, probably the easiest thing to do would be to create a copy of HAPI's [JsonParser](https://github.com/jamesagnew/hapi-fhir/blob/c44b23f493c86c32346e0f0bf50065f64c59b998/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/JsonParser.java) class. In that copy, you could delete all references to javax.json and replace them with equivalent calls to GSON/Jackson's parser classes.

I don't actually think this part would be hard to do- it's really the change management around updating documentation and things like that which have held me back so far..

**Comment by justjanne** [comment]
@jamesagnew I already did that, and am already using that in my projects, but I’d hope that this feature would end up natively by the time the next team takes over my project (because I don’t trust they’ll be able to maintain it)

**Comment by jamesagnew** [comment]
Hi Janne,

Which parser did you end up using? Any interest in contributing it back to HAPI? If it gives us a headstart in moving away from javax.json I guess that's the fastest way to get it natively supported.. :)

**Comment by justjanne** [comment]
I ended up using Gson (because we use that in our project already), but I don’t think my code is worth being integrated here again. I can upload it later today, though.
