### ISSUE TITLE
Value in change message breaks changelog

### ISSUE THREAD

**Issue by adam-carbone** [jamesagnew/hapi-fhir#314]
I was looking at the change log to try to determine what change between versions and noticed that it looks like something in one of the messages, affected the structure of the page. 

http://jamesagnew.github.io/hapi-fhir/changes-report.html

Almost like a CSS, or injection problem with the page! Something looks like it is being written to the page without being escaped!

**Comment by jamesagnew** [comment]
Thanks Adam.. Yup, there was some bad HTML in there. Fix it now.
