### ISSUE TITLE
HAPI client: Allow searches (returning a Bundle) to specify the custom resoure type to return

### ISSUE THREAD

**Issue by sreinst1** [jamesagnew/hapi-fhir#315]
Currently, using "custom resources" (http://www.google.com/url?q=http%3A%2F%2Fjamesagnew.github.io%2Fhapi-fhir%2Fdoc_extensions.html&sa=D&sntz=1&usg=AFQjCNFG1zOo2Czygw16878T1t0vU8gDSA)
is not working during searches that return a Bundle. The "custom resource" type to search for is specified in the search, but the returned Bundle contains other types.
Please fix so that the requested type be returned.
Note that custom resources work fine in reads.

See Google group discussion for reference:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/hapi-fhir/3GYsvpgYwvY/qW42OBbfJAAJ

**Comment by jamesagnew** [comment]
Ok, good news- I took a crack at this on a long train ride this week and it ended up working out (I think) quite well.

I'm going to check in a fix shortly. It won't be available until I push a new snapshot build which will probably happen next week (I'm on the road this week) but you can try it out before that by building HAPI from source locally.

Basically I've added a new method to FhirContext called `setDefaultTypeForProfile` which lets you declare a default type to use for a given resource profile. If a resource is being parsed by itself or in a bundle and it claims to conform to that profile via its metadata statement, the given type will be used instead.

Would be interested to hear your thoughts on whether this works for your use cases...

**Comment by sreinst1** [comment]
Sounds great in general, but currently we don't (yet) make use of profiles.
In addition, as I wrote in my original post, the search itself already
specifies the desired resource type; that's why I expected it to work the
same way that it works in READ requests.

Thanks,
Shlomy

**Comment by jamesagnew** [comment]
Oh, that's an interesting point actually. Yeah, I guess if you explicitly say you are searching for your custom type right in the search request it would make sense for it to use that too.

What you're saying still wouldn't work.. Although the newly checked in code would at least give you a way of achieving what you want. I'm going to reopen to get the other way working too.

**Comment by jamesagnew** [comment]
Ok, now what you are proposing will work too. Good idea!

Will push a new 1.5-SNAPSHOT build this weekend, or you can build from source anytime.

**Comment by sreinst1** [comment]
Great, thanks! I will check it next week, but I probably won't use it until
1.5 is released. Is there a planned date for this?
Thanks,
Shlomy

**Comment by jamesagnew** [comment]
It'll be soon for sure. A few weeks tops, if not less, depending on our schedule over here.
