### ISSUE TITLE
ModelScanner.init generates 'random' NameToResourceDefinitions

### ISSUE THREAD

**Issue by TomasSBerg** [jamesagnew/hapi-fhir#318]
The logic in the ca.uhn.fhir.context.ModelScanner#init uses unordered hashsets for the fields myScanAlso and the local theDatatypes. 

This means, that when using custom extended resources, it sometimes adds the definition for the built-in class first, and sometimes for the custom class. Whichever is last in the set, and thereby added to the definitions last, will be the ruling definition. 
This shows up for extended resources contained in other extended resources, e.g. a CustomMedicationOrder with a contained CustomMedication resource. When this is parsed, it sometimes goes well and sometimes it reverts to the basic Medication resource.

**Comment by jamesagnew** [comment]
Hi Thomas,

Oddly enough, this has been fixed as a part of the fix of #315.

Custom resources now have to be explicitly declared via a separate method on the FhirContext and/or parser if you want them to take priority over the default types.

**Comment by TomasSBerg** [comment]
Sounds great. We need to get that snapshot soon and do a test run.

**Comment by TomasSBerg** [comment]
Hmm, I can't seem to make it work. Now it's consistent, though. It always chooses the built-in type, even though the contained resource has it's profile set. The ModelScanner class always ends up with the built-in type in the map.

**Comment by jamesagnew** [comment]
What are you trying to get it to do? If you want it to parse a tagged resource using your custom type, you need to explicitly declare that type on the context using `setDefaultTypeForProfile`

**Comment by TomasSBerg** [comment]
We have a profiled MedicationOrder with a contained profiled Medication. When it is parsed, the parser reads the contained resource as a built-in Medication class, not our profiled one. 

The outer MedicationOrder is parsed just fine, because we tell the client which type we want. But the list of contained resources is left as they are. Not sure what the best fix would be, reparsing the contained as well or something more elegant? :o)

<MedicationOrder xmlns="http://hl7.org/fhir">
	<id value="44cfa24c-52e1-a8ff-8428-4e7ce1165460-local"/>
	<meta>
		<profile value="http://fhir.something.com/StructureDefinition/our-medication-order"/>
	</meta>
	<contained>
		<Medication xmlns="http://hl7.org/fhir">
			<id value="1"/>
			<meta>
				<profile value="http://fhir.something.com/StructureDefinition/our-medication"/>
			</meta>
			<code>
				<text value="medication"/>
			</code>
		</Medication>
	</contained>
	<medication>
		<reference value="#1"/>
	</medication>
</MedicationOrder>

**Comment by jamesagnew** [comment]
So, the contained is just being parsed into a plain Medication, not your custom one? That's odd, that should work. Let me try by unit test.

**Comment by jamesagnew** [comment]
Ok, confirmed, this isn't working.

**Comment by jamesagnew** [comment]
Ok, this is fixed. `setDefaultTypeForProfile` wasn't being applied to contained resources. It is now.

I'll deploy a new snapshot this weekend.

**Comment by TomasSBerg** [comment]
Thanks a lot, James, will try it out asap.
