### ISSUE TITLE
Organization resource creation error

### ISSUE THREAD

**Issue by gansoper** [jamesagnew/hapi-fhir#319]
Hello, 

I found that system does not allow to create Organization resource. I got resource example from FHIR official site and tried to post it. I got "Error: HTTP 500 Internal Server Error: Failed to call access method" error. 

However, if I left only identifier in the resource it will be created

**Comment by jamesagnew** [comment]
Hi there- Can you link to or attach the resource body you're trying to create?

**Comment by gansoper** [comment]
Hmmm...it is strange but now  it was successfully created. Actually I found that some resources were not created from time to time with the same error,  but now everything is Ok...at least during the last hour.
