### ISSUE TITLE
PractitionerRole.role shouldn't be bound by an enum

### ISSUE THREAD

**Issue by Ricq** [jamesagnew/hapi-fhir#320]
While working with HAPI-FHIR to implement an IHE MHD2 resource provider, we found that the `role` property of the [Practitioner.practitionerRole](https://www.hl7.org/fhir/practitioner-definitions.html#Practitioner.practitionerRole.role) is fixed to an enum (`PractitionerRoleEnum`) in the HAPI code base.

This set is a very limited set of roles, and is only as an example in the FHIR spec. An example code set shouldn't be a fixed enum. Excerpt from the [FHIR description of example code set](https://www.hl7.org/fhir/terminologies.html#example):
> Instances are not expected or even encouraged to draw from the specified value set. The value set merely provides examples of the types of concepts intended to be included.

Can you update the role attribute to be a normal `CodeableConceptDt` instead of a `BoundCodeableConceptDt`?

Note: I haven't looked at other locations, but if you generate these classes from the spec automatically then there may be many more occassions where code sets are only given as examples. The fix should then probably apply to all of these locations.

**Comment by jamesagnew** [comment]
This makes sense, thanks for the suggestion!

I have a fix for this done- will check it in shortly.
