### ISSUE TITLE
LenientErrorHandler: Unknown element 'valueUri' found while parsing

### ISSUE THREAD

**Issue by realbob** [jamesagnew/hapi-fhir#322]
We have just upgraded from HAPI 1.2 to 1.4. Now it seems to me like some of my extensions in the conformance statement regarding security are missing. As our deployment is a bit complex, I cannot go back to 1.2 easily in order to prove the problem is really related to 1.4. 
My conformance provider looks like:

@Override
public Conformance getServerConformance(HttpServletRequest theRequest) 
  {  
      Conformance conformance = super.getServerConformance(theRequest); 
      ExtensionDt extensionDt = new ExtensionDt();
      ExtensionDt extensionDtToken = new ExtensionDt();
      ExtensionDt extensionDtAuthorize = new ExtensionDt();
      Rest rest = new Rest();
      RestSecurity restSecurity = new RestSecurity();
conformance.setAcceptUnknown(UnknownContentCodeEnum.UNKNOWN_ELEMENTS_AND_EXTENSIONS);  
      restSecurity.addService(RestfulSecurityServiceEnum.SMART_ON_FHIR);
      restSecurity.getServiceFirstRep().setText(SMART_ON_FHIR_PROFILE_TEXT);  
      extensionDt.setUrl(SMARTHEALTHIT_OAUTH_URIS);
      extensionDtToken.setUrl("token");
      extensionDtToken.setValue(new UriDt("https://SERVERNAME/token"));
      extensionDtAuthorize.setUrl("authorize");
      extensionDtAuthorize.setValue(new UriDt("https://SERVERNAME/authorize"));
      extensionDt.addUndeclaredExtension(extensionDtToken);
      extensionDt.addUndeclaredExtension(extensionDtAuthorize);
      restSecurity.addUndeclaredExtension(extensionDt);
      rest.setSecurity(restSecurity);  
      conformance.addRest(rest);      

```
  return conformance;
```

  }

I´m not completely sure, but I think this produced a statement as shown below before the upgrade:
...
"rest": [{
   ...
      "security": {
        "service": [
          {
            "coding": [
              {
                "system": "http://hl7.org/fhir/restful-security-service",
                "code": "SMART-on-FHIR"
              }
            ],
            "text": "OAuth2 using SMART-on-FHIR profile (see http://docs.smarthealthit.org)"
          }
        ],
        "extension": [{
          "url": "http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris",
          "extension": [{
            "url": "token",
            "valueUri": "https://SERVERNAME/token"
          },{
            "url": "authorize",
            "valueUri": "https://SERVERNAME/authorize"
          }]
        }],

Now only the "service"-part is present, the "extension"-part is missing, the log shows a warning "Unknown element 'valueUri' found while parsing".  I also tried fetching the conformance resource with a browser from my local Karaf server (http://localhost:8181/security/metadata). The response contained all security extensions that are missing when fetching it using the client (genericClient.fetchConformance().ofType(Conformance.class).execute();). 
The same applies to the trace log done by line 407 of BaseClient.java (ourLog.trace("FHIR response:\n{}\n{}", response, responseString);), all extensions are included in the response. Everything points to a parsing issue from my point of view.

[conformance_baseclient.txt](https://github.com/jamesagnew/hapi-fhir/files/195610/conformance_baseclient.txt)
[conformance_hapi_client.txt](https://github.com/jamesagnew/hapi-fhir/files/195614/conformance_hapi_client.txt)
[conformance_server.txt](https://github.com/jamesagnew/hapi-fhir/files/195615/conformance_server.txt)

**Comment by jamesagnew** [comment]
Unfortunately I am still completely unable to reproduce.

I set up a dumb server that returns the `conformance_server.txt` file you attached, and then plugged in the following code under HAPI FHIR 1.4:

```java
		IGenericClient client = ourCtx.newRestfulGenericClient("http://localhost:8080/fhir");
		Conformance conf = client.fetchConformance().ofType(Conformance.class).execute();
		
		Rest rest = conf.getRest().get(0);
		RestSecurity security = rest.getSecurity();
		
		List<ExtensionDt> ext = security.getUndeclaredExtensionsByUrl("http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris");
		List<ExtensionDt> tokenExts = ext.get(0).getUndeclaredExtensionsByUrl("token");
		ExtensionDt tokenExt = tokenExts.get(0);
		UriDt value = (UriDt) tokenExt.getValue();
		ourLog.info(value.getValueAsString());
```

This produces the output:

```
2016-03-31 06:13:34.430 [main] INFO  ca.uhn.fhir.util.VersionUtil [VersionUtil.java:51] HAPI FHIR version is: 1.4
2016-03-31 06:13:34.454 [main] INFO  ca.uhn.fhir.context.FhirContext [FhirContext.java:137] Creating new FHIR context for FHIR version [DSTU2]
2016-03-31 06:13:35.949 [main] INFO  Tmp [Tmp.java:66] https://my-server.org/token
```

Does this code produce a different output when you point it at your server?

**Comment by realbob** [comment]
Hi James,
it produces a NullPointerException when I point it at my server due to value (tokenExt.getValue()) being null. I was able to repoduce the behaviour on server side by parsing the conformance resource manually inside my ConformanceResourceProvider with:

`final FhirContext ctx = FhirContext.forDstu2();
    final String conf = ctx.newJsonParser().setPrettyPrint(true).encodeResourceToString(conformance);
    final Conformance parsed = ctx.newJsonParser().parseResource(Conformance.class, conf);`	
	
I got these warnings as mentioned before. Then I changed the value type of one of the extensions from UriDt to CodeDt, getting "Unknown element 'valueCode' found while parsing". It looks like only primitives are concerned. I debugged into the code of ca.uhn.fhir.parser.JsonParser and came to a point where the children are parsed. Then this line delivers null for primitives due to the according definitions are missing (ca.uhn.fhir.parser.ParserState, line 1730):

`BaseRuntimeElementDefinition<?> target = myContext.getRuntimeChildUndeclaredExtensionDefinition().getChildByName(theLocalPart); `

I did not find out how these definitions are "collected" by the ModelScanner and why primitives are not contained. Any idea?

**Comment by jamesagnew** [comment]
One thing that I find odd is that the case is different between the conformance statement you attached and the error message.

In the attached file, the attribute is called `valueuri` but the error message shows `valueUri` and this case doesnt' appear anywhere in the attached statement.

When you debugged, what was the case? I'm really stumped by all of this...

**Comment by jamesagnew** [comment]
Another thought- I tried reproducing this entirely in plain code with no fake server at all. Does the following code snippet produce the expected results when you run it in your client code?

```java
		String input = "{\n" + 
				"    \"resourceType\":\"Conformance\",\n" + 
				"    \"publisher\":\"Cloudyle\",\n" + 
				"    \"date\":\"2016-03-30T14:53:23+02:00\",\n" + 
				"    \"kind\":\"instance\",\n" + 
				"    \"software\":{\n" + 
				"        \"name\":\"HAPI FHIR Server\",\n" + 
				"        \"version\":\"1.4\"\n" + 
				"    },\n" + 
				"    \"fhirVersion\":\"1.0.2\",\n" + 
				"    \"acceptUnknown\":\"both\",\n" + 
				"    \"format\":[\n" + 
				"        \"application/xml+fhir\",\n" + 
				"        \"application/json+fhir\"\n" + 
				"    ],\n" + 
				"    \"rest\":[\n" + 
				"        {\n" + 
				"            \"mode\":\"server\",\n" + 
				"            \"security\":{\n" + 
				"                \"extension\":[\n" + 
				"                    {\n" + 
				"                        \"url\":\"http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris\",\n" + 
				"                        \"extension\":[\n" + 
				"                            {\n" + 
				"                                \"url\":\"token\",\n" + 
				"                                \"valueuri\":\"https://my-server.org/token\"\n" + 
				"                            },\n" + 
				"                            {\n" + 
				"                                \"url\":\"authorize\",\n" + 
				"                                \"valueuri\":\"https://my-server.org/authorize\"\n" + 
				"                            }\n" + 
				"                        ]\n" + 
				"                    }\n" + 
				"                ],\n" + 
				"                \"service\":[\n" + 
				"                    {\n" + 
				"                        \"coding\":[\n" + 
				"                            {\n" + 
				"                                \"system\":\"http://hl7.org/fhir/restful-security-service\",\n" + 
				"                                \"code\":\"SMART-on-FHIR\"\n" + 
				"                            }\n" + 
				"                        ],\n" + 
				"                        \"text\":\"OAuth2 using SMART-on-FHIR profile (see http://docs.smarthealthit.org)\"\n" + 
				"                    }\n" + 
				"                ]\n" + 
				"            },\n" + 
				"            \"resource\":[\n" + 
				"                {\n" + 
				"                    \"type\":\"Observation\",\n" + 
				"                    \"profile\":{\n" + 
				"                        \"reference\":\"http://hl7.org/fhir/profiles/Observation\"\n" + 
				"                    },\n" + 
				"                    \"interaction\":[\n" + 
				"                        {\n" + 
				"                            \"code\":\"search-type\"\n" + 
				"                        }\n" + 
				"                    ],\n" + 
				"                    \"searchParam\":[\n" + 
				"                        {\n" + 
				"                            \"name\":\"code\",\n" + 
				"                            \"type\":\"token\",\n" + 
				"                            \"documentation\":\"The code of the observation type\"\n" + 
				"                        },\n" + 
				"                        {\n" + 
				"                            \"name\":\"subject\",\n" + 
				"                            \"type\":\"string\",\n" + 
				"                            \"documentation\":\"The subject that the observation is about\"\n" + 
				"                        }\n" + 
				"                    ]\n" + 
				"                },\n" + 
				"                {\n" + 
				"                    \"type\":\"OperationDefinition\",\n" + 
				"                    \"profile\":{\n" + 
				"                        \"reference\":\"http://hl7.org/fhir/profiles/OperationDefinition\"\n" + 
				"                    },\n" + 
				"                    \"interaction\":[\n" + 
				"                        {\n" + 
				"                            \"code\":\"read\"\n" + 
				"                        }\n" + 
				"                    ]\n" + 
				"                },\n" + 
				"                {\n" + 
				"                    \"type\":\"Patient\",\n" + 
				"                    \"profile\":{\n" + 
				"                        \"reference\":\"http://hl7.org/fhir/profiles/Patient\"\n" + 
				"                    },\n" + 
				"                    \"interaction\":[\n" + 
				"                        {\n" + 
				"                            \"code\":\"read\"\n" + 
				"                        }\n" + 
				"                    ]\n" + 
				"                },\n" + 
				"                {\n" + 
				"                    \"type\":\"StructureDefinition\",\n" + 
				"                    \"profile\":{\n" + 
				"                        \"reference\":\"http://hl7.org/fhir/profiles/StructureDefinition\"\n" + 
				"                    },\n" + 
				"                    \"interaction\":[\n" + 
				"                        {\n" + 
				"                            \"code\":\"read\"\n" + 
				"                        },\n" + 
				"                        {\n" + 
				"                            \"code\":\"search-type\"\n" + 
				"                        }\n" + 
				"                    ]\n" + 
				"                }\n" + 
				"            ]\n" + 
				"        }\n" + 
				"    ]\n" + 
				"}";
		Conformance conf = FhirContext.forDstu2().newJsonParser().parseResource(Conformance.class, input);
		
		Rest rest = conf.getRest().get(0);
		RestSecurity security = rest.getSecurity();
		
		List<ExtensionDt> ext = security.getUndeclaredExtensionsByUrl("http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris");
		List<ExtensionDt> tokenExts = ext.get(0).getUndeclaredExtensionsByUrl("token");
		ExtensionDt tokenExt = tokenExts.get(0);
		UriDt value = (UriDt) tokenExt.getValue();
		System.out.println(value);
```

**Comment by realbob** [comment]
In debugging mode it is lower case (theLocalPart is 'valueuri' in ParserState.java, line 1729), the HashMap does not contain valueuri or valueCode in any case (myRuntimeChildUndeclaredExtensionDefinition -> myAttributeToNameDefinition in FhirContext.java, line 308). I checked all entries of the according Hashmaps an found definitions always in both cases like valuemeta, valueMeta, valuecoding, valueCoding and so on, valueUri or code not among them.

**Comment by jamesagnew** [comment]
Hmm, ok, so `RuntimeChildUndeclaredExtensionDefinition` doesn't even know about that type for some reason. Weird....

The way that class works is that while the context is being initialized, `sealAndInitialize` gets called (this is on initialization of the `FhirContext`) and during that time the class builds up a list of all of the valid element names it can support.

Would you be able to put a breakpoint [here](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/RuntimeChildUndeclaredExtensionDefinition.java#L158) on the line..
```java
for (BaseRuntimeElementDefinition<?> next : theClassToElementDefinitions.values()) {
```
..to see if `theClassToElementDefinitions` has a definition in it for UriDt, and if so why it doesn't get added to the `datatypeAttributeNameToDefinition` map?

Unfortunately I don't see any other option than to try that debug- I've tried and tried to reproduce this here and it just isn't happening on my end in any of 1.3, 1.4 or current trunk.

**Comment by realbob** [comment]
I debugged into it and found out that a definition for UriDt is contained in theClassToElementDefinitions. Unfortunately it is not added to datatypeAttributeNameToDefinition map, because the for loop continues in [line 171](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/RuntimeChildUndeclaredExtensionDefinition.java#L171) and therefor does not get to the point where it should be added to datatypeAttributeNameToDefinition (lines 193 & 194). As you can see in the attached screenshot the value of myStandardType is false what leads to entry of "if (!next.isStandardType())" (line 170) and in the cause to continuation of the loop. Can you tell my how and where this value is set?
![standardtype](https://cloud.githubusercontent.com/assets/13163496/14322778/55d9cd2e-fc1e-11e5-9022-fe631dfdc36d.jpg)

**Comment by jamesagnew** [comment]
Ahhh thank you, that is helpful.

This actually might be fixed already in HAPI 1.5 (which is only available as a SNAPSHOT build right now, but we'll be releasing it in the next week at most).

Until HAPI 1.5 we figured out if something was a standard type using some flawed logic (basically looking at whether it got initialized at startup) which meant that in some setups the flag got incorrectly set. There is probably some specific about your setup that I wasn't including when I was trying to reproduce the issue. As of 1.5 we have better logic there, so this actually is probably fixed. 

Are you able to try with the snapshot build? Thanks again for all of your digging, and sorry if it turns out it was all just to find a fixed issue!

**Comment by realbob** [comment]
Seems like you eliminated the "flawed logic", it works with the Snapnot-Build!
Thanks for your support and steering all my digging into the right direction...

**Comment by jamesagnew** [comment]
Ahh what a relief. Glad it worked out! :)

sent from my phone.
