### ISSUE TITLE
DSTU2 QuantityComparatorEnum should use new =ge and =le prefixes

### ISSUE THREAD

**Issue by Ricq** [jamesagnew/hapi-fhir#324]
The `ca.uhn.fhir.model.dstu2.valueset.QuantityComparatorEnum` still specifies the greater than and less than operators using the `=>` and `=>` operators.

In DSTU2 these changed to `=ge` and `=le`, and alike. See the [prefixes section of the FHIR Search API](http://hl7.org/fhir/DSTU2/search.html#prefix).

HAPI should be updated to support these new operators.

Note: I've submitted a related issue #323.

**Comment by jamesagnew** [comment]
This is fixed in 1.5, which will be released soon. I'm closing this ticket, but please feel free to open if the fix doesn't solve the issue for you.
