### ISSUE TITLE
UndeclaredExtension (added by addExtension method) does not serialize to JSON format properly

### ISSUE THREAD

**Issue by fw060** [jamesagnew/hapi-fhir#326]
This bug is found in version 1.4. 
 
The following test code in PatientProvider would generate correct XML document, but wrong JSON document. Note the valueReference in JSON format contains not reference with id. 
 
@Read()
public Patient read(@IdParam IdType theId) {
Patient patient = new Patient();
patient.setBirthDate(new Date());
patient.addExtension().setUrl("test").setValue(new Reference(new Condition()));
return patient;
}
 
XML:
<Patient xmlns="http://hl7.org/fhir">
    <extension url="test">
        <valueReference>
            <reference value="#1"/>
    
        </valueReference>
    
    </extension>
    <contained>
        <Condition xmlns="http://hl7.org/fhir">
            <id value="1"/>
       
        </Condition>
    
    </contained>
    <birthDate value="2016-03-30"/>
</Patient>
 
JSON:
 
```
{
  "resourceType": "Patient",
  "extension": [
    {
      "url": "test",
      "valueReference": {}
    }
  ],
  "contained": [
    {
      "resourceType": "Condition",
      "id": "1"
    }
  ],
  "birthDate": "2016-03-30"
}
```

**Comment by fw060** [comment]
The following change in JsonParser.java solves the problem. Can you verify if the fix is correct?

diff --git a/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/JsonParser.java b/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/JsonParser.java
index a3c8a9a..f69ccb6 100644
--- a/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/JsonParser.java
+++ b/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/JsonParser.java
@@ -1509,7 +1509,7 @@ public class JsonParser extends BaseParser implements IParser {
                                if (childName == null) {
                                        childName = "value" + myContext.getElementDefinition(value.getClass()).getName();
                                }
-                               BaseRuntimeElementDefinition<?> childDef = myContext.getElementDefinition(value.getClass());
+                               BaseRuntimeElementDefinition<?> childDef = extDef.getChildElementDefinitionByDatatype(value.getClass());
                                if (childDef == null) {
                                        throw new ConfigurationException("Unable to encode extension, unregognized child element type: " + value.getClass().getCanonicalName());
                                }

**Comment by jamesagnew** [comment]
I applied the patch, and it works perfectly. Awesome!

I'll commit this shortly, and make sure you get the credit. :)

**Comment by jamesagnew** [comment]
Ps- I always try to make sure that any who contributes patches gets credit in our changelog. If you want anything other than your github handle listed please feel free to let me know.

**Comment by fw060** [comment]
My github handle works great :)  Thanks James!
