### ISSUE TITLE
Missing "contained" elements when translating from XML -> JSON

### ISSUE THREAD

**Issue by mkitchin** [jamesagnew/hapi-fhir#337]
Hi there,

We're using version 1.4 of the library via Maven to translate FHIR XML bundles to JSON.

I.e.:

final FhirContext ctx = FhirContext.forDstu2();
final IParser xmlParser = ctx.newXmlParser();
final Bundle bundle = xmlParser.parseBundle( xml);
final IParser jsonParser = ctx.newJsonParser();

jsonParser.setSummaryMode( false);
jsonParser.setSuppressNarratives( false);
jsonParser.setPrettyPrint( true);

String json =  jsonParser.encodeBundleToString( bundle);

...and everything's coming out ok except for some contained elements within Patient elements (sample XML attached -- all information is randomized/no real PII). These contained elements are not appearing in the output JSON, though the original XML validates against the FHIR schema, etc.

Thoughts?

[test-bundle-04-18-16-1.xml.txt](https://github.com/jamesagnew/hapi-fhir/files/224513/test-bundle-04-18-16-1.xml.txt)

Please let me know if I may provide any additional information. Thanks.

-Regards,
MjK

**Comment by mkitchin** [comment]
...here's some sample output (not from the same query as the input, but very similar).
[test-bundle-04-18-16-1.json.txt](https://github.com/jamesagnew/hapi-fhir/files/224516/test-bundle-04-18-16-1.json.txt)

**Comment by jamesagnew** [comment]
Hi @mkitchin , would you be able to try this with the current 1.5-SNAPSHOT build in the Maven repos? We just fixed a bunch of bugs relating to contained refs, so this might just already be fixed. :)

**Comment by mkitchin** [comment]
Hi there,

Thanks for getting back to us so quickly. I'll be able to give it a try in the next couple of days and let you know.

**Comment by jamesagnew** [comment]
Closing this as there has been no response. Please feel free to re-open if this problem persists.
