### ISSUE TITLE
Organization.text gets lost on upload

### ISSUE THREAD

**Issue by vadi2** [jamesagnew/hapi-fhir#338]
Given the test case from #335, Patient.contained.Organization.text gets lost on upload to HAPI.

**Comment by jamesagnew** [comment]
Hmm.. I feel like it is stated somewhere or other that contained resources are not allowed to have narratives. Let me see if I can find it.

**Comment by jamesagnew** [comment]
Ahh, there it is: http://hl7-fhir.github.io/references.html#contained

> Contained resources SHALL NOT contain any narrative

HAPI's parser and serializer ignore narratives on contained resources as a result, which is why this is happening.

**Comment by vadi2** [comment]
Yep, that is true.
