### ISSUE TITLE
Parsing Issue with Coverage Under ExplanationOfBenefit FHIR resource

### ISSUE THREAD

**Issue by shovanroygithub** [jamesagnew/hapi-fhir#341]
Hi, 

I am using ExplnationOfBenefit resoruce version 1.4.0 and HAPI version 1.4.

I am facing a strange issue. We are using coverage as a contained resource under ExplanationOfBenefit. The HAPI parser is working well if we use the following (please note this is incorrect as per FHIR spec):
 "coverage": {
          "coverage": {
            "reference": "#cvg-1"
          },
          "relationship": {
            "system": "http://hl7.org/fhir/relationship",
            "code": "1",
            "display": "self"
          }
        }

This is failing if we use 'coverageReference' instead of 'coverage', We are getting parsing error: Unknown element 'coverageReference' found during parse. However as per the FHIR spec, we have to use it as 'coverageReference'. Can you please let me know if I am missing something. 

 "coverage": {
          "coverageReference": {
            "reference": "#cvg-1"
          },
          "relationship": {
            "system": "http://hl7.org/fhir/relationship",
            "code": "1",
            "display": "self"
          }
        }

**Comment by jamesagnew** [comment]
Hi there,

I've committed a unit test that test this issue and it seems to be working for me, see here: https://github.com/jamesagnew/hapi-fhir/commit/f29cda00d01e89fa63fbe0a3ddc2e360a691e164#diff-9b02e9c32507879cd0c108a50074ad74R824

Can you confirm that this is still an issue for you in HAPI 1.5, and if so can you provide a complete code sample illustrating the issue?

**Comment by shovanroygithub** [comment]
Thanks James,

We are using HAPI 1.4. 

I will take the 1.5 version and see how it goes. Meanwhile I would like to check with you if 1.5 version is production ready? can we use it for live system?

Regards,
Shovan

**Comment by jamesagnew** [comment]
Hi Shovan,

I would certainly say that 1.5 is production ready. Naturally we always recommend running as many tests as you can before a new release, but we recommend keeping up to date as much as possible.

**Comment by shovanroygithub** [comment]
Hi James,

coverage resource is working fine with HAPI version 1.5. We are now doing extensive testing. Thanks you very much for the help.

Regards,
Shovan

**Comment by jamesagnew** [comment]
Closing this issue, as it seems to be fixed. Please feel free to re-open if your testing uncovers any issues!
