### ISSUE TITLE
_format parameter does not respect "application/xml+fhir"

### ISSUE THREAD

**Issue by jimsteel** [jamesagnew/hapi-fhir#346]
The _format parameter seems to understand "xml", "text/xml" and "application/xml", but not "application/xml+fhir", as per http://www.hl7.org/fhir/2016May/http.html#mime-type.

**Comment by jamesagnew** [comment]
Relevant spec wording: 

> However in order to support various implementation limitations, servers SHOULD support the optional _format parameter to specify alternative response formats by their MIME-types. This parameter allows a client to override the accept header value when it is unable to set it correctly due to internal limitations (e.g. XSLT usage). For the _format parameter, the values xml, text/xml, application/xml, and application/xml+fhir SHALL be interpreted to mean the normative XML format defined by FHIR and json, application/json and application/json+fhir SHALL be interpreted to mean the informative JSON format. In addition, the values html and text/html are allowed. 

I'm betting we don't support `text/html` either

**Comment by jamesagnew** [comment]
Ok, after some digging, it turns out we do in fact support `_format=application/xml+fhir` except that... the plus needs to be escaped as `%2B` since `xml+fhir` is interpreted as `xml fhir` by the server.

I'm going to commit a fix to be lenient here by accepting the unescaped style, and to accept `text/html` too.

**Comment by jamesagnew** [comment]
Fixed by https://github.com/jamesagnew/hapi-fhir/commit/3eb805fb0a696268015140108a7eb1d9519e3b96
