### ISSUE TITLE
Date Parsing Issue with dateWritten resource under MedicationOrder FHIR resource

### ISSUE THREAD

**Issue by HarshavardhanMokkala** [jamesagnew/hapi-fhir#347]
Hi,

I am using MedicationOrder resoruce version 1.4.0 and HAPI version 1.4.

We are using dateWritten resource which takes the value of dateTime.We are facing issue with the dateformat and tried with the following below formats for the dateTime and HAPI Parser failed it
- Date Format : "YYYY-MM-DD
- Date and Timestamp: "2015-10-05T07:41:03+11:00"
- Date Foramt: "YYYYMMDD"
  Example :- <dateWritten>"2015-10-03"</dateWritten>
  The HAPI parser is working well with other resources when the date format is passed in "YYYY-MM-DD" or timestamp format. Can you please let me know if any other format is supported or to be used.

**Comment by jamesagnew** [comment]
Hi there, can you provide more details about what you are trying to do? The following resource parses correctly for me, and I've committed a unit test that does a full roundtrip of that field:

```xml
<MedicationOrder xmlns="http://hl7.org/fhir">
   <dateWritten value="2015-10-05"/>
</MedicationOrder>
```
