### ISSUE TITLE
HAPI 1.5 search with include issue

### ISSUE THREAD

**Issue by ykovbtc** [jamesagnew/hapi-fhir#348]
While searching with include (include profiled resource CustomPatient for example that extends) we'll receive parent type Patient instead of CustomPatient in patientRef.getResource();

I've also investigated next in GenericClient line 734  
"return parser.parseBundle(myType, theResponseReader)".

this line returns bundle with wrong type of included resource
but if we call  "parser.parseBundle(theResponseReader)"
It'll return a correct one.

P.S. defaultTypeForProfile is set

**Comment by jamesagnew** [comment]
Hi @ykovbtc , would you be able to attach a code sample that illustrates what you are doing? I'm not sure I understand what's happening..

**Comment by ykovbtc** [comment]
Hi @jamesagnew, sure
---------------------------------------------------
//Server code:
@Search public List<CustomProcessRequest>(
             @IncludeParam(allow = {"ProcessRequest:subject"}) Set<Include> includes) {
      // populate data.   
}
-------------------------------------------------------
//Client code:
FhirContext ctx = FhirContext.forDstu2();
ctx.setDefaultTypeForProfile("http://fhir.org.dk/app/StructureDefinition/app-patient", CustomPatient.class);
//also set on server side

Bundle bundle = ctx.newRestfulGenericClient("serverBase").search().forResource(CustomProcessRequest.class).include(new Include("ProcessRequest:subject")).execute(); //info: server has 1 element

CustomProcessRequest cpr =  bundle.getResource(CustomProcessRequest.class).get(0);
Class<Patient> clazz = cpr.getSubject().getResource().getClass(); // but has to be CustomPatient
-----------------------------------------------------------
//Resources:
@ResourceDef(id = "app-process-req",  profile = "http://fhir.org.dk/app/StructureDefinition/app-process-req")
class CustomProcessRequest extends ProcessRequest {
    @Child(name = "subject", min = 1, max = 1, type = {CustomPatient.class})
    @Extension(url = "http://fhir.org.dk/app/ext/pr-subj", definedLocally = false, isModifier = false)
    private ResourceReferenceDt ourSubject;
   // other stuff
}

@ResourceDef(id = "app-patient",  profile = "http://fhir.org.dk/app/StructureDefinition/app-patient")
class CustomPatient extends Patient{
   // some specific stuff
}


so in GenericClient:
myType = CustomProcessRequest .class;
"return parser.parseBundle(myType, theResponseReader)".
it returns bundle with Patient
but without  myType param it returns CustomPatient.

anyway we need to have correct type :)

thanls, Yaroslav

**Comment by jamesagnew** [comment]
So.. is the idea here that you are using the client to invoke your server, and the client isn't returning your custom type (or types)? If so, what is the exact code snippet you are using to invoke the client? Also, can you paste in the exact response from the server?

**Comment by ykovbtc** [comment]
> So.. is the idea here that you are using the client to invoke your server, and the client isn't returning your custom type (or types)? 
yes if the type is in ResourceReferenceDt

this is a client invocation:
`
client.search().forResource(CustomProcessRequest.class).include(new Include("ProcessRequest:subject")).execute();`

**Comment by ykovbtc** [comment]
ty @jamesagnew . it's fixed in HAPI 1.6-SNAPHOT. 
just need to use 

returnBundle(Bundle.class).execute();
instead of just execute();
