### ISSUE TITLE
setter methods removed in 1.5

### ISSUE THREAD

**Issue by rahulsom** [jamesagnew/hapi-fhir#354]
In the 1.4 api, one could do something like

```groovy
def claim = new Claim().
    setIdentifier(identifiers.collect{new IdentifierDt(...)}).
    setCondition(conditions.collect{new CodingDt(...)})
```

It appears the setter methods have been removed in 1.5 and the only way to do that is using `addIdentifier` and `addCondition`.

Can you bring back the setter methods that allow one to set the whole collection?
For those of us who prefer a functional style of programming, that is very helpful.

Thanks!

**Comment by jamesagnew** [comment]
Hi Rahul,

Thanks for the suggestion. These have been re-added to the DSTU3 structures, and will be in the next snapshot.
