### ISSUE TITLE
Problem in Iterating multiple content in a single resource when Historical data came. 

### ISSUE THREAD

**Issue by SanjeevKarki** [jamesagnew/hapi-fhir#357]
Hi Team,

We are having a scenario where a patient historical data came in a single entry with multiple content tag.
We are not able to iterate or fetch all the record.while parsing we are only getting the last record in hapi-fhir bundle entry. Any feedback on this is highly appreciated.
Attaching a sample file with multiple records in Diagnostic Report,Encounter Inpatient etc.

[Beneficiary_create_sample_Helios_To_EHR.txt](https://github.com/jamesagnew/hapi-fhir/files/244591/Beneficiary_create_sample_Helios_To_EHR.txt)

Thanks,
Sanjeev

**Comment by jamesagnew** [comment]
Hi Sanjeev,

Can you provide more detail about what you're doing? Is this a JPA server or a plain one? Are you posting the attached file to the server as a transaction? What are you then doing to retrieve data?

Any code samples, detailed explanations, etc, would make it more likely that we can reproduce your issue.

**Comment by jamesagnew** [comment]
I'm going to close this, as there isn't enough information in the bug report to reproduce the issue. Please feel free to reopen if this is still an issue.
