### ISSUE TITLE
Search by identifier consisting of two words does not work 

### ISSUE THREAD

**Issue by edifecscda** [jamesagnew/hapi-fhir#360]
Hello,

Recently I perform searches by identifier like http://fhirtest.uhn.ca/baseDstu2/Questionnaire?identifier=Coverage+Check   - where "Coverage Check" is identifier of the Questionnaire. 
It worked, but today I found that it stopped. 

I know for sure that such a resources exist  - for example http://fhirtest.uhn.ca/baseDstu2/Questionnaire/31974 

Could you please review this?

**Comment by jamesagnew** [comment]
Thanks for the heads up- this is a regression caused by another commit. Will push a fix shortly and redeploy our public server later this morning.

Cheers,
James

**Comment by jamesagnew** [comment]
Change has been deployed, and your link above now works once again.

Thanks for reporting!
