### ISSUE TITLE
OperationParameter has dead code or a bug

### ISSUE THREAD

**Issue by euvitudo** [jamesagnew/hapi-fhir#362]
ca.uhn.fhir.rest.method.OperationParameter seems to have either a bug or dead code.  See: https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/rest/method/OperationParameter.java#L198
The code on line 198 is not reachable, but didn't know whether this was intentional or not.

**Comment by jamesagnew** [comment]
Hi @euvitudo , Thanks for reporting! Checking in a fix now!
