### ISSUE TITLE
Create absolute urls that don't exist

### ISSUE THREAD

**Issue by NaminderSoorma** [jamesagnew/hapi-fhir#363]
I am using the Document Reference resource and in the subject am trying to create a link to a Patient that may/may not exist locally on the FHIR server. So for example: http://example.com/fhir/Patient/123 does not exist, but I want to create the Document Reference record. I would have thought it would be possible to create a Document Reference using this absolute URL. 

The JPA server requires that all references you send it can be resolved to resources on the same server. We would like it to be configurable so that it can resolve whether it exists locally or not.

**Comment by jamesagnew** [comment]
Hi Narinder- Thanks for the suggestion. I'll be checking in a fix shortly, and this will be possible using the upcoming 1.6 release of HAPI FHIR.
