### ISSUE TITLE
Javadoc on many methods mention null is never returned, where null can actually be returned

### ISSUE THREAD

**Issue by Ricq** [jamesagnew/hapi-fhir#365]
Many accessor methods in the HAPI FHIR API have Javadoc that mentions that the methods cannot return `null`, while the methods can actually return `null`. This is pretty confusing and can easily lead to `NullPointerException` bugs.

As an example, see the `CodingDt.getCode()` method:
```java
/**
 * Gets the value(s) for <b>code</b> ().
 * creating it if it does
 * not exist. Will not return <code>null</code>.
 *
 * <p>
 * <b>Definition:</b>
 * A symbol in syntax defined by the system. The symbol may be a predefined code or an expression in a syntax defined by the coding system (e.g. post-coordination)
 * </p> 
 */
public String getCode() {  
	return getCodeElement().getValue();
}
```

`getCodeElement()` is designed to not return `null`. It will create a new `CodeDt` instance if it was `null`. The `getValue()` call on that just-created code however, _**will**_ actually return `null`.

I'm OK with the methods returning null, but the Javadoc should be cleaned up. It exists on many, if not all accessor methods on the datatypes.

**Comment by jamesagnew** [comment]
Thanks for reporting! This looks like it was a copy-and-paste error, and I'd agree it is confusing! Checking in a fix now.
