### ISSUE TITLE
FhirTerser cannot clone extensions

### ISSUE THREAD

**Issue by Virdulys** [jamesagnew/hapi-fhir#369]
```
    @Test
    public void testTerser() {
        Patient patient = new Patient();

        patient.addUndeclaredExtension(new ExtensionDt(false, "blahblah"));

        new FhirTerser(FhirContext.forDstu1()).cloneInto(patient, new Patient(), false);
    }
```

[FhirTerser:151](https://github.com/jamesagnew/hapi-fhir/blob/d7c683f6b9f2e353aec131ecebfc683e4d5fef8b/hapi-fhir-base/src/main/java/ca/uhn/fhir/util/FhirTerser.java#L151) causes exception to be thrown if we use it to clone extension, no matter if extension is in root or child in [RuntimeChildChoiceDefinition.java:78](https://github.com/jamesagnew/hapi-fhir/blob/d7c683f6b9f2e353aec131ecebfc683e4d5fef8b/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/RuntimeChildChoiceDefinition.java#L78), because the passed parameter value is simply "extension". Is this by design and am I doing something wrong? The same is happening when using xmlParser, when parsing to and from string.

**Comment by jamesagnew** [comment]
Thanks for the report, and for providing a test case!

I'll check in a fix shortly.
