### ISSUE TITLE
profile validation

### ISSUE THREAD

**Issue by wanghaisheng** [jamesagnew/hapi-fhir#37]
there is a method http://jamesagnew.github.io/hapi-fhir/doc_rest_operations.html#type_validate
but how could I do some validation against the base profile requirement provided by fhir spec (let`s say it is not well-formed  xml  or two name elements appear in the Organization resource instance)and my own profile constraints

**Comment by filip-owczarzak** [comment]
I gues it is no longer relevant, since DSTU 2 does not define *validate* interaction anymore. Anyway, good question: how to validate against given profile?
