### ISSUE TITLE
Relatedperson-relationshiptype value set validation fails

### ISSUE THREAD

**Issue by Xoude** [jamesagnew/hapi-fhir#370]
Hi,

I'm using RequestValidationInterceptor with FhirInstanceValidator and during validation of "myRelationship" field of custom resource extended from RelatedPerson I am able to see error below:

> UnprocessableEntityException: HTTP 422 Unprocessable Entity: None of codes provided are in the value set http://hl7.org/fhir/ValueSet/relatedperson-relationshiptype

Other resources with CodeableConceptDt field passed validation without any errors.
Looks like it is related with fact that above value set also includes another one ("http://hl7.org/fhir/v3/RoleCode")`.
I tried to set such system as **"http://hl7.org/fhir/ValueSet/relatedperson-relationshiptype"**, **"http://hl7.org/fhir/patient-contact-relationship"** and **"http://hl7.org/fhir/v3/RoleCode"** but there was the same error.
Also, I debugged HapiWorkerContext.validateCode() method and notice that "expansion" and "concept" fields in ValueSet have null values.

Have you any idea what is cause of this issue?

**Comment by jamesagnew** [comment]
Hi @Xoude,

Thanks for reporting!

This turned out to be an issue with the actual `http://hl7.org/fhir/v3/RoleCode` codesystem as distributed by HL7. It turns out it was missing a code that was preventing successful validation.

I'm checking in a fix shortly, so the next 1.6-SNAPSHOT should be able to validate this successfully.

**Comment by Xoude** [comment]
Hi @jamesagnew ,

Thanks a lot!

**Comment by Xoude** [comment]
Hi,
If i'm not wrong u fixed it in 'hapi-fhir-structures-dstu3' module, but in 'hapi-fhir-structures-hl7org-dstu2' i'm able to reproduce above issue
