### ISSUE TITLE
multiple _sort parameters can result in out of order SortSpec chain

### ISSUE THREAD

**Issue by euz1e4r** [jamesagnew/hapi-fhir#371]
There a bug is the area of a restful FHIR query with multiple sort keys with various sort orders. The sort keys can come out in the wrong order when translated into the SortSpec linked list. HttpServletRequest and RestfulServer hold are held internally in a map by parameter name. The map makes no order guarantee. SortParameter and Constants specify three different parameters {_sort, _sort:asc, _sort:desc}. For a single parameter name used multiple times, the API delivers its values as an array with guaranteed order preservation. 

If I specify exactly one sort key, the bug doesn't byte.
If I use exactly one of the parameter names above, the bug doesn't bite.
It requires a mix of the 3 parameter names to open up the possibility that they are delivered in the wrong order.

I've written a work around sort algorithm, which accepts the leading minus sign syntax, and we use only the _sort parameter and never _sort:asc or _sort:desc.

We were inspired by an version of the spec which used this leading minus sign syntax to mark descending sort keys.  The more recent specification version introduces the :asc and :desc parameter modifier idea. 

Trestful URL could look like ..._sort=key1&_sort=-key2&_sort=key3. I suggest adhering to and reverting to this earlier sort spec. 

This moves the sort order specification from the key to the value. Also in this model we define exactly one parameter name, namely "_sort". 

I've written and unit tested a possible modification of the method in question, below.

jar version: hapi-fhir-base-1.5.jar

method: SortParameter.translateQueryParametersIntoServerArgument(RequestDetails, BaseMethodBinding<?>)

    public Object translateQueryParametersIntoServerArgument(RequestDetails theRequest, BaseMethodBinding<?> theMethodBinding) throws InternalErrorException, InvalidRequestException {
        String[] values = theRequest.getParameters().get(Constants.PARAM_SORT);
        if (values == null) {
            return null;
        }
        SortSpec headSpec = null;
        SortSpec tailSpec = null;
        SortOrderEnum order = null;
        for (String nextValue : values) {
            if (isNotBlank(nextValue)) {
                if (nextValue.startsWith("-")) {
                    order = SortOrderEnum.DESC;
                    nextValue = nextValue.substring(1);
                    if (isBlank(nextValue)) {
                        continue;
                    }
                }
                else {
                    order = SortOrderEnum.ASC;
                }
                SortSpec spec = new SortSpec().setOrder(order).setParamName(nextValue);
                if (tailSpec == null) {
                    headSpec = spec;
                    tailSpec = spec;
                } else {
                    tailSpec.setChain(spec);
                    tailSpec = spec;
                }
            }
        }
        return headSpec;
    }

**Comment by lawley** [comment]
There are many web frameworks that do not make order guarantees about repeated parameters, so it's unwise for any RESTful API to place any significant on parameter order in the URL.

But I'm confused by your references to earlier and later specs and the _sort syntax.

1.0.2 (DSTU2) uses the :asc and :desc approach (which has the ordering issue), while 1.4.0 (and current build) uses the comma-separated list with leading minus signs.

1.0.2 https://www.hl7.org/fhir/search.html#sort
1.4.0 http://hl7.org/fhir/2016May/search.html#sort

**Comment by euz1e4r** [comment]
Michael,

Thank you for your response.
In 1.5 Constants.java, the _sort, _sort:asc and _sort:desc parameters are still in the code and SortParameter.translateClientArgumentIntoQueryArgument parses them into a SortSpec list.
If one passes a comma separated list with minus signs, HAPI passes though as if it were a single sort key.
So as of 1.5, the implementation is lagging behind the spec. I can work around that.
Also, we've added the notion of paths to the sort keys, as in /Patient?_sort=name.family,name.given
We also support lists, which are quite common in DSTU. When we encounter a list, we sort by the elements of that list, stepping through in parallel.
I sort strings case insensitively, also.

        Best,
        Leonard

________________________________

**Comment by euz1e4r** [comment]
I contribute this proposed implementation of the 1.4 _sort spec, in SortParameter.java, supporting the comma separated key list with optional leading minus for each key.

    private static final Pattern comma = Pattern.compile(",", Pattern.LITERAL);
    public Object translateQueryParametersIntoServerArgument(RequestDetails theRequest, BaseMethodBinding<?> theMethodBinding) throws InternalErrorException, InvalidRequestException {
        String[] values = theRequest.getParameters().get(Constants.PARAM_SORT);
        if (values == null) {
            return null;
        }
        if (values.length > 1) {
            throw new UnsupportedOperationException("at most one " + Constants.PARAM_SORT + " parameter is allowed");
        }
        SortSpec headSpec = null;
        SortSpec tailSpec = null;
        for (String nextValue : comma.split(values[0], 0)) {
            SortOrderEnum order = SortOrderEnum.ASC;
            if (isNotBlank(nextValue)) {
                if (nextValue.startsWith("-") && nextValue.length() > 1) {
                    order = SortOrderEnum.DESC;
                    nextValue = nextValue.substring(1);
                }
                SortSpec spec = new SortSpec().setOrder(order).setParamName(nextValue);
                if (tailSpec == null) {
                    headSpec = spec;
                    tailSpec = spec;
                } else {
                    tailSpec.setChain(spec);
                    tailSpec = spec;
                }
            }
        }
        return headSpec;
    }

**Comment by jamesagnew** [comment]
Hi All,

Thanks for reporting and for the detailed analysis. I've worked the attached patch in and made equivalent changes on the client side.

For now I've set it up so that the server will allow both DSTU2 and STU3 style sort params in order to allow people to migrate. Maybe this could be disabled later....
