### ISSUE TITLE
_count param missing from bundle.link.url

### ISSUE THREAD

**Issue by euz1e4r** [jamesagnew/hapi-fhir#372]
The result bundle produced by HAPI does not show that a _count parameter was passed.

Here is an example:

example request:
curl -s 'http://localhost:9080/fhir/MedicationOrder?patient=DAE53A653E834168B68FA5BE56EA06AF&_pretty=true&_format=json&_count=1&_sort=-dateWritten'

example response:
{
    "resourceType":"Bundle",
    "id":"3d1b2c10-7b3d-4d7b-bc36-4cf3a8b15306",
    "meta":{
        "lastUpdated":"2016-05-24T13:52:17.894-07:00"
    },
    "type":"searchset",
    "total":1,
    "link":[
        {
            "relation":"self",
            "url":"http://localhost:9080/fhir/MedicationOrder?_sort=-dateWritten&patient=DAE53A653E834168B68FA5BE56EA06AF&_pretty=true&_format=json"
        }
    ],
…

**Comment by jamesagnew** [comment]
Hi there,

Thanks for reporting. I've added some tests to try and reproduce this, but I'm not able to recreate it.

Can you share more details around what version of HAPI you're using, what version of FHIR you're targeting, and any details about your server you can?
