### ISSUE TITLE
CQL/ Drools Translation

### ISSUE THREAD

**Issue by rajeshnalluri** [jamesagnew/hapi-fhir#376]
Hi James,
I am exploring to generate cql (Clinical Quality Language) to drools(JBossDrools) by using HAPI DSTU3 interface. Do u have any sample example.

Regards,
Rajesh.

**Comment by jamesagnew** [comment]
Hi Rajesh,

We don't have any examples of how to this currently. If you have any, or create any we would gladly attach them to the site though!
