### ISSUE TITLE
Incorrect $validate OperationDefinition in generated Conformance resource

### ISSUE THREAD

**Issue by lawley** [jamesagnew/hapi-fhir#379]
We have three Providers (ConceptMap, ValueSet, and CodeSystem) that each implement both type and instance $validate with @Validate annotations, however the single OperationDefinition included in the Conformance metadata resource lists the type of the resource parameter as CodeSystem.

It also lists 6 entries for type (two per resource type).  It seems that the type/instance distinction is being lost somewhere.

Only in parameters are generated; no out parameter.

Finally, instance is set to true, but the defn seems to cover both type and instance (as per 6 type values); should there be separate OperationDefinitions for each?

**Comment by jamesagnew** [comment]
This is an interesting issue. `OperationDefinition.parameter.type` doesn't allow multiple values, so I guess really this does need to be one OperationDefinition per resource type you can validate. That's easy enough to fix.

> Finally, instance is set to true, but the defn seems to cover both type and instance (as per 6 type values); should there be separate OperationDefinitions for each?

The definition of `OperationDefinition.instance` is "Indicates whether this operation can be invoked on a particular instance of one of the given types.". Given the word "can", I take this to mean that
* a value of `true` means the operation can be applied at both the type and instance level
* a value of `false` means that the operation can be applied at the type level
* there is no way of indicating that the resource can only be applied at the instance level

This seems worth raising on the FHIR channels for clarification, but based on the current wording I don't think it makes sense to split the instance/type definitions into 2. Thoughts?

Will commit a fix to the first part shortly.

**Comment by jamesagnew** [comment]
Added discussion here: https://chat.fhir.org/#narrow/stream/implementers/topic/Operations
