### ISSUE TITLE
Redundant method parameter on UriClientParam

### ISSUE THREAD

**Issue by magnuschatt** [jamesagnew/hapi-fhir#387]
On the matches method in UriClientParam you have:

```
public UriClientParam.IUriMatch matches(String theValue) {
     return new UriClientParam.UriMatches();
}
```

The input parameter is never used. It should probably be removed so you can define an ICriterion like so:

`URL.matches().value("http://bob.com");`

**Comment by jamesagnew** [comment]
Hi @magnuschatt - Thanks for the report!

Oddly enough I just noticed this issue about 2 weeks ago myself. I marked the method with the useless parameter as deprecated in [this commit](https://github.com/jamesagnew/hapi-fhir/commit/99568a4b308402a7cb30b3b80c11ca069ed7bd2b) and will remove the method in the next release.
