### ISSUE TITLE
Error ca.uhn.fhir.model.primitive.XhtmlDt

### ISSUE THREAD

**Issue by YasiAap** [jamesagnew/hapi-fhir#388]
Hi!

I need to crate a simple client to send observations in android studio
I wanna use the code in the following path:
hapi-fhir/examples/src/main/java/example/FhirDataModel.java

Any time U face this error:
`ca.uhn.fhir.context.ConfigurationException: Unknown class[ca.uhn.fhir.model.primitive.XhtmlDt] for data type definition: xhtml`

can you help me please?

**Comment by matt87vl** [comment]
I have this problem too, is there anyone who can help us?
