### ISSUE TITLE
BaseParser.encodeBundleToString does not accept dstu2 Bundle

### ISSUE THREAD

**Issue by bartek-sarul** [jamesagnew/hapi-fhir#390]
Method `encodeBundleToString` in `ca.uhn.fhir.parser.BaseParser` accepts only `ca.uhn.fhir.model.api.Bundle` which is obsolete for DSTU2.

For DSTU2 the `ca.uhn.fhir.model.dstu2.resource.Bundle` is used.

**Comment by jamesagnew** [comment]
Hi Bartek, in DSTU2 the Bundle is a resource like any other resource so you can actually jsut encode it using `encodeResourceToString(bundle)`

**Comment by bartek-sarul** [comment]
@jamesagnew 
I can, but then if Bundle.Entries are empty, `encodeResourceToString` doesn't serialize this property as empty array and just omits it - it doesnt produce `... entry: [ ] `.
If that created json doesn't have empty array then deserialization using `parseResource` fails.

Does this mean that a bug is in serializer `encodeResourceToString` or deserializer `parseResource` or there just should be an annotation on `Bundle.Entry` class that it should be serialized to empty array if object is empty / null?

**Comment by jamesagnew** [comment]
Hi Bartek,

I added a test and I'm not able to reproduce the behaviour you're
describing unfortunately. Can you paste a code snippet into the bug which
demonstrates this issue? You can look at the commit against this bug to see
the test I've added already to see what it might be missing from your case.

**Comment by bartek-sarul** [comment]
Using `encodeResourceToString` on a bundle with empty `Entry` property will serialize to json and omit that property. On the other hand `fhir_search` when there are no results, return empty array `entry: [ ]`

I asked on fhir implementers, what is the desired behaviour as I can't see anything in the documentation.

**Comment by bartek-sarul** [comment]
I've deleted that last message as I was wrong and serialization and deserialization works properly. The problem we are facing is described above

**Comment by jamesagnew** [comment]
Hi Bartek, I'm still not sure what the issue is.. HAPI correctly doesn't include the empty `entry:[]` from the response. What system is requiring that to be present?

**Comment by bartek-sarul** [comment]
We are using fhirbase and implementing an additional kind of search functionality in our service using hapi-fhir.
Fhirbase has a general search function `fhir_search`. When search doesn't have any results it returns a bundle json object and inside it has `entry: [ ]`
In our additional search we serialize Bundle object using `encodeResourceToString` which on no results omits the empty array and doesn't include the entry field at all.
We are trying to be very strict with fhir documentation but it doesn't say if empty arrays are valid or in such case whole field should be omited.
I've raised this here https://chat.fhir.org/#narrow/stream/implementers/topic/returning.20search.20bundle.20with.20no.20result and the most recent response tells me that your implementation is the expected one and that fhir_search improperly returns empty array instead of omitting the field.
This is a small thing, I know, but we just want to be clear and strict with the api.
I think you can close this ticket.
