### ISSUE TITLE
Parse-Unparse problem for BoundCodeDt

### ISSUE THREAD

**Issue by AndriyLendyel** [jamesagnew/hapi-fhir#391]
Hi,

We're using 1.6 version.  And getting DataFormatException while using IElement field and BoundCodeDt object as value in case of JsonParser:

> ca.uhn.fhir.parser.DataFormatException: element has type ca.uhn.fhir.model.primitive.BoundCodeDt but this is not a valid type for this element - Expected one of: [class ca.uhn.fhir.model.dstu2.composite.DistanceDt, class ca.uhn.fhir.model.dstu2.composite.MetaDt, class ca.uhn.fhir.model.dstu2.composite.PeriodDt, class ca.uhn.fhir.model.primitive.PositiveIntDt, ...

And the field is unparsed to CodeDt in case of XmlParser.

``` java
public enum OutcomeEnum {

    ITEM1("item1"),
    ITEM2("item2");

    private final String code;

    OutcomeEnum(String code) {
        this.code = code;
    }

} 

@ResourceDef(profile = "test-outcome", id = "merge-operation-outcome")
public class TestOutcome extends OperationOutcome {

    @Child(name = "element", order = 0, min = 1, max = 1)
    @Description(shortDefinition = "description")
    IElement element;

    @Override
    public <T extends IElement> List<T> getAllPopulatedChildElementsOfType(Class<T> theType) {
        return ElementUtil.allPopulatedChildElements(theType, element);
    }

    @Override
    public boolean isEmpty() {
        return super.isEmpty() && ElementUtil.isEmpty(element);
    }

} 



public class TestOutcomeTest {

    @Test
    public void testParseBoundCodeDtJson() {
        IParser jsonParser = FhirContext.forDstu2().newJsonParser();

        TestOutcome outcome = new TestOutcome();
        outcome.element = new BoundCodeDt<>(new OutcomeBinder(), OutcomeEnum.ITEM1);

        String xmlResource = jsonParser.encodeResourceToString(outcome);
        TestOutcome operationOutcome = jsonParser.parseResource(TestOutcome.class, xmlResource);

        assertNotNull(operationOutcome.element);
        assertTrue(operationOutcome.element instanceof BoundCodeDt);
        assertEquals(outcome.element, operationOutcome.element);
    }

    @Test
    public void testParseBoundCodeDtXml() {
        IParser xmlParser = FhirContext.forDstu2().newXmlParser();

        TestOutcome outcome = new TestOutcome();
        outcome.element = new BoundCodeDt<>(new OutcomeBinder(), OutcomeEnum.ITEM1);

        String xmlResource = xmlParser.encodeResourceToString(outcome);
        TestOutcome operationOutcome = xmlParser.parseResource(TestOutcome.class, xmlResource);

        assertNotNull(operationOutcome.element);
        assertTrue(operationOutcome.element instanceof BoundCodeDt);
        assertEquals(outcome.element, operationOutcome.element);
    }
} 



class OutcomeBinder implements IValueSetEnumBinder<OutcomeEnum> {

    @Override
    public OutcomeEnum fromCodeString(String theCodeString) {
        if (theCodeString.equals("item1")) {
            return OutcomeEnum.ITEM1;
        } else {
            return OutcomeEnum.ITEM2;
        }
    }

    @Override
    public String toCodeString(OutcomeEnum theEnum) {
        if (theEnum.equals(OutcomeEnum.ITEM1)){
            return "item1";
        }else{
            return "item2";
        }
    }

    @Override
    public String toSystemString(OutcomeEnum theEnum) {
        return "system";
    }

    @Override
    public OutcomeEnum fromCodeString(String theCodeString, String theSystemString) {
        return fromCodeString(theCodeString);
    }
} 
```

Please, see example with tests.

Expected result is to have possibility to parse and unparse BoundCodeDt without errors.
Thank you.

**Comment by AndriyLendyel** [comment]
Hi @jamesagnew !
Are you able to reproduce the issue?
Thank you,
Andriy

**Comment by jamesagnew** [comment]
Hi Andriy,

What is the intended outcome here? I managed to get this to work by adding a field to OutcomeEnum:
```java
public static final IValueSetEnumBinder<OutcomeEnum> VALUESET_BINDER = new OutcomeBinder();
```
...and changing the field type to
```java
 BoundCodeDt<OutcomeEnum> element;
```

..but this doens't actually produce a valid resource since OperationOutcome doesn't have a field called "element". Are you looking to add an extension?

**Comment by AndriyLendyel** [comment]
Hi @jamesagnew ,
The problem is that I cannot change the element field type to `BoundCodeDt<OutcomeEnum>` because I don't know the type in advance. It can be any BoundCodeDt or any simple type like StringDt... So, I need to keep it general. Do you have any suggestions how to achieve this?
Thank you,
Andriy

**Comment by jamesagnew** [comment]
The problem is there is that if you don't use a more specific type for your field, there is no way that HAPI would know what type you want it to parse to.

E.g. when the resource is serialized it will look like:
```
<OperationOutcome>
   <element value="item1"/>
</OperationOutcome>
```

If you haven't explicitly told HAPI that this field is of type `BoundCodeDt<OutcomeEnum>`, there are no hints in the serialized resource that would allow HAPI to figure this out on its own. If you want to support multiple types, you could use multiple fields named "elementCode", "elementString", etc and give them the specific types you want to use.
