### ISSUE TITLE
mvn installl on hapi-fhir-master throwing errors on Windows 7

### ISSUE THREAD

**Issue by skuladeep24** [jamesagnew/hapi-fhir#396]
.last few lines from the command prompt..
.
.
.
[INFO] HAPI FHIR Structures - DSTU3 ....................... FAILURE [02:24 min]
[INFO] HAPI FHIR JAX-RS Server ............................ SKIPPED
[INFO] HAPI FHIR JAX-RS Server - Example .................. SKIPPED
[INFO] HAPI FHIR JPA Server ............................... SKIPPED
[INFO] HAPI FHIR TestPage Overlay ......................... SKIPPED
[INFO] HAPI FHIR JPA Server - Example ..................... SKIPPED
[INFO] HAPI FHIR Sample RESTful Server .................... SKIPPED
[INFO] HAPI FHIR Sample RESTful Server - Tests ............ SKIPPED
[INFO] HAPI FHIR - fhirtest.uhn.ca Deployable WAR ......... SKIPPED
[INFO] HAPI FHIR - Android ................................ SKIPPED
[INFO] HAPI FHIR - Command Line Client - Base Project ..... SKIPPED
[INFO] HAPI FHIR - Command Line Client - Server WAR ....... SKIPPED
[INFO] HAPI FHIR - Command Line Client - Application ...... SKIPPED
[INFO] HAPI FHIR - Distribution Archive ................... SKIPPED
[INFO] HAPI FHIR - Examples (for site) .................... SKIPPED
[INFO] hapi-fhir-base-example-embedded-ws ................. SKIPPED
[INFO] HAPI FHIR - JaCoCo Test Coverage ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:31 min
[INFO] Finished at: 2016-07-04T22:24:15+05:30
[INFO] Final Memory: 81M/404M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
19.1:test (default-test) on project hapi-fhir-structures-dstu3: There are test f
ailures.
[ERROR]
[ERROR] Please refer to C:\Kuladeep\Apigee\EMRDEMO\SETUP\hapi-fhir-master\hapi-f
hir-master\hapi-fhir-structures-dstu3\target\surefire-reports for the individual
 test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :hapi-fhir-structures-dstu3

C:\HAPI\SETUP\hapi-fhir-master\hapi-fhir-master>

Contents of the surefire-reports file:
*****************************************
C:\HAPI\SETUP\hapi-fhir-master\hapi-fhir-master\hapi-fhir-structures-dstu3\target\surefire-reports\ca.uhn.fhir.rest.client.GenericClientDstu3Test

-------------------------------------------------------------------------------
Test set: ca.uhn.fhir.rest.client.GenericClientDstu3Test
-------------------------------------------------------------------------------
Tests run: 31, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.568 sec <<< FAILURE! - in ca.uhn.fhir.rest.client.GenericClientDstu3Test
testSearchByDate(ca.uhn.fhir.rest.client.GenericClientDstu3Test)  Time elapsed: 0.028 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...irthdate=gt2011-01-0[2]> but was:<...irthdate=gt2011-01-0[3]>
	at ca.uhn.fhir.rest.client.GenericClientDstu3Test.testSearchByDate(GenericClientDstu3Test.java:724)

-

**Comment by jamesagnew** [comment]
Thanks for reporting! Will check in a fix shortly

**Comment by skuladeep24** [comment]
Thanks a lot  for the quick fix. I found another issue in this process.

Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.07 sec <<< FAI
LURE! - in ca.uhn.fhir.model.ModelDstu3Test
testEqualsDeep(ca.uhn.fhir.model.ModelDstu3Test)  Time elapsed: 0.058 sec  <<< F
AILURE!
java.lang.AssertionError
        at ca.uhn.fhir.model.ModelDstu3Test.testEqualsDeep(ModelDstu3Test.java:1
09)

Running ca.uhn.fhir.context.FhirContextDstu3Test
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.038 sec - in c
a.uhn.fhir.context.FhirContextDstu3Test
Running ca.uhn.fhir.model.BaseDateTimeTypeDstu3Test
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in c
a.uhn.fhir.model.BaseDateTimeTypeDstu3Test
Running ca.uhn.fhir.rest.server.DateRangeParamSearchDstu3Test
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.727 sec - in c
a.uhn.fhir.rest.server.DateRangeParamSearchDstu3Test
Running ca.uhn.fhir.model.DecimalTypeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in c
a.uhn.fhir.model.DecimalTypeTest
Running ca.uhn.fhir.rest.server.RequestValidatingInterceptorDstu3Test
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.166 sec - in
ca.uhn.fhir.rest.server.RequestValidatingInterceptorDstu3Test
Running org.hl7.fhir.dstu3.model.BaseDateTimeTypeDstu3Test
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in
org.hl7.fhir.dstu3.model.BaseDateTimeTypeDstu3Test
Running ca.uhn.fhir.rest.server.DeleteConditionalDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.599 sec - in c
a.uhn.fhir.rest.server.DeleteConditionalDstu3Test
Running ca.uhn.fhir.rest.client.GenericClientDstu3Test
Tests run: 31, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.631 sec - in
ca.uhn.fhir.rest.client.GenericClientDstu3Test
Running ca.uhn.fhir.rest.server.InterceptorDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.616 sec - in c
a.uhn.fhir.rest.server.InterceptorDstu3Test
Running ca.uhn.fhir.validation.SchemaValidationDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.28 sec - in ca
.uhn.fhir.validation.SchemaValidationDstu3Test
Running ca.uhn.fhir.rest.server.UnclassifiedServerExceptionDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.58 sec - in ca
.uhn.fhir.rest.server.UnclassifiedServerExceptionDstu3Test
Running ca.uhn.fhir.parser.XmlParserDstu3Test
Tests run: 81, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 0.587 sec - in
ca.uhn.fhir.parser.XmlParserDstu3Test
Running ca.uhn.fhir.context.RuntimeResourceDefinitionDstu3Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in c
a.uhn.fhir.context.RuntimeResourceDefinitionDstu3Test
Running org.hl7.fhir.dstu3.utils.FhirPathEngineTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.073 sec - in o
rg.hl7.fhir.dstu3.utils.FhirPathEngineTest
Running ca.uhn.fhir.parser.EmptyElementWithExtensionDstu3Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in c
a.uhn.fhir.parser.EmptyElementWithExtensionDstu3Test
Running ca.uhn.fhir.parser.CustomTypeDstu3Test
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.238 sec - in
ca.uhn.fhir.parser.CustomTypeDstu3Test
Running ca.uhn.fhir.rest.client.ClientWithCustomTypeDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec - in c
a.uhn.fhir.rest.client.ClientWithCustomTypeDstu3Test
Running ca.uhn.fhir.context.ContextScanningDstu3Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.628 sec - in c
a.uhn.fhir.context.ContextScanningDstu3Test
Running ca.uhn.fhir.rest.server.CreateDstu3Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.619 sec - in c
a.uhn.fhir.rest.server.CreateDstu3Test
Running ca.uhn.fhir.model.ModelSerializationDstu3Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.065 sec - in c
a.uhn.fhir.model.ModelSerializationDstu3Test
Running ca.uhn.fhir.rest.server.OperationServerDstu3Test
Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.721 sec - in
ca.uhn.fhir.rest.server.OperationServerDstu3Test
Running ca.uhn.fhir.rest.server.CreateBinaryDstu3Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.588 sec - in c
a.uhn.fhir.rest.server.CreateBinaryDstu3Test
Running ca.uhn.fhir.rest.server.OperationServerWithSearchParamTypesDstu3Test
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.676 sec - in c
a.uhn.fhir.rest.server.OperationServerWithSearchParamTypesDstu3Test
Running ca.uhn.fhir.validation.FhirInstanceValidatorDstu3Test
Tests run: 27, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 44.329 sec - in
 ca.uhn.fhir.validation.FhirInstanceValidatorDstu3Test
Running ca.uhn.fhir.rest.server.ServerUsingOldTypesDstu3Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in c
a.uhn.fhir.rest.server.ServerUsingOldTypesDstu3Test
Running z.TestTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec - in z
.TestTest
Running ca.uhn.fhir.rest.server.ValidateDstu3Test
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.569 sec - in c
a.uhn.fhir.rest.server.ValidateDstu3Test
Running ca.uhn.fhir.rest.server.SearchCountParamDstu3Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.649 sec - in c
a.uhn.fhir.rest.server.SearchCountParamDstu3Test
Running ca.uhn.fhir.model.IdTypeDstu3Test
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in
ca.uhn.fhir.model.IdTypeDstu3Test
Running ca.uhn.fhir.context.ModelScannerDstu3Test
Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.083 sec - in c
a.uhn.fhir.context.ModelScannerDstu3Test
Running org.hl7.fhir.utilities.xhtml.XhtmlNodeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in o
rg.hl7.fhir.utilities.xhtml.XhtmlNodeTest
Running ca.uhn.fhir.narrative.DefaultThymeleafNarrativeGeneratorDstu3Test
Tests run: 6, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.448 sec - in c
a.uhn.fhir.narrative.DefaultThymeleafNarrativeGeneratorDstu3Test
Running org.hl7.fhir.dstu3.hapi.validation.ResourceValidatorDstu3Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.686 sec - in
org.hl7.fhir.dstu3.hapi.validation.ResourceValidatorDstu3Test
Running ca.uhn.fhir.rest.client.NonGenericClientDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec - in c
a.uhn.fhir.rest.client.NonGenericClientDstu3Test
Running ca.uhn.fhir.rest.client.OperationClientDstu3Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 sec - in c
a.uhn.fhir.rest.client.OperationClientDstu3Test
Running ca.uhn.fhir.rest.server.SearchWithServerAddressStrategyDstu3Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.592 sec - in c
a.uhn.fhir.rest.server.SearchWithServerAddressStrategyDstu3Test
Running ca.uhn.fhir.validation.QuestionnaireResponseValidatorDstu3Test
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.249 sec - in c
a.uhn.fhir.validation.QuestionnaireResponseValidatorDstu3Test

Results :

Failed tests:
  ModelDstu3Test.testEqualsDeep:109

Tests run: 437, Failures: 1, Errors: 0, Skipped: 18

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] HAPI-FHIR .......................................... SUCCESS [  8.697 s]
[INFO] HAPI FHIR - Deployable Artifact Parent POM ......... SUCCESS [  2.074 s]
[INFO] HAPI FHIR - Core Library ........................... SUCCESS [ 56.952 s]
[INFO] HAPI FHIR - Validation Resources (DSTU3) ........... SUCCESS [  7.248 s]
[INFO] HAPI Tinder Plugin ................................. SUCCESS [ 35.713 s]
[INFO] HAPI FHIR Structures - DSTU1 (FHIR v0.80) .......... SUCCESS [01:45 min]
[INFO] HAPI FHIR - Validation Resources (DSTU2) ........... SUCCESS [  8.121 s]
[INFO] HAPI FHIR Structures - DSTU2 (FHIR v1.0.0) ......... SUCCESS [01:48 min]
[INFO] HAPI FHIR - Minimal Dependency Test - Client ....... SUCCESS [ 18.243 s]
[INFO] HAPI FHIR - Minimal Dependency Test - Server ....... SUCCESS [  7.318 s]
[INFO] HAPI Tinder Plugin - Test Project .................. SUCCESS [ 19.755 s]
[INFO] HAPI FHIR Structures - HL7.org DSTU2 ............... SUCCESS [05:58 min]
[INFO] HAPI FHIR Structures - DSTU3 ....................... FAILURE [08:30 min]
[INFO] HAPI FHIR JAX-RS Server ............................ SKIPPED
[INFO] HAPI FHIR JAX-RS Server - Example .................. SKIPPED
[INFO] HAPI FHIR JPA Server ............................... SKIPPED
[INFO] HAPI FHIR TestPage Overlay ......................... SKIPPED
[INFO] HAPI FHIR JPA Server - Example ..................... SKIPPED
[INFO] HAPI FHIR Sample RESTful Server .................... SKIPPED
[INFO] HAPI FHIR Sample RESTful Server - Tests ............ SKIPPED
[INFO] HAPI FHIR - fhirtest.uhn.ca Deployable WAR ......... SKIPPED
[INFO] HAPI FHIR - Android ................................ SKIPPED
[INFO] HAPI FHIR - Command Line Client - Base Project ..... SKIPPED
[INFO] HAPI FHIR - Command Line Client - Server WAR ....... SKIPPED
[INFO] HAPI FHIR - Command Line Client - Application ...... SKIPPED
[INFO] HAPI FHIR - Distribution Archive ................... SKIPPED
[INFO] HAPI FHIR - Examples (for site) .................... SKIPPED
[INFO] hapi-fhir-base-example-embedded-ws ................. SKIPPED
[INFO] HAPI FHIR - JaCoCo Test Coverage ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20:47 min
[INFO] Finished at: 2016-07-05T17:22:25+05:30
[INFO] Final Memory: 253M/431M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
19.1:test (default-test) on project hapi-fhir-structures-dstu3: There are test f
ailures.
[ERROR]
[ERROR] Please refer to C:\Kuladeep\Apigee\EMRDEMO\SETUP2\hapi-fhir\hapi-fhir-st
ructures-dstu3\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :hapi-fhir-structures-dstu3

C:\Kuladeep\Apigee\EMRDEMO\SETUP2\hapi-fhir>

**Comment by skuladeep24** [comment]
FAILURE! - in ca.uhn.fhir.model.ModelDstu3Test
testEqualsDeep(ca.uhn.fhir.model.ModelDstu3Test)  Time elapsed: 0.058 sec  <<< F
AILURE!
java.lang.AssertionError
        at ca.uhn.fhir.model.ModelDstu3Test.testEqualsDeep(ModelDstu3Test.java:1
09)

**Comment by skuladeep24** [comment]
Tests run: 65, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 57.839 sec <<<
FAILURE! - in ca.uhn.fhir.jpa.dao.dstu3.FhirResourceDaoDstu3SearchNoFtTest
testSearchCompositeParamDate(ca.uhn.fhir.jpa.dao.dstu3.FhirResourceDaoDstu3Searc
hNoFtTest)  Time elapsed: 0.418 sec  <<< FAILURE!
java.lang.AssertionError:

Expected: iterable with items [<Observation/699>] in any order
     but: no item matches: <Observation/699> in []
        at ca.uhn.fhir.jpa.dao.dstu3.FhirResourceDaoDstu3SearchNoFtTest.testSear
chCompositeParamDate(FhirResourceDaoDstu3SearchNoFtTest.java:626)
[ca.uhn.fhir.jpa.dao.dstu3.FhirResourceDaoDstu3SearchNoFtTest.txt](https://github.com/jamesagnew/hapi-fhir/files/348236/ca.uhn.fhir.jpa.dao.dstu3.FhirResourceDaoDstu3SearchNoFtTest.txt)
[ca.uhn.fhir.jpa.dao.dstu3.FhirResourceDaoDstu3SearchNoFtTest-output.txt](https://github.com/jamesagnew/hapi-fhir/files/348237/ca.uhn.fhir.jpa.dao.dstu3.FhirResourceDaoDstu3SearchNoFtTest-output.txt)

**Comment by jamesagnew** [comment]
Hi @skuladeep24 : Everything should be good now, do you mind to try again?

As a part of fixing your original bug I added some code that randomly changes the timezone and system locale before each test, and it looks like it found a few other dependencies I needed to fix.

**Comment by skuladeep24** [comment]
Hi @jamesagnew  Thanks a lot. It is working now.

**Comment by skuladeep24** [comment]
@jamesagnew  After this vagrant setup, I was not able to get results on the rest calls below.

http://192.168.1.136:8080/baseDstu2/Patient/500?_format=json

I dont see any mysql Databases specific to HAPI on the virtualbox ubuntu instance! Can that be a reason.Any suggestions/comments please.
[Error.txt](https://github.com/jamesagnew/hapi-fhir/files/367265/Error.txt)

**Comment by jamesagnew** [comment]
Unfortunately the Vagrant setup was an outside contribution and I don't really know how it works. If you do find a solution to this, please post it.
