### ISSUE TITLE
Unit test failure on Debian Linux (x64) with hapi-fhir  ExampleServerIT.testCreateAndRead

### ISSUE THREAD

**Issue by wpostma** [jamesagnew/hapi-fhir#398]
For hapi-fhir git commit 040c098742e04a3f564a89dcf05c41d4abba857f @  Jul 7 07:40, on my Debian box with jdk 1.8.0_91, `mvn install` fails:

```

[INFO] HAPI FHIR JPA Server - Example ..................... FAILURE [ 15.657 s]
[INFO] HAPI FHIR Sample RESTful Server .................... SKIPPED

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running ca.uhn.fhir.jpa.demo.ExampleServerIT
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.342 sec <<< FAILURE! - in ca.uhn.fhir.jpa.demo.ExampleServerIT
testCreateAndRead(ca.uhn.fhir.jpa.demo.ExampleServerIT)  Time elapsed: 1.051 sec  <<< ERROR!
ca.uhn.fhir.rest.server.exceptions.UnclassifiedServerFailureException: HTTP 503 Service Unavailable
	at ca.uhn.fhir.jpa.demo.ExampleServerIT.testCreateAndRead(ExampleServerIT.java:38)


Results :

Tests in error: 
  ExampleServerIT.testCreateAndRead:38 » UnclassifiedServerFailure HTTP 503 Serv...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0




```

Not sure if this is a local condition that would only affect my system, or a general issue.

**Comment by wpostma** [comment]
Maybe intermittent? Ran again and it passed the second time.

**Comment by jamesagnew** [comment]
If by chance this happens again: Inside `./hapi-fhir-jpaserver-example/target/surefire-reports` there should be files called `[path]ExampleServerIT.txt` and `[path]ExampleServerIT-output.txt`

If you could attach those to this ticket and reopen, that would be awesome. Hopefully this was just a one-off though.

**Comment by gregoriocanal** [comment]
Hi james,
i found the same
[ca.uhn.fhir.jpa.demo.ExampleServerIT.txt](https://github.com/jamesagnew/hapi-fhir/files/2438683/ca.uhn.fhir.jpa.demo.ExampleServerIT.txt)
[ca.uhn.fhir.jpa.demo.ExampleServerIT-output.txt](https://github.com/jamesagnew/hapi-fhir/files/2438684/ca.uhn.fhir.jpa.demo.ExampleServerIT-output.txt)

 issue.
Here you ca find the two files requested:

**Comment by gregoriocanal** [comment]
@jamesagnew

**Comment by jamesagnew** [comment]
Is this happening consistently for you? Or just once?

**Comment by gregoriocanal** [comment]
consistenly, whan i do the maven install from eclipse oxygen of the pom.xml of the hapi-fhir-jpaserver-example downloaded from the git repository

**Comment by gregoriocanal** [comment]
consistenly, whan i do the maven install from eclipse oxygen of the pom.xml
of the hapi-fhir-jpaserver-example downloaded from the git repository
*Gregorio Canal*
Test Architect,
Standardization, Business Analysis and Testing Area | *Arsenàl.IT*
<http://www.consorzioarsenal.it/web/guest/home>
T. +39 0422 216 129 | F. +39 338 667 7556 | S. gregorio.canal
gcanal@consorzioarsenal.it
*Twitter <https://twitter.com/Consorz_Arsenal> | Google Plus
<https://plus.google.com/u/0/113799995708933749665/posts> | LinkedIn
<https://www.linkedin.com/company/1161895> | YouTube
<https://www.youtube.com/user/consorzioarsenal>*


Il giorno mar 2 ott 2018 alle ore 18:15 James Agnew <
notifications@github.com> ha scritto:
