### ISSUE TITLE
fullUrl disappears on storing Bundle

### ISSUE THREAD

**Issue by mbaltus** [jamesagnew/hapi-fhir#401]
I'm running into a problem storing Bundles on the HAPI server. I've created a Bundle of type document and when I put that to the server, the server changes my Bundle by removing the fullUrl part of the entries. Retrieving the Bundle again doesn't list any fullUrl in the entries, even though the spec says:

> bdl-6: On Bundle.entry: The fullUrl element must be present when a resource is present, and not present otherwise (expression on Bundle.entry: fullUrl.empty() xor resource.exists())

**Comment by jamesagnew** [comment]
Thanks for reporting! For some reason there was code in the server to clear this field. I can't see any good reason for that, so I'm going to remove it.

Will push a new build to the public server on Monday afternoon.
