### ISSUE TITLE
XMLParser overwrites section.text in Composition resources

### ISSUE THREAD

**Issue by mbaltus** [jamesagnew/hapi-fhir#402]
When I create a Composition resource and set its Narrative, then create some sections and set the section.text, the XML parser will generate the value of Composition.text in each of the section.text parts, instead of their real value.

**Comment by jamesagnew** [comment]
Hi Mirjam,

I'm having a hard time visualizing how this works. Any chance you could paste in a code snippet or link to a resource that demonstrates this?

**Comment by oxymor0n** [comment]
+1 on this issue, just encountered it myself

**Comment by jamesagnew** [comment]
@mbaltus - Sorry this took so long to close :)
