### ISSUE TITLE
Encoder, version in reference and fullUrl

### ISSUE THREAD

**Issue by cknaap** [jamesagnew/hapi-fhir#403]
When I create a Resource (R) with a Reference (Ref) with a version-specific url, and then encode R, the version is stripped from Ref.url.
On the other hand, when I create a Bundle.Entry with a version-specific fullUrl, the version is retained upon encoding.
Based on the spec about Resolving references in Bundles (http://hl7.org/fhir/bundle.html#references) I would expect the version to be retained in the Reference.
Stripping it from the fullUrl is better understandable, since it is not meant to be version-specific.

**Comment by jamesagnew** [comment]
Thanks for the report! Checking in a fix for 2.0 shortly that will enable you to keep versions in encoded resources if you need.
