### ISSUE TITLE
Better support for setting WWW-Authenticate header for basic autentification

### ISSUE THREAD

**Issue by allanbrohansen** [jamesagnew/hapi-fhir#406]
Issue: The http-response for a failed basic autentification should include a WWW-Authenticate header.
But setting such a header is not supported as part of throwing a ca.uhn.fhir.rest.server.exceptions.AuthenticationException.
My current solution is also to implement handleException for this scenario in the autentification interceptor. The code looking something like this (as we only have basic autentification). 
``
@Override
    public boolean handleException(RequestDetails requestDetails, BaseServerResponseException e,HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        if(e instanceof AuthenticationException) {
            if(!response.containsHeader("WWW-Authenticate")) {
                response.addHeader("WWW-Authenticate", "Basic realm=\"Some realm\"");
            }
        }
        return true;
    }
 ``
Not super nice...

**Comment by jamesagnew** [comment]
Definitely agreed this isn't great.

We don't actually use `WWW-Authenticate` ourselves, so I don't have much insight into how this would be used by HAPI developers. Any insights into what would be useful behaviour/API?

**Comment by allanbrohansen** [comment]
(sorry for the late reply - holiday)
One possible implementation would be to have a specific interceptor class for the basic http autentification (much like I was forced to do). This class should then have an overrideable implementation of String getRealm which the interceptor class would use.
Another way would be to extend the AuthenticationException to support setting any kind of response headers or more specifically a WWW-Authenticate header.
I myself prefer to the latter solution: extend the AuthenticationException with the possiblity to set/add a (WWW-Authenticate) response header(s).

**Comment by jamesagnew** [comment]
Ah, I like the second idea a lot. I am going to add some code to allow any BaseServerResponseException to have arbitrary headers attached, and then add a method to AuthenticationException that allows you to specify the realm.

**Comment by jamesagnew** [comment]
Thanks for the suggestion!

I've added a method to `AuthenticationException` that lets you add a custom realm, and you can now add any other arbitrary headers to the response you want as well.
