### ISSUE TITLE
Feature Request: Add client support for $process-message special  operation

### ISSUE THREAD

**Issue by hugosoares** [jamesagnew/hapi-fhir#407]
The generic IGenericClient.operation() does not work for the special case o $process-message since this operation does not use the parameters resource; the parameters "async" and "response-url" always go in the URL, if they are used, and the message parameter is always the body of the HTTP message.

Please see 
https://www.hl7.org/fhir/messaging.html#process
and 
https://www.hl7.org/fhir/messageheader-operations.html#6.11.10.1

**Comment by hugosoares** [comment]
Due to the lack of feedback, Is this library considering supporting the messaging paradigm at all?

**Comment by jamesagnew** [comment]
Hi Hugo,

We definitely intend/hope to support the entire FHIR specification and messaging would be a part of that.

That said, we're obviously limited by the capacity of our team and volunteers, so at this point we don't have a timeframe for messaging.

We would, of course, welcome any help if anyone wanted to take this one on.

**Comment by hugosoares** [comment]
Hi James,
Thanks for the information.

Ok,  It seems to be an easy job. I Will try and do a pull request.

Em 13/01/2017 12:38, "James Agnew" <notifications@github.com> escreveu:

**Comment by jamesagnew** [comment]
Ah that would be amazing! :)

**Comment by hugosoares** [comment]
Almost done but I am strugling with keeping the fluent api semantics for the execute() method invocation on the genericClient.
It should either return an OperationOutcome or a Bundle depending on wether ther the flag "async" is set or not. 

Right now it is working by simply returning Object. The user must then cast to the correct resource type.
I will finish the unit tests and then do a pull request for you to review the code.
