### ISSUE TITLE
Contained Resources

### ISSUE THREAD

**Issue by paulbarrynz** [jamesagnew/hapi-fhir#410]
Hi James,

We have been using the Hapi server to test the consumption of a MedicationOrder with multiple 'contained' resources e.g. Medication, Practitioner and Organisation. This was working on your server a few days ago but now appears to be broken. Have you been working in this area? Currently the server will only save the first contained resource and omit the rest

**Comment by jamesagnew** [comment]
Hi Paul, can you attach a sample of what you're sending?

sent from my phone.

**Comment by paulbarrynz** [comment]
Hi James,

Bundle attached

Cheers

Paul

**Comment by jamesagnew** [comment]
Hi Paul,

How is this content being generated?

The contained practitioner doesn't have any ID, which means it isn't valid and is therefore being ignored. See:

```xml
				<contained>
					<Practitioner>
						<text>
							<status value="generated" />
							<xhtml:div>Ellison, Christine. HPI-I:8003616566689462</xhtml:div>
						</text>
```
