### ISSUE TITLE
Bug. NPE While parsing extensions

### ISSUE THREAD

**Issue by hugosoares** [jamesagnew/hapi-fhir#414]
Using HAPI Version 1.6
I am getting an NPE every time I try to parse a Json resource with an invalid extension that does not contain extension.url,

Trace:
 at ca.uhn.fhir.parser.JsonParser.parseExtension(JsonParser.java:1331)

Sugestion:
Control the error and throw a ca.uhn.fhir.parser.DataFormatException instead?

**Comment by jamesagnew** [comment]
Hi Hugo, thanks for the report! I'm checking in a fix now. This will trigger a warning by default now, or throw an error if the StrictErrorHandler is configured on the parser.
