### ISSUE TITLE
CreateResource from the browser is failing. Any ideas?

### ISSUE THREAD

**Issue by gsureshkumar** [jamesagnew/hapi-fhir#427]
![hapi issue](https://cloud.githubusercontent.com/assets/19829447/17706130/cd0e85be-63a8-11e6-8bc0-fc0d4b0afe16.png)

when we tried creating a post request for creating a resource from the browser, it complains of invalid request (saying Bundle is missing in the input request). Do we need a bundle entry for a create patient request?

We were creating the request from another javascript based client which was failing.
Just to confirm that we are sending the right request we tried creating the same from the browser itself.
Any insights would be helpful.

**Comment by jamesagnew** [comment]
Hi @gsureshkumar, your POST URL is incorrect. You need to append the resource type to the end of it (i.e. it should end with `/Patient`). Without that, the server thinks you are trying to do a transaction, which requires a bundle.
