### ISSUE TITLE
NPE on Encoding Extension with CodeableConcept when TRACE logging

### ISSUE THREAD

**Issue by bdenton** [jamesagnew/hapi-fhir#428]
With TRACE level logging enabled, a NPE is thrown when JSON encoding an `ExtensionDt` containing a `CodeableConceptDt` (stack trace attached).

The problem seems to be with `BaseParser.CompositeChildElement`. The constructor calls `buildPath()` then TRACE logging. the `buildPath()` method does not work right when `myResDef` and `myParent` are both null.

I tried to create a Surefire test to demonstrate the bug but could not figure out how to enable TRACE logging inside Surefire.

cheers, 
Bill Denton
Akana, Inc.

[patient-npe-0815.txt](https://github.com/jamesagnew/hapi-fhir/files/421252/patient-npe-0815.txt)

**Comment by jamesagnew** [comment]
Hi Bill, thanks for reporting!

Checking in a fix shortly..

FYI- To set the logging level in the unit test environment you just need to edit the `logback-test.xml` file in the same project as the unit test. There's also a programatic way that I've done in the unit test.
