### ISSUE TITLE
DSTU3 - The named query (search) does not been generated in ServerConformanceProvider

### ISSUE THREAD

**Issue by baopingle** [jamesagnew/hapi-fhir#430]
Hello,
   I found that the advanced query which was defined by named query - "@Search(name=xxx)" does not been generated in ServerConformanceProvider.
  http://www.hl7.org/implement/standards/fhir/search.html#advanced, the official document said that "Servers can define their own additional named queries to meet their own uses using an OperationDefinition.", So when there are named queries used in resource providers, then the metadata should generate the OperationDefinition like as the "@Operation" if I understood correctly.
   @jamesagnew, can you check that?

**Comment by jamesagnew** [comment]
The ServerConformanceProvider has a few gaps in what it produces. 

This would be a pretty good introduction bug if anyone wants to take a crack at this as a newbie to hacking on HAPI.
