### ISSUE TITLE
Duplicate entry of Organization tag in ExplanationOfBenefit

### ISSUE THREAD

**Issue by ganesh-athmagnanam** [jamesagnew/hapi-fhir#434]
Duplicate entry of Organization tag in ExplanationOfBenefit
[Duplicate entry of Organization tag in ExplanationOfBenefit.txt](https://github.com/jamesagnew/hapi-fhir/files/449245/Duplicate.entry.of.Organization.tag.in.ExplanationOfBenefit.txt)

FHIR Resource used->ExplanationOfBenefit(PBS)

FHIR version -->1.4.0 
HAPI version -->1.5

**Comment by jamesagnew** [comment]
Hi @ganesh-athmagnanam , we have just released HAPI FHIR 2.0, would you be able to confirm whether this issue is still occurring on that version?
