### ISSUE TITLE
dateWritten element should be placed after the ‘id’ tag

### ISSUE THREAD

**Issue by ganesh-athmagnanam** [jamesagnew/hapi-fhir#436]
dateWritten element should be placed after the ‘id’ tag

dateWritten element under MedicationOrder(contained resource)should be placed after the ‘id’ tag.

FHIR Resource used->ExplanationOfBenefit(PBS & MBS)

FHIR version -->1.4.0 
HAPI version -->1.5
[dateWritten element should be placed after the ‘id’ tag.txt](https://github.com/jamesagnew/hapi-fhir/files/449554/dateWritten.element.should.be.placed.after.the.id.tag.txt)

**Comment by jamesagnew** [comment]
Hi @ganesh-athmagnanam , we have just released HAPI FHIR 2.0, would you be able to confirm whether this issue is still occurring on that version?
