### ISSUE TITLE
saxon parser

### ISSUE THREAD

**Issue by lwedmo** [jamesagnew/hapi-fhir#440]
James et al,

I'm curious about HAPI FHIR's use of the saxon parser (saxon-9.1.0.8.jar and saxon9-dom.jar) It seems very lightly used, almost unused. In all of the HAPI FHIR source, grep shows a reference to it's package net.sf.saxon only in org.hl7.fhir.utilities.Utilities in hapi-fhir-structures-dstu2-2.0.jar.  net.sf.saxon.TransformerFactoryImpl is the only class referenced. There are 4 saxonTransform methods, which are not directly invoked at all.

My QA group reports that this error message has cropped up coincident with the introduction of the saxon parser into our class path:

16/09/06 15:47:47 Recoverable error on line 1269 of baseEnNoteBody.xsl:
  FODC0002: java.io.FileNotFoundException:
  /oas/j2ee/dvqa24/applications/iknowmed/iknowmed-reports/stylesheets/hardcopy/  (No such
  file or directory)

If I change Utilitites.java, removing the saxonTransform methods to remove the dependency on saxon, will it break anything in FHIR?

        Leonard Edmondson
        McKesson

**Comment by euz1e4r** [comment]
Locally, I hacked Utilities.java removing all references to saxon, rebuilt, dropped saxon from the class path, retested and our FHIR server apparently works fine.

         Len

________________________________

**Comment by jamesagnew** [comment]
Hmm, this is interesting. I definitely know for a fact that HAPI itself doesn't use Saxon, but I had to add it to get some of the RI classes to compile. It's quite possible it's not needed at all.

If we can drop it from our dependencies I will certainly be very happy. Saxon is such a mess, it always causes weird failures like the one you're noting.

Are you using the FHR profile validator (InstanceValidator) at all? If not, it's definitely 100% safe to drop saxon. If so, I think I need to check with Grahame what we're using it for..

**Comment by lwedmo** [comment]
We are not using the profile validator yet. But even in InstanceValidator, I see that the reference to Saxon is commented out.




-------- Original Message --------

**Comment by jamesagnew** [comment]
Yeah, after spending a bunch of time looking at it I would say you are right.

I'm going to check in a fix to remove Saxon. Sweet.

**Comment by t106uhn** [comment]
Hi james I think this fix could have caused a change in the parsing of contained objects (in my case contained Observations within a DiagnosticReport) during on the FHIR server during a create/update.  I'm getting the following error:

HTTP 400 Bad Request: Failed to parse request body as XML resource. Error was: DataFormatException at [[row,col {unknown-source}]: [1,1082]]: Invalid JSON content detected, missing required element: 'resourceType'

**Comment by t106uhn** [comment]
I'm assuming this fix was added to hapi-fhir 2.1-SNAPSHOT

**Comment by lwedmo** [comment]
Not true. The source base I am working with is 2.0, and I did not commit it to git at all.


-------- Original Message --------

**Comment by jamesagnew** [comment]
Hi @t106uhn, I haven't actually pushed a new snapshot build with this fix yet, so unless you're building from source I would say it's doubtful that this specific fix caused your regression.

That is a bizarre error message though- "Failed to parse as XML [...] Invalid JSON". I don't get how it would be doing both.

Can you grab the stack trace and the request headers?

**Comment by jamesagnew** [comment]
Closing this issue per discussion with @t106uhn
