### ISSUE TITLE
org.hl7.fhir.utilities.xhtml.XhtmlNode#equalsDeep   incorrect  (HAPI v2.0)

### ISSUE THREAD

**Issue by XcrigX** [jamesagnew/hapi-fhir#443]
In  org.hl7.fhir.utilities.xhtml.XhtmlNode
The equalsDeep() method contains the following:
`public boolean equalsDeep(XhtmlNode other) {
    if (other instanceof XhtmlNode)
      return false;
...
}`

I believe the IF statement should be negated. 

This causes an equalsDeep to fail for any resource containing a section like:
`<text>
    <status value="generated"/>
    <div xmlns="http://www.w3.org/1999/xhtml">A human-readable rendering of the ExplanationOfBenefit</div>
  </text>`

The ExplanationOfBenefit sample xml from the FHIR main site fails, for example. 

http://hl7.org/fhir/2016Sep/explanationofbenefit-example.xml.html

**Comment by jamesagnew** [comment]
Thanks for reporting! Checking in a fix now.
