### ISSUE TITLE
Confused about content-type (application/json+fhir)

### ISSUE THREAD

**Issue by Robbert1** [jamesagnew/hapi-fhir#445]
Hi,

Currently the HAPI-FHIR JPA server returns results as content-type "application/json+fhir".

This is also stated here:
[https://www.hl7.org/fhir/json.html](https://www.hl7.org/fhir/json.html)
[https://www.hl7.org/fhir/valueset-content-type.json.html](https://www.hl7.org/fhir/valueset-content-type.json.html)

however this [site](https://hl7-fhir.github.io/valueset-content-type.html) states "application/fhir+json" which I feel is actually more correct as general JSON parsers like Springs AbstractJackson2HttpMessageConverter are configured to work for "application/*+json".

Although it's not yet a real spec by my knowledge, I do believe more custom JSON based content types like HAL also conform to this pattern.

I'd like to get some info on if any switch to "application/fhir+json" is planned or if "application/json+fhir" is the definitive type.

**Comment by jamesagnew** [comment]
Hi @Robbert1,

FHIR itself defines the content types we use as they have them spelled out as requirements in the specification.

One of the changes in the current STU3 ballot is that they've shifted from using `application/json+fhir` to using `application/fhir+json` (and same change for XML). 

This change is reflected in HAPI's 2.0 release, but only in STU3 mode (i.e. DSTU3 contexts). You can see the updated content types in the request and response headers here for example: http://fhirtest.uhn.ca/conformance?serverId=home_21&pretty=true

**Comment by jamesagnew** [comment]
...although I notice that the types are actually wrong in the conformance statement itself. Argh!

I'll keep this bug open to track that. :)

**Comment by Robbert1** [comment]
I'm actually using HAPI 2.0 with STU3. (my server response contains  X-Powered-By=[HAPI FHIR 2.0 REST Server (FHIR Server; FHIR 1.6.0/DSTU3)])

**Comment by jamesagnew** [comment]
Is the client you're using sending the correct `Accept` header? In order to avoid breaking existing clients, HAPI tries to negotiate and will pick "the old or the new" depending on what the request looks like.

**Comment by jamesagnew** [comment]
E.g. the following is required to get the new content type from our public server:

```
$ curl -H "Accept: application/fhir+json" --head "http://fhirtest.uhn.ca/baseDstu3/metadata"
HTTP/1.1 405 Method Not Allowed
Date: Tue, 13 Sep 2016 14:18:47 GMT
Server: Apache-Coyote/1.1
X-Powered-By: HAPI FHIR 2.1-SNAPSHOT REST Server (FHIR Server; FHIR 1.6.0/DSTU3)
Allow: GET
Content-Type: application/fhir+json;charset=UTF-8
Transfer-Encoding: chunked
Connection: close
```

**Comment by Robbert1** [comment]
The accept header is working like a charm thanks!

**Comment by jamesagnew** [comment]
Closing this issue as it seems to be all good. :)
