### ISSUE TITLE
Parsing profile information causes UnsupportedOperationException

### ISSUE THREAD

**Issue by FilipDomazet** [jamesagnew/hapi-fhir#447]
Preconditions:
There exist custom types which extend the default FHIR resources. 
FhirContext has been set up with default types for profile:
ctx.setDefaultTypeForProfile("http://customResourceProfileId", CustomResource.class);
The resource fetched from the server contains the appropriate profile tag within metadata. 

When fetching the resource through the restful client, an UnsupportedOperationException occurs in the ParserState class within the method enteringNewElement(String, String). 

Upon examination, the cause is the following:
When attempting to add a profile first the current profile list is fetched, and an attempt to add to this list causes the abovementioned exception. The list appears to be unmodifiable, which is also mentioned in the documentation of the ResourceMetadataKeyEnum.PROFILES constant. 

A pull request has been made with a solution to this issue.

**Comment by jamesagnew** [comment]
Closing this ticket, as the PR has been merged. Thanks for reporting!
