### ISSUE TITLE
When encoding JSON on server, extensions of type valueReference are left empty

### ISSUE THREAD

**Issue by FilipDomazet** [jamesagnew/hapi-fhir#449]
When fetching a resource with extensions from the server in JSON encoding, extensions of type valueReference are left empty. For example:
"extensions": [
    {
        "url": "http://extensionUrl",
        **"valueReference": {}**
    }
]

This only happens when encoding to JSON, XML encoding will contain the expected valueReference. 
This issue is also present in version 1.6.

**Comment by jamesagnew** [comment]
Hi Filip,

Can you provide any sample code that demonstrates this issue?

Extensions appear to work for me, e.g. this resource is being returned correctly by HAPI: http://fhirtest.uhn.ca/baseDstu3/Patient/139716

**Comment by FilipDomazet** [comment]
Hi James,

I have created a [sample project](https://github.com/FilipDomazet/hapi-valuereference-encoding-example) on GitHub which reproduces this issue. I will try outline the project and issue in this comment. 

The project contains one extension class, called ExtendedDevice and a DeviceResourceProvider which supports the search operation and returns some dummy data. 

The resource can be accessed on the url <base_context>/fhir/Device

I would like to point out that this issue has only been observed when dealing with valueReferences, valueString extensions and other seem to work fine. Therefore, in the example some different ways of adding a resource reference are explored. 
For start, these are the extensions defined by ExtendedDevice:
```
@ResourceDef(name="Device", id="ExtendedDevice")
public class ExtendedDevice extends Device {
	
	@Child(name="someOrg")
	@Extension(url="http://extensionsBaseUrl/Device#someOrg", definedLocally=true, isModifier = false)
	private ResourceReferenceDt someOrg;
	
	@Child(name="someOtherOrg")
	@Extension(url="http://extensionsBaseUrl/Device#someOtherOrg", definedLocally=true, isModifier = false)
	private ResourceReferenceDt someOtherOrg;

	public ResourceReferenceDt getSomeOrg() {
		if (someOrg == null) {
			someOrg = new ResourceReferenceDt();
		}
		return someOrg;
	}
	//... other getters and setters ...
}
```
When using the following code to set one of these extension: 
`dev.getSomeOrg().setResource(org);`
the resulting valueReference will be left empty: 
`"valueReference": {}`

Using the following almost works: 
`dev.setSomeOtherOrg(new ResourceReferenceDt(org));` 
The ID will be present, but the resource prefix, which should in this case be "Organization/", is missing. For example: 
```"valueReference": {
    "reference": "57e75fc6-8ea4-4c00-b6e4-50a2ecad841a"
}```

When using
```
ExtensionDt someExt = new ExtensionDt();
someExt.setUrl("http://extensionsBaseUrl/Device#someExt");
ResourceReferenceDt orgRef = new ResourceReferenceDt();
orgRef.setResource(org);
someExt.setValue(orgRef);
dev.addUndeclaredExtension(someExt);
```
the undeclared extension will be properly encoded: 
```"valueReference": {
    "reference": "Organization/57e75fc6-8ea4-4c00-b6e4-50a2ecad841a"
}```

Also, when setting references for fields already defined by the FHIR standard, there appears to be no problem. The following code:
`dev.getOwner().setResource(org);`
results in the following JSON element being added:
```"owner": {
    "reference": "Organization/57e75fc6-8ea4-4c00-b6e4-50a2ecad841a"
}```

I hope this helps.

**Comment by FilipDomazet** [comment]
Hi James, did you have a chance to look at this issue?

**Comment by jamesagnew** [comment]
Hi Filip,

I believe this was fixed as a part of another bug which is a dupe of this one, although I'm not finding the reference right now. Can you try with the latest `2.1-SNAPSHOT` build to see if you're still experiencing it?

**Comment by FilipDomazet** [comment]
In the current commit (89e3021) everything seems to be working fine. Thank you, I will close this issue now.
