### ISSUE TITLE
Chinese characters can't be saved into postgresql such as in a CodeSystem post and be as a url parameter to search something (version 2.0)

### ISSUE THREAD

**Issue by YinAqu** [jamesagnew/hapi-fhir#454]
It comes with a org.postgresql.util.PSQLException: 错误: 无效的 "UTF8" 编码字节顺序: 0x00, in English the error information means about error:invalid "UTF8" code byte sequence:0x00.
I think this can be resolved in the method BaseHapiFhirDao.normalizeString() .

**Comment by jamesagnew** [comment]
Hi @YinAqu , would you be able to attach a resource body we could use in a testcase? Or some sample code to generate one?

**Comment by YinAqu** [comment]
Hi @jamesagnew ,thanks for your comment.Any resource body including Chinese characters anywhere will result in this exception.The below is a sample for CodeSystem:
`{
  "resourceType": "CodeSystem",
 
  "url": "http://nestvision.com/fhir/myexample-yh",
  "name": "NestVision Restful Interactions",
  "status": "active",
  "publisher": "杨浩",
  "description": "this is a codesystem example.",
  "caseSensitive": true,
  "concept": [
    {
      "code": "mygod",
      "display": "wholly shit",
      "definition": "this is a translate."
    },
    {
      "code": "checknow",
      "display": "qiekenao",
      "definition": "yaoyaoqiekenao."
    },
    {
      "code": "didi",
      "display": "dididache",
      "definition": "just a taxi software"
    }
  ]
}`

**Comment by jamesagnew** [comment]
So.. I'm very confused about this. So far I haven't been able to reproduce it.

Are you using the `charSet` parameter on your database connection URL, and do you have PGSQL configured to use UTF-8?

**Comment by YinAqu** [comment]
Hi @jamesagnew, sorry to confuse you, it's my mistake to mention to database. 

In fact this has nothing to do with database, but the method BaseHapiFhirDao.normalizeString() doesn't allow characters which are greater than '\u007F' to be stored.. 

I don't know why the program make the rule only English characters can get through the filter, but I really wish I could populate some Chinese characters into the ‘description‘ property so that Chinese people can understand what it is used for..

Please have a look at the method's codes:

`	public static String normalizeString(String theString) {
		char[] out = new char[theString.length()];
		theString = Normalizer.normalize(theString, Normalizer.Form.NFD);
		int j = 0;
		for (int i = 0, n = theString.length(); i < n; ++i) {
			char c = theString.charAt(i);
			if (c <= '\u007F') {
				out[j++] = c;
			}
		}
		return new String(out).toUpperCase();
	}`

**Comment by jamesagnew** [comment]
Hi @YinAqu , ahhhhh ok thanks for the explanation. That makes sense, and I was able to reproduce your issue.

I'm checking in a fix now.
