### ISSUE TITLE
PUBLISHED date in the Resource Metadata not being returned by the FHIR server

### ISSUE THREAD

**Issue by t106uhn** [jamesagnew/hapi-fhir#457]
HI James,

In my ResourceProvider I have code like the following:

ResourceMetadataKeyEnum.PUBLISHED.put(enc, new InstantDt(createdDateTime)); 

Unfortunately the data does not get populated in the <meta> element.  

Although, ResourceMetadataKeyEnum.UPDATED.put(enc, new InstantDt(lastUpdatedDateTime)); works without issues.

**Comment by jamesagnew** [comment]
Hey Neal, PUBLISHED actually doesn't exist in FHIR any more. It had a spot in the Atom feed bundles, but there is no equivalent concept in DSTU2+. I think the idea is that you can figure out the published date by querying for the first version of a resource and getting the UPDATE date for it... Which doesn't help if you're not doing versioning of course

I guess ultimately you'd need an extension if you wanted to convey this concept
