### ISSUE TITLE
Pull request builds are failing

### ISSUE THREAD

**Issue by bdenton** [jamesagnew/hapi-fhir#459]
Why are most of the pull request builds failing on tests not related to the change?
Seems like lots of build failures around the interceptor tests in both DSTU1 and DSTU2.
Once these are resolved, how do we get or pull requests to get retested?

**Comment by bdenton** [comment]
Three times in a row the build has failed on one of the interceptor tests. These tests all run successfully in my development environment and I fail to see how the changes in my pull request are having an effect on these failing tests. Since I have no visibility into the surefire logs to see what the problem might be, I am not able to diagnose or correct the issue. Quite frustrating trying to get my PR to mass muster

cheers, 
Bill Denton

**Comment by jamesagnew** [comment]
Oh man, after way too much time I think I figured this out. It's a race condition.

The servlet was calling outputstream.close() prior to invoking the final interceptor method which means that if the server was under a particular amount of load the unit test thread would check for this firing prior to the server thread actually calling that interceptor method.

I guess on Travis the load was such that this happened, but on everyone's workstations it wasn't. Go figure.

I'm checking in a fix now.

**Comment by jamesagnew** [comment]
Well now that sure didn't work.
