### ISSUE TITLE
support prettyPrint in browser display

### ISSUE THREAD

**Issue by allanbrohansen** [jamesagnew/hapi-fhir#464]
Small request :-)
We are not using prettyPrint but do support a browser friendly display (via ResponseHighlighterInterceptor).
I would like the generated html do include a "view as pretty print" option, adding a _pretty=true parameter to the url.

**Comment by jamesagnew** [comment]
Hi Allan,

Maybe I'm missing something obvious, but why would you want this? The ResponseHighlighterInterceptor already pretty prints by default (even if that parameter isn't found in the URL) so wouldn't this link not have any effect?

**Comment by allanbrohansen** [comment]
Hi James. I do not experience a pretty print by default, so adding ?_pretty=true makes a difference.
E.g.. http://username:password@my-environment.com/Organization/OrgId?_pretty=true.
I am using HAPI 1.6. I also notice that I do not have the "Response generated in "-display that is shown on http://fhirtest.uhn.ca/baseDstu2/Patient/.

**Comment by jamesagnew** [comment]
Well I'll be.

I always thought pretty was the default in that interceptor, but you're right, it isn't. I guess I've always used it on servers where pretty was the default all over! Learn something new every day..

I see no reason why it shouldn't be the default when using the interceptor.. Pretty coloured source that's all on one line is not very useful :)

Will fix.
