### ISSUE TITLE
some questions to ask you about HAPI IParser

### ISSUE THREAD

**Issue by JesseHu1520** [jamesagnew/hapi-fhir#478]
Hello @jamesagnew ,I am a java developer,Today i found a problem when i use IParser.encodeResourceToString(DiagnosticReport),
But i find the ContainedResources(observations) is not included the string(json/xml),
So I am confuse,I need you help😁
I hope you reply as soon as possible😘

**Comment by jamesagnew** [comment]
Hi Jesse,

We have a google group where you can ask questions here: https://groups.google.com/d/forum/hapi-fhir

(The GitHub issue tracker is for reporting bugs.)

Cheers,
James

**Comment by JesseHu1520** [comment]
Thank you！l have resolved this problem. case the contained resource doesn't use local-ID
