### ISSUE TITLE
Question about paging search operation, there may be a bug (version2.0)

### ISSUE THREAD

**Issue by YinAqu** [jamesagnew/hapi-fhir#481]
Hi James, I've got a question (possibly a bug? I'm not sure) about paging search:

When the rest server has got a paging provider,  search request at the first time stores the result collection in database or memory with a generated `UUID` as a mark. 

All the  subsequently returned paging links(next/previous) include this `UUID`. It seems via these links the client `can only `get the data of the result collection stored as a cache before which is marked by this `UUID`.

`My question is` what about `a new resource is created` or `a existing resource is deleted` during the paging search in the above? `The client can't get the newly created resource in the last page because the cache doesn't include it`.

a paging link (e.g. http://localhost:8080/Dstu3?_getpages=8deeeb67-0256-4434-8f1d-f7fb3b38946a&_getpagesoffset=10&_count=10&_bundletype=searchset)

Would you please tell me is this the desired behavior or not? 

Sorry about my poor Chinese English :-D. 

Thanks in advanced
Your friend YinAqu

**Comment by jamesagnew** [comment]
This behaviour is actually by design. Per the [fhir spec](http://hl7.org/fhir/search.html#currency):

> The results of a search operation are only guaranteed to be current at the moment the operation is executed. After the operation is executed, ongoing actions performed on the resources against which the search was executed will render the results increasingly stale. The significance of this depends on the nature of the search, and the kind of use that is being made of the results.

The idea at least with the way we built HAPI's searching is that it's more important to have stable results than to have extra-current results at the expense of paging being unpredictable.

Do you have a use case where this isn't desirable?

**Comment by YinAqu** [comment]
Thanks James, your answer is very helpful to me.

I've got a front-end web page containing a paging list of some resource, in which add and delete operation can be performed. Add or delete operation will reload the current page. I'm considering how to design this. For example, when I'm in the 2nd page, delete all the resources in that page making the page empty, then I go to the 3rd, then turn back to the 2nd, the page is still empty. This is what I met.

Furthermore, a search data cleanup every 10's by HAPI would lock the search table frequently, any possibility this will result in a performance problem when too many search requests come?

**Comment by jamesagnew** [comment]
Hi YinAqu, you definitely don't want to use the Derby database if you have any kind of load requirements. Derby does indeed lock tables to one user at a time, so it doesn't scale at all. The search data cleanup hasn't caused us any issues even under big loads on Postgres or MySQL for example.

**Comment by YinAqu** [comment]
Tks James. 
Consider this use case, a resource such as Patient has 2000 data in the resource table (greater in practice, 2000 is just my test number, my test system is on Postgres, just a simple test). 

The link of the 1st front-end Patient page is `http://example/Patient`, loading this link means inserting 2000+ data into the search tables(when `_lastupdated` or `_sort` is provided, the amount will be double or treble), it takes 800ms when there's no concurrent request, 1200ms per request when there are 5 concurrent requests, 2400ms when 10.

It seems this costs too much, is there any suggestion for me to avoid this?

**Comment by jamesagnew** [comment]
If you have any alternative ways for this to work, we would absolutely welcome a pull request!

**Comment by YinAqu** [comment]
It's my pleasure if I can contribute HAPI. I do have a pan for this. Before that would you please  tell me the reason `FifoMemoryPagingProvider` replaced by `DatabaseBackedPagingProvider` by default, this is very important for my solution.

**Comment by jamesagnew** [comment]
The main reason for that was simply that the memory provider holds all of
the results in memory, which means that if you have lots and lots of
concurrent searches happening at the same time you will run out of memory..

If you find a good alternative that doesn't use
DatabaseBackedPagingProvider I certainly don't see a problem with that.
Especially if we can set things up so that implementors can choose which
one to use

**Comment by YinAqu** [comment]
Got it, I'll have a try to implement my solution, and send you a pull request if it works. Thanks for your time my friend.

**Comment by jamesagnew** [comment]
Best of luck!! Happy to chat about the approach if that's useful at all
