### ISSUE TITLE
FhirContext.forDstu2: failed to createForcedIdIfNeeded

### ISSUE THREAD

**Issue by rqg0717** [jamesagnew/hapi-fhir#482]
Dear Mr. Agnew,

I have established a hapi-fhir-jpaserver with MySQL locally (based on hapi-fhir-jpaserver-example from https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-fhir-jpaserver-example). Then I tried to use the HAPI RESTful client to create an instance of the resource with client forced resource ID using the following code:
```
// Create a context
FhirContext ctxInt = FhirContext.forDstu2();
// Create a internal server client and use it
IGenericClient clientInt = ctxInt.newRestfulGenericClient("http://127.0.0.1:8080/hapi-fhir/baseDstu2");
//create a sample patient with client signed id
Patient patient = new Patient();
patient.addIdentifier().setSystem("urn:system").setValue("12345");
patient.addName().addFamily("Smith").addGiven("John");
patient.setID("Patient-12345");

MethodOutcome outcome = clientInt.create()                                               
                                                .resource(patient)
                                                .prettyPrint()
                                                .encodedJson()
                                                .execute();

System.out.println("Got ID: " + (IdDt)outcome.getId());
``` 
I could create the new patient successfully since:

```
2016-10-31 11:39:53.331 [qtp1752365512-59] INFO  c.u.f.j.dao.BaseHapiFhirResourceDao [BaseHapiFhirResourceDao.java:365] Successfully created resource "Patient/51/_history/1" in 235ms
```

However, when I checked the table "HFJ_FORCED_ID", the table is empty. 

I dug the source code on GitHub and found the following code:

```
protected void validateResourceIdAndUrlIdForNonConditionalOperation(IBaseResource theResource, String theResourceId, String theUrlId, String theMatchUrl) {
		if (isNotBlank(theUrlId)) {
			String msg = getContext().getLocalizer().getMessage(BaseOutcomeReturningMethodBindingWithResourceParam.class, "idInUrlForCreate", theUrlId);
			throw new InvalidRequestException(msg);
		}
		if (getContext().getVersion().getVersion().isOlderThan(FhirVersionEnum.DSTU3)) {
			if (isNotBlank(theResourceId)) {
				String msg = getContext().getLocalizer().getMessage(BaseOutcomeReturningMethodBindingWithResourceParam.class, "idInBodyForCreate", theResourceId);
				throw new InvalidRequestException(msg);
			}
		} else {
			theResource.setId((IIdType)null);
		}
	}
```
in CreateMethodBinding.java.

I was wondering if
```
createForcedIdIfNeeded(entity, theResource.getIdElement());
```
got bypassed by the code somehow, so it will never create forced id.  Or the way I was trying to assign a forced ID was not right. Please let me know. 

I forgot to mention that I am using the following HAPI RESTful client version:
```
<dependency>
    <groupId>ca.uhn.hapi.fhir</groupId>
    <artifactId>hapi-fhir-structures-dstu2</artifactId>
    <version>2.0</version>
</dependency>
```
Thank you.

Sincerely,
Ren

**Comment by rqg0717** [comment]
I forgot to mention that I am using the following HAPI RESTful client version:
```
<dependency>
    <groupId>ca.uhn.hapi.fhir</groupId>
    <artifactId>hapi-fhir-structures-dstu2</artifactId>
    <version>2.0</version>
</dependency>
```
Thank you.

**Comment by rqg0717** [comment]
I also tried the "CRUD Operations" on the server. It says "Create an instance of the resource. Generally you do not need to specify an ID but you may force the server to use a specific ID by including one. "
but it seems it was also  failed to force the server to use a specific ID. the table  HFJ_FORCED_ID is still empty.
I have tried to add a new row in HFJ_FORCED_ID manually 
```
<DATA>
	<ROW>
		<PID>1</PID>
		<FORCED_ID>Patient-12345</FORCED_ID>
		<RESOURCE_PID>51</RESOURCE_PID>
		<RESOURCE_TYPE>Patient</RESOURCE_TYPE>
	</ROW>
</DATA>
```
and then created an instance of "Person" linked to the forced ID. It has been working fine so far.

**Comment by rqg0717** [comment]
I found the following code in FhirSystemDaoDstu2.java:

```
...
switch (verb) {
			case POST: {
				// CREATE
				@SuppressWarnings("rawtypes")
				IFhirResourceDao resourceDao = getDaoOrThrowException(res.getClass());
                                //why?
				res.setId((String) null);
				//
                                DaoMethodOutcome outcome;
				outcome = resourceDao.create(res, nextReqEntry.getRequest().getIfNoneExist(), false, theRequestDetails);
				handleTransactionCreateOrUpdateOutcome(idSubstitutions, idToPersistedOutcome, nextResourceId, outcome, nextRespEntry, resourceType, res);
				entriesToProcess.put(nextRespEntry, outcome.getEntity());
				if (outcome.getCreated() == false) {
					nonUpdatedEntities.add(outcome.getEntity());
				}
				break;
			}
...
```
It seems it has been hard coded that `res.setId((String)` null);` . I was wondering why. Is Forced ID not allowed in DSTU2 anymore please? Please let me know. Thank you.

Urgenly waiting for the answer,
Ren

**Comment by jamesagnew** [comment]
Hi Ren,

Under FHIR's rules if you do a "create" (aka HTTP POST) the server will assign an ID so you are not using forced ID.

If you want the client to specify the ID you need to use "update" (aka HTTP PUT) even if the resource doesn't yet exist on the server. In that case the server will use the ID assigned by the client.
