### ISSUE TITLE
Tester Client returning 500 error after upgrade to 2.0

### ISSUE THREAD

**Issue by laffandan** [jamesagnew/hapi-fhir#485]
Hi, I previously had a working client with Hapi 1.4 but following an upgrade to 2.0 -  I am getting a 500 internal error after the method has executed in the corresponding Provider class.

I have a custom resource that extends ca.uhn.fhir.model.dstu2.resource.BaseResource and I return a list - the tester client gives the following error:

{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "ca.uhn.fhir.context.RuntimeResourceDefinition.isStandardProfile()Z"
    }
  ]
}

Any help/thoughts? If you need more info please ask
Thanks
Dan

**Comment by jamesagnew** [comment]
Is there any chance you still have old copies of the HAPI library on your classpath (i.e. possibly you need to do a clean-build of your project?)

That method `isStandardProfile` was removed from the API before 2.0 so i'm assuming it must be coming from an older copy of the library..

**Comment by laffandan** [comment]
Thanks James everything at 2.0 now - maven repo doesnt contain any older versions - but now when running the tester client i receive the following 

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is ca.uhn.fhir.context.ConfigurationException: Unknown class[ca.uhn.fhir.model.dstu2.resource.Documentation] for resource definition: Documentation
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.ebaysf.web.cors.CORSFilter.handleNonCORS(CORSFilter.java:437)
	org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:172)

It looks like the Documentation class was dropped from the structures - but something in the tester is referencing it

**Comment by jamesagnew** [comment]
> Unknown class[ca.uhn.fhir.model.dstu2.resource.Documentation] for resource definition: Documentation

That error message doesn't make sense to me. There is no resource called "Documentation" in FHIR, so it's not clear to me why it would be trying to load one. Have you made any customizations to HAPI?

**Comment by laffandan** [comment]
![image](https://cloud.githubusercontent.com/assets/2759846/20059917/8a29c8ec-a4f0-11e6-94cd-24ad8abf86b1.png)

seems this class from version 1.4 was called Documentation - we haven't customized any of the code just extended some of the resources - more specifically we haven't done anything with a class called Documentation,

If we load the 1.4 version of the dtsu2 structures - the tester runs correctly but then i receive the original error i posted about

**Comment by laffandan** [comment]
checked the mvn dependency:tree an there is no mention of anything other than 2.0 jars - did a clean install -U and my local maven repo only contains 2.0 jars - checked the war file for the server and the tester client in my tomcat and they dont contain anything that should not be there (all version 2.0) - also cleared out any temp tomcat dirs (work/temp etc.) - still seems i have the problem as below 

type Exception report

message Request processing failed; nested exception is ca.uhn.fhir.context.ConfigurationException: Unknown class[ca.uhn.fhir.model.dstu2.resource.Documentation] for resource definition: Documentation

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is ca.uhn.fhir.context.ConfigurationException: Unknown class[ca.uhn.fhir.model.dstu2.resource.Documentation] for resource definition: Documentation
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.ebaysf.web.cors.CORSFilter.handleNonCORS(CORSFilter.java:437)
	org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:172)
root cause

ca.uhn.fhir.context.ConfigurationException: Unknown class[ca.uhn.fhir.model.dstu2.resource.Documentation] for resource definition: Documentation
	ca.uhn.fhir.context.ModelScanner.scanVersionPropertyFile(ModelScanner.java:548)
	ca.uhn.fhir.context.ModelScanner.init(ModelScanner.java:163)
	ca.uhn.fhir.context.ModelScanner.<init>(ModelScanner.java:96)
	ca.uhn.fhir.context.FhirContext.scanResourceTypes(FhirContext.java:609)
	ca.uhn.fhir.context.FhirContext.scanResourceType(FhirContext.java:593)
	ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:317)
	ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:357)
	ca.uhn.fhir.parser.JsonParser.doEncodeResourceToWriter(JsonParser.java:207)
	ca.uhn.fhir.parser.BaseParser.encodeResourceToWriter(BaseParser.java:399)
	ca.uhn.fhir.parser.BaseParser.encodeResourceToString(BaseParser.java:382)
	ca.uhn.fhir.to.BaseController.loadAndAddConfDstu2(BaseController.java:401)
	ca.uhn.fhir.to.BaseController.loadAndAddConf(BaseController.java:321)
	ca.uhn.fhir.to.BaseController.addCommonParams(BaseController.java:97)
	ca.uhn.fhir.to.Controller.actionHome(Controller.java:230)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.ebaysf.web.cors.CORSFilter.handleNonCORS(CORSFilter.java:437)
	org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:172)
root cause

java.lang.ClassNotFoundException: ca.uhn.fhir.model.dstu2.resource.Documentation
	org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1858)
	org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1709)
	java.lang.Class.forName0(Native Method)
	java.lang.Class.forName(Class.java:191)
	ca.uhn.fhir.context.ModelScanner.scanVersionPropertyFile(ModelScanner.java:538)
	ca.uhn.fhir.context.ModelScanner.init(ModelScanner.java:163)
	ca.uhn.fhir.context.ModelScanner.<init>(ModelScanner.java:96)
	ca.uhn.fhir.context.FhirContext.scanResourceTypes(FhirContext.java:609)
	ca.uhn.fhir.context.FhirContext.scanResourceType(FhirContext.java:593)
	ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:317)
	ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:357)
	ca.uhn.fhir.parser.JsonParser.doEncodeResourceToWriter(JsonParser.java:207)
	ca.uhn.fhir.parser.BaseParser.encodeResourceToWriter(BaseParser.java:399)
	ca.uhn.fhir.parser.BaseParser.encodeResourceToString(BaseParser.java:382)
	ca.uhn.fhir.to.BaseController.loadAndAddConfDstu2(BaseController.java:401)
	ca.uhn.fhir.to.BaseController.loadAndAddConf(BaseController.java:321)
	ca.uhn.fhir.to.BaseController.addCommonParams(BaseController.java:97)
	ca.uhn.fhir.to.Controller.actionHome(Controller.java:230)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.ebaysf.web.cors.CORSFilter.handleNonCORS(CORSFilter.java:437)
	org.ebaysf.web.cors.CORSFilter.doFilter(CORSFilter.java:172)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.64 logs.

Can you try with the same setup please?

**Comment by jamesagnew** [comment]
We're actually hosting our public DSTU2 server ( http://fhirtest.uhn.ca/baseDstu2/Patient ) on Tomcat 7, so it at least certainly can work. :)

When HAPI logs its version on startup, is it reporting "2.0"?

If so, I'm wondering if you could try putting a breakpoint in the `scanVersionPropertyFile` method in ModelScanner (i.e. [here](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/ModelScanner.java#L493) )

This method should be loading the `fhirversion.properties` file from `hapi-fhir-structures-dstu2-2.0.jar` which I've confirmed has no reference to the `Documentation` class.

```
10:23:37 [Jamess-MacBook-Pro-2 tmp]$ jar xf ../hapi-fhir-structures-dstu2-2.0.jar
10:24:04 [Jamess-MacBook-Pro-2 tmp]$ cat ca/uhn/fhir/model/dstu2/fhirversion.properties | grep Documentation
resource.SupportingDocumentation=ca.uhn.fhir.model.dstu2.resource.SupportingDocumentation
10:24:08 [Jamess-MacBook-Pro-2 tmp]$
```

**Comment by laffandan** [comment]
1) Cant see any version in log file as app doesn't get that far 
2) Got the breakpoint working and here is the enum value that is passed to the method 
![image](https://cloud.githubusercontent.com/assets/2759846/20066121/687bc98a-a508-11e6-933e-c3ce15200a28.png) which looks slightly awry..

The resulting string that gets read from the props file after this line is executed 'prop.load(str);' actually contains the below which includes the erroneous 'Documentation' class reference

{datatype.boolean=ca.uhn.fhir.model.primitive.BooleanDt, datatype.Coding=ca.uhn.fhir.model.dstu2.composite.CodingDt, datatype.decimal=ca.uhn.fhir.model.primitive.DecimalDt, datatype.ElementDefinitionDt=ca.uhn.fhir.model.dstu2.composite.ElementDefinitionDt, datatype.Identifier=ca.uhn.fhir.model.dstu2.composite.IdentifierDt, datatype.CodeableConcept=ca.uhn.fhir.model.dstu2.composite.CodeableConceptDt, resource.CarePlan=ca.uhn.fhir.model.dstu2.resource.CarePlan, resource.AuditEvent=ca.uhn.fhir.model.dstu2.resource.AuditEvent, resource.EnrollmentRequest=ca.uhn.fhir.model.dstu2.resource.EnrollmentRequest, resource.Communication=ca.uhn.fhir.model.dstu2.resource.Communication, resource.OrderResponse=ca.uhn.fhir.model.dstu2.resource.OrderResponse, datatype.Attachment=ca.uhn.fhir.model.dstu2.composite.AttachmentDt, datatype.Period=ca.uhn.fhir.model.dstu2.composite.PeriodDt, resource.Test=ca.uhn.fhir.model.dstu2.resource.Test, datatype.ElementDefinition=ca.uhn.fhir.model.dstu2.composite.ElementDefinitionDt, resource.Organization=ca.uhn.fhir.model.dstu2.resource.Organization, datatype.DistanceDt=ca.uhn.fhir.model.dstu2.composite.DistanceDt, datatype.AgeDt=ca.uhn.fhir.model.dstu2.composite.AgeDt, datatype.base64Binary=ca.uhn.fhir.model.primitive.Base64BinaryDt, datatype.Narrative=ca.uhn.fhir.model.dstu2.composite.NarrativeDt, resource.Conformance=ca.uhn.fhir.model.dstu2.resource.Conformance, datatype.Quantity=ca.uhn.fhir.model.dstu2.composite.QuantityDt, resource.Schedule=ca.uhn.fhir.model.dstu2.resource.Schedule, resource.Observation=ca.uhn.fhir.model.dstu2.resource.Observation, resource.StructureDefinition=ca.uhn.fhir.model.dstu2.resource.StructureDefinition, resource.Binary=ca.uhn.fhir.model.dstu2.resource.Binary, resource.Subscription=ca.uhn.fhir.model.dstu2.resource.Subscription, resource.DataElement=ca.uhn.fhir.model.dstu2.resource.DataElement, datatype.instant=ca.uhn.fhir.model.primitive.InstantDt, resource.Order=ca.uhn.fhir.model.dstu2.resource.Order, datatype.CountDt=ca.uhn.fhir.model.dstu2.composite.CountDt, datatype.Money=ca.uhn.fhir.model.dstu2.composite.MoneyDt, datatype.SimpleQuantity=ca.uhn.fhir.model.dstu2.composite.SimpleQuantityDt, resource.EpisodeOfCare=ca.uhn.fhir.model.dstu2.resource.EpisodeOfCare, datatype.contained=ca.uhn.fhir.model.dstu2.composite.ContainedDt, resource.Basic=ca.uhn.fhir.model.dstu2.resource.Basic, resource.Account=ca.uhn.fhir.model.dstu2.resource.Account, resource.EligibilityResponse=ca.uhn.fhir.model.dstu2.resource.EligibilityResponse, resource.Medication=ca.uhn.fhir.model.dstu2.resource.Medication, resource.Contract=ca.uhn.fhir.model.dstu2.resource.Contract, resource.Coverage=ca.uhn.fhir.model.dstu2.resource.Coverage, datatype.SampledDataDt=ca.uhn.fhir.model.dstu2.composite.SampledDataDt, resource.ProcessRequest=ca.uhn.fhir.model.dstu2.resource.ProcessRequest, datatype.PeriodDt=ca.uhn.fhir.model.dstu2.composite.PeriodDt, resource.DeviceUseRequest=ca.uhn.fhir.model.dstu2.resource.DeviceUseRequest, resource.ImmunizationRecommendation=ca.uhn.fhir.model.dstu2.resource.ImmunizationRecommendation, resource.User=ca.uhn.fhir.model.dstu2.resource.User, resource.MedicationOrder=ca.uhn.fhir.model.dstu2.resource.MedicationOrder, resource.List=ca.uhn.fhir.model.dstu2.resource.ListResource, datatype.integer=ca.uhn.fhir.model.primitive.IntegerDt, datatype.dateTime=ca.uhn.fhir.model.primitive.DateTimeDt, datatype.RangeDt=ca.uhn.fhir.model.dstu2.composite.RangeDt, resource.SupplyDelivery=ca.uhn.fhir.model.dstu2.resource.SupplyDelivery, datatype.MetaDt=ca.uhn.fhir.model.dstu2.composite.MetaDt, resource.Specimen=ca.uhn.fhir.model.dstu2.resource.Specimen, resource.ConceptMap=ca.uhn.fhir.model.dstu2.resource.ConceptMap, resource.ClinicalImpression=ca.uhn.fhir.model.dstu2.resource.ClinicalImpression, resource.ReferralRequest=ca.uhn.fhir.model.dstu2.resource.ReferralRequest, resource.ImplementationGuide=ca.uhn.fhir.model.dstu2.resource.ImplementationGuide, resource.Documentation=ca.uhn.fhir.model.dstu2.resource.Documentation, datatype.TimingDt=ca.uhn.fhir.model.dstu2.composite.TimingDt, datatype.Ratio=ca.uhn.fhir.model.dstu2.composite.RatioDt, resource.RiskAssessment=ca.uhn.fhir.model.dstu2.resource.RiskAssessment, resource.Immunization=ca.uhn.fhir.model.dstu2.resource.Immunization, datatype.DurationDt=ca.uhn.fhir.model.dstu2.composite.DurationDt, resource.FamilyMemberHistory=ca.uhn.fhir.model.dstu2.resource.FamilyMemberHistory, datatype.markdown=ca.uhn.fhir.model.primitive.MarkdownDt, datatype.ContactPointDt=ca.uhn.fhir.model.dstu2.composite.ContactPointDt, resource.DeviceComponent=ca.uhn.fhir.model.dstu2.resource.DeviceComponent, resource.ClinicalAdvice=com.imsmaxims.fhir.model.ClinicalAdvice, resource.Patient=ca.uhn.fhir.model.dstu2.resource.Patient, resource.Encounter=ca.uhn.fhir.model.dstu2.resource.Encounter, resource.Claim=ca.uhn.fhir.model.dstu2.resource.Claim, resource.DetectedIssue=ca.uhn.fhir.model.dstu2.resource.DetectedIssue, datatype.SampledData=ca.uhn.fhir.model.dstu2.composite.SampledDataDt, resource.NutritionOrder=ca.uhn.fhir.model.dstu2.resource.NutritionOrder, resource.ProcedureRequest=ca.uhn.fhir.model.dstu2.resource.ProcedureRequest, resource.OperationDefinition=ca.uhn.fhir.model.dstu2.resource.OperationDefinition, datatype.CodeableConceptDt=ca.uhn.fhir.model.dstu2.composite.CodeableConceptDt, datatype.oid=ca.uhn.fhir.model.primitive.OidDt, resource.Group=ca.uhn.fhir.model.dstu2.resource.Group, resource.Questionnaire=ca.uhn.fhir.model.dstu2.resource.Questionnaire, resource.EnrollmentResponse=ca.uhn.fhir.model.dstu2.resource.EnrollmentResponse, datatype.positiveInt=ca.uhn.fhir.model.primitive.PositiveIntDt, datatype.ContactPoint=ca.uhn.fhir.model.dstu2.composite.ContactPointDt, resource.PaymentNotice=ca.uhn.fhir.model.dstu2.resource.PaymentNotice, resource.MedicationDispense=ca.uhn.fhir.model.dstu2.resource.MedicationDispense, datatype.ResourceReferenceDt=ca.uhn.fhir.model.dstu2.composite.ResourceReferenceDt, resource.Condition=ca.uhn.fhir.model.dstu2.resource.Condition, resource.AppointmentResponse=ca.uhn.fhir.model.dstu2.resource.AppointmentResponse, datatype.Range=ca.uhn.fhir.model.dstu2.composite.RangeDt, resource.PaymentReconciliation=ca.uhn.fhir.model.dstu2.resource.PaymentReconciliation, resource.Slot=ca.uhn.fhir.model.dstu2.resource.Slot, datatype.Signature=ca.uhn.fhir.model.dstu2.composite.SignatureDt, resource.ClaimResponse=ca.uhn.fhir.model.dstu2.resource.ClaimResponse, resource.Media=ca.uhn.fhir.model.dstu2.resource.Media, resource.DiagnosticReport=ca.uhn.fhir.model.dstu2.resource.DiagnosticReport, datatype.HumanNameDt=ca.uhn.fhir.model.dstu2.composite.HumanNameDt, resource.Goal=ca.uhn.fhir.model.dstu2.resource.Goal, resource.SupportingDocumentation=ca.uhn.fhir.model.dstu2.resource.SupportingDocumentation, datatype.AnnotationDt=ca.uhn.fhir.model.dstu2.composite.AnnotationDt, resource.EligibilityRequest=ca.uhn.fhir.model.dstu2.resource.EligibilityRequest, resource.HealthcareService=ca.uhn.fhir.model.dstu2.resource.HealthcareService, resource.ValueSet=ca.uhn.fhir.model.dstu2.resource.ValueSet, resource.SupplyRequest=ca.uhn.fhir.model.dstu2.resource.SupplyRequest, resource.ExplanationOfBenefit=ca.uhn.fhir.model.dstu2.resource.ExplanationOfBenefit, resource.Practitioner=ca.uhn.fhir.model.dstu2.resource.Practitioner, resource.Device=ca.uhn.fhir.model.dstu2.resource.Device, resource.DocumentManifest=ca.uhn.fhir.model.dstu2.resource.DocumentManifest, datatype.Annotation=ca.uhn.fhir.model.dstu2.composite.AnnotationDt, resource.CommunicationRequest=ca.uhn.fhir.model.dstu2.resource.CommunicationRequest, datatype.AddressDt=ca.uhn.fhir.model.dstu2.composite.AddressDt, datatype.uri=ca.uhn.fhir.model.primitive.UriDt, resource.SearchParameter=ca.uhn.fhir.model.dstu2.resource.SearchParameter, resource.Bundle=ca.uhn.fhir.model.dstu2.resource.Bundle, datatype.SignatureDt=ca.uhn.fhir.model.dstu2.composite.SignatureDt, resource.Appointment=ca.uhn.fhir.model.dstu2.resource.Appointment, resource.OperationOutcome=ca.uhn.fhir.model.dstu2.resource.OperationOutcome, resource.Procedure=ca.uhn.fhir.model.dstu2.resource.Procedure, resource.NamingSystem=ca.uhn.fhir.model.dstu2.resource.NamingSystem, resource.DocumentReference=ca.uhn.fhir.model.dstu2.resource.DocumentReference, datatype.QuantityDt=ca.uhn.fhir.model.dstu2.composite.QuantityDt, resource.DeviceUseStatement=ca.uhn.fhir.model.dstu2.resource.DeviceUseStatement, resource.DiagnosticOrder=ca.uhn.fhir.model.dstu2.resource.DiagnosticOrder, datatype.HumanName=ca.uhn.fhir.model.dstu2.composite.HumanNameDt, resource.Remittance=ca.uhn.fhir.model.dstu2.resource.Remittance, resource.DeviceMetric=ca.uhn.fhir.model.dstu2.resource.DeviceMetric, datatype.code=ca.uhn.fhir.model.primitive.CodeDt, datatype.IdentifierDt=ca.uhn.fhir.model.dstu2.composite.IdentifierDt, resource.MedicationStatement=ca.uhn.fhir.model.dstu2.resource.MedicationStatement, datatype.time=ca.uhn.fhir.model.primitive.TimeDt, resource.Composition=ca.uhn.fhir.model.dstu2.resource.Composition, datatype.CodingDt=ca.uhn.fhir.model.dstu2.composite.CodingDt, resource.BodySite=ca.uhn.fhir.model.dstu2.resource.BodySite, resource.Person=ca.uhn.fhir.model.dstu2.resource.Person, resource.VisionPrescription=ca.uhn.fhir.model.dstu2.resource.VisionPrescription, datatype.xhtml=ca.uhn.fhir.model.primitive.XhtmlDt, datatype.Meta=ca.uhn.fhir.model.dstu2.composite.MetaDt, resource.MessageHeader=ca.uhn.fhir.model.dstu2.resource.MessageHeader, datatype.date=ca.uhn.fhir.model.primitive.DateDt, resource.QuestionnaireResponse=ca.uhn.fhir.model.dstu2.resource.QuestionnaireResponse, resource.ImagingStudy=ca.uhn.fhir.model.dstu2.resource.ImagingStudy, datatype.AttachmentDt=ca.uhn.fhir.model.dstu2.composite.AttachmentDt, resource.Parameters=ca.uhn.fhir.model.dstu2.resource.Parameters, datatype.Address=ca.uhn.fhir.model.dstu2.composite.AddressDt, resource.MedicationAdministration=ca.uhn.fhir.model.dstu2.resource.MedicationAdministration, resource.Location=ca.uhn.fhir.model.dstu2.resource.Location, datatype.idref=ca...

**Comment by laffandan** [comment]
Finally got it thanks - I have a customized version of fhirversion.properties in the classpath to override/extend the resource definitions - that's the problem! - we created another resource, 
How do i achieve extending the resource definitions in a better way? - because now the solution for me is clear - can overwrite this local copy with the one from the jar - but this will then happen again on the next version update.

**Comment by jamesagnew** [comment]
Ahhh ok that would explain t.

In HAPI 2.0 you shouldn't need to customize that file in order to use custom types, we've come up with an "official" way to register them without tweaking the file.

There are some examples of how to register a custom type with the context here: http://hapifhir.io/doc_extensions.html#Custom_Resource_Types
