### ISSUE TITLE
Transactions doesn't validate the input for the resource

### ISSUE THREAD

**Issue by gsureshkumar** [jamesagnew/hapi-fhir#487]
Hi,

I ran a transaction with a bunch of create requests.
The requested resources lacked the mandatory fields.
The transaction ran fine and created all the resources (without mandatory fields)
To me, it should have rejected the transaction.
Let me know if something is wrong in the request.

<Bundle xmlns="http://hl7.org/fhir"><entry><resource><Patient /></resource><request><method value="POST" /><url value="http://localhost:8080/hapi-fhir/baseDstu2/Patient" /></request></entry><entry><resource><Patient><identifier><system value="http://example.com/fhir/MRN" /><value value="Test2" /></identifier><name><family /><given /></name><birthDate value="2016-10-24" /></Patient></resource><request><method value="POST" /><url value="http://localhost:8080/hapi-fhir/baseDstu2/Patient" /></request></entry><entry><resource><Observation /></resource><request><method value="POST" /><url value="http://localhost:8080/hapi-fhir/baseDstu2/Observation" /></request></entry></Bundle>

thanks,
Suresh

**Comment by jamesagnew** [comment]
Hi Suresh,

By default the validator is not run on incoming requests or responses. You can enable validation by using the RequestValidatingInterceptor, per the instructions here: http://hapifhir.io/doc_rest_server_interceptor.html#RequestResponse_Validation

**Comment by gsureshkumar** [comment]
Hi James,

I integrated the changes as per the above documentation.
In the HAPI home page, I see the following error.

Unable to determine type of target resource.

thanks,
Suresh

![hapi error](https://cloud.githubusercontent.com/assets/19829447/20363353/e64358aa-ac0c-11e6-9ad5-a3b08688dbac.png)

**Comment by gsureshkumar** [comment]
Hi James,

I noticed that this happens if you have ResponseValidatingInterceptor. If you only have the request interceptor, looks like it runs fine.

thanks,
Suresh
