### ISSUE TITLE
 Missing artifact ca.uhn.hapi.fhir:hapi-fhir-validation-resources-dstu2:jar:2.2-SNAPSHOT 

### ISSUE THREAD

**Issue by jayashreeb081767** [jamesagnew/hapi-fhir#497]
games,
i'm getting the above problem in pom.xml, so please  suggest me to solve this.

**Comment by jamesagnew** [comment]
I'm closing this ticket, please see the comment here for details: https://github.com/jamesagnew/hapi-fhir/issues/498

If you want to open any more tickets please leave a complete description of what you are trying to accomplish as well as a DETAILED explanation of the steps you have taken, any steps you have taken, etc.
