### ISSUE TITLE
Failed to execute goal on project hapi-fhir-cli-jpaserver: 

### ISSUE THREAD

**Issue by jayashreeb081767** [jamesagnew/hapi-fhir#498]
Failed to execute goal on project hapi-fhir-cli-jpaserver: Could not resolve dependencies for project ca.uhn.hapi.fhir:hapi-fhir-cli-jpaserver:war:2.2-SNAPSHOT: The following artifacts could not be resolved: ca.uhn.hapi.fhir:hapi-fhir-base:jar:2.2-SNAPSHOT, ca.uhn.hapi.fhir:hapi-fhir-structures-dstu:jar:2.2-SNAPSHOT, ca.uhn.hapi.fhir:hapi-fhir-structures-dstu2:jar:2.2-SNAPSHOT, ca.uhn.hapi.fhir:hapi-fhir-jpaserver-base:jar:2.2-SNAPSHOT, ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay:war:2.2-SNAPSHOT, ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay:jar:classes:2.2-SNAPSHOT: Failure to find ca.uhn.hapi.fhir:hapi-fhir-base:jar:2.2-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]

**Comment by jamesagnew** [comment]
You have filed 6-8 separate bugs all with different build issues. Can you please give some details about what you are doing? If the build is failing in one spot, how is it also failing in another spot?

These bugs do not have nearly enough detail to be useful. Please close any that are not actually issues and provide more details in any others.
