### ISSUE TITLE
Clicking Next Page from HAPI's resource search page seems to be not working.

### ISSUE THREAD

**Issue by gsureshkumar** [jamesagnew/hapi-fhir#500]
Hi,

I use HAPI FHIR Server - 2.1-SNAPSHOT (master).
From HAPI's home page, the pagination seems to be not working.
Clicking on any resource >Search >Next Page doesn't seem to work.

Returns the page with the following text.

Warning!
Invalid page URL: <th:block th:text="${bundle.linkNext}"/>

thanks,
Suresh

**Comment by rqg0717** [comment]
Got the same issue in HAPI FHIR Server - 2.2-SNAPSHOT as well.

**Comment by elnin0815** [comment]
2.1 final as well

**Comment by jamesagnew** [comment]
Thanks for reporting! Checking in a fix now.
