### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project hapi-fhir-structures-dstu3: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?

### ISSUE THREAD

**Issue by jayashreeb081767** [jamesagnew/hapi-fhir#501]
please help

Running ca.uhn.fhir.rest.server.OperationDuplicateServerHl7OrgDstu2Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.033 sec - in ca.uhn.fhir.rest.server.PreferHl7OrgDstu2Test
Running ca.uhn.fhir.validation.QuestionnaireResponseValidatorTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.003 sec - in ca.uhn.fhir.rest.server.TransactionWithBundleResourceParamHl7OrgDstu2Test
Running ca.uhn.fhir.parser.XmlParserHl7OrgDstu2Test
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.271 sec - in ca.uhn.fhir.validation.QuestionnaireResponseValidatorTest
Running ca.uhn.fhir.model.InstantiationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.255 sec - in ca.uhn.fhir.rest.server.OperationDuplicateServerHl7OrgDstu2Test
Running ca.uhn.fhir.rest.server.SearchHl7OrgDstu2Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.716 sec - in ca.uhn.fhir.rest.server.SearchHl7OrgDstu2Test
Running ca.uhn.fhir.rest.server.CreateConditionalHl7OrgTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.438 sec - in ca.uhn.fhir.model.InstantiationTest
Running ca.uhn.fhir.model.PrimititeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.074 sec - in ca.uhn.fhir.model.PrimititeTest
Running ca.uhn.fhir.rest.client.BundleTypeTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.158 sec - in ca.uhn.fhir.rest.server.CreateConditionalHl7OrgTest
Running ca.uhn.fhir.model.XhtmlNodeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.21 sec - in ca.uhn.fhir.model.XhtmlNodeTest
Running ca.uhn.fhir.rest.server.BinaryHl7OrgDstu2Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.201 sec - in ca.uhn.fhir.rest.client.BundleTypeTest
Running ca.uhn.fhir.validation.QuestionnaireResponseValidatorIntegrationTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.164 sec - in ca.uhn.fhir.rest.server.BinaryHl7OrgDstu2Test
Running ca.uhn.fhir.rest.client.OperationClientTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.844 sec - in ca.uhn.fhir.validation.QuestionnaireResponseValidatorIntegrationTest
Running ca.uhn.fhir.rest.server.IncludeHl7OrgDstu2Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.673 sec - in ca.uhn.fhir.rest.client.OperationClientTest
Running ca.uhn.fhir.rest.server.OperationServerHl7OrgTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.638 sec - in ca.uhn.fhir.rest.server.IncludeHl7OrgDstu2Test
Running ca.uhn.fhir.rest.server.IncludeAndRevincludeParameterHl7OrgTest
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.281 sec - in ca.uhn.fhir.rest.server.OperationServerHl7OrgTest
Running ca.uhn.fhir.rest.server.DeleteConditionalHl7OrgTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.714 sec - in ca.uhn.fhir.rest.server.IncludeAndRevincludeParameterHl7OrgTest
Running ca.uhn.fhir.rest.server.ServerConformanceProviderHl7OrgDstu2Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.177 sec - in ca.uhn.fhir.rest.server.DeleteConditionalHl7OrgTest
Running ca.uhn.fhir.rest.server.ValidateHl7OrgDstu2Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.646 sec - in ca.uhn.fhir.rest.server.ValidateHl7OrgDstu2Test
Running ca.uhn.fhir.rest.client.GenericClientDstu2Hl7OrgTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.568 sec - in ca.uhn.fhir.rest.client.GenericClientDstu2Hl7OrgTest
Running ca.uhn.fhir.model.ModelInheritanceTest
Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.081 sec - in ca.uhn.fhir.model.ModelInheritanceTest
Running ca.uhn.fhir.rest.server.ETagServerHl7OrgTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.682 sec - in ca.uhn.fhir.rest.server.ETagServerHl7OrgTest
Running ca.uhn.fhir.rest.server.UpdateConditionalHl7OrgDstu2Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.609 sec - in ca.uhn.fhir.rest.server.UpdateConditionalHl7OrgDstu2Test
Running ca.uhn.fhir.rest.server.SearchWithHl7OrgDstu2BundleTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.702 sec - in ca.uhn.fhir.rest.server.SearchWithHl7OrgDstu2BundleTest
Running ca.uhn.fhir.rest.server.BundleTypeInResponseHl7OrgTest
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 23.796 sec - in ca.uhn.fhir.validation.FhirInstanceValidatorTest
Tests run: 51, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 47.406 sec - in ca.uhn.fhir.parser.XmlParserHl7OrgDstu2Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30.486 sec - in ca.uhn.fhir.rest.server.BundleTypeInResponseHl7OrgTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 68.366 sec - in ca.uhn.fhir.rest.server.ServerConformanceProviderHl7OrgDstu2Test

Results :

Tests run: 273, Failures: 0, Errors: 0, Skipped: 5

[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.15:check (check-java-api) @ hapi-fhir-structures-hl7org-dstu2 ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ hapi-fhir-structures-hl7org-dstu2 ---
[INFO] Building jar: C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0\hapi-fhir-structures-hl7org-dstu2\target\hapi-fhir-structures-hl7org-dstu2-2.0.jar
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ hapi-fhir-structures-hl7org-dstu2 ---
[INFO] Installing C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0\hapi-fhir-structures-hl7org-dstu2\target\hapi-fhir-structures-hl7org-dstu2-2.0.jar to C:\Users\User\.m2\repository\ca\uhn\hapi\fhir\hapi-fhir-structures-hl7org-dstu2\2.0\hapi-fhir-structures-hl7org-dstu2-2.0.jar
[INFO] Installing C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0\hapi-fhir-structures-hl7org-dstu2\pom.xml to C:\Users\User\.m2\repository\ca\uhn\hapi\fhir\hapi-fhir-structures-hl7org-dstu2\2.0\hapi-fhir-structures-hl7org-dstu2-2.0.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building HAPI FHIR Structures - DSTU3 2.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hapi-fhir-structures-dstu3 ---
[INFO] Deleting C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0\hapi-fhir-structures-dstu3\target
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ hapi-fhir-structures-dstu3 ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-java) @ hapi-fhir-structures-dstu3 ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.7.201606060606:prepare-agent (default-prepare-agent) @ hapi-fhir-structures-dstu3 ---
[INFO] argLine set to -javaagent:C:\\Users\\User\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.7.201606060606\\org.jacoco.agent-0.7.7.201606060606-runtime.jar=destfile=C:\\Users\\User\\Downloads\\hapi-fhir-2.0\\hapi-fhir-2.0\\hapi-fhir-structures-dstu3\\target\\jacoco.exec,dumponexit=true
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hapi-fhir-structures-dstu3 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ hapi-fhir-structures-dstu3 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 278 source files to C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0\hapi-fhir-structures-dstu3\target\classes
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0\hapi-fhir-structures-dstu3\src\main\java\org\hl7\fhir\dstu3\validation\InstanceValidator.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hapi-fhir-structures-dstu3 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 22 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ hapi-fhir-structures-dstu3 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 73 source files to C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0\hapi-fhir-structures-dstu3\target\test-classes
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ hapi-fhir-structures-dstu3 ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running ca.uhn.fhir.rest.server.RequestValidatingInterceptorDstu3Test
Running ca.uhn.fhir.context.FhirContextDstu3Test
Running ca.uhn.fhir.rest.server.SearchSortDstu3Test
Running ca.uhn.fhir.rest.server.ServerUsingOldTypesDstu3Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.683 sec - in ca.uhn.fhir.rest.server.ServerUsingOldTypesDstu3Test
Running org.hl7.fhir.utilities.xhtml.XhtmlNodeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.178 sec - in org.hl7.fhir.utilities.xhtml.XhtmlNodeTest
Running ca.uhn.fhir.validation.QuestionnaireResponseValidatorDstu3Test
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 24.16 sec - in ca.uhn.fhir.context.FhirContextDstu3Test
Running ca.uhn.fhir.parser.EmptyElementWithExtensionDstu3Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.862 sec - in ca.uhn.fhir.parser.EmptyElementWithExtensionDstu3Test
Running ca.uhn.fhir.util.FhirTerserDstu3Test
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.389 sec - in ca.uhn.fhir.util.FhirTerserDstu3Test
Running ca.uhn.fhir.rest.method.MethodUtilTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.238 sec - in ca.uhn.fhir.rest.method.MethodUtilTest
Running ca.uhn.fhir.rest.client.SearchClientDstu3Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.079 sec - in ca.uhn.fhir.rest.client.SearchClientDstu3Test
Running ca.uhn.fhir.rest.server.ServerMimetypeDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 32.663 sec - in ca.uhn.fhir.rest.server.SearchSortDstu3Test
Running ca.uhn.fhir.model.DateTypeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.32 sec - in ca.uhn.fhir.model.DateTypeTest
Running ca.uhn.fhir.parser.ErrorHandlerTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.057 sec - in ca.uhn.fhir.parser.ErrorHandlerTest
Running ca.uhn.fhir.rest.server.DeleteConditionalDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.534 sec - in ca.uhn.fhir.rest.server.DeleteConditionalDstu3Test
Running ca.uhn.fhir.parser.RoundTripDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.095 sec - in ca.uhn.fhir.parser.RoundTripDstu3Test
Running ca.uhn.fhir.model.ModelDstu3Test
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.721 sec - in ca.uhn.fhir.model.ModelDstu3Test
Running ca.uhn.fhir.context.ModelScannerDstu3Test
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.244 sec - in ca.uhn.fhir.rest.server.ServerMimetypeDstu3Test
Running org.hl7.fhir.dstu3.hapi.validation.ResourceValidatorDstu3Test
Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 2.713 sec - in ca.uhn.fhir.context.ModelScannerDstu3Test
Running ca.uhn.fhir.parser.XmlParserDstu3Test
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 29.62 sec - in ca.uhn.fhir.validation.QuestionnaireResponseValidatorDstu3Test
Running ca.uhn.fhir.rest.server.CreateBinaryDstu3Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.137 sec - in ca.uhn.fhir.rest.server.CreateBinaryDstu3Test
Running ca.uhn.fhir.model.DecimalTypeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in ca.uhn.fhir.model.DecimalTypeTest
Running ca.uhn.fhir.narrative.DefaultThymeleafNarrativeGeneratorDstu3Test
Tests run: 6, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 21.607 sec - in ca.uhn.fhir.narrative.DefaultThymeleafNarrativeGeneratorDstu3Test
Running ca.uhn.fhir.rest.server.SearchWithGenericListDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.634 sec - in ca.uhn.fhir.rest.server.SearchWithGenericListDstu3Test
Running ca.uhn.fhir.context.ContextScanningDstu3Test
Tests run: 93, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 56.457 sec - in ca.uhn.fhir.parser.XmlParserDstu3Test
Running ca.uhn.fhir.rest.server.DateRangeParamSearchDstu3Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.395 sec - in ca.uhn.fhir.context.ContextScanningDstu3Test
Running ca.uhn.fhir.util.XmlUtilDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.195 sec - in ca.uhn.fhir.util.XmlUtilDstu3Test
Running ca.uhn.fhir.rest.server.SearchCountParamDstu3Test
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.059 sec - in ca.uhn.fhir.rest.server.DateRangeParamSearchDstu3Test
Running ca.uhn.fhir.rest.client.NonGenericClientDstu3Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.893 sec - in ca.uhn.fhir.rest.server.SearchCountParamDstu3Test
Running org.hl7.fhir.dstu3.hapi.rest.server.ServerConformanceProviderDstu3Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.083 sec - in ca.uhn.fhir.rest.client.NonGenericClientDstu3Test
Running org.hl7.fhir.dstu3.model.BaseDateTimeTypeDstu3Test
Tests run: 54, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.855 sec - in org.hl7.fhir.dstu3.model.BaseDateTimeTypeDstu3Test
Running org.hl7.fhir.dstu3.utils.FhirPathEngineTest
Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.011 sec - in org.hl7.fhir.dstu3.hapi.rest.server.ServerConformanceProviderDstu3Test
Running ca.uhn.fhir.rest.client.ClientWithCustomTypeDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.918 sec - in ca.uhn.fhir.rest.client.ClientWithCustomTypeDstu3Test
Running ca.uhn.fhir.model.ModelSerializationDstu3Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.803 sec - in org.hl7.fhir.dstu3.utils.FhirPathEngineTest
Running ca.uhn.fhir.rest.server.ValidateDstu3Test
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.08 sec - in ca.uhn.fhir.rest.server.ValidateDstu3Test
Running ca.uhn.fhir.rest.server.CreateDstu3Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.846 sec - in ca.uhn.fhir.model.ModelSerializationDstu3Test
Running ca.uhn.fhir.parser.JsonParserDstu3Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.054 sec - in ca.uhn.fhir.rest.server.CreateDstu3Test
Running ca.uhn.fhir.rest.server.ServerExceptionDstu3Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 93.575 sec - in org.hl7.fhir.dstu3.hapi.validation.ResourceValidatorDstu3Test
Running ca.uhn.fhir.rest.server.InterceptorDstu3Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.251 sec - in ca.uhn.fhir.rest.server.ServerExceptionDstu3Test
Running ca.uhn.fhir.rest.server.MetadataDstu3Test
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 136.921 sec - in ca.uhn.fhir.rest.server.RequestValidatingInterceptorDstu3Test
Running ca.uhn.fhir.parser.CustomTypeDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.051 sec - in ca.uhn.fhir.rest.server.InterceptorDstu3Test
Running z.TestTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.618 sec - in ca.uhn.fhir.rest.server.MetadataDstu3Test
Running ca.uhn.fhir.rest.server.SearchHasParamDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.085 sec - in z.TestTest
Running ca.uhn.fhir.context.RuntimeResourceDefinitionDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.957 sec - in ca.uhn.fhir.rest.server.SearchHasParamDstu3Test
Running ca.uhn.fhir.rest.server.ResponseValidatingInterceptorDstu3Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.581 sec - in ca.uhn.fhir.context.RuntimeResourceDefinitionDstu3Test
Running ca.uhn.fhir.rest.server.UpdateDstu3Test
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.231 sec - in ca.uhn.fhir.parser.CustomTypeDstu3Test
Running ca.uhn.fhir.validation.SchemaValidationDstu3Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.242 sec - in ca.uhn.fhir.rest.server.UpdateDstu3Test
Running ca.uhn.fhir.rest.server.SearchWithServerAddressStrategyDstu3Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.813 sec - in ca.uhn.fhir.rest.server.SearchWithServerAddressStrategyDstu3Test
Running ca.uhn.fhir.rest.server.interceptor.BanUnsupprtedHttpMethodsInterceptorDstu3Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.783 sec - in ca.uhn.fhir.rest.server.interceptor.BanUnsupprtedHttpMethodsInterceptorDstu3Test
Running ca.uhn.fhir.model.IdTypeDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.196 sec - in ca.uhn.fhir.validation.SchemaValidationDstu3Test
Running ca.uhn.fhir.rest.server.UnclassifiedServerExceptionDstu3Test
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.905 sec - in ca.uhn.fhir.model.IdTypeDstu3Test
Running ca.uhn.fhir.rest.server.ReadDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.736 sec - in ca.uhn.fhir.rest.server.ReadDstu3Test
Running ca.uhn.fhir.rest.client.OperationClientDstu3Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.36 sec - in ca.uhn.fhir.rest.server.UnclassifiedServerExceptionDstu3Test
Running ca.uhn.fhir.rest.server.FormatParameterDstu3Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.372 sec - in ca.uhn.fhir.rest.client.OperationClientDstu3Test
Running ca.uhn.fhir.rest.server.OperationServerWithSearchParamTypesDstu3Test
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.666 sec - in ca.uhn.fhir.rest.server.FormatParameterDstu3Test
Running ca.uhn.fhir.rest.server.OperationServerDstu3Test
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.185 sec - in ca.uhn.fhir.rest.server.OperationServerWithSearchParamTypesDstu3Test
Running ca.uhn.fhir.rest.client.GenericClientDstu3Test
Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.821 sec - in ca.uhn.fhir.rest.server.OperationServerDstu3Test
Running ca.uhn.fhir.rest.client.ClientMimetypeDstu3Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.081 sec - in ca.uhn.fhir.rest.client.ClientMimetypeDstu3Test
Running ca.uhn.fhir.validation.FhirInstanceValidatorDstu3Test
Tests run: 35, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.987 sec - in ca.uhn.fhir.rest.client.GenericClientDstu3Test
Tests run: 62, Failures: 0, Errors: 0, Skipped: 7, Time elapsed: 22.077 sec - in ca.uhn.fhir.parser.JsonParserDstu3Test
Tests run: 15, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 25.985 sec - in ca.uhn.fhir.rest.server.ResponseValidatingInterceptorDstu3Test

Results :

Tests run: 510, Failures: 0, Errors: 0, Skipped: 16

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] HAPI-FHIR .......................................... SUCCESS [ 36.312 s]
[INFO] HAPI FHIR - Deployable Artifact Parent POM ......... SUCCESS [  7.676 s]
[INFO] HAPI FHIR - Core Library ........................... SUCCESS [04:47 min]
[INFO] HAPI FHIR - Validation Resources (DSTU3) ........... SUCCESS [ 20.213 s]
[INFO] HAPI Tinder Plugin ................................. SUCCESS [01:56 min]
[INFO] HAPI FHIR Structures - DSTU1 (FHIR v0.80) .......... SUCCESS [02:50 min]
[INFO] HAPI FHIR - Validation Resources (DSTU2) ........... SUCCESS [ 24.163 s]
[INFO] HAPI FHIR Structures - DSTU2 (FHIR v1.0.0) ......... SUCCESS [04:25 min]
[INFO] HAPI FHIR - Minimal Dependency Test - Client ....... SUCCESS [ 39.850 s]
[INFO] HAPI FHIR - Minimal Dependency Test - Server ....... SUCCESS [ 18.574 s]
[INFO] HAPI Tinder Plugin - Test Project .................. SUCCESS [01:01 min]
[INFO] HAPI FHIR Structures - HL7.org DSTU2 ............... SUCCESS [06:39 min]
[INFO] HAPI FHIR Structures - DSTU3 ....................... FAILURE [06:20 min]
[INFO] HAPI FHIR JAX-RS Server ............................ SKIPPED
[INFO] HAPI FHIR JAX-RS Server - Example .................. SKIPPED
[INFO] HAPI FHIR JPA Server ............................... SKIPPED
[INFO] HAPI FHIR TestPage Overlay ......................... SKIPPED
[INFO] HAPI FHIR JPA Server - Example ..................... SKIPPED
[INFO] HAPI FHIR Sample RESTful Server .................... SKIPPED
[INFO] HAPI FHIR Sample RESTful Server - Tests ............ SKIPPED
[INFO] HAPI FHIR - fhirtest.uhn.ca Deployable WAR ......... SKIPPED
[INFO] HAPI FHIR OkHttp Client ............................ SKIPPED
[INFO] HAPI FHIR - Android ................................ SKIPPED
[INFO] HAPI FHIR - Command Line Client - Base Project ..... SKIPPED
[INFO] HAPI FHIR - Command Line Client - Server WAR ....... SKIPPED
[INFO] HAPI FHIR - Command Line Client - Application ...... SKIPPED
[INFO] HAPI FHIR - Distribution Archive ................... SKIPPED
[INFO] HAPI FHIR - Examples (for site) .................... SKIPPED
[INFO] hapi-fhir-base-example-embedded-ws ................. SKIPPED
[INFO] HAPI FHIR - JaCoCo Test Coverage ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30:33 min
[INFO] Finished at: 2016-11-16T03:39:47-05:00
[INFO] Final Memory: 213M/403M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project hapi-fhir-structures-dstu3: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_111\jre\bin\java" -javaagent:C:\\Users\\User\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.7.201606060606\\org.jacoco.agent-0.7.7.201606060606-runtime.jar=destfile=C:\\Users\\User\\Downloads\\hapi-fhir-2.0\\hapi-fhir-2.0\\hapi-fhir-structures-dstu3\\target\\jacoco.exec,dumponexit=true -Dfile.encoding=UTF-8 -Xmx712m -jar C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0\hapi-fhir-structures-dstu3\target\surefire\surefirebooter6999721827998689705.jar C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0\hapi-fhir-structures-dstu3\target\surefire\surefire2580342216570914684tmp C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0\hapi-fhir-structures-dstu3\target\surefire\surefire_258210442200106325432tmp"
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hapi-fhir-structures-dstu3

C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0>
C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0>
C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0>
C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0>
C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0>
C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0>
C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0>
C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0>
C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0>
C:\Users\User\Downloads\hapi-fhir-2.0\hapi-fhir-2.0>

**Comment by jamesagnew** [comment]
I'm closing this ticket, please see the comment here for details: https://github.com/jamesagnew/hapi-fhir/issues/498

If you want to open any more tickets please leave a complete description of what you are trying to accomplish as well as a DETAILED explanation of the steps you have taken, any steps you have taken, etc.
