### ISSUE TITLE
Checking authorization again patient compartment fails with delete operation

### ISSUE THREAD

**Issue by eevaturkka** [jamesagnew/hapi-fhir#503]
The notification for interceptors seems to be too late in the delete sequence as the resource has already been updated with deleted metadata to evaluate the operation and a deleted resouce doesn't have a patient reference so the reference cannot be compared against the patient given in the patient compartment of the ruleset.

**Comment by jamesagnew** [comment]
Thanks for reporting!! Checking in a fix shortly.
