### ISSUE TITLE
Binary resource loses extensions when encoding

### ISSUE THREAD

**Issue by TomasSBerg** [jamesagnew/hapi-fhir#504]
Hey James and friends :o)

As we discussed today in Amsterdam, the Binary resource loses all extensions when it is being encoded by the Parser (only on DSTU2). Have written a test to demonstrate both declared and undeclared extension:

    @Test
    public void testBinaryEncodingWithKnownExtension() {
        LetterTemplate template = new LetterTemplate();
        template.setName(new StringDt("Testname"));
        template.setContentType(new CodeDt("test-type"));

        IParser parser = FhirContext.forDstu2().newJsonParser();
        String resourceToString = parser.encodeResourceToString(template);
        LetterTemplate resource = parser.parseResource(LetterTemplate.class, resourceToString);
        assertNotNull(resource.getContentType());
        assertNotNull(resource.getName());
    }

    @Test
    public void testBinaryEncodingWithUnknownExtension() {
        Binary template = new Binary();
        String extensionURL = "http://www.something.org/StructureDefinition/letter-template";
        ExtensionDt e = new ExtensionDt(false, extensionURL, new StringDt("Testname"));
        template.getUndeclaredExtensions().add(e);
        template.setContentType(new CodeDt("test-type"));

        IParser parser = FhirContext.forDstu2().newJsonParser();
        String resourceToString = parser.encodeResourceToString(template);
        Binary resource = parser.parseResource(Binary.class, resourceToString);
        assertNotNull(resource.getContentType());
        assertFalse((resource.getUndeclaredExtensionsByUrl(extensionURL).isEmpty()));
        assertNotNull(resource.getUndeclaredExtensionsByUrl(extensionURL).get(0));
    }

    @ResourceDef(name = "Binary", id = "letter-template", profile = "http://www.something.org/StructureDefinition/letter-template")
    public static class LetterTemplate extends Binary {

        @Child(name="name")
        @Extension(url="http://example.com/dontuse#name", definedLocally=false, isModifier=false)
        @Description(shortDefinition="The name of the template")
        private StringDt myName;

        public LetterTemplate() {}

        public void setName(StringDt name) {
            myName = name;
        }

        public StringDt getName() {
            return myName;
        }
    }

**Comment by rqg0717** [comment]
I tried to add extension to a Binary and got:
```
java.lang.NoClassDefFoundError: org/hl7/fhir/instance/model/api/IBaseDatatype
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
	at java.lang.Class.getMethod0(Class.java:3010)
	at java.lang.Class.getMethod(Class.java:1776)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.hl7.fhir.instance.model.api.IBaseDatatype
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Exception in thread "main" 
```
I checked the class IBaseDatatype and realized the class is incomplete [here](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/org/hl7/fhir/instance/model/api/IBaseDatatype.java)

**Comment by jamesagnew** [comment]
Hi Tomas,

I did some digging into this one today, and I realized why.. Binary is actually not allowed to have extensions, per FHIR's rules.

The parser should probably emit a warning, so I'll get it to do that though...
