### ISSUE TITLE
Referenced Included Resources are lost in HAPI 2.1

### ISSUE THREAD

**Issue by TomasSBerg** [jamesagnew/hapi-fhir#505]
Hey James and friends

When trying out the new HAPI 2.1 here in Amsterdam, we found that the .setResource method on References (both DSTU2 and STU3) no longer makes the resource survive an encoding/parsing. It use to use the contained-list in the resources, but as we discussed, the bundle is probably the right place for the included resource. 
I guess that might cause some confusion regarding what to do when you want to save a contained resource. Maybe it's best to just manually add the resource to the contained list in that case?

Anyway, here is a test that shows that a reference resource is not added to the bundle:

public void testIncludeResourceWhenEncoding() {
        Condition condition = new Condition();
        condition.setId("condition1");
        Goal goal = new Goal();
        goal.setId("Goal1");
        ResourceReferenceDt resourceReferenceDt = new ResourceReferenceDt(condition);
        goal.setAddresses(Collections.singletonList(resourceReferenceDt));

        Bundle bundle = new Bundle();
        Bundle.Entry entry = bundle.addEntry();
        entry.setResource(goal);

        IParser parser = FhirContext.forDstu2().newJsonParser();

        String resourceToString = parser.encodeResourceToString(bundle);
        Bundle parsedBundle = parser.parseResource(Bundle.class, resourceToString);
        assertEquals(2, parsedBundle.getEntry().size());
    }

**Comment by jamesagnew** [comment]
Hi Thomas,

I'm wondering if this is caused by the bundle inclusion rule.. Are you experiencing this on a HAPI server? If so, can you try setting the inclusion rule by calling

`myRestfulServer#setBundleInclusionRule(BundleInclusionRuleEnum.BASED_ON_RESOURCE_PRESENCE);`
