### ISSUE TITLE
In DSTU2 Location, type and physicalType are reverse

### ISSUE THREAD

**Issue by rqg0717** [jamesagnew/hapi-fhir#508]
According to [Location](https://www.hl7.org/fhir/location.html), type is defined as [ServiceDeliveryLocationRoleType](https://www.hl7.org/fhir/v3/ServiceDeliveryLocationRoleType/index.html) and physicalType is defined as [LocationType](https://www.hl7.org/fhir/valueset-location-physical-type.html); however, in ca.uhn.fhir.model.dstu2.resource.Location:
```
/**
     * Sets the value(s) for <b>type</b> (class)
     *
     * <p>
     * <b>Definition:</b>
     * Indicates the type of function performed at the location
     * </p> 
     */
	public Location setType(LocationTypeEnum theValue) {
		setType(new BoundCodeableConceptDt<LocationTypeEnum>(LocationTypeEnum.VALUESET_BINDER, theValue));

		return this;
	}
...
     /**
      * Sets the value(s) for <b>physicalType</b> (class)
      *
     * <p>
     * <b>Definition:</b>
     * Physical form of the location, e.g. building, room, vehicle, road
     * </p> 
	 */
	public Location setPhysicalType(CodeableConceptDt theValue) {
		myPhysicalType = theValue;
		return this;
	}
```
They are reversed.

**Comment by james-answer** [comment]
I have also just had a problem with this, the PhysicalType should be bound to the LocationTypeEnum rather than the Type element.
