### ISSUE TITLE
JPA server performs unnecessary update for conditional creates with one match

### ISSUE THREAD

**Issue by visceroid** [jamesagnew/hapi-fhir#509]
I wanted to perform a conditional create on the resource Encounter as a part of a transaction. The condition is on Encounter.identifier with an exact match. I put in the related information in Bundle.entry.request according to the specification: "method":"POST", "url":"Encounter", "ifNoneExist":"identifier={mysystem}|{myidentifier}" (parameter value is url encoded).
When I submit the transaction, the server found one match with a previously created Encounter having the identifier; however, it then proceeds to update the resource, kindof "silently" (content is changed to what is in Bundle.entry.resource, but no new version created and no new entry in history), which is inconsistent with the specification since it states: in the case of "One Match: The server *ignore* the post and returns 200 OK".
The status and location in returned response are as expected (200 OK and relative url of the Encounter, with version unchanged).
I'm using 2.1-SNAPSHOT version of hapi-fhir-base and hapi-fhir-jpaserver-base as server, 2.1 release version of hapi-fhir-base and hapi-fhir-structures-dstu3 as client. The FHIR version is DSTU3.

**Comment by jamesagnew** [comment]
Just realized this bug was fixed back in February, but this issue was never closed. The fix is in HAPI FHIR 2.3.

See this discussion for details: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/hapi-fhir/WtwD5kJzcVw/f49eP_TrBwAJ
