### ISSUE TITLE
:contains modifier not working

### ISSUE THREAD

**Issue by patrick-werner** [jamesagnew/hapi-fhir#512]
I just tested the :contains modifier on our HAPI 2.1 JPA Example server:
https://fhir.gecko.hs-heilbronn.de/
It doesn't seem to work, neither with name:contains or family:contains or given:contains. The behaviour is the same like without a modifier. 
( the :exact modifier is working)

**Comment by patrick-werner** [comment]
Update 24.1.2018:
I just tested the issue with HAPI FHIR Server - 3.1.0.

- Every string search seems to use :contains by default now.
- :exact has no effect, still searching anywhere in the String
- no modifier doesn't search at the start of a String, it searches anywhere

**Comment by anthonys123** [comment]
I've identified and implemented fixes for this issue.  I will create a pull request for the next HAPI release.

**Comment by jamesagnew** [comment]
Closing, as this has been merged. Woohoo!
