### ISSUE TITLE
dstu2 - HAPI 2.0 validate fixed code not working

### ISSUE THREAD

**Issue by allanbrohansen** [jamesagnew/hapi-fhir#513]
Hi James
At DevDays I (somewhat together with you) tried to create a structure definition for Flag.
My first issue:
I want flag.status to be fixed to "active". I create a structure defintition using Forge with the differential being (removed the mapping part):

```
    <element>
      <path value="Flag.status" />
      <short value="active | inactive | entered-in-error" />
      <definition value="Supports basic workflow." />
      <min value="1" />
      <max value="1" />
      <base>
        <path value="Flag.status" />
        <min value="1" />
        <max value="1" />
      </base>
      <type>
        <code value="code" />
      </type>
      <fixedCode value="active" />
      <isModifier value="true" />
      <isSummary value="true" />
      <binding>
        <strength value="required" />
        <description value="Indicates whether this flag is active and needs to be displayed to a user, or whether it is no longer needed or entered in error." />
        <valueSetReference>
          <reference value="http://hl7.org/fhir/ValueSet/flag-status" />
        </valueSetReference>
      </binding>
    </element>
```

I now expect Hapi to validate this via:
        IParser iParser = FhirContext.forDstu2Hl7Org().newXmlParser();
        StructureDefinition flagStructureDefinition = iParser.parseResource(StructureDefinition.class, getFlagStructureDefinition());

        FhirInstanceValidator instanceValidator = new FhirInstanceValidator();
        instanceValidator.setStructureDefintion(flagStructureDefinition);

        FhirValidator validator = FhirContext.forDstu2().newValidator();
        validator.registerValidatorModule(instanceValidator);

        ValidationResult result = validator.validateWithResult(flag);

But this does not work ("inactive" is accepted) - and I cannot see any attempts in the code to handle the fixed code (or any kind of fixed value).
Is this a bug or am I missing something?

**Comment by aberge** [comment]
Hello.
I have the same issue when I try to validate with a custom structure definition for DSTU3 resources. Although constraints on cardinality, fixedCode are added via the differential elements, the validator does not report any error related to those constraints.

StructureDefinition snippet is provided below.

 <baseDefinition value="http://hl7.org/fhir/StructureDefinition/HealthcareService" />
  <derivation value="constraint" />
  <differential>
    <element id="HealthcareService.type">
      <path value="HealthcareService.type" />
      <min value="1" />
    </element>
    <element id="HealthcareService.name">
      <path value="HealthcareService.name" />
      <min value="1" />
    </element>
  </differential>

I do reference this structure definition when creating the validator:

        PrePopulatedValidationSupport valSupport = new PrePopulatedValidationSupport();
        DefaultProfileValidationSupport defaultSupport = new DefaultProfileValidationSupport();
        ValidationSupportChain support = new ValidationSupportChain(valSupport, defaultSupport);
        valSupport.addStructureDefinition(structureDefinition);
        FhirContext context = FhirContextProvider.instance();
        FhirValidator customStructureDefValidator = context.newValidator();
        FhirInstanceValidator fhirInstanceValidator = new FhirInstanceValidator();
        fhirInstanceValidator.setStructureDefintion(structureDefinition);
        fhirInstanceValidator.setValidationSupport(support);
        customStructureDefValidator.registerValidatorModule(fhirInstanceValidator);

Is there a bug or did I miss something when configuring the validator ?
