### ISSUE TITLE
Bundle's entries are not marshalled according to their profile

### ISSUE THREAD

**Issue by rshnaper** [jamesagnew/hapi-fhir#515]
FHIR HAPI Version: 1.6, DSTU2

When POSTing a bundle to FHIR Server, the resulting Bundle entries are created with improper types. For example using below bundle will generate an entry of type *org.hl7.fhir.instance.model.Patient* instead of the required *ca.cihi.nsir.fhir.model.Patient*
```
<Bundle xmlns="http://hl7.org/fhir">
    <type value="transaction"/>
    <entry>
        <fullUrl value="Patient/1"/>
        <resource>
            <Patient xmlns="http://hl7.org/fhir">
                <meta>
                    <profile value="http://cihi.ca/fhir/StructureDefinition/rad-patient"/>
                </meta>
                <gender value="female"/>
            </Patient>
        </resource>
    </entry>
</Bundle>
```

Custom Patient resource class definition:
```
@ResourceDef(id="rad-patient", name="Patient", profile="http://cihi.ca/fhir/StructureDefinition/rad-patient")
public class Patient extends org.hl7.fhir.instance.model.Patient {}
```

Looking at the  [ParserState.java](https://github.com/jamesagnew/hapi-fhir/blob/80350a52ec9cef6ed0db2b173f3e286e97c6eb17/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/ParserState.java#L1673) implementation, the actual resource type is being set to null, can this be the cause of the issue?

**Comment by jamesagnew** [comment]
Hi @rshnaper - Have you registered the profile URL against the FhirContext via the `FhirContext#setDefaultTypeForProfile` method? You'd need to do that for this to work.

**Comment by rshnaper** [comment]
Got it! Thanks @jamesagnew, didn't realize FhirContext had this functionality.

**Comment by jamesagnew** [comment]
You're not the only one. I think we need to improve our docs in this area. :)
