### ISSUE TITLE
STU3 issues with /metadata

### ISSUE THREAD

**Issue by effad** [jamesagnew/hapi-fhir#519]
http://fhirtest.uhn.ca/baseDstu3/metadata seems to have a few issues:

- It still delivers "resourceType": "Conformance", but should deliver "CapabilityStatement"
- searchParam "_id" is listed twice (with slightly different documentation)
- searchParam "_id" is given as type "string", but according to http://hl7.org/fhir/2016Sep/searchparameter-registry.html it should by type "token"

**Comment by jamesagnew** [comment]
Thanks for reporting! Will check in a fix shortly
