### ISSUE TITLE
#305 has regressed

### ISSUE THREAD

**Issue by jimsteel** [jamesagnew/hapi-fhir#521]
#305 (updates with conflicting IDs in the URL and the resource body) seems to have regressed.

**Comment by jamesagnew** [comment]
Argh.. Proper handling for this situation has gone back and forth a fair bit. I can't find the reference right now but IIRC back in May the FHIR-I group voted that updates should ignore incorrect IDs. It appears that this has gone back.

One way or the other, I'd agree this is a bug. Fixing now.
