### ISSUE TITLE
IServerInterceptor.incomingRequestPreHandled gets called twice when serving single request

### ISSUE THREAD

**Issue by mattiuusitalo** [jamesagnew/hapi-fhir#532]
We are using hapi-fhir-jpaserver-base/2.1 currently. When a request is handled, first this happens.
![image](https://cloud.githubusercontent.com/assets/24521829/21498984/833f0f30-cc3a-11e6-83ee-74f63b547492.png)

After ProfileInterceptor handles the request it goes to resource providers which call all the registered IServerInterceptors again, like so:
![image](https://cloud.githubusercontent.com/assets/24521829/21498988/8802a2f2-cc3a-11e6-9202-dc76495fc511.png)

Our code is based on the JPA server example. Is this normal? How can we avoid our IServerInterceptors processing the same requests twice?

**Comment by jamesagnew** [comment]
Hi @mattiuusitalo : Thanks for reporting!

I was able to reproduce this in a unit test.. A few things:

* Do you have your interceptor registered with both the RestfulServer and the DaoConfig, or just the DaoConfig? If you have it against both, you'll always get a double call. I should probably make this clear in the documentation. Will fix.
* Even if you only have the interceptor registered against the RestfulServer you'll still get a double call if your client performs a FHIR `transaction` operation. Will fix.

**Comment by mattiuusitalo** [comment]
We are registering the interceptors with RestfulServer.registerInterceptor method. As far as I know they are only registered against the Restfulserver.
