### ISSUE TITLE
JSON parser is dropping referenced contained resources

### ISSUE THREAD

**Issue by stefan-evinance** [jamesagnew/hapi-fhir#537]
Potentially related to https://github.com/jamesagnew/hapi-fhir/issues/505

We have a resource which references another resource (3 levels down), The referenced resource itself has contained resources which are referenced within it. When we try to serialize the top level resource the contained resources of the referenced resource are lost, while the references to them are kept.

If we manually move the contained resources from the referenced resource to the top level resource then after serialization the contained resources appear 3 times in the JSON output (with the same id).

**Comment by jamesagnew** [comment]
Thanks for reporting!

Any chance you have a code sample that shows how the resource is built?

**Comment by jamesagnew** [comment]
Fyi I had a go at reproducing this and I was unable to. If you look at commit https://github.com/jamesagnew/hapi-fhir/commit/ea27689a4040b275627fb0c69e03422919aa3e66 maybe you can see what is different about my test?

**Comment by stefan-evinance** [comment]
@jamesagnew thanks for looking into it. In our case we have RequestGroup with contained resources which are added as references (but not throught the setResource() method). This RequestGroup is then added as  action resource to another RequestGroup and finally this RequestGroup is added as result reference to a GuidanceResponse. When we serialize the GuidanceResponse created in this way the RequestGroup still has its references (the "id" string) but the actual contained resources are not moved up to the GuidanceResponse. If we add the resources directly to the GuidanceResponse instead of the child RequestGroup (a hack) then when the GuidanceResponse is serialized the contained resources are duplicated.
