### ISSUE TITLE
Performing an interaction on an unknown FHIR resource results in 400, not 404 as per FHIR spec

### ISSUE THREAD

**Issue by CarthageKing** [jamesagnew/hapi-fhir#539]
Hi,

When performing an interaction against an unknown resource (e.g. [baseurl]/Patent) (i.e. Patient that was misspelled), HAPI will return 400 instead of 404. AEGIS Touchstone thinks FHIR servers should return 404 in these cases, probably because of the following:
http://hl7.org/fhir/2017Jan/http.html#create
```
404 Not Found - resource type not supported, or not a FHIR end-point
```
also in http://hl7.org/fhir/2017Jan/http.html#2.44.0.10.1.

I would think that in RestfulServer.determineResourceMethod(), changing "if(resourceBinding==null)" to throw a ResourceNotFoundException instead of an InvalidRequestException should solve this problem.

```java
		} else {
			resourceBinding = myResourceNameToBinding.get(resourceName);
			if (resourceBinding == null) {
				throw new InvalidRequestException("Unknown resource type '" + resourceName + "' - Server knows how to handle: " + myResourceNameToBinding.keySet());
			}
		}
```

Tested with HAPI 2.2 and master.

Best Regards,

**Comment by jamesagnew** [comment]
Hi @CarthageKing , thanks for the PR! Looks good, merging it now.
