### ISSUE TITLE
Generate narrative of Composition in Bundle: resolve references?

### ISSUE THREAD

**Issue by robertvdl** [jamesagnew/hapi-fhir#541]
Hi James,

we're using HAPI 2.1 to create a bundle that contains several resources. We're using the CustomThymeleafNarrativeGenerator with our own templates to let HAPI generate the Narrative of all the resource inside the bundle. For our use case the Narrative of the Composition is the most important one, and we would like this Narrative to represent the Composition as a whole (including the Resources in the Bundle it refers to), so that it represents the full message we're sending. Moreover, in our case the Composition provides the context for all the other Resources within the Bundle.

The CustomThymeleafNarrativeGenerator when encountering a Reference in the Composition, for example the .subject that refers to a Patient, just renders that Reference as an ID, not the Narrative of the Resource it refers to. This is just as we would expect Thymeleaf handle this, but it results in a Narrative that is not fit for human consumption. We can not expect a human reader to 'resolve' the Reference by id and the generate HTML also does not allow for automatic resolving of that ID to a Resource.

What is the best way to handle this? I first thought of adding a pre-filled Narrative to the Reference, but that is against the FHIR prescriptions.

Best,
Robert.

**Comment by robertvdl** [comment]
We're having some progress in our understanding of a Composition's Narrative. We read this in the Fhir documentation (https://www.hl7.org/fhir/documents.html#presentation)

> When the document is presented for human consumption, applications must present the collated narrative portions in order:
> 
>     The Composition resource Narrative
>     The subject resource Narrative
>     The section.text Narratives

This means the Patient and Section Narratives should not be included in the Composion's narrative. 

This leaves us with the problem that within the Composition template we only have access to the references in the Composition, not to the referred Resources in the Bundle, and we cannot render data from those Resources in the Composition Narrative.

I guess we'll have to pre-fill the Composition's Narrative with our desired narrative. I don't see how we could use the NarrativeGenerator to directly generate a Composition narrative for us the way we want, but i'm open to any suggestion.

**Comment by fer8a** [comment]
I'm having the same doubt myself. I need to extend the current templates to be able to display a bundle (and its references) in a human-readable way.

Also I'd like to share my templates with the community and add them to the repository maybe. That way people implementing custom templates for resources don't have to start from scratch.
