### ISSUE TITLE
Reference resource in bundle entry by UUID via fullURL does not work

### ISSUE THREAD

**Issue by jodue** [jamesagnew/hapi-fhir#544]
I am currently trying to process a bundle which contains a DocumentReference resource that has an author which is a reference to another resource in this bundle (another entry) and the reference is done by UUID. 

`<DocumentReference>
...
   <author><reference value="urn:uuid:c7ed89ea-e167-4fab-876c-93d535cb0553" /></author>
...
</DocumentReference>`

and

`<entry>
   <fullUrl value="urn:uuid:c7ed89ea-e167-4fab-876c-93d535cb0553" />
   <resource>
      <Practitioner>...</Practitioner>
   </resource>
   ...
</entry>`

As far as i can see in the FHIR standard this should be correct (see example in https://www.hl7.org/FHIR/bundle.html#references) but the parser in HAPI-FHIR does not resolve the author resource properly. I had a look in the code in ParserState.stitchBundleCrossReferences which should handle this and it seems that this kind of references are currently not supported/implemented by HAPI-FHIR.

See also example bundle in the attachement.

[Bundle.txt](https://github.com/jamesagnew/hapi-fhir/files/723067/Bundle.txt)

**Comment by jamesagnew** [comment]
Thanks for reporting! This is going to be a pain to fix.. :) but I agree it should be stitching these.

**Comment by jodue** [comment]
Great, thank you for the fast answer! If i can help (also by contributing code) i am more than willing. Just let me know.

**Comment by jamesagnew** [comment]
Hey @jodue , I actually only saw your reply after already having fixed this. The root cause was an issue I've wanted to fix for a while (IdType/IdDt parsing placeholder IDs into a prefix and a root when it should actually treat them as an opaque string) so I dove in and corrected all of that.

If you're interested in getting involved in other parts of the code base, naturally we would welcome any help you want to offer! :)

**Comment by jodue** [comment]
Perfect! Thanks again for fixing this so fast!

I am working on a project where we utilize the HAPI-FHIR library and since we just started we probably will find other areas where we want to fix/improve code. I already saw that at least one other person from my company (Agfa Healthcare) contributed code to this library in the past.

**Comment by jamesagnew** [comment]
Oh cool! Yeah, we've had some really cool contributions out of your company.

Glad to hear we have another team from AGFA using HAPI now :)
