### ISSUE TITLE
Post to DSTU3 

### ISSUE THREAD

**Issue by jeffeastman** [jamesagnew/hapi-fhir#557]
When I post this to http://localhost:8080/fhir/baseDstu3: 

Sending 'POST' request to URL: http://localhost:8080/fhir/baseDstu3/Organization
{
  "resourceType": "Organization",
  "identifier": [
    {
      "use": "official",
      "system": "http://www.hl7.org/oid/",
      "value": "1.2.3.4.3013"
    },
    {
      "use": "official",
      "type": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/v2/0203",
            "code": "TAX",
            "display": "Tax ID number"
          }
        ],
        "text": "US Employer Identification Number"
      },
      "system": "http://hl7.org/fhir/sid/us-tax",
      "value": "000003013"
    }
  ],
  "active": true,
  "name": "Windward General Hospital",
  "telecom": [
    {
      "system": "phone",
      "value": "(989) 555-5275",
      "use": "work"
    }
  ],
  "address": [
    {
      "line": [
        "677 E Potomac Street"
      ],
      "city": "Stanton",
      "district": "Montcalm County",
      "state": "MI",
      "postalCode": "48888"
    }
  ]
}

I get back this, but the OperationOutcome has a null id. According to the FHIR spec it should just be returning a Location: [base]/[type]/[id]/_history/[vid]. That information is buried inside of the <div> but it isn't very easy to get to. Am I missing something?:

Response Code : 201

{  "resourceType": "OperationOutcome",  "text": {    "status": "generated",    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">INFORMATION</td><td>[]</td><td><pre>Successfully created resource &quot;Organization/1/_history/1&quot; in 994ms</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"  },  "issue": [    {      "severity": "information",      "code": "informational",      "diagnostics": "Successfully created resource \"Organization/1/_history/1\" in 994ms"    }  ]}

**Comment by jamesagnew** [comment]
Hi Jeff,

I'm having a bit of trouble reading the ticket as the formatting is a bit wonky, but when you POST (aka create) a resource to the server, you should get back a header along the lines of:
```http
Location: http://fhirtest.uhn.ca/baseDstu3/Organization/123/_history/1
```

Is that not happening?

**Comment by jeffeastman** [comment]
No, it didn’t. Now, I’m not using the HAPI client methods, but POSTing is returning an OperationOutcome. But should I be looking in the result header instead?

Reason I’m not using the HAPI client methods is I can’t figure out how. Is there any good documentation on this? Also, to talk to the MiHIN server I need to use OAuth and I can’t figure out if thats even supported by the HAPI client.

Jeff

**Comment by jeffeastman** [comment]
OK, its in the header not in the returned OperationOutcome.  I’ll close the issue.

Thanks,
Jeff

**Comment by jeffeastman** [comment]
This was Pilot Error so closing

**Comment by jamesagnew** [comment]
hehe cool :)
