### ISSUE TITLE
Why are choice fields of different types using the same attribute?

### ISSUE THREAD

**Issue by stefan-evinance** [jamesagnew/hapi-fhir#559]
For instance, an Observation has valueQuantity, valueCodeableConcept, etc. according to all the choices in FHIR, while HAPI-FHIR has one attribute for all of them (protected Type value;) and then the addChild method checks for the original FHIR field name and maps it to a type. Why not have an attribute  for each type?

**Comment by jamesagnew** [comment]
Choices in FHIR itself don't allow you to mix types. I'm not sure what would be the benefit of having separate fields for valueQuantity and valueCodeableConcept if FHIR only allows one to be populated at any given moment?

**Comment by stefan-evinance** [comment]
The benefit for our use case would be when populating the mustSupport field of a DataRequirement. There we are required to provide the path to an element, and in the case of choice fields we can't infer the path from the field name (because the field name in HAPI-FHIR is "value" while in FHIR it would be "valueQuantity" for example).

**Comment by jamesagnew** [comment]
I'm not sure I follow. Why would you need to infer the path name from the field name? HAPI's parser does this automatically... And if you had separate fields for the different types, a user might put a value in both which is illegal in FHIR.

**Comment by stefan-evinance** [comment]
HAPI's parser does it when deserializing resources. If we have a HAPI-FHIR resource and want to create a DataRequirement indicating that certain fields for the resource are used then we need to manually construct the path (or does HAPI-FHIR have such facility?) to these fields and add the resulting string to the mustSupport field of DataRequirement.

Say we have an Observation resource with field "value" of type Quantity. We want to create a DataRequirement which communicates to an external system that we are interested in this Observation. We create a new DataRequirement, set the type to "Observation". Now how do we indicate that a value of type Quantity is used? My understanding is that we need to put "valueQuantity" in mustSupport. But by looking at the Observation resource in HAPI-FHIR the field name is "value" not "valueQuantity". So we need to map field name + type to FHIR field name in order to get the path.

**Comment by jamesagnew** [comment]
Can you post a code sample that shows what isn't working the way you expect it to? I'm still not getting it.

**Comment by stefan-evinance** [comment]
```
		Observation test = new Observation();
		test.setValue(new Quantity(43));
		DataRequirement dr = new DataRequirement(new CodeType(test.fhirType()));
		List<StringType> mustSupport = new ArrayList<StringType>();
		for (Field field : test.getClass().getDeclaredFields()) {
			for (Child child : field.getAnnotationsByType(Child.class)) {
				List<Base> result;
				try {
					result = test.listChildrenByName(child.name());
					if (result != null && !result.isEmpty()) {
						mustSupport.add(new StringType(child.name()));
					}
				} catch (FHIRException e) {
					e.printStackTrace();
				}
			}
		}
		dr.setMustSupport(mustSupport);
		FhirContext ctx = FhirContext.forDstu3();
		IParser parser = ctx.newJsonParser().setPrettyPrint(true);
		List<DataRequirement> drList = new ArrayList<DataRequirement>();
		drList.add(dr);
		GuidanceResponse response = new GuidanceResponse();
		response.setDataRequirement(drList);
		String jsonObservation = parser.encodeResourceToString(response);
		System.out.println(jsonObservation);
```

Note that the alternative (getting the children() of the resource and taking the Property name for all properties that have value) also renders wrong path ("value[x]" instead of "valueQuantity"). We need a way to get the correct FHIR path for all fields which have values.

**Comment by jamesagnew** [comment]
Ahhhhh ok I'm getting it now.

For this type of thing, you actually shouldn't be using field names anyhow. They will align to the FHIR element names for the built structures as they exist today, but the intent is not that this is a hard and fast rule. The model has annotations that describe the element names, and HAPI builds up an internal metamodel of these.

I believe the following code achieves exactly what you're after:

```java
        Observation test = new Observation();
        test.setValue(new Quantity(43));
        DataRequirement dr = new DataRequirement(new CodeType(test.fhirType()));
        List<StringType> mustSupport = new ArrayList<StringType>();
        
        FhirContext ctx = FhirContext.forDstu3();
        RuntimeResourceDefinition resDef = ctx.getResourceDefinition(Observation.class);
        for (BaseRuntimeChildDefinition nextChildElement : resDef.getChildren()) {
            for (String nextChildName : nextChildElement.getValidChildNames()) {
                mustSupport.add(new StringType(nextChildName));
            }
        }
        
        dr.setMustSupport(mustSupport);
        IParser parser = ctx.newJsonParser().setPrettyPrint(true);
        List<DataRequirement> drList = new ArrayList<DataRequirement>();
        drList.add(dr);
        GuidanceResponse response = new GuidanceResponse();
        response.setDataRequirement(drList);
        String jsonObservation = parser.encodeResourceToString(response);
        System.out.println(jsonObservation);
```

This produces the following output:

```json
{
  "resourceType": "GuidanceResponse",
  "dataRequirement": [
    {
      "type": "Observation",
      "mustSupport": [
        "id",
        "meta",
        "implicitRules",
        "language",
        "text",
        "contained",
        "extension",
        "modifierExtension",
        "identifier",
        "status",
        "category",
        "code",
        "subjectResource",
        "subject",
        "encounterResource",
        "encounter",
        "effectivePeriod",
        "effectiveDateTime",
        "issued",
        "performer",
        "performerResource",
        "valueCodeableConcept",
        "valueRatio",
        "valueTime",
        "valueAttachment",
        "valueString",
        "valueRange",
        "valueSampledData",
        "valuePeriod",
        "valueDateTime",
        "valueQuantity",
        "dataAbsentReason",
        "interpretation",
        "comment",
        "bodySite",
        "method",
        "specimenResource",
        "specimen",
        "deviceResource",
        "device",
        "referenceRange",
        "related",
        "component"
      ]
    }
  ]
}
```

If you only want the `value[x]` field's candidate names, the code would look like this:

```java
        RuntimeResourceDefinition resDef = ctx.getResourceDefinition(Observation.class);
        BaseRuntimeChildDefinition childElement = resDef.getChildByName("value[x]");
         for (String nextChildName : childElement.getValidChildNames()) {
             mustSupport.add(new StringType(nextChildName));
         }
```

**Comment by stefan-evinance** [comment]
Thanks, but what we need is the path to fields which have values. The code above just gives us the path for all fields. If we try "test.getChildByName(nextChildName);" for "valueQuantity" it returns null. So how do we filter the list above to include only fields that are populated for the given Observation?

**Comment by jamesagnew** [comment]
```java
		Observation test = new Observation();
		test.setValue(new Quantity(43));
		DataRequirement dr = new DataRequirement(new CodeType(test.fhirType()));
		List<StringType> mustSupport = new ArrayList<StringType>();

		FhirContext ctx = FhirContext.forDstu3();
		RuntimeResourceDefinition resDef = ctx.getResourceDefinition(Observation.class);
		for (BaseRuntimeChildDefinition nextChildElement : resDef.getChildren()) {
			if (nextChildElement.getAccessor().getValues(test).size() > 0) {
				String childName = nextChildElement.getChildNameByDatatype(nextChildElement.getAccessor().getValues(test).get(0).getClass());
				mustSupport.add(new StringType(childName));
			}
		}

		dr.setMustSupport(mustSupport);
		IParser parser = ctx.newJsonParser().setPrettyPrint(true);
		List<DataRequirement> drList = new ArrayList<DataRequirement>();
		drList.add(dr);
		GuidanceResponse response = new GuidanceResponse();
		response.setDataRequirement(drList);
		String jsonObservation = parser.encodeResourceToString(response);
		System.out.println(jsonObservation);
```
