### ISSUE TITLE
org.hl7.fhir.dstu2016may.hapi.validation.DefaultProfileValidationSupport - Unable to load profiles

### ISSUE THREAD

**Issue by lawley** [jamesagnew/hapi-fhir#567]
The log message is:
`org.hl7.fhir.dstu2016may.hapi.validation.DefaultProfileValidationSupport - Unable to load resource: /org/hl7/fhir/instance/model/dstu3/profile/profiles-resources.xml`

The problem seems to be the `dstu3` in the path which should instead be `dstu2016may`

**Comment by jamesagnew** [comment]
PR merged in. Thanks for the contribution!
