### ISSUE TITLE
Custom Validator - IValidationSupport

### ISSUE THREAD

**Issue by jasnajayaraj** [jamesagnew/hapi-fhir#570]
I created a new Profile for Contract and published the same in Simplifier.net .But Iam finding issues in using that for Profile for validations .Any pointers to do the same would be helpful.

Regards
Jasna

**Comment by jamesagnew** [comment]
Hi Jasna,

Please use our Google Group to ask questions on how to use HAPI, the issue trtacker is for reporting bugs and suggesting features.
