### ISSUE TITLE
How to support text matching operation for searching

### ISSUE THREAD

**Issue by baopingle** [jamesagnew/hapi-fhir#577]
Hi,
  How the HAPI fhir server support the text matching operation? For example, if I want to search all the reports which observation text contains "abc", is there any example?

**Comment by jamesagnew** [comment]
Hi @baopingle, please use our Google Group or Zulip to ask questions on how FHIR works.

See our FAQ for more information: http://hapifhir.io/hapi-fhir-faq.html
