### ISSUE TITLE
Supply requestDetails (or some collection) to Resourceproviders - Hapi 2.2

### ISSUE THREAD

**Issue by allanbrohansen** [jamesagnew/hapi-fhir#579]
Hi
Currently Hapi only lets interceptors know about the request headers (via the RequestDetails object).
The resourceprovider are only given the request body (for PUT/POST) as a ressource), or the query parameters (for GET) as search parameters.
I have scenarios where the username (part of the requestHeader - basic authentication) is needed for both PUT, POST, GET.

I think in general it would be nice for the resourceProvider to have access to the requestDetails, or maybe even better: for the interceptors to be able to add information to some generic Object, and supply this object to the resource provider (getUserData of the requestDetails seems to be designed to be that object).

Right now I get by by doing the following:
for PUT/POST: an interceptor adds a (secret) metatag to the resource (not terrible wrong/ugly)
for Search: an intercceptor adds an extra optional parameter to the search, and removes it again later  (very ugly)

My request can probably be achieved in many ways; one way to do it:
1) add support for an @IncludeRequestDetails annotation at the resourceprovider methods
2) if @IncludeRequestDetails is set: call the resourceProvider method with this as its first argument

I can see that some effort has already been made to support this in RequestDetails#getUserData, so maybe I am missing something? 

The Javadoc for RequestDetails#getUserData:
/**
	 * Returns a map which can be used to hold any user specific data to pass it from one
	 * part of the request handling chain to another. Data in this map can use any key, although
	 * user code should try to use keys which are specific enough to avoid conflicts.
	 * <p>
	 * A new map is created for each individual request that is handled by the server,
	 * so this map can be used (for example) to pass authorization details from an interceptor
	 * to the resource providers, or from an interceptor's {@link IServerInterceptor#incomingRequestPreHandled(RestOperationTypeEnum, ca.uhn.fhir.rest.server.interceptor.IServerInterceptor.ActionRequestDetails)} 
	 * method to the {@link IServerInterceptor#outgoingResponse(RequestDetails, org.hl7.fhir.instance.model.api.IBaseResource, javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)}
	 * method.  
	 * </p>
	 */
	public Map<Object, Object> getUserData() {

Br Allan

**Comment by jamesagnew** [comment]
Hi Allan,

You can include a RequestDetails parameter on your resource provider methods if you want. The server will populate that for you automatically. You can also include a parameter of type `HttpServletRequest` if it's just the headers you want.

**Comment by allanbrohansen** [comment]
Ha, fantastic - the feature was already there, and even more elegant/simple that I suggested :-).

I couldn't find it this on http://hapifhir.io/doc_rest_operations.html though - maybe it isn't there and I just didn't see it  - otherwise I would suggest adding information about the feature.
Thx
Br Allan
