### ISSUE TITLE
Connecting to external Resource Server

### ISSUE THREAD

**Issue by hareemmughis** [jamesagnew/hapi-fhir#580]
As mentioned in blog, I am changing the daoConfig() function in FhirServerConfig.java file to following way:

@Bean()
	public DaoConfig daoConfig() {
	        DaoConfig retVal = new  #DaoConfig();
	        retVal.setSubscriptionEnabled(true);
	        retVal.setSubscriptionPollDelay(5000);
	        retVal.setSubscriptionPurgeInactiveAfterMillis(DateUtils.MILLIS_PER_HOUR);
	        retVal.setAllowMultipleDelete(true);
                // Allow external references
                retVal.setAllowInlineMatchUrlReferences(true);
               // If you are allowing external references, it is recommended to
                // also tell the server which references actually will be local
                retVal.getTreatBaseUrlsAsLocal().add("http://fhirtest.uhn.ca/baseDstu1");
		return retVal;
	}

But it is still not accessing the http://fhirtest.uhn.ca/baseDstu1 for searching the resource. Am I doing it wrong or does this configuration is for only creating and updating the resource in external server?

**Comment by jamesagnew** [comment]
All this setting means is that you'll be allowed tio create resources with links to external servers, not that indexing will search across external servers.

Indexing across servers would be really hard to do efficiently, I'm not sure I can see a way to do that.

**Comment by hareemmughis** [comment]
Okay, i am trying to add "http://spark.furore.com/fhir/" external server to link my resource to it, but my local server says it doesn't allow me to external server, even though i have allowed it in my FhirServerConfig.java file

**Comment by jamesagnew** [comment]
If you just want to allow references to external resources from within your server you need to allow this via the DaoConfig using the setting:
```java
daoConfig.setAllowExternalReferences(true);
```

I notice that the example on the website is wrong (it suggests `setAllowInlineMatchUrlReferences` which is for something else) so I'll fix that.
