### ISSUE TITLE
Dublicate files copied in APK ca/uhn/fhir/model/dstu2/fhirversion.properties on Android

### ISSUE THREAD

**Issue by daandebie** [jamesagnew/hapi-fhir#582]
Hi, I just updated my Android project from version 1.6 to version 2.2 (see configurations below). On compile time the follow error occurs:

```
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK ca/uhn/fhir/model/dstu2/fhirversion.properties
  	File1: .../.gradle/caches/modules-2/files-2.1/ca.uhn.hapi.fhir/hapi-fhir-structures-dstu2/2.2/8a030ba9c1080eebed0b68edc76d5ad26d3639c6/hapi-fhir-structures-dstu2-2.2.jar
  	File2: .../.gradle/caches/modules-2/files-2.1/ca.uhn.hapi.fhir/hapi-fhir-android/2.2/445ab289c6ab27c5b7598c75331f6e8371af5e31/hapi-fhir-android-2.2-dstu2.jar
```

Dependency setup:
```
compile (group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-android', version: '2.2', classifier: 'dstu2') {
        exclude module: 'javax.servlet-api'
        exclude module: 'hapi-fhir-base'
}
```

Gradle version: classpath 'com.android.tools.build:gradle:2.3.0'

I have tried cleaning the gradle cache, and excluding the fhirversion.properties file from packaging, which fixes the compile time error (instead it complains at runtime about a missing .properties file):
```
packagingOptions {
        exclude 'ca/uhn/fhir/model/dstu2/fhirversion.properties'
}
```

Unfortunately no success running the 2.2 library yet. Anybody has a suggestion? Thanks!

**Comment by jamesagnew** [comment]
Hi @daandebie , 

There is a working Android project using HAPI FHIR 2.2 here: https://github.com/hapifhir/hapi-fhir-android-integration-test

It might be worth comparing your configuration to this one.

**Comment by daandebie** [comment]
Thanks for the help/link @jamesagnew. Compared my configuration with the android-integration-test project helped and fixed my issue.

I used the dependecy code from: [http://hapifhir.io/doc_android.html](url), but that doesn't seem to work since version >= 2.0 anymore.

Thanks again!
