### ISSUE TITLE
FhirInstanceValidator fails for some CodeableConcept elements

### ISSUE THREAD

**Issue by jasminas** [jamesagnew/hapi-fhir#583]
Using a RequestValidatingInterceptor with the provided FhirInstanceValidator & DefaultProfileValidationSupport, I am encountering some errors when trying to post the following resources:

- MedicationOrder with a valid reasonEnded element

- Procedure with valid reasonNotPerformed

Both elements have CodeableConcept as data type. I've attached the JSON samples. The error messages are similar for both resources:
`{
      "severity": "error",
      "code": "processing",
      "diagnostics": "Element matches more than one slice",
      "location": [
        "/reasonEnded"
      ]
}`

[medication-order.txt](https://github.com/jamesagnew/hapi-fhir/files/831708/medication-order.txt)
[procedure.txt](https://github.com/jamesagnew/hapi-fhir/files/831714/procedure.txt)

**Comment by danieljianu** [comment]
Any updates on this?

**Comment by jasminas** [comment]
I've been inquiring this issue and I found that it is related to the existence of another field named "reason[x]" in both profiles (a reasonCodeableConcept or a reasonReference). The instance validator checks the belonging of an element to a slice by using the "nameMatches" function which is trying to match the element name to the prefix of the slice when it's ending in "[x]". This is also the case of  _reasonEnded_/_reasonNotPerformed_ elements vs. _reason[x]_ slice. The validator sees that both names start with "reason" so it marks them as errors.

**Comment by jamesagnew** [comment]
Just to confirm, which version of HAPI is this happening with and which version of the model?

**Comment by jasminas** [comment]
I am using HAPI 2.3 version along with the HAPI DSTU2 structures.

**Comment by jamesagnew** [comment]
Ah yes, the DSTU2 validator does have a number of issues unfortunately that have been addressed in the STU3 validator.

Pull requests definitely welcome.
