### ISSUE TITLE
When is the next FHIR structures update planed?

### ISSUE THREAD

**Issue by stefan-evinance** [jamesagnew/hapi-fhir#594]
Hi, when is the next FHIR structures update planed? Thank you.

**Comment by jamesagnew** [comment]
Hi Steven, 

If you want to check out the 1.9.0 FHIR definitions, they can be found in the [dstu3_latest_structs](https://github.com/jamesagnew/hapi-fhir/tree/dstu3_latest_structs) branch.

We'll be merging this into master and releasing later this week, after testing and documentation is complete.

Ps- If possible, please use the google group for questions. The issue tracker is intended for issue reports.
