### ISSUE TITLE
The HAPI FHIR test server instance is down

### ISSUE THREAD

**Issue by mohan-gliimpse** [jamesagnew/hapi-fhir#596]
Hello,

The HAPI FHIR test server instance is currently down @ http://fhirtest.uhn.ca/  Receiving **HTTP 502** at present.

When will it be back up?

Thanks

**Comment by jamesagnew** [comment]
Ah thanks for the heads up. It has been restored.

Now to figure out why the monitor didn't catch that.... sigh... :)
