### ISSUE TITLE
The transactions from HAPIs test home page displays a warning, but the transaction as such is executed.

### ISSUE THREAD

**Issue by gsureshkumar** [jamesagnew/hapi-fhir#607]
The transactions from HAPIs test home page displays a warning, but the transaction is executed.
The page displays the following

![image](https://cloud.githubusercontent.com/assets/19829447/24270598/2f20fd78-0fec-11e7-877b-8a766ebd3739.png)

Request used is as follows.

{
	"resourceType": "Bundle",
	"type": "transaction",
	"entry": [
		{
			"fullUrl": "Organization/EPI",
			"resource": {
				"resourceType": "Organization",
				"id": "EPI",
				"identifier": [
					{
						"system": "http://someurl/OrganizationIdentifier",
						"value": "EPI"
					}
				],
				"name": "EPI"
			},
			"request": {
				"method": "POST",
				"url": "Organization",
				"ifNoneExist": "Organization?identifier=http://someurl/OrganizationIdentifier|EPI"
			}
		}
        ]
}

**Comment by jamesagnew** [comment]
Thanks for reporting!

Can you please describe the steps you took to produce this?

**Comment by gsureshkumar** [comment]
Just copy the json data from the bug, paste it on to the text box for
transaction on hapi's test home page and click transaction button.

**Comment by jamesagnew** [comment]
Great, thanks for the insights. I'm checking in a fix now!
