### ISSUE TITLE
SupportingDocumentation resource exists in conformance for DSTU2

### ISSUE THREAD

**Issue by travistcummings** [jamesagnew/hapi-fhir#608]
Hi,

I recently build a Hapi 2.2 server for FHIR DSTU2.  However, the SupportingDocumentation resource is included in the conformance statement.  Some users are reporting this causes parsers to fail.

Here are snippets from my conformance statement:

{
  "resourceType": "Conformance",
  "publisher": "Not provided",
  "date": "2017-03-23T17:11:18-06:00",
  "kind": "instance",
  "software": {
    "name": "HAPI FHIR Server",
    "version": "2.2"
  },
  "implementation": {
    "description": "HSPC Reference API Server"
  },
  "fhirVersion": "1.0.2",
....

        },
        {
          "type": "SupportingDocumentation",
          "profile": {
            "reference": "http://hl7.org/fhir/profiles/SupportingDocumentation"
          },
          "interaction": [
            {
              "code": "read"

Alternatively, is there a way for me to exclude this resource from registering in the conformance?  

Thanks!
Travis Cummings

**Comment by jamesagnew** [comment]
Thanks for pointing this out! Fixed in the latest master.

You could work around this if you needed in HAPI 2.3 by subclassing the conformance provider, but you could certainly also use the latest 2.4 SNAPSHOT.
