### ISSUE TITLE
Need to implement a bean for a DSTU2 FhirInstanceValidator.

### ISSUE THREAD

**Issue by dmuylwyk** [jamesagnew/hapi-fhir#609]
Here's what I _think_ I need to do in `hapi-fhir` in order to implement bean for a DSTU2 `FhirInstanceValidator`:

In `BaseDstu3Config`, I have [this at Line 67](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/config/dstu3/BaseDstu3Config.java#L67):
```
	@Bean(name = "myInstanceValidatorDstu3")
	@Lazy
	public IValidatorModule instanceValidatorDstu3() {
		FhirInstanceValidator val = new FhirInstanceValidator();
		val.setBestPracticeWarningLevel(BestPracticeWarningLevel.Warning);
		val.setValidationSupport(validationSupportChainDstu3());
		return val;
	}
```

In `FhirResourceDaoDstu3`, I have [this at Line 70](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/dstu3/FhirResourceDaoDstu3.java#L70):
```
	@Autowired()
	@Qualifier("myInstanceValidatorDstu3")
	private IValidatorModule myInstanceValidator;
```
And [this at Line 131](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/dstu3/FhirResourceDaoDstu3.java#L131):
```
		validator.registerValidatorModule(myInstanceValidator);
```

**Therefore...**

In `BaseDstu2Config`, I should refactor [this](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/config/BaseDstu2Config.java) to be as `BaseDstu3Config`.

In `FhirResourceDaoDstu2`, I should refactor [this at Line 127]() to be as `FhirResourceDaoDstu3`:
```
		FhirInstanceValidator val = new FhirInstanceValidator();
		val.setBestPracticeWarningLevel(BestPracticeWarningLevel.Warning);
		val.setValidationSupport(new ValidationSupportChain(new DefaultProfileValidationSupport(), myJpaValidationSupport));
		validator.registerValidatorModule(val);
```

**Comment by dmuylwyk** [comment]
See feature branch:

https://github.com/jamesagnew/hapi-fhir/tree/609-need-to-implement-a-bean-for-a-dstu2-fhirinstancevalidator

**Comment by jamesagnew** [comment]
Looks right to me

sent from my phone.

**Comment by dmuylwyk** [comment]
Looks like this may be more complicated.

I _think_ I'll need to create and/or modify DSTU2 equivalents of the following:

- Modify [`BaseDstu2Config`](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/config/BaseDstu2Config.java) to be like [`BaseDstu3Config`](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/config/dstu3/BaseDstu3Config.java)
- Modify [`FhirResourceDaoDstu2`](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/FhirResourceDaoDstu2.java) to be like [`FhirResourceDaoDstu2`](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/dstu3/FhirResourceDaoDstu3.java)
- Create `JpaValidationSupportChainDstu2` to be like [`JpaValidationSupportChainDstu3`](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/validation/JpaValidationSupportChainDstu3.java)
- Create `IHapiTerminologySvcDstu2` to be like [`IHapiTerminologySvcDstu3`](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/IHapiTerminologySvcDstu3.java)
- Modify [`HapiTerminologySvcDstu2`](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/HapiTerminologySvcDstu2.java) to be like [`HapiTerminologySvcDstu3`](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/IHapiTerminologySvcDstu3.java)
- Create and modify additional files as necessary to facilitate these changes

Is that correct?

**Comment by dmuylwyk** [comment]
Re: [my earlier comment](https://github.com/jamesagnew/hapi-fhir/issues/609#issuecomment-289660596).

I've figured out how to do this without such extensive modification. Submitting a pull request.

**Comment by dmuylwyk** [comment]
See #611.

**Comment by dmuylwyk** [comment]
Merger into `master` in commit 4748c8b. Closing issue.
