### ISSUE TITLE
Not able to find DiagnosticOrder in DSTU3

### ISSUE THREAD

**Issue by rk5944** [jamesagnew/hapi-fhir#612]
I am trying to update from DSTU2 to DSTU3 and I am not able to find out couple of class in DSTU3.
examples are 
DiagnosticOrder
MedicationOrder
Order

Please let mme know if it's a known issue or I am doing something wrong.

**Comment by SRiviere** [comment]
Hi,
Quickly check the difference between DSTU2 and STU3 defintion:

[https://www.hl7.org/fhir/diff.html](https://www.hl7.org/fhir/diff.html)
and the changelog
[https://www.hl7.org/fhir/history.html](https://www.hl7.org/fhir/history.html)

You can see that some resource were deleted/renamed from the standard in STU3

For example:
DiagnosticOrder become DiagnosticRequest
MedicationOrder become MedicationRequest
