### ISSUE TITLE
JsonParser is not generating a valid fhir json. 

### ISSUE THREAD

**Issue by heravelli** [jamesagnew/hapi-fhir#614]
FHIR xml is validated using this 
 fhirContext= FhirContext.forDstu3();
 fhirContext.setParserErrorHandler(new StrictErrorHandler());
 ValidationResult result = fhirContext.newValidator().setValidateAgainstStandardSchema(true).validateWithResult(patientbundle);
 The same xml  when tried to covert to json:
With LenientErrorHandler, it generates the json.

When I tried to validate the json I am getting this error:
ValidationResult{messageCount=1836, isSuccessful=false, description='ERROR - cvc-complex-type.2.4.a: Invalid content was found starting with element 'provider'. One of '{"http://hl7.org/fhir":extension, "http://hl7.org/fhir":modifierExtension, "http://hl7.org/fhir":sequence}' is expected. - null'}

What is the best way to covert to json?

**Comment by jamesagnew** [comment]
Hi @heravelli, would you be able to provide a complete code sample which illustrates the issue?

**Comment by heravelli** [comment]
@jamesagnew Thank you so much for the quick response.
I created a bundle that has Patient, Coverage, MedicationDispense, Claim.
It validates fine with my method(see below).
When I try to covert with StrictErrorHandler, I am getting this error:
FhirConverter:64 - Could not convert to fhir 
ca.uhn.fhir.parser.DataFormatException: DataFormatException at [[row,col {unknown-source}]: [298,6]]: Unknown attribute 'type' found during parse
	at ca.uhn.fhir.parser.XmlParser.doXmlLoop(XmlParser.java:272)
	at ca.uhn.fhir.parser.XmlParser.parseResource(XmlParser.java:1050)
	at ca.uhn.fhir.parser.XmlParser.doParseResource(XmlParser.java:183)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:641)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:689)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:699)

If I covert it to Json using LenientErrorHandler, It generates json, but it's  NOT valid when I try to validated with my method(see below), I am getting this error:
FhirConverter:99 - Result is: ValidationResult{messageCount=1836, isSuccessful=false, description='ERROR - cvc-complex-type.2.4.a: Invalid content was found starting with element 'provider'. One of '{"http://hl7.org/fhir":extension, "http://hl7.org/fhir":modifierExtension, "http://hl7.org/fhir":sequence}' is expected. - null'}

Here is my class: 
public class FhirConverter {
    private final static Logger logger = Logger.getLogger(FhirConverter.class);
    private static FhirContext fhirContext;
    static {
        fhirContext= FhirContext.forDstu3();
        fhirContext.setParserErrorHandler(new StrictErrorHandler());
    }

    public static boolean convertToFhirXmlToFhirJson(String inputFilePath, String outputFilePath){

        boolean isSuccess = true;
        File outputFile = new File(outputFilePath);
        File inputFile = new File(inputFilePath);
        IParser inputParser;
        IParser outputParser;
        IBaseResource fhirObject = null;
        try {
            if (!outputFile.exists()) {
                boolean createdNewFile = outputFile.createNewFile();
                if (!createdNewFile) {
                    return false;
                }
            }
            if (!inputFile.exists()) {
                return false;
            }

            inputParser = fhirContext.newXmlParser();
            String content = new String(Files.readAllBytes(Paths.get(inputFilePath)));
            fhirObject = inputParser.parseResource(content);
           // System.out.println(fhirObject.getStructureFhirVersionEnum().getFhirVersionString());
            outputParser=fhirContext.newJsonParser();
            outputParser.setPrettyPrint(true);
            String outputString = outputParser.encodeResourceToString(fhirObject);
            //System.out.println(fhirContext.getVersion().getVersion().getFhirVersionString());
            // write to output file
            Files.write(Paths.get(outputFilePath), outputString.getBytes());

        }catch(Exception e){
            logger.error("Could not convert to fhir ", e);
            e.printStackTrace();
            isSuccess = false;
        }

        return isSuccess;
    }


    public static JSONObject convertxmlToJsonObj(String inputxml){
        JSONObject jsonObject = null;
        try {
            IBaseResource fhirObject = null;
            IParser xmlParser = fhirContext.newXmlParser();
            fhirObject = xmlParser.parseResource(inputxml);
            IParser jsonParser = fhirContext.newJsonParser();
            jsonParser.setPrettyPrint(true);
            Gson gson = new Gson();
            gson.toJson(fhirObject);
            String outputString = jsonParser.encodeResourceToString(fhirObject);
            ObjectMapper mapper = new ObjectMapper().setVisibility(FIELD, ANY);
            jsonObject = mapper.readValue(outputString, JSONObject.class);
            return jsonObject;
        }catch (Exception e){
            logger.error("Could not convert to fhir ", e);
        }

        return jsonObject;
    }


    public static boolean validatePatientBundleJson(String patientbundle){
        ValidationResult result = fhirContext.newValidator().setValidateAgainstStandardSchema(true).validateWithResult(patientbundle);
        logger.info("Result is: " + result.toString());
        return result.isSuccessful();

        /*FhirInstanceValidator instanceValidator = new FhirInstanceValidator();
        validator.registerValidatorModule(instanceValidator);
        ValidationResult result =  validator.validateWithResult(patientbundle);
        return result.isSuccessful();*/
    }

    private static String getFileExtension(File file) {
        String fileName = file.getName();
        if(fileName.lastIndexOf(".") != -1 && fileName.lastIndexOf(".") != 0)
            return fileName.substring(fileName.lastIndexOf(".")+1);
        else return "";
    }

}

**Comment by heravelli** [comment]
[fhir_samplepatient_bundle.xml.zip](https://github.com/jamesagnew/hapi-fhir/files/900481/fhir_samplepatient_bundle.xml.zip)

@jamesagnew Please use the attached xml file to see the issue.
A quick fix is appreciated. Thank you.

**Comment by jamesagnew** [comment]
That source bundle is not valid.

Claim.careTeam.sequence is required, but it's empty in your source:
```xml
                <careTeam>
                    <sequence/>
                    <provider id="208VP0000X"/>
                </careTeam>
```

**Comment by heravelli** [comment]
But, how come the validation is passing?
