### ISSUE TITLE
MedicationDispense  <value xsi:type="decimal" is not handled.

### ISSUE THREAD

**Issue by heravelli** [jamesagnew/hapi-fhir#615]
<daysSupply>
        <value xsi:type="decimal"
               value="25"/>
        <unit value="DAYS"/>
    </daysSupply>
fhirContext= FhirContext.forDstu3();
        fhirContext.setParserErrorHandler(new StrictErrorHandler());
 inputParser = fhirContext.newXmlParser();
            String content = new String(Files.readAllBytes(Paths.get(inputFilePath)));
            fhirObject = inputParser.parseResource(content);
           // System.out.println(fhirObject.getStructureFhirVersionEnum().getFhirVersionString());
            outputParser=fhirContext.newJsonParser();
            outputParser.setPrettyPrint(true);
            String outputString = outputParser.encodeResourceToString(fhirObject);

ca.uhn.fhir.parser.DataFormatException: com.ctc.wstx.exc.WstxParsingException: Undeclared namespace prefix "xsi" (for attribute "type")
 at [row,col {unknown-source}]: [41,27]
	at ca.uhn.fhir.parser.XmlParser.doXmlLoop(XmlParser.java:277)
	at ca.uhn.fhir.parser.XmlParser.parseResource(XmlParser.java:1050)
	at ca.uhn.fhir.parser.XmlParser.doParseResource(XmlParser.java:183)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:641)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:689)

**Comment by jamesagnew** [comment]
Could you please attach a copy of the full resource body you're parsing? (with any sensitive bits redacted)

**Comment by heravelli** [comment]
[fhir_samplepatient_bundle.xml.zip](https://github.com/jamesagnew/hapi-fhir/files/903302/fhir_samplepatient_bundle.xml.zip)
You can use this.
