### ISSUE TITLE
hapi-fhir-jpaserver-base - Test Failed

### ISSUE THREAD

**Issue by rishikanths** [jamesagnew/hapi-fhir#626]
Hi,

I am new to HAPI-FHIR implementation. When I was building the system, the following test class failed. The  problem with two pieces of code. 

Package - ca.uhn.fhir.jpa.dao.dstu3
Class - FhirResourceDaoDstu3Test
Code -  
`	
IBundleProvider found = myObservationDao.search(Observation.SP_DATE, new DateParam("sa2015-01-02T00:00:00Z"));
 				List<IIdType> list = toUnqualifiedVersionlessIds(found);
 				assertThat(list, containsInAnyOrder(id2));
`
Error -  Unvalid lower bound comparator: STARTS_AFTER

Code -  
`IBundleProvider found = myObservationDao.search(Observation.SP_DATE, new DateParam("eb2015-01-13T00:00:00Z"));
			List<IIdType> list = toUnqualifiedVersionlessIds(found);
			assertThat(list, containsInAnyOrder(id1));`
Error -  Unvalid UPPER bound comparator: ENDS_BEFORE

After I have commented the code, the server package compiled and I was also able to run the jpaserver example

Thanks,
Rishi

**Comment by jamesagnew** [comment]
This error has been resolved. Thanks for reporting!
