### ISSUE TITLE
ProcedureRequest in DSTU3 does not handle scheduledDateTime

### ISSUE THREAD

**Issue by lvdstam** [jamesagnew/hapi-fhir#629]
When POSTing/PUTing a ProcedureRequest with a scheduledDateTime field. A subsequent GET does not contain this field. When running the same test against http://fhirtest.uhn.ca/baseDstu3 shows the same behavior. On http://fhirtest.uhn.ca/baseDstu2 the behavior is as expected.

**Comment by jamesagnew** [comment]
The R3/DSTU3 resource definition for procedurerequest has no field called `scheduled[x]`.

See: http://hl7.org/fhir/procedurerequest.html

**Comment by lvdstam** [comment]
Hi James, thanks for your quick response. You are right the field is renamed in STU3. But it was not the case in the latest DSTU3 up until 1.8.0. I assumed that it was like this in hapi 2.3 also, but assumed wrong I guess.

Using the library version 2.4 (published today) conforming to specification 3.0.1 resolves this problem.

Sorry for wasting your time. Thanks again for the quick response and for this great library.

**Comment by jamesagnew** [comment]
Not a problem at all. Glad you're finding HAPI useful! :)
