### ISSUE TITLE
IResource should have getResourceType()

### ISSUE THREAD

**Issue by wdaehn** [jamesagnew/hapi-fhir#642]
The Resource has a method getResourceType(). This is convenient for Case clauses

``
switch (resource.getResourceType()) {
case: ....;
}
``

Since all Resource objects have that, I would appreciate to add that to the IResource interface as well.

**Comment by jamesagnew** [comment]
The DSTU1 and DSTU2 resource classes don't currently have a getResourceType() method, so adding this to the interface wouldn't work without changes to the code generator. 

Happy to accept patches to add that.
