### ISSUE TITLE
Setting of database URL at runtime for Docker container.

### ISSUE THREAD

**Issue by preston** [jamesagnew/hapi-fhir#644]
For JPA containers, database settings really need to be set via environment variables at runtime. Is this possible with the current build? I'm hoping it's just not documented. :)

**Comment by preston** [comment]
@jamesagnew We may be able to submit a patch if you'll accept a PR.

**Comment by jamesagnew** [comment]
Hi Preston,

The intent with hapi-fhir-jpaserver-base is that you can create a project which imports it and put your configuration in that project.

The hapi-fhir-jpaserver-example project is an example of such a project, and it uses hardcoded properties, but you could certainly create a similar project that takes DB properties from environment variables. If you wanted to create one and submit it as a PR certainly we'd accept it.
