### ISSUE TITLE
getChildren does not contain resourceType

### ISSUE THREAD

**Issue by wdaehn** [jamesagnew/hapi-fhir#645]
We have discussed that internally and came to the conclusion this is missing. 

When you look at a FHIR resource, e.g. Patient, it consists of
```
{
  "resourceType": "Patient",
  "id": "example",
   "identifier": [
    {
      "use": "usual",
      ...
```
The id is a child, the identifier is a child, .... but the resourceType on the same level is not.

Of course you could argue that this field is used only to know the target class Patient, hence not needed, but for data processing you might use the Resource as variable instead. Yeah, you can use instanceof but....
Close call, we wanted to suggest to add that after some discussions.

**Comment by jamesagnew** [comment]
resourceType is a part of the wire format and not a child of the element. It doesn't actually appear in the XML serialization, so including it in a list of children would be quite misleading. Unfortunately I don't think this change can happen.
