### ISSUE TITLE
Queries returned stale data

### ISSUE THREAD

**Issue by javajeff** [jamesagnew/hapi-fhir#647]
I have run a query for all observations with code 123 for 2.5 SNAPSHOT.
I then add or delete an observation with code 123.
I immediately rerun the query for all observations with code 123.  I don't see the change.  It appears to be using a cached version of the result.  After some time or after a number of queries I finally do see the expected change.  In version 2.4 release this query works fine reliably.  

Is there a way to turn off caching results on the server?  
Or is there a way to specify in the query to not use cached results?

**Comment by jamesagnew** [comment]
Hi Jeff,

Yes, as of 2.5 there is caching of search results for better performance. You can disable this if you want, have a look at `DaoConfig#setReuseCachedSearchResultsForMillis`

**Comment by javajeff** [comment]
Thanks!
