### ISSUE TITLE
FHIR bundle always failing validation

### ISSUE THREAD

**Issue by TomsonNgassa** [jamesagnew/hapi-fhir#653]
After adding all the necessary FHIR maven dependencies in my project, I have the following implementation:

FHIR BEANS CONFIGURATION:
----------------------------------

@Configuration
public class FhirConfig {

    @Bean
    public FhirContext fhirContext() {
        FhirContext fhirContext = FhirContext.forDstu3();
        return fhirContext;
    }

    @Bean
    public XmlParser fhirXmlParser() {
        return (XmlParser) fhirContext().newXmlParser();
    }

    @Bean
    public JsonParser fhirJsonParser() {
        return (JsonParser) fhirContext().newJsonParser();
    }

    @Bean
    public FhirValidator fhirValidator() {
        FhirContext fhirContext =  fhirContext();
        FhirValidator fhirValidator = fhirContext().newValidator();

        // Create some modules and register them
        IValidatorModule module1 = new SchemaBaseValidator(fhirContext);
        fhirValidator.registerValidatorModule(module1);
        IValidatorModule module2 = new SchematronBaseValidator(fhirContext);
        fhirValidator.registerValidatorModule(module2);

        return fhirValidator;
    }
}

IN THE SERVICE
-----------------

 @Autowired
    private FhirValidator fhirValidator;

private void assertIsValidateBundle(Bundle fhirbundle){
        final ValidationResult taggedBundleValidationResult = fhirValidator.validateWithResult(fhirbundle);
        taggedBundleValidationResult.getMessages().stream().forEach(error -> System.out.println("Error: " + error.getMessage()));
        Assert.isTrue(taggedBundleValidationResult.isSuccessful(), "FHIR validation is failed for the segmented bundle with " + taggedBundleValidationResult.getMessages().size() + " messages");
    }

VALIDATION ERRORS
-----------------------------------------------------------------------------------------------
Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'subject'. One of '{"http://hl7.org/fhir":category, "http://hl7.org/fhir":code}' is expected.
Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'subject'. One of '{"http://hl7.org/fhir":category, "http://hl7.org/fhir":code}' is expected.
Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'subject'. One of '{"http://hl7.org/fhir":category, "http://hl7.org/fhir":code}' is expected.
Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'subject'. One of '{"http://hl7.org/fhir":category, "http://hl7.org/fhir":code}' is expected.
Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'subject'. One of '{"http://hl7.org/fhir":category, "http://hl7.org/fhir":code}' is expected.
Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'subject'. One of '{"http://hl7.org/fhir":category, "http://hl7.org/fhir":code}' is expected.
Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'subject'. One of '{"http://hl7.org/fhir":category, "http://hl7.org/fhir":code}' is expected.
Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'subject'. One of '{"http://hl7.org/fhir":category, "http://hl7.org/fhir":code}' is expected.
Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'subject'. One of '{"http://hl7.org/fhir":category, "http://hl7.org/fhir":code}' is expected.
Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'subject'. One of '{"http://hl7.org/fhir":category, "http://hl7.org/fhir":code}' is expected.

SAMPLE FHIR BUNDLE
-------------------------
{
		"resourceType" : "Bundle",
		"id" : "c79c19ba-3133-4c4c-8494-77e7e53f9065",
		"meta" : {
			"lastUpdated" : "2017-05-01T09:38:35.133-04:00"
		},
		"type" : "searchset",
		"total" : 19,
		"link" : [{
				"relation" : "self",
				"url" : "https://fhirtest.uhn.ca/baseDstu2/Patient/13275/$everything?_format=json"
			}, {
				"relation" : "next",
				"url" : "https://fhirtest.uhn.ca/baseDstu2?_getpages=3bf5f8ea-69c8-4de0-84cf-db09d44adfc7&_getpagesoffset=10&_count=10&_format=json&_pretty=true&_bundletype=searchset"
			}
		],
		"entry" : [{
				"fullUrl" : "https://fhirtest.uhn.ca/baseDstu2/Observation/13276",
				"resource" : {	
					"resourceType" : "Observation",
					"id" : "13276",
					"meta" : {
						"versionId" : "1",
						"lastUpdated" : "2017-02-17T11:50:51.607-05:00"
					},
					"status" : "amended",
					"subject" : {
							"reference" : "Patient/13275"
					},
					"component" : [{
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 6,
								"unit" : "1 step(walking)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.05,
								"unit" : "1 minute(walking)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 16,
								"unit" : "1 step(running)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.03333333333333333,
								"unit" : "1 minute(running)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "66267-6",
										"display" : "Time Period"
									}
								]
							},
							"valuePeriod" : {
								"start" : "2014-12-20T06:00:00+00:00",
								"end" : "2014-12-20T12:00:00+00:00"
							}
						}
					]
				},
				"search" : {
					"mode" : "match"
				}
			}, {
				"fullUrl" : "https://fhirtest.uhn.ca/baseDstu2/Observation/13277",
				"resource" : {
					"resourceType" : "Observation",
					"id" : "13277",
					"meta" : {
						"versionId" : "1",
						"lastUpdated" : "2017-02-17T11:50:51.607-05:00"
					},
					"status" : "amended",
					"subject" : {
						"reference" : "Patient/13275"
					},
					"component" : [{
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 667,
								"unit" : "1 step(walking)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 5.59999999999999,
								"unit" : "1 minute(walking)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 43,
								"unit" : "1 step(running)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.08333333333333333,
								"unit" : "1 minute(running)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "66267-6",
										"display" : "Time Period"
									}
								]
							},
							"valuePeriod" : {
								"start" : "2014-12-21T00:00:00+00:00",
								"end" : "2014-12-21T06:00:00+00:00"
							}
						}
					]
				},
				"search" : {
					"mode" : "match"
				}
			}, {
				"fullUrl" : "https://fhirtest.uhn.ca/baseDstu2/Observation/13278",
				"resource" : {
					"resourceType" : "Observation",
					"id" : "13278",
					"meta" : {
						"versionId" : "1",
						"lastUpdated" : "2017-02-17T11:50:51.607-05:00"
					},
					"status" : "amended",
					"subject" : {
						"reference" : "Patient/13275"
					},
					"component" : [{
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 18,
								"unit" : "1 step(walking)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.16666666666666666,
								"unit" : "1 minute(walking)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 82,
								"unit" : "1 step(running)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.08333333333333333,
								"unit" : "1 minute(running)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "66267-6",
										"display" : "Time Period"
									}
								]
							},
							"valuePeriod" : {
								"start" : "2014-12-21T06:00:00+00:00",
								"end" : "2014-12-21T12:00:00+00:00"
							}
						}
					]
				},
				"search" : {
					"mode" : "match"
				}
			}, {
				"fullUrl" : "https://fhirtest.uhn.ca/baseDstu2/Observation/13279",
				"resource" : {
					"resourceType" : "Observation",
					"id" : "13279",
					"meta" : {
						"versionId" : "1",
						"lastUpdated" : "2017-02-17T11:50:51.607-05:00"
					},
					"status" : "amended",
					"subject" : {
						"reference" : "Patient/13275"
					},
					"component" : [{
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 37,
								"unit" : "1 step(walking)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.35,
								"unit" : "1 minute(walking)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 12,
								"unit" : "1 step(running)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.05,
								"unit" : "1 minute(running)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "66267-6",
										"display" : "Time Period"
									}
								]
							},
							"valuePeriod" : {
								"start" : "2014-12-21T12:00:00+00:00",
								"end" : "2014-12-21T18:00:00+00:00"
							}
						}
					]
				},
				"search" : {
					"mode" : "match"
				}
			}, {
				"fullUrl" : "https://fhirtest.uhn.ca/baseDstu2/Observation/13280",
				"resource" : {
					"resourceType" : "Observation",
					"id" : "13280",
					"meta" : {
						"versionId" : "1",
						"lastUpdated" : "2017-02-17T11:50:51.607-05:00"
					},
					"status" : "amended",
					"subject" : {
						"reference" : "Patient/13275"
					},
					"component" : [{
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0,
								"unit" : "1 step(walking)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "2.16.840.1.113883.6.103",
										"code" : "292.0",
										"display" : "Amphetamine Withdrawal"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0,
								"unit" : "1 minute(walking)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 12,
								"unit" : "1 step(running)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.05,
								"unit" : "1 minute(running)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "66267-6",
										"display" : "Time Period"
									}
								]
							},
							"valuePeriod" : {
								"start" : "2014-12-21T18:00:00+00:00",
								"end" : "2014-12-22T00:00:00+00:00"
							}
						}
					]
				},
				"search" : {
					"mode" : "match"
				}
			}, {
				"fullUrl" : "https://fhirtest.uhn.ca/baseDstu2/Observation/13281",
				"resource" : {
					"resourceType" : "Observation",
					"id" : "13281",
					"meta" : {
						"versionId" : "1",
						"lastUpdated" : "2017-02-17T11:50:51.607-05:00"
					},
					"status" : "amended",
					"subject" : {
						"reference" : "Patient/13275"
					},
					"component" : [{
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 1141,
								"unit" : "1 step(walking)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 9.64999999999999,
								"unit" : "1 minute(walking)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 17,
								"unit" : "1 step(running)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.08333333333333333,
								"unit" : "1 minute(running)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "66267-6",
										"display" : "Time Period"
									}
								]
							},
							"valuePeriod" : {
								"start" : "2014-12-22T00:00:00+00:00",
								"end" : "2014-12-22T06:00:00+00:00"
							}
						}
					]
				},
				"search" : {
					"mode" : "match"
				}
			}, {
				"fullUrl" : "https://fhirtest.uhn.ca/baseDstu2/Observation/13282",
				"resource" : {
					"resourceType" : "Observation",
					"id" : "13282",
					"meta" : {
						"versionId" : "1",
						"lastUpdated" : "2017-02-17T11:50:51.607-05:00"
					},
					"status" : "amended",
					"subject" : {
						"reference" : "Patient/13275"
					},
					"component" : [{
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 1605,
								"unit" : "1 step(walking)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 13.700000000000014,
								"unit" : "1 minute(walking)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 6,
								"unit" : "1 step(running)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.03333333333333333,
								"unit" : "1 minute(running)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "66267-6",
										"display" : "Time Period"
									}
								]
							},
							"valuePeriod" : {
								"start" : "2014-12-22T06:00:00+00:00",
								"end" : "2014-12-22T12:00:00+00:00"
							}
						}
					]
				},
				"search" : {
					"mode" : "match"
				}
			}, {
				"fullUrl" : "https://fhirtest.uhn.ca/baseDstu2/Observation/13283",
				"resource" : {
					"resourceType" : "Observation",
					"id" : "13283",
					"meta" : {
						"versionId" : "1",
						"lastUpdated" : "2017-02-17T11:50:51.607-05:00"
					},
					"status" : "amended",
					"subject" : {
						"reference" : "Patient/13275"
					},
					"component" : [{
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 917,
								"unit" : "1 step(walking)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 7.649999999999985,
								"unit" : "1 minute(walking)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 12,
								"unit" : "1 step(running)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.05,
								"unit" : "1 minute(running)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "66267-6",
										"display" : "Time Period"
									}
								]
							},
							"valuePeriod" : {
								"start" : "2014-12-22T12:00:00+00:00",
								"end" : "2014-12-22T18:00:00+00:00"
							}
						}
					]
				},
				"search" : {
					"mode" : "match"
				}
			}, {
				"fullUrl" : "https://fhirtest.uhn.ca/baseDstu2/Observation/13284",
				"resource" : {
					"resourceType" : "Observation",
					"id" : "13284",
					"meta" : {
						"versionId" : "1",
						"lastUpdated" : "2017-02-17T11:50:51.607-05:00"
					},
					"status" : "amended",
					"subject" : {
						"reference" : "Patient/13275"
					},
					"component" : [{
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0,
								"unit" : "1 step(walking)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0,
								"unit" : "1 minute(walking)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 46,
								"unit" : "1 step(running)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.08333333333333333,
								"unit" : "1 minute(running)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "66267-6",
										"display" : "Time Period"
									}
								]
							},
							"valuePeriod" : {
								"start" : "2014-12-22T18:00:00+00:00",
								"end" : "2014-12-23T00:00:00+00:00"
							}
						}
					]
				},
				"search" : {
					"mode" : "match"
				}
			}, {
				"fullUrl" : "https://fhirtest.uhn.ca/baseDstu2/Observation/13285",
				"resource" : {
					"resourceType" : "Observation",
					"id" : "13285",
					"meta" : {
						"versionId" : "1",
						"lastUpdated" : "2017-02-17T11:50:51.607-05:00"
					},
					"status" : "amended",
					"subject" : {
						"reference" : "Patient/13275"
					},
					"component" : [{
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 20,
								"unit" : "1 step(walking)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.16666666666666666,
								"unit" : "1 minute(walking)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55423-8",
										"display" : "Number of steps"
									}
								]
							},
							"valueQuantity" : {
								"value" : 96,
								"unit" : "1 step(running)",
								"system" : "iPhone",
								"code" : "step"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "55411-3",
										"display" : "Exercise duration"
									}
								]
							},
							"valueQuantity" : {
								"value" : 0.08333333333333333,
								"unit" : "1 minute(running)",
								"system" : "iPhone",
								"code" : "minute"
							}
						}, {
							"code" : {
								"coding" : [{
										"system" : "http://loinc.org",
										"code" : "66267-6",
										"display" : "Time Period"
									}
								]
							},
							"valuePeriod" : {
								"start" : "2014-12-23T00:00:00+00:00",
								"end" : "2014-12-23T06:00:00+00:00"
							}
						}
					]
				},
				"search" : {
					"mode" : "match"
				}
			}, {
				"fullUrl" : "https://fhirtest.uhn.ca/baseDstu2/Patient/13275",
				"resource" : {
					"resourceType" : "Patient",
					"id" : "13275",
					"meta" : {
						"versionId" : "1",
						"lastUpdated" : "2017-02-17T11:50:43.979-05:00"
					},
					"text" : {
						"status" : "generated",
						"div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><div class=\"hapiHeaderText\">Joh <b>SHEN </b></div><table class=\"hapiPropertyTable\"><tbody><tr><td>Identifier</td><td>0000</td></tr></tbody></table></div>"
					},
					"identifier" : [{
							"system" : "https://fhirtest.uhn.ca/baseDstu2",
							"value" : "0000"
						}
					],
					"name" : [{
							"family" : "Shen",
							"given" : [
								"Joh"
							]
						}
					],
					"contact" : [{
							"telecom" : [{
									"value" : "1234567"
								}
							]
						}
					]
				},
				"search" : {
					"mode" : "include"
				}
			}
		]
	}

**Comment by clarotech** [comment]
Observation.code (of type CodeableConcept) is mandatory and your example seems to be missing it in the Bundle entries.
