### ISSUE TITLE
SchematronBaseValidator issue with Observation 

### ISSUE THREAD

**Issue by contactkuchi** [jamesagnew/hapi-fhir#654]
Hi, 

The SchematronBaseValidator is failing for Observation resource as there seems to be a incorrect implementation of the rule "+ If code is the same as a component code then the value element associated with the code SHALL NOT be present".

The rule says that the Observation cannot have a value component if the code and the component code are same, but it does not mean that if the code and the component.code are different then the value can exist with the observation. A sample code that actually should go through is:

{
        "resourceType": "Observation",
        "id": "176",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2017-05-25T12:44:36.653-04:00"
        },
        "status": "final",
        "category": [
          {
            "coding": [
              {
                "system": "http://hl7.org/fhir/observation-category",
                "code": "procedure",
                "display": "Procedure"
              }
            ],
            "text": "one_min_check"
          },
          {
            "coding": [
              {
                "system": "http://hl7.org/fhir/observation-category",
                "code": "procedure",
                "display": "Procedure"
              }
            ],
            "text": "pre"
          }
        ],
        
        "code": {
          "coding": [
            {
              "system": "http://snomed.info/sct",
              "code": "424850005",
              "display": "424850005"
            }
          ],
          "text": "424850005"
        },
       	 "valueString": "Strength",
        "effectiveDateTime": "2017-01-01T00:00:00-05:00",
        "method": {
          "coding": [
            {
              "system": "http://fmcna.com/fhir/observation-methods",
              "code": "look",
              "display": "look"
            }
          ],
          "text": "look"
        },
        "component": [
          {
            "code": {
              "coding": [
                {
                  "system": "http://snomed.info/sct",
                  "code": "66019005",
                  "display": "Changes in Extremity"
                }
              ],
              "text": "Changes in Extremity"
            },
            "valueString": "Not observed Swelling"
          },
          {
            "code": {
              "coding": [
                {
                  "system": "http://snomed.info/sct",
                  "code": "423493009",
                  "display": "Changes in Extremity"
                }
              ],
              "text": "Changes in Extremity"
            },
            "valueString": "Weakness"
          }
        ]
      }

I have tested this against publicly available servers and they go through fine. Only when I add the SchematronBaseValidator to my FHIR server I see that this validation fails. Please advice.

**Comment by jamesagnew** [comment]
Hi @contactkuchi ,

Two questions- 

1. which version of FHIR are you using?
2. are you able to fix the formatting on the snippet? It looks like the paste didn't quite work.

**Comment by contactkuchi** [comment]
{
	"resourceType": "Observation",
	"id": "176",
	"meta": {
		"versionId": "1",
		"lastUpdated": "2017-05-25T12:44:36.653-04:00"
	},
	"status": "final",
	"category": [{
			"coding": [{
				"system": "http://hl7.org/fhir/observation-category",
				"code": "procedure",
				"display": "Procedure"
			}],
			"text": "one_min_check"
		},
		{
			"coding": [{
				"system": "http://hl7.org/fhir/observation-category",
				"code": "procedure",
				"display": "Procedure"
			}],
			"text": "pre"
		}
	],

	"code": {
		"coding": [{
			"system": "http://snomed.info/sct",
			"code": "424850005",
			"display": "424850005"
		}],
		"text": "424850005"
	},
	"valueString": "Strength",
	"effectiveDateTime": "2017-01-01T00:00:00-05:00",
	"method": {
		"coding": [{
			"system": "http://fmcna.com/fhir/observation-methods",
			"code": "look",
			"display": "look"
		}],
		"text": "look"
	},
	"component": [{
			"code": {
				"coding": [{
					"system": "http://snomed.info/sct",
					"code": "66019005",
					"display": "Changes in Extremity"
				}],
				"text": "Changes in Extremity"
			},
			"valueString": "Not observed Swelling"
		},
		{
			"code": {
				"coding": [{
					"system": "http://snomed.info/sct",
					"code": "423493009",
					"display": "Changes in Extremity"
				}],
				"text": "Changes in Extremity"
			},
			"valueString": "Weakness"
		}
	]
}

Hi James,

I tried with 2.4, 2.4-SNAPSHOT versions, both give error

**Comment by jkiddo** [comment]
I'm also seeing it on version 2.5
