### ISSUE TITLE
HAPI FHIR public test server is down

### ISSUE THREAD

**Issue by vladf95** [jamesagnew/hapi-fhir#657]
Hello,

The HAPI FHIR test server is currently down.
This is the error I'm getting in eclipse: 
Failed to retrieve the server metadata statement during client initialization. URL used was http://fhirtest.uhn.ca/baseDstu3/metadata

When will it be back up?

Thank you.

Best regards,
Vlad

**Comment by AAdewunmi** [comment]
Hi,

I am having a similar problem. 
Been trying to load my clinical senario's but clinfhir.com says: Error loading models http://clinfhir.com/builder.html

Regards

Ade

**Comment by jamesagnew** [comment]
Thanks for reporting.

We had some weird issues this week. Someone managed to upload a resource that was corrupted sufficiently badly as to keep the server constantly crashing. Sigh.

We should be up again.
