### ISSUE TITLE
Unknown attribute 'value' while processing Identifier

### ISSUE THREAD

**Issue by harimh** [jamesagnew/hapi-fhir#658]
May 30, 2017 10:11:00 AM ca.uhn.fhir.util.VersionUtil initialize
May 30, 2017 10:11:01 AM ca.uhn.fhir.parser.LenientErrorHandler unknownAttribute
WARNING: Unknown attribute 'value' found while parsing

Attaching the source JSON with output log.

![screen shot 2017-05-30 at 10 22 34 am](https://cloud.githubusercontent.com/assets/6888077/26596049/489c4148-4522-11e7-9bc1-1a91fce1888c.jpg)
![screen shot 2017-05-30 at 10 22 47 am](https://cloud.githubusercontent.com/assets/6888077/26596048/48995f8c-4522-11e7-8455-d829cf14aaf9.jpg)

**Comment by jamesagnew** [comment]
Hi @harimh , would you be able to attach the actual text of the resource that is causing this issue so I can create a unit test of it?

**Comment by harimh** [comment]
Sure @jamesagnew.

Please see attached resources.
[Output.txt](https://github.com/jamesagnew/hapi-fhir/files/1064829/Output.txt)
[Patient.json.txt](https://github.com/jamesagnew/hapi-fhir/files/1064833/Patient.json.txt)
[PatientTest.java.txt](https://github.com/jamesagnew/hapi-fhir/files/1064832/PatientTest.java.txt)

Thank you,
Harish

**Comment by jamesagnew** [comment]
Hi @harimh,

The issue here is with the assigner in your patient's identifiers:
```json
  "identifier": [{
    "use": "official",
    "type": {
      "coding": [{
        "system": "http://hl7.org/fhir/identifier-type",
        "code": "MR",
        "display": "Medical Record Number",
        "userSelected": true
      }]
    },
    "system": "urn:oid:2.16.840.1.113883.3.566",
    "value": "220457511",
    "assigner": "MU"
  },
```

Assigner is a reference, so it should look more like:

```json
    "assigner": { "reference": "MU" }
```

The parser in HAPI FHIR 2.5 has been adjusted to make the error message more useful.

**Comment by harimh** [comment]
Thank you James.
