### ISSUE TITLE
Size attribute in object Attachment should be long instead of int

### ISSUE THREAD

**Issue by jodue** [jamesagnew/hapi-fhir#661]
The setSize and getSize methods in the Attachment Object operate with int (UnsignedIntType internally) which limits the size of the attachment to ~2.1GB. The FHIR specification defines size to be of type "unsignedInt" which is in turn defined by regex: [0]|([1-9][0-9]*), so no size restriction is imposed there. Since we have to assume that there will be files > 2.1GB (possible eg. for operation videos etc.) the type of the size variable in java should be long, which does not put any unreasonable restrictions on the attachment size.

**Comment by jamesagnew** [comment]
Hi @jodue - Sorry for missing this. FYI the datatype for attachment is mandated by the FHIR standard, not by HAPI FHIR, so we aren't really in a good position to change it. You do make a valid point though about the limitations of that datatype.

Raising this on chat.fhir.org would probably be a logical step to see if there is consensus to change the datatype for that field.
