### ISSUE TITLE
Failed to build HAPI-FHIR Server / JPA Server error - See details section below

### ISSUE THREAD

**Issue by mjosborne1** [jamesagnew/hapi-fhir#663]
I'm willing to bet that this is environmental not code related, but I have been unable after 2 days of trying stuff out to work out why I get an error building HAPI. The error is related to FHIR JPA Server.

Environment:
Attempting to install HAPI-FHIR on BioLinux 8 VM inside VMWare Workstation, running on a Windows 10 laptop.

Software versions:
Ubuntu Linux 14.04
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-55-generic", arch: "amd64", family: "unix"

I have run `sudo apt-get update` prior to the attempt at installing hapi
The error:
[INFO] HAPI Tinder Plugin - Test Project ................. SUCCESS [35.583s]
[INFO] HAPI FHIR JAX-RS Server ........................... SUCCESS [26.172s]
[INFO] HAPI FHIR JAX-RS Server - Example ................. SUCCESS [21.941s]
[INFO] HAPI FHIR JPA Server .............................. FAILURE [17:12.527s]
[INFO] HAPI FHIR TestPage Overlay ........................ SKIPPED
...

My thoughts are that I am missing some sort of dependency. 
I have tried to resolve the issue by installing the following packages:
libopenjpa-java (2.2.2-1)
tomcat7 (7.0.52)
tomcat7-common (7.0.52)

Any advice would be gratefully received.
Thanks

**Comment by mjosborne1** [comment]
This is the Error stack trace when I run mvn install -X
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26:53.500s
[INFO] Finished at: Sun Jun 04 09:09:36 AEST 2017
[INFO] Final Memory: 62M/343M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project hapi-fhir-jpaserver-base: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/michael/hapi-fhir/hapi-fhir-jpaserver-base && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/michael/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/jacoco.exec,dumponexit=true -Dfile.encoding=UTF-8 -Xmx1024m -jar /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefirebooter6265710569049797373.jar /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefire5745270925364950470tmp /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefire_115825283990538959317tmp
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project hapi-fhir-jpaserver-base: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/michael/hapi-fhir/hapi-fhir-jpaserver-base && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/michael/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/jacoco.exec,dumponexit=true -Dfile.encoding=UTF-8 -Xmx1024m -jar /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefirebooter6265710569049797373.jar /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefire5745270925364950470tmp /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefire_115825283990538959317tmp
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/michael/hapi-fhir/hapi-fhir-jpaserver-base && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/michael/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/jacoco.exec,dumponexit=true -Dfile.encoding=UTF-8 -Xmx1024m -jar /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefirebooter6265710569049797373.jar /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefire5745270925364950470tmp /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefire_115825283990538959317tmp
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.RuntimeException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/michael/hapi-fhir/hapi-fhir-jpaserver-base && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/michael/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/jacoco.exec,dumponexit=true -Dfile.encoding=UTF-8 -Xmx1024m -jar /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefirebooter6265710569049797373.jar /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefire5745270925364950470tmp /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefire_115825283990538959317tmp
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:590)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:460)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:229)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:201)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1026)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:862)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hapi-fhir-jpaserver-base

**Comment by lawley** [comment]
Are you doing "mvn compile" or "mvn package"?

I found that, at least the first time, you needed to do a package as it builds some extra stuff

Michael

**Comment by mjosborne1** [comment]
I'm doing mvn install. I will try mvn package.

**Comment by mjosborne1** [comment]
Same error with mvn package unfortunately.

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24:29.373s
[INFO] Finished at: Sun Jun 04 09:41:10 AEST 2017
[INFO] Final Memory: 61M/260M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project hapi-fhir-jpaserver-base: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/michael/hapi-fhir/hapi-fhir-jpaserver-base && /usr/lib/jvm/java-8-oracle/jre/bin/java -javaagent:/home/michael/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/jacoco.exec,dumponexit=true -Dfile.encoding=UTF-8 -Xmx1024m -jar /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefirebooter3263806549666754938.jar /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefire4129946649063042652tmp /home/michael/hapi-fhir/hapi-fhir-jpaserver-base/target/surefire/surefire_11668760511271539507tmp
[ERROR] -> [Help 1]

**Comment by mjosborne1** [comment]
Some googling found this:
Surefire fails with the message "The forked VM terminated without properly saying goodbye".

    Surefire does not support tests or any referenced libraries calling System.exit() at any time. If they do so, they are incompatible with Surefire and you should probably file an issue with the library/vendor. Alternatively the forked VM could also have crashed for a number of reasons. Look for the classical "hs_err*" files indicating VM crashes or examine the Maven log output when the tests execute. Some "extraordinary" output from crashing processes may be dumped to the console/log. If this happens on a CI environment and only after it runs for some time, there is a fair chance your test suite is leaking some kind of OS-level resource that makes things worse at every run. Regular OS-level monitoring tools may give you some indication.

**Comment by jamesagnew** [comment]
Try running the build with

mvn -P NOPARALLEL install

If that works, your VM is running out of memory.

Cheers,
James

sent from my phone.

**Comment by mjosborne1** [comment]
Yes, that appears to work...
michael@biolinux8[hapi-fhir] mvn -P NOPARALLEL install                                                                  [11:04AM]
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building HAPI-FHIR 2.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ hapi-fhir ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-java) @ hapi-fhir ---
[INFO] 
[INFO] --- license-maven-plugin:1.12:update-project-license (update-project-license) @ hapi-fhir ---
[INFO] Will check encoding : UTF-8
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ hapi-fhir ---
[INFO] Installing /home/michael/hapi-fhir/pom.xml to /home/michael/.m2/repository/ca/uhn/hapi/fhir/hapi-fhir/2.5-SNAPSHOT/hapi-fhir-2.5-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.771s
[INFO] Finished at: Sun Jun 04 11:05:11 AEST 2017
[INFO] Final Memory: 8M/31M
[INFO] ------------------------------------------------------------------------

I'll throw some more memory at the VM and try again

**Comment by mjosborne1** [comment]
my HAPI is Happy now.
I increased the VM memory to 4 Gb and it worked....
Thanks  Michael Lawley and James Agnew..

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27:52.788s
[INFO] Finished at: Sun Jun 04 11:43:32 AEST 2017
[INFO] Final Memory: 80M/456M
