### ISSUE TITLE
Unxpected element 'identifier' in element 'Bundle'

### ISSUE THREAD

**Issue by rgeimer** [jamesagnew/hapi-fhir#670]
Using the following code in HAPI 2.4:

	public ValidationResult validateFhirBundle(File fhirDoc) throws IOException{
		ValidationResult result = null;
		FhirValidator validator = context.newValidator();
		FhirInstanceValidator instanceValidator = new FhirInstanceValidator();
		validator.registerValidatorModule(instanceValidator);
		String xmlResourceStr = loadAsXml(fhirDoc);
		XmlParser parser = (XmlParser) context.newXmlParser();
		Bundle resource = parser.parseBundle(xmlResourceStr);
		result = validator.validateWithResult(resource);
		return result;
	}

Against a Bundle like this (abbreviated):

`<?xml version="1.0" encoding="UTF-8"?>
<Bundle xmlns="http://hl7.org/fhir">
   <identifier>
      <system value="urn:ietf:rfc:3986"/>
      <value value="urn:uuid:b700797c-693d-42f5-be3c-ee25dbbc4bbd"/>
   </identifier>
   <type value="document"/>
   <entry>
      <fullUrl value="urn:uuid:25250693-433f-443c-a724-48be8c4ff4aa"/>
      <resource>
         <Composition>
            ...
         </Composition>
      </resource>
   </entry>
</Bundle>
`

I get the following error:

ca.uhn.fhir.parser.DataFormatException: DataFormatException at [[row,col {unknown-source}]: [3,4]]: Unxpected element 'identifier' in element 'Bundle'
	at ca.uhn.fhir.parser.XmlParser.doXmlLoop(XmlParser.java:272)
	at ca.uhn.fhir.parser.XmlParser.parseBundle(XmlParser.java:1045)
	at ca.uhn.fhir.parser.XmlParser.parseBundle(XmlParser.java:1040)
	at ca.uhn.fhir.parser.BaseParser.parseBundle(BaseParser.java:635)
	at ca.uhn.fhir.parser.BaseParser.parseBundle(BaseParser.java:641)
...

Identifier is not only allowed in Bundle resources, but it is required in document bundles according to the following constraint:

bdl-9: A document must have an identifier with a system and a value (expression : type = 'document' implies (identifier.system.exists() and identifier.value.exists()))

Also, the error message has a typo: "Unxpected" should be "Unexpected".

**Comment by jamesagnew** [comment]
Hi Rick,

For parsing a DSTU2/3 Bundle it it much better to do:
```java
parser.parseResource(Bundle.class, input);
```

...instead of...

```java
parser.parseBundle(input);
```

The latter tries to parse into an Atom structure (because that was how we did it in DSTU1 of course) and it doesn't support most of the features of DSTU2+. Now that R3 is out and we're starting the drive to R4 I think we'll finally be able to deprecate and ultimately remove the parseBundle method entirely.

**Comment by rgeimer** [comment]
Thanks James, makes perfect sense. I was using parseResource, then changed to parseBundle because it seemed more appropriate. Will move back to parseResource, and I agree that parseBundle should be deprecated.

**Comment by jamesagnew** [comment]
Sounds good!
