### ISSUE TITLE
Executing a search for Observation that returns no results produces a Bundle whose getTotal() method returns null, rather than usual int 0

### ISSUE THREAD

**Issue by dcollins15** [jamesagnew/hapi-fhir#677]
Bundle results = client.search()
                    .forResource(Observation.class)
                    .where(Observation.PATIENT.hasId({some patient_id with no Observation resources}))
                    .returnBundle(Bundle.class)
                    .execute();
int resultSize = results.getTotal();

//resultSize is null, expected to be 0

**Comment by eug48** [comment]
In case this helps - I've also started to see Bundle.total intermittently missing from search results with HAPI 2.5 CLI, but haven't figured out what reproduces it yet. In my case the true number of resources to be found is approx 500, and except for the missing total the first page appears fine - the code errors out and doesn't attempt to get the next page.

**Comment by gsureshkumar** [comment]
I'm able to consistently reproduce this with JPA Server on v2.5
