### ISSUE TITLE
RuntimeResourceDefinition depends on Phloc-commons

### ISSUE THREAD

**Issue by jamesagnew** [jamesagnew/hapi-fhir#68]
Need to remove this dependency (not released, only exists in 0.9-SNAPSHOT)

**Comment by andyhuang91** [comment]
I think that this problem exists in 0.8:
https://github.com/jamesagnew/hapi-fhir/commit/1501b3e278482188e86e1b40b8ff35a43cae6956

I had trouble upgrading from 0.7 to 0.8 since I didn't have the optional Phloc-commons dependency in my pom.xml
