### ISSUE TITLE
Webclient & Search & Date

### ISSUE THREAD

**Issue by parisni** [jamesagnew/hapi-fhir#687]
Hey

I d'like to search by date parameter in the webclient. However, the interface does not propose me a form field when I choose the date parameter.
In the meantime, the API is working (tested with curl).
`curl "http://fhirtest.uhn.ca/baseDstu3/Observation?date=2017-01-01"`

**Comment by ZedOweYou** [comment]
What date is it querying for with API?
I've tested it on a few observations and while it does seem to return observations, none of their date values match the date in the query.

Also, the webclient's date still does not have a field to input a parameter.
