### ISSUE TITLE
FHIR Transaction is taking a lot of time

### ISSUE THREAD

**Issue by gsureshkumar** [jamesagnew/hapi-fhir#694]
Hi, 

We use HAPI server 2.3 with DSTU2.
JPA server with SQL Server 2012.
When we ran a transaction with the attached json, it took around 10-12 seconds.
Wanted to know if this can be improved.

thanks,
Suresh
[TransactionData.json.txt](https://github.com/jamesagnew/hapi-fhir/files/1166714/TransactionData.json.txt)

**Comment by jamesagnew** [comment]
I'm seeing this take about 6 seconds against our public server (which is a fully functional deployment of HAPI against a Postgres backend), using the command:

```bash
time curl -X POST --data @TransactionData.json  -H "Content-Type: application/json" 
(snip)
       6.12 real         0.00 user         0.00 sys
```

I'd recommend using the latest version of HAPI and making sure that your server is fully initialized. Beyond that if you can supply profiling numbers that show where the time is being spent that could be useful.

**Comment by gsureshkumar** [comment]
How can I collect the profiling numbers?
To run the transaction, we just pasted the json data on the transaction text box of the hapi test page.
I assume that the public server you maintain runs the latest hapi codebase.
Yes, the performance number was collected after few test runs.

**Comment by gsureshkumar** [comment]
Another thing we noticed is that when we turned off the fhir resource validation, we noticed a boost in the performance.
Here is how we do the validation (in the initialize() method of JpsServerDemo.java) 
Please let me know if this looks OK.

RequestValidatingInterceptor requestInterceptor = new RequestValidatingInterceptor();
       
		// Register a validator module (you could also use SchemaBaseValidator and/or SchematronBaseValidator)
		requestInterceptor.addValidatorModule(new FhirInstanceValidator());
       
		requestInterceptor.setFailOnSeverity(ResultSeverityEnum.ERROR);
		requestInterceptor.setAddResponseHeaderOnSeverity(ResultSeverityEnum.INFORMATION);
		requestInterceptor.setResponseHeaderValue("Validation on ${line}: ${message} ${severity}");
		requestInterceptor.setResponseHeaderValueNoIssues("No issues detected");
       
		// Now register the validating interceptor
		registerInterceptor(requestInterceptor);

**Comment by jamesagnew** [comment]
Oh yeah, the Validator is notorious for adding some overhead time, and especially when validating a transaction it does a lot of work.

There are no quick fixes on that, sadly. But i'd agree the performance needs to be improved.
