### ISSUE TITLE
Negative quantities not returned in query parameters with 

### ISSUE THREAD

**Issue by kwboone** [jamesagnew/hapi-fhir#696]
Found in HAPI-FHIR 2.1 in ca.uhn.fhir.rest.param.BaseParamWithPrefix:

	String extractPrefixAndReturnRest(String theString) {
		int offset = 0;
		while (true) {
			if (theString.length() == offset || Character.isDigit(theString.charAt(offset))) {
				break;
			}
			offset++;
		}

		String prefix = theString.substring(0, offset);
		myPrefix = ParamPrefixEnum.forValue(prefix);
		if (myPrefix == null) {
			myPrefix = ParamPrefixEnum.forDstu1Value(prefix);
		}

		return theString.substring(offset);
	}

This code fails to accept a quantity parameter with a negative value.  
test should include || (theString.charAt(offset) == '-')

**Comment by jamesagnew** [comment]
Hi Keith,

Thanks for the report! I've confirmed this, and will check in the fix you suggest momentarily.
