### ISSUE TITLE
=ge20||a translates to having a as system

### ISSUE THREAD

**Issue by kwboone** [jamesagnew/hapi-fhir#697]
Again in HAPI 2.1:

ca.uhn.fhir.rest.param.ParameterUtil.splitParameterString(String theInput, char theDelimiter, boolean theUnescapeComponents)

has: 			if (b.length() > 0) {
				retVal.add(b.toString());
			}

But, parameters split around | are positional in use of this method from ca.uhn.fhir.rest.param.QuantityParam.doSetValueAsQueryToken().

**Comment by CarthageKing** [comment]
Hello Keith,

I believe this has been fixed as of HAPI 2.2. I also found this before in #514.

Can you try a version newer than 2.1?
