### ISSUE TITLE
Organization does not support the active element

### ISSUE THREAD

**Issue by wanghaisheng** [jamesagnew/hapi-fhir#7]
when I run GET http://fhirtest.uhn.ca/base/Organization
return 40 entries.
I find all entries does have active element .
then I try http://fhirtest.uhn.ca/base/Organization?active:missing
it return 0 instead of 40

**Comment by t4deon** [comment]
Proposing this for closing as this is supported and fixed.

**Comment by jamesagnew** [comment]
@t4deon thanks, good call.
