### ISSUE TITLE
How to generate StructureDefinition per defined profile files in local

### ISSUE THREAD

**Issue by baopingle** [jamesagnew/hapi-fhir#707]
Now in my server side, I use the hapi-fhir-base, hapi-fhir-structures-dstu3 and hapi-fhir-validation-resources-dstu3 like below.

`<dependency>
			<groupId>ca.uhn.hapi.fhir</groupId>
			<artifactId>hapi-fhir-base</artifactId>
			<version>${hapi.fhir.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
		   <groupId>ca.uhn.hapi.fhir</groupId>
		   <artifactId>hapi-fhir-structures-dstu3</artifactId>
		   <scope>provided</scope>
		   <version>${hapi.fhir.version}</version>
		</dependency>`

When I try to check the StructureDefinition of one of fhir resource, then no results return. It seems that there is not StructureDefinitionProvider. I found the http://fhirtest.uhn.ca/baseDstu3/StructureDefinition/Patient?_pretty=true could be generated the real StructureDefinition, then how I could do like it, which code/project that I can refer to?

Thanks in advance!

**Comment by jamesagnew** [comment]
Hi @baopingle, please see our [FAQ](http://hapifhir.io/hapi-fhir-faq.html) for information on where to ask questions about HAPI FHIR.

With regards to your specific question, the JPA server allows resources to be uploaded, so the definitions are all uploaded by the [http://hapifhir.io/doc_cli.html](CLI) using the `upload-definitions` command. If you are using the plain server you will need to implement your own provider that has the semantics you want.
