### ISSUE TITLE
Error searching DiagnosticReport on test serer.

### ISSUE THREAD

**Issue by malcolmm83** [jamesagnew/hapi-fhir#715]
GET http://fhirtest.uhn.ca/baseDstu3/DiagnosticReport?_count=3&_pretty=true
produces this (_count=2 is ok):
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Failed to parse database resource[class org.hl7.fhir.dstu3.model.DiagnosticReport/32951 (pid 32951, version DSTU3): Unknown resource name &quot;DiagnosticRequest&quot; (this name is not known in FHIR version &quot;DSTU3&quot;)</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Failed to parse database resource[class org.hl7.fhir.dstu3.model.DiagnosticReport/32951 (pid 32951, version DSTU3): Unknown resource name \"DiagnosticRequest\" (this name is not known in FHIR version \"DSTU3\")"
    }
  ]
}

Seems to be a data problem, but I wanted to test some chaining and needed to find some DiagnosticReports based-on ProcedureRequests.

**Comment by jamesagnew** [comment]
Thanks for reporting! There was some old data on the server from before some model elements got renamed (i.e. before STU3 was actually released).

This has been corrected.
