### ISSUE TITLE
[FhirContext.newXmlParser] Potential Parsing Error when parsing previously generated xml/JSON string way back to resource

### ISSUE THREAD

**Issue by mosaic-hgw** [jamesagnew/hapi-fhir#720]
Hello,

right now we are running first implementational tests using and developing FHIR ressources. Therefore the provided FHIR-HAPI (version 2.5, DTSU3) massivly simplifies necessary work. Thank you.

Based on your documentation we designed a new FHIR-Type "ConsentTemplate" containing a existing FHIR resource "Person" to store contact information. Including this FHIR-Type in a new resource "ImportFormatDefinition" was no problem. 

(Resource ImportFormatDefinition-> Type ConsentTemplate-> Person contact)

Parsing it directly in JAVA to XML and/or JSON using FHIR-HAPI, the FHIRcontext and provided ParsingFunctionalities (encodeResourceToString) generated the expected XML/JSON output.

`
{"resourceType":"ImportFormatDefinition","meta":{"profile":["http://example.com/StructureDefinition/dontuse#ImportFormatDefinition"]},"supportedVersion":"2.5.x","templatesConsentTemplate":[{"domainName":"name","Name":"template_01","version":"1.0","title":"title","comment":"comment","contact":{"resourceType":"Person","name":[{"family":"Mustermann","given":["Max"]}],"telecom":[{"system":"email","value":"max.mustermann@mail.de"},{"system":"phone","value":"+49 1234 23232"}],"address":[{"text":"street 1-2","city":"city","postalCode":"12345","country":"Germany"}]}}]}`

But, parsing this generated and obviuously correct String back to a resource (parseResource) fails , when the string contains Person-Information. A java.lang.ClassCastException occurs in both cases (XML and JSON) when trying to parse the Person-info.

```
Exception in thread "main" java.lang.ClassCastException: org.hl7.fhir.dstu3.model.Person cannot be cast to ca.uhn.fhir.model.api.IResource
	at ca.uhn.fhir.parser.ParserState$PreResourceStateHapi.wereBack(ParserState.java:2259)
	at ca.uhn.fhir.parser.ParserState.pop(ParserState.java:124)
	at ca.uhn.fhir.parser.ParserState.access$100(ParserState.java:54)
	at ca.uhn.fhir.parser.ParserState$ElementCompositeState.endingElement(ParserState.java:1562)
	at ca.uhn.fhir.parser.ParserState.endingElement(ParserState.java:96)
	at ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:1415)
	at ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:1330)
	at ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:1413)
	at ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:1394)
	at ca.uhn.fhir.parser.JsonParser.parseChildren(JsonParser.java:1330)
	at ca.uhn.fhir.parser.JsonParser.doParseResource(JsonParser.java:265)
	at ca.uhn.fhir.parser.JsonParser.doParseResource(JsonParser.java:247)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:656)
	at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:705)
```

This problem only occurs if the Person-Information is set. Leaving it blank, parsing from resource to xml string and way back is not a problem.

Here is how we are including the Person-Resource into the Datatype
```
@DatatypeDef(name = "ConsentTemplate")
public class ConsentTemplate  extends Type implements ICompositeType {	
	[...]
	@Child(name = "contact", order = 8, min = 0, max = 1)
	@Description(shortDefinition = "responsible contact for this consent template")
	private Person contact= new Person();	


```

Here is how we are including the datatype in our Resource

```
@ResourceDef(name="ImportFormatDefinition", profile = "http://example.com/StructureDefinition/dontuse#ImportFormatDefinition")
public class ImportFormatDefinition extends DomainResource{
[...]
	@Child(name = "templates", order = 4, min = 1, max = Child.MAX_UNLIMITED)
	@Description(shortDefinition = "import information for 1-n consent templates")	
	private List<Type> templates = new ArrayList<Type>();	
[...]
```

Any recommendations or might it be an error in the FHIR-HAPI?

Thanks in advance!

**Comment by jamesagnew** [comment]
The fact that it's going into `PreResourceStateHapi` means that at some point in the parsing it's getting conmfused and thinking that this is a DSTU2 structure, which used a different interface (IResource) from all of the later structures (IAnyResource).

Can you put a breakpoint in the two constructors of ParserState.PreResourceStateHapi and see what is leading it to go there? Given that you are using a DSTU3 structure if should be going into PreResourceStateHl7Org

**Comment by mosaic-hgw** [comment]
Hello,

I made a break point in ParserState.class at Line 1664 and 2259. Parsing of ConsentTemplate-Class goes into PreResourceStateHapi instead of PreResourceStateHl7Org, but it is noticed as DSTU3. (see picture 1). Parsing seems no problem at this point. 

![screenshot_debugging_consent_template](https://user-images.githubusercontent.com/22166209/29827978-cd84ae76-8cdb-11e7-881e-b45e20dafec7.PNG)

A few lines later, when trying to cast the Person.class as IResource (getCurrentElement) the processing fails with the stated exception (see picture 2). Hope this info helps.

![screenshot_debugging_parser class](https://user-images.githubusercontent.com/22166209/29827993-d7c86dc8-8cdb-11e7-8383-6b00dbbcf81a.PNG)

**Comment by mosaic-hgw** [comment]
Any Suggestions?

**Comment by jamesagnew** [comment]
Hi @mosaic-hgw  - I've just given it a shot, and after some tweaking I was able to reproduce your issue.

Will keep you posted, but this should be fixable.

**Comment by jamesagnew** [comment]
Ok, fix incoming. Thanks for reporting! :)
