### ISSUE TITLE
hapi-fhir-jpaserver-example works only on port 8080

### ISSUE THREAD

**Issue by AlEilers** [jamesagnew/hapi-fhir#726]
Hi,

when creating and building the docker jpa server example like it is described in [this file](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-example/README.md#running-hapi-fhir-jpaserver-example-in-a-docker-container) it is running without any problem.

As soon as you map the image to another port like 8081 (with `-p 8081:8080`) you get a warning on the start page:  

    Warning!
    Failed to load conformance statement, error was: ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: Failed to parse response from server when performing GET to URL http://localhost:8081/baseDstu3/metadata - org.apache.http.conn.HttpHostConnectException: Connect to localhost:8081 [localhost/127.0.0.1] failed: Connection refused (Connection refused)

**Comment by thomasclifford** [comment]
I'm currently having the same issue.  The github project cqf-ruler runs just fine in multiple docker 
containers mapped this way.  Has there been any resolution of this issue ?
Thank you....

**Comment by AlEilers** [comment]
If I remember correctly I solved this by editing the base URL in [this file](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirTesterConfig.java#L45).

**Comment by thomasclifford** [comment]
Yeah, I was wondering about that.I asked another device where I was about it, and he says you can dynamically switch the port (and maybe the IP address too).Thanks for the reply.

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 26, 2018 at 10:27 AM, Alexander Eilers<notifications@github.com> wrote:   
If I remember correctly I solved this by editing the base URL in this file.

**Comment by antoninod** [comment]
Hi,

I'm having the same issue too.
What I am trying to do is to launch several docker containers running the hapi-fhir-jpaserver-example. 
As @AlEilers, I'm getting a warning when I try to map an image to the 8081 port. I tried to replace the base url in the FhirTesterConfig class by "http://localhost:8081/baseStu3", but it didn't work.
Moreover, it seems like, when I build the second image after modifying the configuration in the FhirServerConfig class, the newly built image still uses the configuration of the first one.

Could you tell me if I'm doing something wrong? How did you resolve or work around this issue?

Thanks

**Comment by ahanoff** [comment]
@AlEilers @thomasclifford  I think I'm facing the same issue. Did you just add new server in your TesterConfig? Or I can configure serverBase variable so it can work with another port? Thanks
