### ISSUE TITLE
Creating resource problem and persistence

### ISSUE THREAD

**Issue by karkaletsis** [jamesagnew/hapi-fhir#729]
I have implemented a method for creating a patient which does the followin:
1. Tries to find if patient exists with a specific identifier
2. If not found creates a new patient

What I saw is that if I run very quickly 2 times this method, the second time the step 1 fails to find the patient, and so creates it again. If I wait for some seconds between step 1 and step 2 all are ok.

I am using this code for creating a client
 protected FHIRClient() {
        try {
            ourCtx = FhirContext.forDstu3();
            LOG.info("Initializing the HAPI FHIR Client .... ");
            ourCtx.getRestfulClientFactory().setServerValidationMode(ServerValidationModeEnum.NEVER);
            ourCtx.getRestfulClientFactory().setSocketTimeout(1200 * 1000);
            String serverBase = "http://localhost:8080/hapi-fhir-jpaserver-example/baseDstu3";
            ourClient = ourCtx.newRestfulGenericClient(serverBase);
            ourClient.registerInterceptor(new LoggingInterceptor(true));
            LOG.info("HAPI FHIR Client initialized");
        } catch (Exception e) {
            e.printStackTrace();
            LOG.error("Error - HAPI FHIR Clien not initialized");
        }
    }

and then I have this method for creating a resource
   public String createResource(DomainResource resource) {
        MethodOutcome outcome = ourClient.create()
                .resource(resource)
                .prettyPrint()
                .encodedJson()
                .execute();
        IIdType id = outcome.getId();
        System.out.println("Got ID: " + id.getValue());
        return id.getValue();
    }

Any idea?

If I look from the web interface and do the seach after first creation, the patient can be found.

**Comment by KevinMayfield** [comment]
Are you using a single PUT to do 1 and 2?

e.g. something like this?

MethodOutcome outcome = client.create()
        .resource(patient)
        .conditionalByUrl("Patient?identifier=system%7C00001")
        .execute();

**Comment by karkaletsis** [comment]
For 1 (search) I am using 
 Bundle bundle = client.getOurClient().search().forResource(Patient.class)
                .where(new TokenClientParam("identifier").exactly().code(patientIdentifier))
                .returnBundle(Bundle.class)
                .execute();

and for 2 (create)
MethodOutcome outcome = ourClient.create()
.resource(resource)
.prettyPrint()
.encodedJson()
.execute();

**Comment by KevinMayfield** [comment]
My guess is it’s not hitting the database on the second call, instead running the query against the lucene index and the identifier there (yet).

**Comment by karkaletsis** [comment]
Yes, perhaps it should be like this. But the strange is if I wait some seconds before rerunning all are ok. It seems that some delay in search interface

**Comment by jamesagnew** [comment]
There is query result caching in place (assuming you're using the latest version of HAPI?) which is almost certainly causing the results you are seeing.

You have two options:

* Use a conditional create, as @KevinMayfield suggests (this is the better approach since conditional operations disable the caching automatically)
* Disable the caching globally via the setting on the DaoConfig

**Comment by karkaletsis** [comment]
I put in DaoConfig	
retVal.setReuseCachedSearchResultsForMillis(null);

and now it works as expected;
