### ISSUE TITLE
WW

### ISSUE THREAD

**Issue by Weglarz** [jamesagnew/hapi-fhir#730]
Hi
Test server don't working properly:
![testserver_uhn_hapi server stu3 fhir](https://user-images.githubusercontent.com/28480250/30578969-cbc992a4-9d16-11e7-9aa9-a4cda541236a.PNG)

**Comment by KevinMayfield** [comment]
Have a look in the log files. It seems you’re FHIR server hasn’t started up (but the web front end has).

Normally I see this when I’d misconfigured the database

**Comment by Weglarz** [comment]
This FHIR server is not my server, it is public test server started from:

**Comment by KevinMayfield** [comment]
Yep its down.

**Comment by jamesagnew** [comment]
Ah thanks for the heads up. For some reason my monitor didn't trigger.. weird.

I'm restarting it now.

**Comment by Weglarz** [comment]
Thank You
