### ISSUE TITLE
FHIR Data Encryption

### ISSUE THREAD

**Issue by karkaletsis** [jamesagnew/hapi-fhir#732]
Hello, I try to investigate how to provide data encryption in FHIR Database. I first saw the database tables and found the table "HFJ_RESOURCE" which contains info about my stored resources. How these data stored in Database? With some encryption? Can I change in this case the encryption key?

**Comment by jamesagnew** [comment]
Hi @karkaletsis - The data in that column is compressed with Gzip, but it is not encrypted.

We've had a few people ask about encryption and I'm certainly not opposed to adding it but it's not in there right now.

**Comment by karkaletsis** [comment]
Thanks for your answer. It would be great to have some type of encryption as we have sensitive data
