### ISSUE TITLE
I can not access to extended operation like $ in JaxRS ?

### ISSUE THREAD

**Issue by Weglarz** [jamesagnew/hapi-fhir#737]
I use JAX-RS Server as a hapifhir server. Is there any way to use   extended operation like $everything, $lookup, etc as bellow  or I have to develop my own custom operation?

![image](https://user-images.githubusercontent.com/28480250/30801002-1db53f94-a1e2-11e7-9a09-fef030c37360.png)

**Comment by gitrust** [comment]
This issue is still open but FHIR JAX-RS documentation 3.5 (http://hapifhir.io/doc_rest_server_jaxrs.html) says

>  The server currently supports Conformance Statements, @Read, @Search, @Create, @Update, @Delete and @Operation. 

Has this request been already implemented?

I was just looking for Observation/$lastn operation.
