### ISSUE TITLE
Server Side Gzip answer

### ISSUE THREAD

**Issue by parisni** [jamesagnew/hapi-fhir#738]
Hey,

I get performances bottleneck when sharing the json between. I have not found
any documented way to gzip the json/xml to the client.
I only found a way for the client to gzip it's data passed to server

Thanks

**Comment by jamesagnew** [comment]
Hi @parisni , 

The client can request Gzip compressed content by using the [Accept-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) header. If this is set with a value of `gzip` HAPI's RestfulServer will automatically compress response content.

Note: Please direct questions to the HAPI FHIR [Google Group](https://groups.google.com/forum/#!forum/hapi-fhir) and not the issue tracker.
