### ISSUE TITLE
Hapi-Fhir DSTU2 and STU3 validation of Medication Issue

### ISSUE THREAD

**Issue by WyldWilly** [jamesagnew/hapi-fhir#739]
When you go to validate the full JSON for Medication in both, Hapi strips out the entry for Ingredient that is in the JSON and then errors out complaining that Ingredient is not present.

Here is my sample.
{
    "resourceType": "Medication",
    "code": {
        "coding": [
            {
                "system": "urn:2.16.840.1.113883.6.88",
                "code": "1191",
                "display": "aspirin"
            }
        ],
        "text": "ASPIRIN 325 MG TABLET"
    },
    "form": {
        "coding": [
            {
                "system": "http://upmc.com/enterprises/rakia/rakida/cerner/h1/medication/form/code",
                "code": "687545",
                "display": "Tab"
            }
        ],
        "text": "Tab"
    },
    "ingredient": [
        {
            "item": {
                "reference": "medication/613168",
                "display": "aspirin"
            },
            "amount": {
                "numerator": {
                    "value": "650",
                    "unit": "mg",
                    "system": "http://upmc.com/enterprises/rakia/rakida/cerner/h1/medication/strength/unit",
                    "code": "MG"
                },
                "denominator": {
                    "value": "2",
                    "unit": "tab(s)",
                    "system": "http://upmc.com/enterprises/rakia/rakida/cerner/h1/medication/volume/unit",
                    "code": "TAB"
                }
            }
        }
    ]
}

**Comment by jamesagnew** [comment]
Hi @WyldWilly ,

The `item` element on the FHIR [resource defnition](http://hl7.org/fhir/medication.html) is actually called `item[x]`. The JSON object name needs to be `itemReference`, not just `item`. I'm fairly sure that's why this isn't validating cleanly.

**Comment by WyldWilly** [comment]
Thanks will try that.

Sent from my 10BX iPhone

On Sep 27, 2017, at 21:35, James Agnew <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @WyldWilly<https://github.com/wyldwilly> ,

The item element on the FHIR resource defnition<http://hl7.org/fhir/medication.html> is actually called item[x]. The JSON object name needs to be itemReference, not just item. I'm fairly sure that's why this isn't validating cleanly.

**Comment by WyldWilly** [comment]
Hi James. Sorry I had a wire crossed. DSTU2 is Item. But STU3 is ItemReference. It still fails in DSTU2 as Item.

WMC

**Comment by jamesagnew** [comment]
In DSTU2 the `ingredient` element is not at the root of the model (it's inside an element called `product`) so that resource would not be a valid DSTU2 medication either unfortunately. :)

http://hl7.org/fhir/DSTU2/medication.html
