### ISSUE TITLE
paging & _elements problem

### ISSUE THREAD

**Issue by parisni** [jamesagnew/hapi-fhir#750]
Hi

In case of a search query, when one need to subset the Resource's elements returned, it can use _elements.

> http://fhirtest.uhn.ca/baseDstu3/Observation?_elements=id&_count=10&_pretty=true

Then the result is subseted:

   

>  {
>       "fullUrl": "http://fhirtest.uhn.ca/baseDstu3/Observation/147601",
>       "resource": {
>         "resourceType": "Observation",
>         "id": "147601",
>         "meta": {
>           "versionId": "1",
>           "lastUpdated": "2017-06-16T16:33:09.047-04:00",
>           "tag": [
>             {
>               "system": "http://hl7.org/fhir/v3/ObservationValue",
>               "code": "SUBSETTED",
>               "display": "Resource encoded in summary mode"
>             }
>           ]
>         }
>       },
>       "search": {
>         "mode": "match"
>       }
>     },
> 

To get the 500 next items, the HAPI server gives a "next link":

>     {
>       "relation": "next",
>       "url": "http://fhirtest.uhn.ca/baseDstu3?_getpages=2f8d49e4-9269-4040-8cfe-8958f441be06&_getpagesoffset=10&_count=10&_pretty=true&_bundletype=searchset"
>     }

However, the resulting bundle is not subseted anymore:

 

>    {
>       "fullUrl": "http://fhirtest.uhn.ca/baseDstu3/Observation/147601",
>       "resource": {
>         "resourceType": "Observation",
>         "id": "147601",
>         "meta": {
>           "versionId": "1",
>           "lastUpdated": "2017-06-16T16:33:09.047-04:00"
>         },
>         "identifier": [
>           {
>             "value": "1.3.6.1.4.1.16517"
>           }
>         ],
>         "status": "final",
>         "code": {
>           "coding": [
>             {
>               "system": "http://loinc.org",
>               "code": "2823-3",
>               "display": "Potassium [Moles/volume] in Serum or Plasma"
>             }
>           ]
>         },
>         "subject": {
>           "reference": "Patient/undefined"
>         },
>         "effectiveDateTime": "2014-02-11T13:54:00",
>         "valueQuantity": {
>           "value": 4.4,
>           "unit": "mmol/L"
>         },
>         "referenceRange": [
>           {
>             "text": "3.4-5.0 mmol/L"
>           }
>         ]
>       },
>       "search": {
>         "mode": "match"
>       }
>     },
> 

Am I missing something ?

The syntax 

> http://fhirtest.uhn.ca/baseDstu3?_elements=id&_getpages=2f8d49e4-9269-4040-8cfe-8958f441be06&_getpagesoffset=0&_count=10&_pretty=true

returns an empty bundle

> 
> {
>   "resourceType": "Bundle",
>   "id": "79b5eef7-d52d-4608-9723-6ec5aa96f6ed",
>   "meta": {
>     "lastUpdated": "2017-10-07T08:48:47.859-04:00",
>     "tag": [
>       {
>         "system": "http://hl7.org/fhir/v3/ObservationValue",
>         "code": "SUBSETTED",
>         "display": "Resource encoded in summary mode"
>       }
>     ]
>   }
> }

Thanks

**Comment by jamesagnew** [comment]
Thanks for reporting! Checking in a fix now.
