### ISSUE TITLE
Delete operation does not respect InCompartment AuthorizationInterceptor

### ISSUE THREAD

**Issue by alvinleonard** [jamesagnew/hapi-fhir#751]
When deleting a resource by URL such as `Observation?performer=<somepatientid>`, the Rule checker is using the resource that has been deleted and hence returning null for InCompartment case.

This issue has been fixed for deleting by ID `Observation/123` in #503.

**Comment by jamesagnew** [comment]
Hi @alvinleonard - I added some tests, and this seems to work for me. Could you have a look at this test and see if it's missing something from what you're seeing? 

https://github.com/jamesagnew/hapi-fhir/commit/37c8e6c6458bb3ba8a50b0fe3eeaff2cd79457a3#diff-d37b27bd7523a9eb1a80c4d245074897R91

**Comment by alvinleonard** [comment]
Test looks good to me. Delete of Observation in patient compartment is allowed and blocked when it is not assigned to any patient.

**Comment by jamesagnew** [comment]
I'm not totally clear on the difference between this and #756. How is that bug different from this one?

I'm also not really sure about this one for that matter.. It was already working as designed as far as I can tell. I added an extra test to be sure, but I believe this was already working unles I'm missing something.

**Comment by alvinleonard** [comment]
Hi James, #751 and #756 is actually talking about the same problem.

Ok I get what you mean. So if you look at #756 tests, basically if you try to delete the Observation using a condition, it does not work. For example, 

Delete /Observation?performer=1234
