### ISSUE TITLE
invalid character, please remove.

### ISSUE THREAD

**Issue by janol77** [jamesagnew/hapi-fhir#758]
https://github.com/jamesagnew/hapi-fhir/blob/9d6bfdc25a64c4e8adbacfd5d15253c1fd7ca11b/hapi-fhir-validation/src/main/java/org/hl7/fhir/dstu3/validation/InstanceValidator.java#L295

**Comment by jamesagnew** [comment]
What the heck? How did that get there? Thanks for reporting :)
