### ISSUE TITLE
Missing codesystems enums in structures-dstu3

### ISSUE THREAD

**Issue by CarthageKing** [jamesagnew/hapi-fhir#761]
Hello,

I am trying to upgrade to HAPI FHIR 3.0.0 but found that structures-dstu3 does not contain the "codesystems" package. https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-fhir-structures-dstu3/src/main/java/org/hl7/fhir/dstu3/model

However, the R4 package contains them: https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-fhir-structures-r4/src/main/java/org/hl7/fhir/r4/model

Is it possible to regenerate the codesystems for STU3 in the next release? I believe HAPI FHIR 2.5 had these codesystems so not sure why they disappeared in HAPI FHIR 3.0.0.

Best Regards,

**Comment by ohr** [comment]
+1

**Comment by jamesagnew** [comment]
Weird, I don't know why that didn't make it across in the last sync.

I'm adding a unit test to make sure those don't get omitted again.
