### ISSUE TITLE
Parameters: _has, _include and _revinclude

### ISSUE THREAD

**Issue by Weglarz** [jamesagnew/hapi-fhir#763]
I'am using hapifhir version 2.5  with implementation server as is described in http://hapifhir.io/doc_rest_server_jaxrs.html

I'd like search Practitioners with specified specialty  in PractitionerRole. When I'am using 

http://mymedic.com.pl:8082/Practitioner?_revinclude:PractitionerRole:practitioner:specialty=0731

it returns all Practitioners not only these with specialty=0731. It seams that in version 2.5 these parameters are not active ?

My be in hapifhir version 3.0 these parameters: _has, _include and _revinclude was implemented ?

**Comment by jamesagnew** [comment]
Hi @Weglarz , please use the project Google Group to ask questions.

Please see the following link: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/hapi-fhir/xYw7XH49unU/JdZDIicgBQAJ
