### ISSUE TITLE
Undocumented "Test" resource

### ISSUE THREAD

**Issue by vlad-ignatov** [jamesagnew/hapi-fhir#765]
Some clients of ours are having issues with the DSTU2 conformance statement. They are using third-party libraries (like https://github.com/ewoutkramer/fhir-net-api) to walk over the conformance statement and do something with any resource... Unfortunately, that fails on DSTU2 because of the "Test" resource. 

You can see it existing at http://fhirtest.uhn.ca/baseDstu2/metadata and http://fhirtest.uhn.ca/baseDstu2/Test. Such a resource type is not documented anywhere (or I can't find it). Furthermore, the clients are trying to load the profile reference (http://hl7.org/fhir/profiles/Test) which yields 404...

So, the question is: can this "invalid" resource be removed from the conformance statement?

Thanks

**Comment by jamesagnew** [comment]
Thanks for reporting! I have no idea why that is there, to be honest. Will remove.
