### ISSUE TITLE
Resources with deleted references can't be deleted

### ISSUE THREAD

**Issue by gsureshkumar** [jamesagnew/hapi-fhir#773]
Here are the steps.
1. Create a Patient.
2. Create a DiagnosticStudy with the subject as the created patient.
3. Delete the DiagnosticStudy (study is deleted)
4. Try deleting the Patient (the server complains of existing reference DiagnosticStudy)

Observed only in v3.0 (DSTU2)

**Comment by jamesagnew** [comment]
Hi @gsureshkumar , I've added a unit test and it seems to work ok for me: https://github.com/jamesagnew/hapi-fhir/commit/395c8b6acc4141721f6bae01b482b631a528b092

Can you verify whether you are seeing this behaviour on the fhirtest.uhn.ca server?
