### ISSUE TITLE
Deserialization issue with jil . the exception says jil.deserialization  expected { null

### ISSUE THREAD

**Issue by hanu05** [jamesagnew/hapi-fhir#779]
XmlNode xmlnode = xmlDoc.GetElementsByTagName("GetCompositeRxDetailsResponse")[0];
            XmlNode imageDataNode = xmlnode.SelectSingleNode("imageData");
       
           jsonText = Jil.JSON.Serialize(xmlnode.OuterXml);
            jsonText = Regex.Replace(jsonText, "\"\\s*(.*?)\\s*\"", "\"$1\"");  //Regex to trim the string value
            var typed = Jil.JSON.Deserialize<LoadResponse>(jsonText); 
            LoadResponse loadResponse = Jil.JSON.DeserializeDynamic(jsonText);

please let me the reason for the exception

**Comment by jamesagnew** [comment]
Hi @hanu05 , did you create this bug against the wrong project? This does not appear to be anything to do with HAPI FHIR.
