### ISSUE TITLE
DSTU2: Transaction bundle with a single search request that filters by patient identifier, returns incorrect result

### ISSUE THREAD

**Issue by sreinst1** [jamesagnew/hapi-fhir#780]
In DSTU2, searching for List resources with a patient identifier filter, works fine when issued on its own. However, it returns incorrect results (as if the patient identifier filter is ignored) when included in a Transaction or a Batch bundle.
Here's an example of such a Transaction bundle:
{
  "resourceType": "Bundle",
  "type": "transaction",
  "entry": [
    {
      "fullUrl": "urn:uuid:61ebe359-bfdc-4613-8bf2-c5e300945f0a",
      "request": {
        "method": "GET",
        "url": "List?patient.identifier=https://www.lumc.nl|10215&_include=*"
      }
    }
  ]
}

The results of this transaction include both the Lists of the requested patient, and also the Lists of all other patients as well. Here's a small part of the results of the above bundle; you can see that there are two different patient resources in the results. (And of course, in the FHIR server this was executed on, there are no two Patient resources with the same patient identifier.)
                    {
                        "fullUrl": "http://localhost:8080/onco-fhir-dummy-ois-dev-organization-server/baseDstu2/List/32695",
                        "resource": {
                            "resourceType": "List",
                            "id": "32695",
                            "meta": {
                                "versionId": "4",
                                "lastUpdated": "2017-10-27T18:47:09.177+03:00"
                            },
                            "extension": [
                                {
                                    "url": "philips-ois-provenance-agent-role",
                                    "valueString": "enterer"
                                }
                            ],
                            "code": {
                                "coding": [
                                    {
                                        "system": "http://snomed.info/sct",
                                        "code": "108290001",
                                        "display": "Radiation oncology AND/OR radiotherapy "
                                    }
                                ]
                            },
                            "subject": {
                                "reference": "Patient/28226"
                            },
                            "status": "current",
                            "mode": "working",
                            "entry": [
                                {
                                    "item": {
                                        "reference": "Procedure/55144"
                                    }
                                },
                                {
                                    "item": {
                                        "reference": "Procedure/55145"
                                    }
                                }
                            ]
                        },
                        "search": {
                            "mode": "match"
                        }
                    },
                    {
                        "fullUrl": "http://localhost:8080/onco-fhir-dummy-ois-dev-organization-server/baseDstu2/List/39101",
                        "resource": {
                            "resourceType": "List",
                            "id": "39101",
                            "meta": {
                                "versionId": "6",
                                "lastUpdated": "2017-10-24T15:10:27.371+03:00"
                            },
                            "extension": [
                                {
                                    "url": "philips-ois-provenance-agent-role",
                                    "valueString": "enterer"
                                }
                            ],
                            "code": {
                                "coding": [
                                    {
                                        "system": "http://snomed.info/sct",
                                        "code": "367336001",
                                        "display": "Chemotherapy"
                                    }
                                ]
                            },
                            "subject": {
                                "reference": "Patient/34124"
                            },
                            "status": "current",
                            "mode": "working",
                            "entry": [
                                {
                                    "item": {
                                        "reference": "Procedure/39450"
                                    }
                                },
                                {
                                    "item": {
                                        "reference": "Procedure/39451"
                                    }
                                },
                                {
                                    "item": {
                                        "reference": "Procedure/39452"
                                    }
                                },
                                {
                                    "item": {
                                        "reference": "Procedure/39453"
                                    }
                                }
                            ]
                        },
                        "search": {
                            "mode": "match"
                        }
                    },

**Comment by sreinst1** [comment]
I've updated my bug report. It turns out that the search request does not work correctly in a bundle, both in Batch and Transaction mode. It seems like, when the request is part of a bundle, the patient filter is ignored.

**Comment by RingOfStorms** [comment]
Confirming this bug. I can do a search for `Observation?subject=51673&code=185923000&_elements=_id` normally and will get the expected resource back with just the _id field. If I put it into a Bundle the result has the full object. It seems like many search parameters stop working in bundles.
