### ISSUE TITLE
If-Match Header / ETAG Support for Weak Comparison

### ISSUE THREAD

**Issue by thomasKalmar** [jamesagnew/hapi-fhir#782]
We currently use HAPI FHIR RestClient. Our server sends ETAGs in the form W/"123" so according to https://tools.ietf.org/html/rfc7232#section-3.1 a Weak Comparison should be used. The (HAPI)client always sends an If-Match Header without the leading W/ so the comparison never succeds. We solved the problem with an custom interceptor, but it would be nice to have support for this directly build into HAPI.

**Comment by mjhcorporate** [comment]
This behavior is also relevant to us. Contrary to [what the docs say](https://hapifhir.io/hapi-fhir/docs/client/generic_client.html#etags), the If-Match header that is being sent by the HAPI BaseClient is a strong ETag. In my opinion, it should be sending a weak ETag (starting with `W/`).

**Comment by mjhcorporate** [comment]
For those that are facing the same issue: Here is an example Client Interceptor that prefixes the ETag with `W/`. Don't forget to register this interceptor using something like `client.registerInterceptor(new ETagWeakifyingInterceptor());`!

``` java
@Interceptor
public class ETagWeakifyingInterceptor {

    private static final String IF_MATCH_KEY = "If-Match";

    /**
     * Prefixes the If-Match header value with `W/`
     * 
     */
    @Hook(Pointcut.CLIENT_REQUEST)
    public void outgoingRequestModifier(IHttpRequest theRequest) {
        List<String> headerValues = theRequest.getAllHeaders().get(IF_MATCH_KEY);
        if (null == headerValues) {
            // nothing to add -> return
            return;
        }
        String ifMatchHeaderValue = headerValues.get(0);

        if (!ifMatchHeaderValue.startsWith("W/")) {
            ifMatchHeaderValue = "W/" + ifMatchHeaderValue;
            theRequest.removeHeaders(IF_MATCH_KEY);
            theRequest.addHeader(IF_MATCH_KEY, ifMatchHeaderValue);
        }
    }
}
```
