### ISSUE TITLE
Modularize hapi-fhir-osgi-core

### ISSUE THREAD

**Issue by joedai** [jamesagnew/hapi-fhir#784]
Currently, the hapi-fhir-osgi-core is an all-in-one module which has everything in one big jar, e.g. client, server, model, utils etc. This means we will have to release the whole thing even for small bug fixes.

Do we have any plan to modularize it into individual bundles in the same way as we have done for the standard libraries?

**Comment by bdenton** [comment]
The only reason all of the core and resource modules are bundled together is that there are “split packages” (Java package appearing in multiple JARs) in those projects which OSGi does not really allow. My original goal when writing the hapi-osgi-core project was just to publish all of the core projects as OSGi bundles. I did some analysis at the time and determined that three or four packages (mostly around the model classes) that would need to be refactored to allow this. At the time, James thought that this could possibly break existing user code.

Cheers,
Bill Denton
Akana/Rogue Wave

**Comment by jamesagnew** [comment]
I just realized we have two open bugs about this (other one is  #777 )
