### ISSUE TITLE
Conformance issue with STU3 context

### ISSUE THREAD

**Issue by c-schuler** [jamesagnew/hapi-fhir#787]
Looks like there was a fix for issues #517 and #518 that is causing new issues in my hapi fhir server (using 3.1.0-SNAPSHOT).
```
ca.uhn.fhir.parser.DataFormatException: Unknown resource name "Conformance" (this name is not known in FHIR version "DSTU3")
	at ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:369)
	at ca.uhn.fhir.rest.client.impl.RestfulClientFactory.validateServerBase(RestfulClientFactory.java:305)
	at ca.uhn.fhir.rest.client.impl.RestfulClientFactory.validateServerBaseIfConfiguredToDoSo(RestfulClientFactory.java:264)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:210)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:448)
	at ca.uhn.fhir.rest.client.impl.GenericClient$SearchInternal.execute(GenericClient.java:1776)
```
Unsure how to resolve. Please advise.

Thank you.

**Comment by jamesagnew** [comment]
Hi @c-schuler , @speriosu, Would you be able to provide a code snippet that shows how to reproduce this issue?

**Comment by speriosu** [comment]
I figured out the problem. I was adding HAPI to an existing Maven project that referenced Gson as a dependency, with a version of 2.1. **By removing Gson from my own pom.xml entirely (I wasn't actually using it in my own code anymore) the error messages magically went away.** I checked HAPI's own pom.xml, and sure enough it depends on Gson 2.8.1. Just to confirm, I added the dependency to Gson back to my own pom.xml file with a version of 2.8.1, and things continued to work.

**Comment by jamesagnew** [comment]
Ah interesting. Thanks for following up!

@c-schuler any chance it's the same issue for you?

**Comment by jeffeastman** [comment]
I changed the gson version in cqf-ruler from 2.8.0 to 2.8.1 and am still getting the e500 on the CDS-Hook request in the above issue. So I'd say no, this doesn't resolve c-schuler (and my) issue.

**Comment by c-schuler** [comment]
Changing the gson version partially solved the problem. There was also an issue with the cds hooks request that was resulting in the same error, which made things confusing. Thank you @speriosu, @jamesagnew, and @jeffeastman!
