### ISSUE TITLE
JPA Server - Example - Issue with Lucene in Hibernate - unkown definition: standardAnalyzer

### ISSUE THREAD

**Issue by martinbenedict** [jamesagnew/hapi-fhir#789]
Last week I have set up an own HAPI FHIR server based on the basic JPA example server contained in the sources. Everything ran until today. 

Since today, without doing any changes in POM and other configurations, I am faced with the following exception, when starting the JPA example server in a jetty context (I've added the full log attached to this message):

` org.hibernate.search.exception.SearchException: Lucene analyzer found with an unknown definition: standardAnalyzer`
[standardAnalyzer-exception.txt](https://github.com/jamesagnew/hapi-fhir/files/1478185/standardAnalyzer-exception.txt)

This message also appears if I pull the unchanged hapi-fhir-jpaserver-example and doing the following steps:

1. mvn clean
2. mvn install
3. chmod -R 777 target/
4. jetty:run

I've already wiped my .m2 local repository. The effect persists. Furthermore I checked to use fixed values for 

`extraProperties.put("hibernate.search.lucene_version", "LUCENE_CURRENT");`

replaced by 

`extraProperties.put("hibernate.search.lucene_version", "LUCENE_57");`

I would be grateful for any ideas to solve this problem.

EDIT: I missed to mention, that I use 3.1.0-SNAPSHOT. The fail also appears when running `mvn install` for hapi-fhir-jpaserver-example. The fail appears the in the test `ExampleServerIT`.
[ca.uhn.fhir.jpa.demo.ExampleServerIT-output.txt](https://github.com/jamesagnew/hapi-fhir/files/1478544/ca.uhn.fhir.jpa.demo.ExampleServerIT-output.txt)

**Comment by c-schuler** [comment]
I had this same issue. Went away when I added the following [line](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfig.java#L84) to my server config.

**Comment by jamesagnew** [comment]
Closing this, as we have now added that newly required line to all of our examples and added a note about it to the changelog.

Please feel free to reopen if this doesn't help for you.

**Comment by martinbenedict** [comment]
Worked for me! Thank you!

**Comment by bratwurzt** [comment]
Would it be possible to reference the soluctions to issues without referencing files that don't exist anymore?
https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-example/src/main/java/ca/uhn/fhir/jpa/demo/FhirServerConfig.java#L84

**Comment by theshoeshiner** [comment]
Files no longer exist. Can someone just paste the solution into a comment?
