### ISSUE TITLE
Search _count parameter implementation broken in release 3.0.0

### ISSUE THREAD

**Issue by dlynch33** [jamesagnew/hapi-fhir#793]
With HAPI 2.5, when searching for resources, _count specifies how many "primary" resources I want returned, not including any resources included via _include parameter. For example, if I search for ProcedureRequest resources with _count=10 and an _include on ProcedureRequest.subject, I might get back a Bundle containing 10 ProcedureRequests and 10 Patients.

With 3.0.0, it seems that the _count now covers all returned resources. So, for the same search I might get back 7 ProcedureRequests and 3 Patients - no more than 10 resources total, counting both "matches" and "includes".

Seems like this will make it significantly more difficult to implement paging features. Is this an intentional change, and can it be reversed via configuration? Or, a bug?

**Comment by jamesagnew** [comment]
Hi @dlynch33,

I have added a test case, and I am not able to reproduce this locally, and the following query seems to return the expected results as well: http://hapi.fhir.org/baseDstu3/Patient?organization:missing=false&_include=Patient:organization&_count=2

Would you be able to supply any additional details about how to trigger this?

**Comment by dlynch33** [comment]
Hi @jamesagnew,

I'm also unable to reproduce this anywhere other than my local HAPI instance running against a local Derby DB.  I can't reproduce it when I switch my local instance to point to the Public HAPI Test Server, and other developers in my organization can't reproduce it (even locally).  I pulled down 3.1.0 and see the same odd behavior.  I guess I can chalk it up to something odd about how my dev machine is set up.  No idea what though.  I guess you should close this as "unable to reproduce".

**Comment by jamesagnew** [comment]
Oh man I hate that kind of thing. Oh well, I'll close, but by all means feel free to reopen if it comes back.
