### ISSUE TITLE
FhirContext is not threadsave on initialization

### ISSUE THREAD

**Issue by jodue** [jamesagnew/hapi-fhir#794]
The first time a resource is created with the FhirContext class the resource types are scanned ie. validateInitialized is called. If multiple parallel requests are incoming, the first will start the initialization and the second will skip this and use the uninitialized class which then results in a NPE.

The synchronization method in FhirContext.validateInitialized is not sufficient to cover this case.

**Comment by jamesagnew** [comment]
Hi @jodue - Would you be able to provide code which shows how to replicate this?

**Comment by jodue** [comment]
`public static void main( String args[] )
    {
        FhirContext dstu3FhirContext = FhirContext.forDstu3();
        for ( int i = 0; i < 10; i++ )
        {
            new Thread( new Runnable()
            {
                @Override
                public void run()
                {
                    OperationOutcomeUtil.newInstance( dstu3FhirContext );
                }
            } ).start();
        }
    }`

Will result in multiple NPEs:
`Exception in thread "Thread-4" java.lang.NullPointerException
	at ca.uhn.fhir.context.FhirContext.getResourceDefinition(FhirContext.java:376)
	at ca.uhn.fhir.util.OperationOutcomeUtil.newInstance(OperationOutcomeUtil.java:138)
	at com.agfa.mma.launchers.Test$1.run(Test.java:33)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by jamesagnew** [comment]
Awesome, thanks! I'll have a look.

**Comment by jamesagnew** [comment]
@jodue - Hmm, weird! I added a [test method](https://github.com/jamesagnew/hapi-fhir/commit/d1f8bce4173e48a2391c2dc1a084cce962160be9#diff-48b63e870e38916337934d16f3d7f392R111) using your code, but it passes consistently for me.

Can you describe your set up? What version of HAPI are you using, what platform, what version of Java, etc?

**Comment by jodue** [comment]
Hi James, sadly i'm still using HAPI FHIR 2.3 and obviously should update! After trying my test case on version 3.0.0 i found out that this issue was already fixed in #610! Sorry for the additional work!

In the future i will try with the newest version before submitting a bug! :)
