### ISSUE TITLE
JsonParser : Meta tag is not serialized for types that only implement IBaseResource

### ISSUE THREAD

**Issue by ohaganniall** [jamesagnew/hapi-fhir#795]
ca.uhn.fhir.parser.JsonParser.encodeResourceToJsonStreamWriter (Line 643) will only serialize the "meta" tag (including tags, profiles, etc.) if the provided resource implements IResource.  This means that the "meta" tag is excluded for resources that only implement the IBaseResource interface (which also provides "getMeta") but that do not also implement IResource, e.g. the "Binary" class

**Comment by jamesagnew** [comment]
Hi @ohaganniall - Which version of the structures and which version of HAPI are you seeing this with? Would you be able to provide sample code which shows what you're seeing?

The intent at least is that for the DSTU3+ structures (as well as the hl7org-dstu2 structures) the Meta element is a normal element and doesn't need any special handling. Probably there is some situation where this isn't working as expected though..

**Comment by ohaganniall** [comment]
Sorry, that info really would've helped up front ..... lesson learned for next time
We're seeing the issue with the DSTU3 model using ca.uhn.hapi.fhir:hapi-fhir-client:3.0.0, sample JUnit5 test attached
[JsonParserSerializeMetaTest.zip](https://github.com/jamesagnew/hapi-fhir/files/1488204/JsonParserSerializeMetaTest.zip)

**Comment by jamesagnew** [comment]
Ah awesome, thanks! Will have a look.
