### ISSUE TITLE
Spaces in query strings get encoded as + plus signs instead of %20

### ISSUE THREAD

**Issue by jamesdaily** [jamesagnew/hapi-fhir#796]
In the Java client, when producing a URL, space characters in query strings get encoded as + plus signs instead of %20.

For example a search for address "123 main street" would produce a URL such as:

`https://example.com/search?address=123+main+street`

This is correct for application/x-www-form-urlencoded, but for non-forms based applications, it should just be RFC 3986 which uses %20 instead of + signs for spaces within query strings values.

Is it possible to configure this to use %20 instead:

`https://example.com/search?address=123%20main%20street`

It looks like the code responsible for the + signs is the URLEncoder.encode call here in `ca.uhn.fhir.rest.client.method.HttpGetClientInvocation`

```	
private boolean addQueryParameter(StringBuilder b, boolean first, String nextKey, String nextValue) {
		boolean retVal = first;
		if (retVal) {
			b.append('?');
			retVal = false;
		} else {
			b.append('&');
		}
		try {
			b.append(URLEncoder.encode(nextKey, "UTF-8"));
			b.append('=');
			b.append(URLEncoder.encode(nextValue, "UTF-8"));
		} catch (UnsupportedEncodingException e) {
			throw new ConfigurationException("Could not find UTF-8 encoding. This shouldn't happen.", e);
		}
		return retVal;
	}
```

**Comment by jamesagnew** [comment]
Thanks for reporting! Fix incoming.
