### ISSUE TITLE
Unable to use @Read annotation with the HAPI FHIR Jax-RS server base with R4 and DSTU2_1 Fhir contexts

### ISSUE THREAD

**Issue by InfiniteLoop90** [jamesagnew/hapi-fhir#799]
I'm unable to use `@Read` annotation with the HAPI FHIR Jax-RS server base with R4 and DSTU2_1 Fhir contexts.
I get the following stacktrace:
[jaxrs-read-r4-error.txt](https://github.com/jamesagnew/hapi-fhir/files/1511282/jaxrs-read-r4-error.txt)

It looks like the `JaxRsRequest` class wasn't updated to support the R4 and DSTU2_1 contexts.

**Comment by jamesagnew** [comment]
Fix merged.
