### ISSUE TITLE
In the dev resources Observation.setSubject() still takes a dstu ResourceReferenceDt parameter

### ISSUE THREAD

**Issue by dkincaid** [jamesagnew/hapi-fhir#80]
The parameter for Observation.setSubject() is still of type ca.uhn.fhir.model.dstu.composite.ResourceReferenceDt instead of ca.uhn.fhir.model.dev.composite.ReferenceDt. It looks like setPerformer and setEncounter do as well.

**Comment by steve1medix** [comment]
This also affects the new ca.uhn.fhir.model.dstu2 packages, such as:

* Patient.addIdentifier().setAssigner()
* Patient.setManagingOrganization()

**Comment by jamesagnew** [comment]
This has finally been resolved. DSTU2 structures now use their own ResourceReferenceDt, Bundle resource, Binary resource, and ValueSet enums. A new 0.9-SNAPSHOT has been pushed with this change.

Thanks for reporting!
