### ISSUE TITLE
Using Tinder Plugin to generate POJO Classes

### ISSUE THREAD

**Issue by SriLalithaV** [jamesagnew/hapi-fhir#81]
We are using Tinder Plugin to generate POJO Classes.  Can we have deserialized response in JSON from generated POJO Classes with HAPI primitives classes using MappingJackson2HttpMessageConverter.

**Comment by SriLalithaV** [comment]
We want to map JSO response from spring Rest template however shows error as  "Could not extract response: no suitable HttpMessageConverter found for response type "

**Comment by jamesagnew** [comment]
Hi Sri,
I guess there are two parts to this. First, I would really recommend that you just not use Spring REST in this case, but rather use HAPI FHIR's built in REST framework, as they are fairly overlapping in terms of what they try to solve but HAPI is quite customized for FHIR's usage patterns.
If there are specific parts of Spring REST (which is a wonderful framework I'll agree) that you need, maybe we could look at adding equivalent functionality to HAPI FHIR's RestfulServer, or finding some way to make the two play better together?

If you are really set on using HAPI's model objects with Spring REST it should be possible, but not using Jackson (or for that matter, JAXB, JSONP, or any of the other object binding libraries). You would need to implement your own AbstractHttpMessageConverter implementation that uses HAPI's parser to do the conversion. This wouldn't actually be too hard to do, but no such implementation exists yet..
