### ISSUE TITLE
Duplicate contained resource

### ISSUE THREAD

**Issue by franktao2008** [jamesagnew/hapi-fhir#814]
[MedicationDispenseTester.zip](https://github.com/jamesagnew/hapi-fhir/files/1589352/MedicationDispenseTester.zip)

A MedicationDispense references to a Medication and a MedicationRequest,  the MedicationRequest references to the same Medication. When the Medication resource is added as contained resource in the MedicationDispense, the Medication resource is listed twice as a contained resource. The issue appears on HAPI 2.5, 3.0.0 and 3.1.0. Here is the json output.  The sample code is attached.
{
  "resourceType": "MedicationDispense",
  "id": "1234567890",
  "meta": {
    "lastUpdated": "2017-12-27T10:33:29.978-05:00"
  },
  "contained": [
    {
      **"resourceType": "Medication",
      "id": "Medication1"**
    },
    {
      "resourceType": "MedicationRequest",
      "id": "MedRequest1",
      "identifier": [
        {
          "value": "MedRequest1"
        }
      ],
      "intent": "order",
      "medicationReference": {
        "reference": "#Medication1"
      }
    },
    {
      **"resourceType": "Medication",
      "id": "Medication1"**
    }
  ],
  "identifier": [
    {
      "value": "1234567890"
    }
  ],
  "status": "completed",
  "medicationReference": {
    "reference": "#Medication1"
  },
  "authorizingPrescription": [
    {
      "reference": "#MedRequest1"
    }
  ]
}

Frank Tao

**Comment by franktao2008** [comment]
The issue is at hapi-fhir-base/BaseParser.java recursive call at line 220
containResourcesForEncoding(theContained, potentialTarget, theTarget);

**Comment by jamesagnew** [comment]
Hi @franktao2008 - I have added two test cases, and I am not able to reproduce this issue. Would you mind to look at https://github.com/jamesagnew/hapi-fhir/commit/84dcd51091e944fd1e29b2837cd808dec0935125 to compare it to your setup to see if there is anything obvious that I'm doing wrong?

**Comment by franktao2008** [comment]
@jamesagnew 
it's reproduced by  modify your second test case testDuplicateContainedResourcesNotOutputtedTwiceWithManualIds of #814

1.  Create a medRef object and assign the id
2. md.setMedication to the medRef instead of new Reference(med)  which creates a different object ref
3. add to the contained resource,  here is modified code.

-------------------------
MedicationDispense md = new MedicationDispense();

        MedicationRequest mr = new MedicationRequest();
        mr.setId("#MR");
        md.addAuthorizingPrescription().setResource(mr);

        Medication med = new Medication();
        med.setId("#MED");
        
        ****Reference medRef = new Reference();
        medRef.setReference("#MED");
                
        md.setMedication(medRef);
        mr.setMedication(medRef);**

        **md.getContained().add(mr);
        md.getContained().add(med);****

......

**Comment by franktao2008** [comment]
Reference medRef = new Reference();
    medRef.setReference("#MED");
            
    md.setMedication(medRef);
    mr.setMedication(medRef);

    md.getContained().add(mr);
    md.getContained().add(med);

**Comment by franktao2008** [comment]
Closed with a mistake
