### ISSUE TITLE
Search : TokenParamModifier "not" not implemented

### ISSUE THREAD

**Issue by JulieDu** [jamesagnew/hapi-fhir#815]
Hi, 
In our app, we will need to filter out some resources `Organization` by type with the token param modifier `not`. 
For example : `/Organization?type:not=dept`

As you can see inside `SearchBuilder` class, logic of `TokenParamModifier.NOT` is commented :  
https://github.com/jamesagnew/hapi-fhir/blob/bdf734fc3c5668266a00daa92b5ef4c2944f7349/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/SearchBuilder.java#L635

I would like some insights about this work started by @jamesagnew two years ago,  (seems to be unchanged since this commit : https://github.com/jamesagnew/hapi-fhir/commit/ad34e38dee6efd76bb5837cfbca2265f378408c8 ). 

Thanks a lot,
Julie

**Comment by splatch** [comment]
I've run into same issue with Observation.

**Comment by splatch** [comment]
I've commited to my fork a small change to support not modifier for standard search queries. It works for me, however I'm not sure if that's the best way to solve this issue.

Let me know if it's fine to proceed with if condition there, if so I will provide complete pull request.

**Comment by jamesagnew** [comment]
Fixed in #819
