### ISSUE TITLE
Package name is incorrect in CodesystemsR4Test

### ISSUE THREAD

**Issue by jonathan-clark** [jamesagnew/hapi-fhir#823]
The package in the following class is dstu3 instead of r4

https://github.com/jamesagnew/hapi-fhir/blob/d375977410f98cd6de44ef64a902d9769a4c3d97/hapi-fhir-structures-r4/src/test/java/org/hl7/fhir/r4/model/CodesystemsR4Test.java#L1

**Comment by jamesagnew** [comment]
This was fixed, thanks for reporting!
