### ISSUE TITLE
STU3 warning message while browsing resources

### ISSUE THREAD

**Issue by mitulsampat** [jamesagnew/hapi-fhir#827]
after browsing FHIR , i get following warning. I also cant see resource types under 'Resources'

'Failed to load conformance statement, error was: ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 Bad Request: Unknown resource type 'Stu3' - Server knows how to handle: [Appointment, Account, ReferralRequest, DocumentManifest, MessageDefinition, Goal, Endpoint, EnrollmentRequest, Consent, CapabilityStatement, Measure, Medication, ResearchSubject, Subscription, DocumentReference, ImagingManifest, Parameters, MeasureReport, PractitionerRole, RelatedPerson, SupplyRequest, Practitioner, ExpansionProfile, Slot, Contract, Person, RiskAssessment, Group, PaymentNotice, Organization, CareTeam, ImplementationGuide, ImagingStudy, DeviceComponent, FamilyMemberHistory, Encounter, Substance, SearchParameter, ServiceDefinition, ActivityDefinition, Communication, Linkage, DeviceUseStatement, RequestGroup, MessageHeader, BodySite, ImmunizationRecommendation, Provenance, Task, Questionnaire, ExplanationOfBenefit, ResearchStudy, Specimen, AllergyIntolerance, CarePlan, StructureDefinition, EpisodeOfCare, OperationOutcome, Procedure, List, ConceptMap, OperationDefinition, ValueSet, DiagnosticRequest, Immunization, MedicationRequest, Device, VisionPrescription, Media, EligibilityResponse, ProcedureRequest, DeviceUseRequest, Sequence, DeviceMetric, CodeSystem, Flag, AppointmentResponse, StructureMap, GuidanceResponse, Observation, MedicationAdministration, EnrollmentResponse, Binary, Library, MedicationStatement, CommunicationRequest, TestScript, Basic, TestReport, ClaimResponse, EligibilityRequest, ProcessRequest, MedicationDispense, DiagnosticReport, HealthcareService, DataElement, NutritionRequest, AuditEvent, PaymentReconciliation, Condition, Composition, DetectedIssue, Bundle, CompartmentDefinition, Patient, Coverage, QuestionnaireResponse, ProcessResponse, NamingSystem, Schedule, SupplyDelivery, ClinicalImpression, PlanDefinition, Claim, Location]'

Attached is the screenshot
![fhir_warning](https://user-images.githubusercontent.com/35488820/34985491-04c288ac-faac-11e7-8829-a6dae986deb0.jpg)

Please help!

**Comment by jamesagnew** [comment]
There is a complete working sample here: https://github.com/furore-fhir/fhirstarters/tree/master/java/hapi-fhirstarters-jpaserver-example

I would recommend starting with that project and comparing it to yours to see what change has caused this issue.
