### ISSUE TITLE
Support bundle type = 'collection'

### ISSUE THREAD

**Issue by citizenrich** [jamesagnew/hapi-fhir#828]
Synthetic data from synthea are produced as collections. Posting the data to hapi-fhir-cli results in the error:
```
WARN  c.u.f.r.s.i.ExceptionHandlingInterceptor - Failure during REST processing: ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: Unable to process transaction where incoming Bundle.type = collection
```

**Comment by gabriel-bezerra** [comment]
Check https://github.com/synthetichealth/uploader

**Comment by conceptant** [comment]
https://github.com/synthetichealth/uploader was not updated for 2 years. It's missing support for some models from FHIR v3.0.1 that synthea uses. As a result it frequently fails to post the bundle with null pointer exception. You need to either update the  models in the vendor directory and rebuild the uploader or just use https://hub.docker.com/r/conceptant/synthea-fhir/ where it's already done.
