### ISSUE TITLE
Hapi Validation doesn't allow extensions for boolean values

### ISSUE THREAD

**Issue by patrick-werner** [jamesagnew/hapi-fhir#829]
When validating a profile which adds an Extension to Medication the following issue is thrown:
```
<issue>
        <severity value="error"/>
        <code value="processing"/>
        <diagnostics value="No extensions allowed"/>
        <location value="Medication.isBrand"/>
</issue>
```

This should be wrong: [The following table describes the primitive types that are used in this specification. Primitive types are those with only a value, and no additional elements as children (though, like all types, they have extensions). See also the Examples.](https://www.hl7.org/fhir/datatypes.html#boolean)

**Comment by grahamegrieve** [comment]
This error indicates that a fixed value has been specified, and the fixed value does not include any extensions. I'll improve the error message

**Comment by jamesagnew** [comment]
Updated message has been synced in 2810fff39f
