### ISSUE TITLE
BaseMethodBinding Exception reporting

### ISSUE THREAD

**Issue by kwboone** [jamesagnew/hapi-fhir#830]
I'm thinking that the code in BaseMethodBinding that reports on InvocationTargetException is actually reporting the wrong thing.  It reads as:

	protected final Object invokeServerMethod(IRestfulServer<?> theServer, RequestDetails theRequest, Object[] theMethodParams) {
 ...
		// Actually invoke the method
		try {
			Method method = getMethod();
			return method.invoke(getProvider(), theMethodParams);
		} catch (InvocationTargetException e) {
			if (e.getCause() instanceof BaseServerResponseException) {
				throw (BaseServerResponseException) e.getCause();
			}
			throw new InternalErrorException("Failed to call access method", e);
		}  ...

But what I think it should say is:
  if (**e.getTarget()** instanceof BaseServerResponseException) {
    throw (BaseServerResponseException)**e.getTarget()**;
  } 

This will actually show the wrapped exception, which is what I would want to see.

   Keith

**Comment by jamesagnew** [comment]
Hi Keith,

Are you referring to `InvocationTargetException#getTargetException()`? That method actually internally returns the same thing as `getCause()`, and the javadocs recommend using `getCause()` instead:

```java
    /**
     * Get the thrown target exception.
     *
     * <p>This method predates the general-purpose exception chaining facility.
     * The {@link Throwable#getCause()} method is now the preferred means of
     * obtaining this information.
     *
     * @return the thrown target exception (cause of this exception).
     */
    public Throwable getTargetException() {
        return target;
    }

    /**
     * Returns the cause of this exception (the thrown target exception,
     * which may be {@code null}).
     *
     * @return  the cause of this exception.
     * @since   1.4
     */
    public Throwable getCause() {
        return target;
    }
```
