### ISSUE TITLE
Doesn't seem to support _tag search

### ISSUE THREAD

**Issue by angelok1** [jamesagnew/hapi-fhir#831]
Is _tag supported in search (https://www.hl7.org/fhir/search.html#tag)? I can't seem to be able to find any documentation one way or the other. I see @TagListParam, but that doesn't appear to work.

**Comment by jamesagnew** [comment]
`_tag` is a normal search parameter of type token. You can see an example of using it in the JPA server's providers:

http://hapifhir.io/xref-jpaserver/ca/uhn/fhir/jpa/rp/dstu2/PatientResourceProvider.html#L42

**Comment by angelok1** [comment]
Thanks @jamesagnew. Perfect!

What's `@TagListParam` for?

**Comment by jamesagnew** [comment]
This is a good point, that should be deleted.

It's actually a holdover from DSTU1 days.. Back then there was an operation called "tags" which could be used to retrieve and set tags. That has long since been replaced by the `_tags` search and the `$meta` operations.

**Comment by angelok1** [comment]
If you'd like, I can remove it and do a pull request...

**Comment by jamesagnew** [comment]
Ahh you know what I just beat you to it before I saw your message. I'm just running a build now.

Appreciate the offer!! :)
