### ISSUE TITLE
Error caused by Korean language

### ISSUE THREAD

**Issue by JoonggeonLee** [jamesagnew/hapi-fhir#832]
When I create FHIR Resource having some values in Korean, the server throws ArrayIndexOutOfBoundsException. 

Best
Joonggeon

**Comment by jamesagnew** [comment]
Hi, can you please provide an example?

**Comment by JoonggeonLee** [comment]
This is sample FHIR resource having values in Korean.

<Patient>
	<identifier>
	<use value="usual" />
	<type>
		<coding>
			<system value="http://hl7.org/fhir/v2/0203" />
			<code value="MR" />
		</coding>
	</type>
	<system value="urn:oid:1.2.410.100110.10.41308301" />
	<value value="88888888" />
	<assigner>
		<display value="Seoul Samsung" />
		</assigner>
  </identifier>
  <active value="true" />
 <name>
  <use value="official" />
  <family value="김" />
  <given value="준수" />
  </name>
  <gender value="male" />
  <birthDate value="1988-01-01" />
 <contact>
 <telecom>
  <system value="phone" />
  <value value="010-0000-1000" />
  </telecom>
  </contact>
 <managingOrganization>
  <display value="Seoul Samsung" />
  </managingOrganization>
</Patient>

![image](https://user-images.githubusercontent.com/35584416/35131818-af6e8d80-fd0b-11e7-87de-35f039672fde.png)

This is where the exception happens.

I guess Normalizer.normalize(theString, Normalizer.Form.NFD) method works wrong.

Thank you for your concern
Best

**Comment by jamesagnew** [comment]
Hello, did you accidentally include the wrong attachment? That appears to be a screenshot.

Can you please provide a sample resource which demonstrates this problem?

**Comment by JoonggeonLee** [comment]
Oh sorry, I thought I pasted the resource. 


<Patient>
	<identifier>
	<use value="usual" />
	<type>
		<coding>
			<system value="http://hl7.org/fhir/v2/0203" />
			<code value="MR" />
		</coding>
	</type>
	<system value="urn:oid:1.2.410.100110.10.41308301" />
	<value value="88888888" />
	<assigner>
		<display value="Seoul Samsung" />
		</assigner>
  </identifier>
  <active value="true" />
 <name>
  <use value="official" />
  <family value="김" />
  <given value="준수" />
  </name>
  <gender value="male" />
  <birthDate value="1988-01-01" />
 <contact>
 <telecom>
  <system value="phone" />
  <value value="010-0000-1000" />
  </telecom>
  </contact>
 <managingOrganization>
  <display value="Seoul Samsung" />
  </managingOrganization>
</Patient>

**Comment by jamesagnew** [comment]
Perfect, thanks!  That example did the trick, I'm committing a fix shortly.
