### ISSUE TITLE
cannot run jpaserver-example in docker

### ISSUE THREAD

**Issue by jkiddo** [jamesagnew/hapi-fhir#842]
Doing what is stated on https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-fhir-jpaserver-example yields an error:

> 2018-01-30 12:56:25.915:INFO:oejs.AbstractConnector:Thread-0: Stopped ServerConnector@5bc79255{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
> 2018-01-30 12:56:25.969:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.w.WebAppContext@4590c9c3{/,null,UNAVAILABLE}{/root.war}
> 2018-01-30 12:56:27.770:INFO::main: Logging initialized @230ms to org.eclipse.jetty.util.log.StdErrLog
> 2018-01-30 12:56:28.003:INFO:oejs.Server:main: jetty-9.4.7.v20170914
> 2018-01-30 12:56:28.024:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/] at interval 1
> 2018-01-30 12:56:29.801:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@4590c9c3{/,file:///tmp/jetty-0.0.0.0-8080-root.war-_-any-9127338409235931605.dir/webapp/,UNAVAILABLE}{/root.war}
> java.lang.IllegalStateException: Duplicate fragment name: spring_web for jar:file:///tmp/jetty-0.0.0.0-8080-root.war-_-any-9127338409235931605.dir/webapp/WEB-INF/lib/spring-web-5.0.3.RELEASE.jar!/META-INF/web-fragment.xml and jar:file:///tmp/jetty-0.0.0.0-8080-root.war-_-any-9127338409235931605.dir/webapp/WEB-INF/lib/spring-web-5.0.0.RELEASE.jar!/META-INF/web-fragment.xml
> 	at org.eclipse.jetty.webapp.MetaData.addFragment(MetaData.java:284)
> 	at org.eclipse.jetty.webapp.FragmentConfiguration.addWebFragments(FragmentConfiguration.java:88)
> 	at org.eclipse.jetty.webapp.FragmentConfiguration.preConfigure(FragmentConfiguration.java:39)
> 	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
> 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
> 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> 	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
> 	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
> 	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:502)
> 	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:150)
> 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
> 	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:447)
> 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
> 	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
> 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
> 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
> 	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
> 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
> 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> 	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:564)
> 	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:239)
> 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
> 	at org.eclipse.jetty.server.Server.start(Server.java:449)
> 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
> 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
> 	at org.eclipse.jetty.server.Server.doStart(Server.java:416)
> 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
> 	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1584)
> 	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1508)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1507)
> 2018-01-30 12:56:29.819:INFO:oejs.AbstractConnector:main: Started ServerConnector@5bc79255{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
> 2018-01-30 12:56:29.820:INFO:oejs.Server:main: Started @2282ms

**Comment by jkiddo** [comment]
noteworthy to say it was on the master branch ...

**Comment by jamesagnew** [comment]
Duplicate fragment errors are typically caused by having multiple
conflicting versions of spring on the classpath. Does a clean build solve
this?

sent from my phone.

**Comment by jkiddo** [comment]
nop .... I think it might be related to some dependencies not updated on the overlay component (I think it drags some spring-* 5.0.0 to the table where the rest of the suite uses 5.0.3)

It works like a charm on the tag 3.2.0 at least

**Comment by jamesagnew** [comment]
Hmm- Could you paste in a list of the files that are in your WAR file?

**Comment by jkiddo** [comment]
[out.txt](https://github.com/jamesagnew/hapi-fhir/files/1682032/out.txt)

**Comment by jkiddo** [comment]
wait ... forgot to switch branch

**Comment by jkiddo** [comment]
[out.txt](https://github.com/jamesagnew/hapi-fhir/files/1682120/out.txt)
....
[DEBUG] adding entry WEB-INF/lib/spring-web-5.0.3.RELEASE.jar
....
[DEBUG] adding entry WEB-INF/lib/spring-web-5.0.0.RELEASE.jar
....

**Comment by jamesagnew** [comment]
hmm, there should be no references to spring-web-5.0.0.RELEASE.jar anywhere in the build.

Can you manually verify what is in your overlay jar?

E.g. for me:

```bash
$ jar tvf ~/.m2/repository/ca/uhn/hapi/fhir/hapi-fhir-testpage-overlay/3.3.0-SNAPSHOT/hapi-fhir-testpage-overlay-3.3.0-SNAPSHOT.war | grep spring-web
783058 Sun Jan 28 14:09:46 CST 2018 WEB-INF/lib/spring-webmvc-5.0.3.RELEASE.jar
1243899 Sun Jan 28 14:09:50 CST 2018 WEB-INF/lib/spring-web-5.0.3.RELEASE.jar
```

**Comment by jkiddo** [comment]
$ jar tvf ~/.m2/repository/ca/uhn/hapi/fhir/hapi-fhir-testpage-overlay/3.3.0-SNAPSHOT/hapi-fhir-testpage-overlay-3.3.0-SNAPSHOT.war | grep spring-web
1215666 Tue Oct 17 16:20:38 CEST 2017 WEB-INF/lib/spring-web-5.0.0.RELEASE.jar
779982 Tue Oct 17 16:20:36 CEST 2017 WEB-INF/lib/spring-webmvc-5.0.0.RELEASE.jar

**Comment by jamesagnew** [comment]
This makes no sense to me. Are you building that locally based on the
latest master git?

When I build on my machine I end up with 5.0.3, not 5.0.0.

**Comment by jkiddo** [comment]
[out.file.txt](https://github.com/jamesagnew/hapi-fhir/files/1683511/out.file.txt)
 tried on another machine ...
fresh clone on master ... still 5.0.3 and 5.0.0 are included

**Comment by jamesagnew** [comment]
What does the mvn dependency tree look like for the hapi-fhir-testpage-overlay project for you?

```
hapi-fhir-testpage-overlay$ mvn dependency:tree | grep spring-web
[INFO] |  +- org.springframework:spring-websocket:jar:5.0.3.RELEASE:test
[INFO] +- org.springframework:spring-webmvc:jar:5.0.3.RELEASE:compile
[INFO] +- org.springframework:spring-web:jar:5.0.3.RELEASE:compile
```

**Comment by jkiddo** [comment]
hapi-fhir-jpaserver-example]# mvn dependency:tree | grep spring-web
[INFO] |  +- org.springframework:spring-webmvc:jar:5.0.3.RELEASE:compile
[INFO] |  +- org.springframework:spring-websocket:jar:5.0.3.RELEASE:compile
[INFO] +- org.springframework:spring-web:jar:5.0.3.RELEASE:compile

**Comment by jamesagnew** [comment]
this makes zero sense to me.

it claims that it depends on 5.0.3 but when you build, it actually puts 5.0.0 into the war file?

unfortunately i have no idea how to diagnose this, as this isn't what it does when i build locally.

**Comment by jamesagnew** [comment]
Out of curiosity, is this still happening? We have pushed a few new 3.3.0-SNAPSHOTS to central in the last while so I'm wondering if it may have been a maven caching issue

**Comment by splatch** [comment]
I've been there with slightly different case around Spring and HAPI, BUT what have happened is desynchronised snapshot. You had few artifacts which were updated to spring 5.0.3 and few older ones which referenced a older parent with spring 5.0.0.

This happens with test page overlay as it is cached so it doesn't get downloaded each time AND WEB-INF/lib entries in there are not managed by maven. These are just binary files.

Hope that this information helps. :-)
