### ISSUE TITLE
docker container support

### ISSUE THREAD

**Issue by haffonist** [jamesagnew/hapi-fhir#843]
Hello, 
Any plan to support deployment in docker containers ?

**Comment by jkiddo** [comment]
It already does

**Comment by haffonist** [comment]
where ?

**Comment by haffo** [comment]
Found it.

**Comment by citizenrich** [comment]
Is there an official Docker image that is maintained by the core devs for demos or CI/CD? Most on Docker Hub are out of date. I'm looking for an image for demonstration purposes, not for production. Data can be blown away.

The big picture is that we are encouraging users to try HAPI FHIR in the our (OpenHIE) architecture which relies on Docker containers. The most common approach it seems is that folks build their own WAR file and Docker image but those go out of data quickly.

**Comment by carloscaverobarca** [comment]
You can check [this HAPI FHIR image v3.8.0] (https://hub.docker.com/r/arihealth/hapi-fhir-cdr-oauth) with support for several databases. We are planning to upgrade the image to 4.0.0 soon.
