### ISSUE TITLE
_id parameter in search

### ISSUE THREAD

**Issue by lwedmo** [jamesagnew/hapi-fhir#844]
It's not clear (to me) how to implement the builtin _id parameter for resource search.  We need basically a read operation with the ability to _include additional resources. Is it implemented and is there an example code snippet?

        leonard.edmondson@mckesson.com

**Comment by jamesagnew** [comment]
Hi Leonard,

_id is a plain string search parameter, so you just need to treat it like
any other search parameter.

Here's an example that shows it:
http://hapifhir.io/xref-jpaserver/ca/uhn/fhir/jpa/rp/dstu2/PatientResourceProvider.html

Cheers,
James

On Mon, Feb 5, 2018 at 12:54 PM, Leonard Edmondson <notifications@github.com

**Comment by euz1e4r** [comment]
Thank you. The extensive search parameters in the example are instructive.

                L
