### ISSUE TITLE
HAPI FHIR public test server down

### ISSUE THREAD

**Issue by rmertz92** [jamesagnew/hapi-fhir#845]
Hello,

I see that when this has happened in the past, people have reported it here.
I'm consistently getting either a 502 Bad Gateway or 504 Gateway Time-Out

Thanks!

**Comment by rmertz92** [comment]
Annnnndddddd its back up. Thanks!

**Comment by rmertz92** [comment]
Sorry. Spoke too soon. I'll wait a little longer to close next time.

**Comment by jamesagnew** [comment]
We've been really unstable lately.. the server keeps running out of RAM. 

We've now migrated completely to a new host, so this should hopefully be behind us now.

**Comment by jamesagnew** [comment]
BTW thanks for reporting :)

**Comment by goku0** [comment]
It seems the server is down again, getting a 502 gateway error when I try to go to:

http://hapi.fhir.org/baseDstu3
http://fhirtest.uhn.ca/baseDstu3
http://hapi.fhir.org/baseDstu2

**Comment by jamesagnew** [comment]
Should be back up again

**Comment by Kunalrk1** [comment]
Hello,
It seems FHIR Test server is down again. I am getting following error - "504 Gateway Time-out" since last couple of days.
