### ISSUE TITLE
add IResourceProvider to hapi-fhir-spring-boot FhirRestfulServerConfiguration @ConditionalOnClass

### ISSUE THREAD

**Issue by nkarip** [jamesagnew/hapi-fhir#850]
FhirAutoConfiguration.FhirRestfulServerConfiguration currently is @ConditionalOnClass(AbstractJaxRsProvider.class). The configuration requires you to use the jaxrs/Jersey base server implementation, however it should work as-is with a servlet based server. I tested it out with @ConditionalOnClass(IResourceProvider.class) and this seems to work. Would it be possible to add this class to the ConditionalOnClass annotation to allow it to work with IResourceProvider implementations?

**Comment by jamesagnew** [comment]
@mouellet any thoughts about this?

**Comment by mouellet** [comment]
In short, the jpa and rest (jersey) autoconfiguration were made to activate based on the presence of either `hapi-fhir-jpaserver-base` or `hapi-fhir-jaxrsserver-base` dependency. If we simply change the condition to `@ConditionalOnClass(IResourceProvider.class)` on the rest config, then it could activate something unintentionally as this interface is in the `hapi-fhir-server` module (which both `hapi-fhir-jpaserver-base` and `hapi-fhir-jaxrsserver-base` depend on).

Or maybe thats fine, I'm not sure about the use cases of the jpa server... Let me know if you need help adding an autoconfiguration for simple servlet server.

**Comment by nkarip** [comment]
Could you add an additional ConditionalOnMissingBean to prevent the rest autoconfig from running with jpaproviders?
