### ISSUE TITLE
Validation error message 'Error null validating Coding' is non descriptive

### ISSUE THREAD

**Issue by edeati** [jamesagnew/hapi-fhir#851]
You receive `Error null validating Coding` validation error message whenever you try to validate a CodeSystem resource with `CodeSystem.concept.designation.use.system` element and using custom `ValidationSupport` with an unimplemented `isCodeSystemSupported` that throws an `UnsupportedOperationException` exception like this:
```
     @Override
     public boolean isCodeSystemSupported(FhirContext arg0, String arg1) {
         throw new UnsupportedOperationException();
     }
```

#### Explanation:
During validation the `boolean ss = context.supportsSystem(system);` part of the checkCode function in `src/main/java/org/hl7/fhir/r4/validation/InstanceValidator.java` is throwing the `UnsupportedOperationException` causing the catch in `checkCoding` function to report the error but because `UnsupportedOperationException` was thrown with no message given we get 'null' in the validation message.
```
...
      } catch (Exception e) {
        rule(errors, IssueType.CODEINVALID, element.line(), element.col(), path, false, "Error "+e.getMessage()+" validating Coding");
      }
...
```
This can be fixed by checking if `e.getMessage()` is null and use `e.toString()` for example to get a more descriptive validation error message. 

Please note: There are more  places in the validation code that uses `e.getMessage()` to report exceptions in the validation error message so a review of the exception reporting might be needed.

**Comment by jamesagnew** [comment]
Hi @edeati - I am not able to replicate this, as least in a very basic test. 

Could you supply a code snippet link the unit test in https://github.com/jamesagnew/hapi-fhir/commit/c8e61cd9a372ecbbdaa6dd430d0aa7ee5f2f6580 that demonstrates this issue?

**Comment by edeati** [comment]
Hi James,
This would do the job but would break other tests of course
```
		when(myMockSupport.isCodeSystemSupported(any(FhirContext.class), any(String.class))).thenAnswer(new Answer<Boolean>() {
			@Override
			public Boolean answer(InvocationOnMock theInvocation) {
			    throw new UnsupportedOperationException();
			}
		});
```

**Comment by edeati** [comment]
Actually this is better, this will not break your other tests
```
		when(myMockSupport.isCodeSystemSupported(any(FhirContext.class), any(String.class))).thenAnswer(new Answer<Boolean>() {
			@Override
			public Boolean answer(InvocationOnMock theInvocation) {
				boolean retVal = myValidSystems.contains(theInvocation.getArguments()[1]);
				if ( theInvocation.getArguments()[1].equals("http://foo") ) {
		                throw new UnsupportedOperationException();
		        }
				ourLog.info("isCodeSystemSupported({}) : {}", new Object[]{theInvocation.getArguments()[1], retVal});
				return retVal;
			}
		});
```
