### ISSUE TITLE
Resource validation throws an Error when an Observation has multiple performers

### ISSUE THREAD

**Issue by mattiuusitalo** [jamesagnew/hapi-fhir#853]
Observations go through this validation
[https://github.com/jamesagnew/hapi-fhir/blob/89a834723c87939843aa72c3140e356ba933f82b/hapi-fhir-validation/src/main/java/org/hl7/fhir/r4/validation/InstanceValidator.java#L3541](url)

which ends up throwing an Error when there are more than one Performer for an Observation. However, Performer is a 0...* element in FHIR.

[https://www.hl7.org/fhir/observation.html](url)

**Comment by patrick-werner** [comment]
should be fixed by my pull request
