### ISSUE TITLE
Replacement of temporary UUIDs in uri in transaction not working

### ISSUE THREAD

**Issue by t4deon** [jamesagnew/hapi-fhir#854]
I'm trying to post a Binary along with a DiagnosticResource (DR) in a transaction. In the DR, I reference the Binary in DR.presentedForm[0].uri with an UUID before posting (this is not a reference, just an uri). [According to the spec](https://www.hl7.org/fhir/http.html#2.21.0.17.2), this UUID should be replaced with the ID of the Binary given by the server. Right now, the UUID is **not** replaced in DR.presentedForm[0].uri.

Here is some example code for testing:
```java
Binary binary = new Binary();
binary.setId(IdType.newRandomUuid());
binary.setContent(bytes);
binary.setContentType("application/pdf");

DiagnosticReport dr = new DiagnosticReport();
dr.setId(IdDt.newRandomUuid());
Attachment attachment = new Attachment();
attachment.setContentType("application/pdf");
attachment.setUrl(binary.getId());
dr.setPresentedForm(Collections.singletonList(attachment));
dr.setSubject(new Reference().setIdentifier(patient.getIdentifierFirstRep()));

Bundle transactionBundle = new Bundle();
transactionBundle.setType(Bundle.BundleType.BATCH);

Bundle.BundleEntryComponent binaryEntry = new Bundle.BundleEntryComponent();   
binaryEntry.setResource(binary).setFullUrl(binary.getId()).getRequest().setUrl("Binary").setMethod(Bundle.HTTPVerb.POST);       
transactionBundle.addEntry(binaryEntry);

Bundle.BundleEntryComponent drEntry = new Bundle.BundleEntryComponent();     
drEntry.setResource(dr).setFullUrl(dr.getId()).getRequest().setUrl("DiagnosticReport").setMethod(Bundle.HTTPVerb.POST);         
transactionBundle.addEntry(drEntry);

FhirContext.forDstu3().newRestfulGenericClient(fhirBase).transaction().withBundle(transactionBundle).execute();
```
Versions tried:
Hapi Client: 3.2.0
Hapi Server: 3.2.0

**Comment by jamesagnew** [comment]
Note that you have `transactionBundle.setType(Bundle.BundleType.BATCH)` set. You'd definitely need to change it to `transactionBundle.setType(Bundle.BundleType.TRANSACTION)` for transaction processing rules to apply.

It still doesn't work in my unit test with that change, so that's not a fix, but it's a factor.

**Comment by jamesagnew** [comment]
Alright, fix coming up. Thanks for supplying a testcase, that makes this very easy to fix.

**Comment by t4deon** [comment]
> Note that you have transactionBundle.setType(Bundle.BundleType.BATCH) set. You'd definitely need to change it to transactionBundle.setType(Bundle.BundleType.TRANSACTION) for transaction processing rules to  @apply.

Yes that's right. Thanks for the fix James :-)
