### ISSUE TITLE
Build failing cannot find com.sun.prism

### ISSUE THREAD

**Issue by aanchan** [jamesagnew/hapi-fhir#859]
While trying to do a mvn install on the main project the build fails during the compilation of the HAPI FHIR JPA Server:

[INFO] ------------------------------------------------------------------------
[INFO] Building HAPI FHIR JPA Server 3.3.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
....
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/aanchan/work/fhir-hapi/hapi-fhir/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/ResourceIndexedSearchParamCoords.java:[34,26] error: package com.sun.prism.image does not exist

The offending file seems to be this one calling the com.sun.prism library : https://github.com/jamesagnew/hapi-fhir/search?utf8=%E2%9C%93&q=package+com.sun.prism&type=

Useful information:
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-112-generic", arch: "amd64", family: "unix"
On Ubuntu 16.04 LTS

**Comment by jamesagnew** [comment]
Oh weird, that import isn't used. I'll remove. 

Thanks for reporting!
