### ISSUE TITLE
:not modifier not working

### ISSUE THREAD

**Issue by eborey** [jamesagnew/hapi-fhir#862]
I just tested the :not modifier on your HAPI 3.3 JPA Example server :

GET http://hapi.fhir.org/baseDstu3/Patient?gender:not=male

It doesn't seem to work, it returns only patient with male gender.

**Comment by JulieDu** [comment]
I have the same issue (https://github.com/jamesagnew/hapi-fhir/issues/815), there is already an open PR to fix this problem :  https://github.com/jamesagnew/hapi-fhir/pull/819

**Comment by jamesagnew** [comment]
Fixed in #819
