### ISSUE TITLE
DSTU2 validation issue related to Daylight Savings Time

### ISSUE THREAD

**Issue by jawalonoski** [jamesagnew/hapi-fhir#873]
DSTU2. HAPI `ca.uhn.hapi.fhir:hapi-fhir-structures-dstu2:3.1.0`

Trying to validate this Procedure fails due to `performedPeriod.start` being after `performedPeriod.end`.... however, if you look closely, the start is actually before the end, but the timezone offset has shifted due to daylight savings.

Here is the resource:
```
{
  "resourceType": "Procedure",
  "subject": {
    "reference": "urn:uuid:120d8a1e-21da-4d19-965f-1d28c09307b0"
  },
  "status": "completed",
  "code": {
    "coding": [
      {
        "system": "http://snomed.info/sct",
        "code": "180256009",
        "display": "Subcutaneous immunotherapy"
      }
    ],
    "text": "Subcutaneous immunotherapy"
  },
  "performedPeriod": {
    "start": "2010-11-07T01:59:26-04:00",
    "end": "2010-11-07T01:57:26-05:00"
  },
  "encounter": {
    "reference": "urn:uuid:5776f4b9-f908-4080-a53e-964c712eefe6"
  }
}
```

Here is the error message that HAPI gives me related to the FHIR XPath invariant:
```
ERROR: [error] Procedure @ /*:Procedure[namespace-uri()='http://hl7.org/fhir'][1]/*:performedPeriod[namespace-uri()='http://hl7.org/fhir'][1]; Test=not(exists(f:start)) or not(exists(f:end)) or (f:start/@value <= f:end/@value); Message=per-1: If present, start SHALL have a lower value than end
```

**Comment by jamesagnew** [comment]
Oh man, this seems like it's probably an issue with the invariant. If the schematron version of the invariant has a rule like `(f:start/@value <= f:end/@value)` presumably it's just comparing strings, so this will break on DST, but also on any other timezone discrepancies. Ugh.

One workaround would be to use the profile validator instead of the schematron validator, but that still leaves the SCH files pretty glaringly broken.

**Comment by lmckenzi** [comment]
We need to change the rule to xs:dateTime(f:start/@value) <= xs:dateTime(f:end/@value).  Can you submit a change request?

**Comment by jawalonoski** [comment]
Done. Added FHIR Tracker 15680.

https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=15680

**Comment by jamesagnew** [comment]
FYI @grahamegrieve I tested this using FHIRPathEngine and it does not work there either. I will fix it, I have unit tests written up and a fix half coded.
