### ISSUE TITLE
mvn install failed

### ISSUE THREAD

**Issue by trourance** [jamesagnew/hapi-fhir#891]
I've cloned the master branch, but `mvn install` failed with the following error:

`
[ERROR] Failed to execute goal on project hapi-fhir-jpaserver-example: Could not resolve dependencies for project ca.uhn.hapi.fhir:hapi-fhir-jpaserver-example:war:3.3.0-SNAPSHOT: Failure to find ca.uhn.hapi.fhir:hapi-fhir-jpaserver-elasticsearch:jar:3.3.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/`

**Comment by patrick-werner** [comment]
This shouldn't happen if you build the whole project locally, did you do maven install on the root level of the project? 
Do you find ca.uhn.hapi.fhir:hapi-fhir-jpaserver-elasticsearch in your local .m2 repo?
What is the output of: `mvn -version` on your system?

see also related: #898

**Comment by trourance** [comment]
No, I did `mvn install` directly in the hapi-fhir-jpaserver-example directory, as stated in the doc here: http://hapifhir.io/doc_jpa.html.
If I run it on the root level of the project, it builds successfully.
`mvn -version
Apache Maven 3.5.2 (NON-CANONICAL_2017-10-25T13:09:52+03:00_root; 2017-10-25T12:09:52+02:00)
Maven home: /opt/maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-jdk/jre
Default locale: fr_CH, platform encoding: UTF-8
OS name: "linux", version: "4.14.5-1-arch", arch: "amd64", family: "unix"`
