### ISSUE TITLE
Performance improvements for FhirConext

### ISSUE THREAD

**Issue by t106uhn** [jamesagnew/hapi-fhir#901]
Hi james and anyone else,

Has there been any performance improvements to the FhirContext class in its ability to deserialize requests and serialize responses?  Right now we are using version 2.1

Thanks

**Comment by jamesagnew** [comment]
Closing, as this isn't a bug.

DIscussion can be found here: https://groups.google.com/forum/#!topic/hapi-fhir/qwF8WIbFOY4
