### ISSUE TITLE
IndexOutOfBoundsException for DSTU2 QuestionnaireResponses with groups

### ISSUE THREAD

**Issue by dgileadi** [jamesagnew/hapi-fhir#902]
I'm able to consistently get an IndexOutOfBoundsException when trying to create a DSTU2 QuestionnaireResponse. After some digging I've discovered the cause in org.hl7.fhir.instance.validation.QuestionnaireResponseValidator on line 248.

`QuestionnaireResponseValidator.validateGroups` loops through the answer groups and calls `validateGroup` on each one, starting on line 247. Line 248 gets an index to use in `thePathStack` for reporting errors. However instead of getting the index of `nextAnswerGroup` like the previous version of `validateGroups` did, it gets the index of `answerGroups.get(1)`. If answerGroups should happen to only have one group in it, which is the expected behavior of *all* groups that don't repeat, then this line of code will throw an IndexOutOfBoundsException every time a group is validated.

The fix is to revert line 248 to get the index of `nextAnswerGroup`, not of `answerGroups.get(1)`.

**Comment by dgileadi** [comment]
By the way I created PR #903 to address this issue.

**Comment by dgileadi** [comment]
Note that this issue prevents DSTU2 Questionnaires from having subgroups at all, because the presence of any subgroups triggers the bug. To work around the bug, DSTU2 Questionnaires are forced to place all their questions into the root group.

**Comment by danieljianu** [comment]
Any updates on this?
The issue is affecting us as well.
Thanks.
