### ISSUE TITLE
Implementing operation outcomes with BaseOperationOutcome

### ISSUE THREAD

**Issue by fmayoral** [jamesagnew/hapi-fhir#904]
Hello!

We are implementing some server STU3 infrastructure using hapi-fhir and got ourselves into trouble when returning a collection that could contain [OperationOutcome](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-structures-dstu3/src/main/java/org/hl7/fhir/dstu3/model/OperationOutcome.java) as part of the response.

We are getting an InternalErrorException from hapi-fhir because our [OperationOutcome](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-structures-dstu3/src/main/java/org/hl7/fhir/dstu3/model/OperationOutcome.java) doesn't have a resource id, and if I put one then I get a weird url in the resource.

By reading at [the code](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java#L199) I can see that [BaseResourceReturningMethodBinding](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java#L199) allows anything that is a [BaseOperationOutcome](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/model/base/resource/BaseOperationOutcome.java#L33) to not have an id (_which is what we want)_ but [STU3 OperationOutcome](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-structures-dstu3/src/main/java/org/hl7/fhir/dstu3/model/OperationOutcome.java) _(the one we are using)_ does not implement [BaseOperationOutcome](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/model/base/resource/BaseOperationOutcome.java#L33) but [IBaseOperationOutcome](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/org/hl7/fhir/instance/model/api/IBaseOperationOutcome.java).

Now looking for implementations of [BaseOperationOutcome](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/model/base/resource/BaseOperationOutcome.java#L33) I couldn't find any within hapi-fhir (I might have missed something here). Is the expectation for the implementer to have their own [BaseOperationOutcome](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/model/base/resource/BaseOperationOutcome.java#L33) implementation? I would expect that [OperationOutcome](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-structures-dstu3/src/main/java/org/hl7/fhir/dstu3/model/OperationOutcome.java) does that but it seems like it's not the case. I quickly went trough the docs but I couldn't find anything helpful for this specific scenario.

I'm wondering now if this is intentional, accidental, or if I'm doing the wrong thing.
Any help/comments would be very appreciated.

Thanks!

**Comment by jamesagnew** [comment]
Can you elaborate on what you're actually trying to accomplish? I.e. what does your resource provider actually look like, what operation are you implementing, what is your expected outcome, etc?

**Comment by joedai** [comment]
Hi James,
What we are doing is that we've got data that comes from different sources, the FHIR APIs we have are aggregated. When one of the sources are down, we want to return whatever we have but also tell the client that something went wrong. To achieve that, we added an operation outcome in the returned bundle, HAPI should have treated OperationOutcome differently, i.e. not requiring an id, but because of this bug, it throws an exception instead.

Hopefully, my explanation clears it up

**Comment by fmayoral** [comment]
On this matter, we've tried implementing our own [BaseOperationOutcome](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/model/base/resource/BaseOperationOutcome.java#L33), and while it passes the validation in [BaseResourceReturningMethodBinding](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java#L199) it blows up later in the server when it tries to cast it to a BaseResource (BaseOperationOutcome when it's actually extending IResource -> IBaseResource)

**Comment by jamesagnew** [comment]
This sounds to me like you want an OperationOutcome in the bundle in `Bundle.response.outcome` as opposed to having it mixed in with results, no?

You could have your resource providers return a Bundle insetad of a List/IResourceProvider as one way of accomplishing this, if that helps.

**Comment by joedai** [comment]
Hi James,
Another way of asking is that why is [BaseResourceReturningMethodBinding](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/BaseResourceReturningMethodBinding.java#L199)
does an instanceOf check on an Interface that STU3 OperationOutcome and R4 OperationOutcome don't implement?
