### ISSUE TITLE
DSTU2 portion of XmlParser ignores most resource metadata

### ISSUE THREAD

**Issue by mochaholic** [jamesagnew/hapi-fhir#92]
I noticed that when I create a ResourceMetadataMap and add it to a resource only some of the metadata end up in the XML encoding of the resource. Looking at the code of XmlParser.java (near lines 750-783) it seems like the code only cares about versionId and lastUpdated.
As a result it is impossible to get other metadata in the resulting XML, e.g. the security labels as specified here:
http://hl7.org/implement/standards/FHIR-Develop/security-labels.html

**Comment by mochaholic** [comment]
This issue also applies to parsing resources from XML content. The if block near line 1502 of ParserState.java only accepts versionId and lastUpdated and throws a parsing exception if any other tags are encountered.

**Comment by jamesagnew** [comment]
Commenting to make a note to myself- Mohammad indicated by email that he has done some work on fixing this issue.

**Comment by ilpianista** [comment]
Any news about this? Thanks.

**Comment by jamesagnew** [comment]
My apologies, I should have closed this bug. @mochaholic ended up implementing an excellent fix which was merged and released in HAPI FHIR 0.9.
