### ISSUE TITLE
Build issue with "Apache Karaf :: Features" project for 3.3.0 source on Windows 7

### ISSUE THREAD

**Issue by anthonys123** [jamesagnew/hapi-fhir#921]
I downloaded the 3.3.0 source this morning and attempted a build in Windows 7.  Observed a build failure with the Apache Karaf :: Features project:

[WARNING] Settings file [C:\Users\Precision\.m2\settings.xml] cannot be used and
 will be skipped (malformed url or file does not exist)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] HAPI-FHIR 3.3.0 .................................... SUCCESS [ 44.789 s]
[INFO] HAPI FHIR - Deployable Artifact Parent POM ......... SUCCESS [ 14.656 s]
[INFO] HAPI FHIR - Core Library ........................... SUCCESS [02:06 min]
[INFO] HAPI FHIR - Utilities .............................. SUCCESS [ 20.252 s]
[INFO] HAPI FHIR - Server Framework ....................... SUCCESS [ 32.033 s]
[INFO] HAPI Tinder Plugin ................................. SUCCESS [01:50 min]
[INFO] HAPI FHIR - Validation Resources (DSTU2) ........... SUCCESS [  6.451 s]
[INFO] HAPI FHIR - Client Framework ....................... SUCCESS [ 17.142 s]
[INFO] HAPI FHIR Structures - DSTU2 (FHIR v1.0.0) ......... SUCCESS [02:41 min]
[INFO] HAPI FHIR - Validation Resources DSTU2.1 (2016May) . SUCCESS [  3.171 s]
[INFO] HAPI FHIR Structures - DSTU2.1 (2016May) ........... SUCCESS [02:00 min]
[INFO] HAPI FHIR - Validation Resources (DSTU3) ........... SUCCESS [  3.602 s]
[INFO] HAPI FHIR Structures - DSTU3 ....................... SUCCESS [02:51 min]
[INFO] HAPI FHIR Structures - HL7.org DSTU2 ............... SUCCESS [01:51 min]
[INFO] HAPI Tinder Plugin - Test Project .................. SUCCESS [ 36.058 s]
[INFO] HAPI FHIR - Validation Resources (FHIR R4) ......... SUCCESS [  4.387 s]
[INFO] HAPI FHIR Structures - FHIR R4 ..................... SUCCESS [03:11 min]
[INFO] HAPI FHIR - Converter .............................. SUCCESS [ 37.603 s]
[INFO] HAPI FHIR - Validation ............................. SUCCESS [08:19 min]
[INFO] HAPI FHIR JAX-RS Server ............................ SUCCESS [01:27 min]
[INFO] HAPI FHIR JAX-RS Server - Example .................. SUCCESS [ 26.501 s]
[INFO] HAPI FHIR JPA Server ............................... SUCCESS [18:37 min]
[INFO] HAPI FHIR JPA Server - ElasticSearch Integration ... SUCCESS [ 10.283 s]
[INFO] HAPI FHIR TestPage Overlay ......................... SUCCESS [ 12.597 s]
[INFO] HAPI FHIR JPA Server - Example ..................... SUCCESS [01:13 min]
[INFO] HAPI FHIR Sample RESTful Server .................... SUCCESS [  9.179 s]
[INFO] HAPI FHIR Sample RESTful Server - Tests ............ SUCCESS [  3.821 s]
[INFO] HAPI FHIR - fhirtest.uhn.ca Deployable WAR ......... SUCCESS [ 21.599 s]
[INFO] HAPI FHIR OkHttp Client ............................ SUCCESS [ 23.720 s]
[INFO] HAPI FHIR - Android ................................ SUCCESS [ 15.809 s]
[INFO] HAPI FHIR - Command Line Client - Base Project ..... SUCCESS [  0.075 s]
[INFO] HAPI FHIR - Command Line Client - Server WAR ....... SUCCESS [ 14.549 s]
[INFO] hapi-fhir-igpacks .................................. SUCCESS [ 13.249 s]
[INFO] HAPI FHIR - Command Line Client - Application ...... SUCCESS [01:01 min]
[INFO] HAPI FHIR - Distribution Archive ................... SUCCESS [  0.087 s]
[INFO] HAPI FHIR - Examples (for site) .................... SUCCESS [  8.623 s]
[INFO] HAPI FHIR - Apache Karaf :: Features ............... FAILURE [01:46 min]
[INFO] HAPI-FHIR Apache Karaf Integration Tests ........... SKIPPED
[INFO] hapi-fhir-base-example-embedded-ws ................. SKIPPED
[INFO] hapi-fhir-standalone-overlay-example ............... SKIPPED
[INFO] HAPI FHIR JPA Clinical Decision Support Server - Example SKIPPED
[INFO] HAPI FHIR JPA Server - Example for CHIP ............ SKIPPED
[INFO] HAPI FHIR - Minimal Dependency Test - Client ....... SKIPPED
[INFO] HAPI FHIR - Minimal Dependency Test - Server ....... SKIPPED
[INFO] HAPI FHIR - JaCoCo Test Coverage ................... SKIPPED
[INFO] hapi-fhir-spring-boot-autoconfigure ................ SKIPPED
[INFO] hapi-fhir-spring-boot-starter ...................... SKIPPED
[INFO] hapi-fhir-spring-boot .............................. SKIPPED
[INFO] hapi-fhir-spring-boot-samples ...................... SKIPPED
[INFO] hapi-fhir-spring-boot-sample-client-apache ......... SKIPPED
[INFO] hapi-fhir-spring-boot-sample-client-okhttp ......... SKIPPED
[INFO] hapi-fhir-spring-boot-sample-server-jersey ......... SKIPPED
[INFO] hapi-fhir-spring-boot-sample-server-jpa 3.3.0 ...... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 56:09 min
[INFO] Finished at: 2018-04-17T13:00:36-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.1.4
:verify (validate) on project hapi-fhir: Unable to load features descriptors: Er
ror:
[ERROR]         Error downloading file://C:\hapi-fhir-3.3.0\osgi\hapi-fhir-karaf
-features\target/classes/features.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :hapi-fhir

**Comment by Mobe91** [comment]
I am having the same issue with version 4.2.0 of the plugin on Windows 10.

**Comment by anthonys123** [comment]
If you don't need the Karaf functionality, comment out the Karaf references in the ALLMODULES profile section of the root POM.  I was able to complete the rest of the build successfully doing that.

**Comment by jamesagnew** [comment]
We were able to verify that HAPI currently doesn't build for us on Windows either.

I've disabled the Karaf Validation feature by default now, although it will still run on the CI server (or any other time the `DIST` profile is used).
