### ISSUE TITLE
dstu3 FhirInstanceValidator has depdency to fhir.r4 modules

### ISSUE THREAD

**Issue by sandrozbinden** [jamesagnew/hapi-fhir#922]
The class [org.hl7.fhir.dstu3.hapi.validation.FhirInstanceValidator](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-validation/src/main/java/org/hl7/fhir/dstu3/hapi/validation/FhirInstanceValidator.java) in the hapi-fhir-validation release 3.3.0 has package dependency to r4 classes.

Is this correct? 

```java
import org.hl7.fhir.r4.context.IWorkerContext;  
import org.hl7.fhir.r4.formats.IParser;
import org.hl7.fhir.r4.formats.ParserType;
import org.hl7.fhir.r4.terminologies.ValueSetExpander;
```

**Comment by jamesagnew** [comment]
This is correct, yes.

We use a single validation codebase (the R4) codebase to validate both DSTU3 and R4 content in order to increase maintainability.

This is causing an issue?
