### ISSUE TITLE
Add Homebrew installation option to documentation for CLI

### ISSUE THREAD

**Issue by johngrimes** [jamesagnew/hapi-fhir#926]
Following the successful merge of Homebrew/homebrew-core#26208, it is now possible to install `hapi-fhir-cli` on a Mac using the following command:

```
brew install hapi-fhir-cli
```

We should add this to the documentation, so that people know about it.

**Comment by jamesagnew** [comment]
Thanks John, this is awesome!

**Comment by jamesagnew** [comment]
BTW- The CLI docs have been added, and will be deployed in the next week or so when we release the new version of HAPI FHIR.
