### ISSUE TITLE
CLI tooling is needed for creating and maintaining ConceptMaps using CSVs.

### ISSUE THREAD

**Issue by dmuylwyk** [jamesagnew/hapi-fhir#927]
We need some form of CLI tooling that will accept a CSV of mappings and convert them to one or more `ConceptMap` resources/entities. It should be possible to create new mappings, update existing mappings, and logically delete retired mappings using this tool.

Additionally, we may also want to export `ConceptMap` resources as CSVs (to be confirmed by @jamesagnew).

**Comment by dmuylwyk** [comment]
See feature branch:

https://github.com/jamesagnew/hapi-fhir/tree/927-cli-tooling-is-needed-for-creating-and-maintaining-conceptmaps-using-csvs

**Comment by dmuylwyk** [comment]
See pull request:

#934

**Comment by dmuylwyk** [comment]
Done!

**Comment by armstrongdcosta** [comment]
Hey Guys, I was running hapi-fhir-cli, have started verion r4 on localhost:8080, Can I also run version dstu3 on the same port? If yes what is the command?

**Comment by dmuylwyk** [comment]
Hi, Armstrong.

If you'd like to start a server that supports DSTU3 _instead_ of R4, simply use `-v dstu3` instead of `-v r4`. If you've already started an R4 server, you'll want to shut it down and either remove the database or select a different directory for your DSTU3 server.

If you'd like to run both an R4 and a DSTU3 server at the same time, the endpoints will have to listen on different ports.

Note: please ask questions on our Google Group. [See here for details.](https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help)
