### ISSUE TITLE
IdDt.isLocal doesn't work correctly 0.7.1

### ISSUE THREAD

**Issue by akley** [jamesagnew/hapi-fhir#93]
If a resource is encoded as a contained reference in XML,'#' is set to the first position of th id. But IdDt.isLocal() check the ID part, not the compined string!
Example:
 [ResourceReferenceDt[reference=#Medication/499059CE-CDD4-48BC-9014-528A35D15CED/_history/1,loaded=true]]

Backround: BaseParser set the '#' in front of the whole IdDt, IdDt.isLocal() expects the '#' only on the id part. It seems that this is the problem.

BaseParser.containResourcesForEncoding(IResource theResource, IResource theTarget) @line 157: next.setReference("#" + resource.getId().getValue());

IdDt.isLocal() @line 309.
return myUnqualifiedId != null && myUnqualifiedId.isEmpty() == false && myUnqualifiedId.charAt(0) == '#';

**Comment by akley** [comment]
Sorry, #67 has been fixed the Problem.
Please retract the issue!

**Comment by jamesagnew** [comment]
Oops, I was offline for a few days and didn't even see that you had closed this. :)

Thanks for following up, glad it's resolved!
