### ISSUE TITLE
Apache Karaf :: Features build fails in master

### ISSUE THREAD

**Issue by anthonys123** [jamesagnew/hapi-fhir#931]
Maven build is failing with same error in both IntelliJ and Command Prompt.  Problem observed with master from 5/4/18:

[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.1.4:verify (validate) on project hapi-fhir: Unable to load features descriptors: Error:
[ERROR] Error downloading file://C:\temp\hapi-fhir-master\osgi\hapi-fhir-karaf-features\target/classes/features.xml

Refer to attached screenshot.
![karafbuildfailure](https://user-images.githubusercontent.com/15097189/39679385-abae23c8-516a-11e8-8f53-08fc0b09c77c.jpg)

**Comment by splatch** [comment]
I believe this one is already resolved, isn't it @anthonys123?

**Comment by jamesagnew** [comment]
This should be solved (confirmation would be appreciated). The Karaf-maven-plugin verify task seems to not play nicely on Windows. I've disabled it from running by default for now.

**Comment by anthonys123** [comment]
Many thanks James.  I'll confirm with master on Windows this Friday after I return from vacation.
