### ISSUE TITLE
Resource fails on PUT/CREATE when abatement is present

### ISSUE THREAD

**Issue by Kaninsokk** [jamesagnew/hapi-fhir#933]
Hi,

I'm having an issue when sending a resource to my server. I'm not a wiz with validation schematics, but seems that either resource definition are wrong or the structureDefinition xml has a bug. Hope you can help, James.

Here are the relevant lines of what I post:

`{
  "resourceType": "Condition",
  "clinicalStatus": "remission",
  "abatementDateTime": "2018-05-31T02:00:00+02:00"
}`

this results in:

`{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "[error] Condition @ /*:Condition[namespace-uri()='http://hl7.org/fhir'][1]; Test=not(f:abatementBoolean/@value=true() or (not(exists(f:abatementBoolean)) and exists(*[starts-with(local-name(.), 'abatement')])) or f:clinicalStatus/@value=('resolved', 'remission', 'inactive')); Message=con-4: If condition is abated, then clinicalStatus must be either inactive, resolved, or remission",
            "location": [
                "Condition @ /*:Condition[namespace-uri()='http://hl7.org/fhir'][1]"
            ]
        }
    ]
}`

**Comment by Kaninsokk** [comment]
No one having issue with sending abatementDate?

**Comment by jamesagnew** [comment]
Can you try this with the latest git master to confirm that it's still an
issue?

sent from my phone.

**Comment by Kaninsokk** [comment]
@jamesagnew actually it appears to have been taken care of. How nice! Do you have a release date on 3.4.0? Do you have any idea of cause? It worked when I referred to the github project from my .m2 folder, but when I switched to 3.3.0 it failed. I need to check later if it has anything to do with transitive dependencies, unless you know of some changes in that area.

// Thomas
