### ISSUE TITLE
validating a resource with a value="" attribute returns 'Failed to call access method'

### ISSUE THREAD

**Issue by patrick-werner** [jamesagnew/hapi-fhir#938]
When validating a resource containing a empty string value attribute: `<value value=""/> ` you get:
```xml
 <issue>
        <severity value="error"/>
        <code value="processing"/>
        <diagnostics value="Failed to call access method"/>
    </issue>
```
Which is very misleading.

**Comment by jamesagnew** [comment]
Any hints on how to trigger this? The test above passes.

..although note that I synced to the latest RI code literally yesterday, so it's possible this bug just got fixed upstream.

**Comment by patrick-werner** [comment]
i now discovered the source of the issue: it wasn't the empty value, it was a FHIRPath expression containing resolve() - wich isn't implemented yet.
