### ISSUE TITLE
XmlParser.parseBundle(String) fails for f:Bundle expects atom feed

### ISSUE THREAD

**Issue by ahenket** [jamesagnew/hapi-fhir#94]
<code>Bundle r = xmlp.parseBundle("&lt;Bundle xmlns='http://hl7.org/fhir'>"+
	    "&lt;id value='7829798d-ec94-456f-8d58-ab6adb54a7'/>" +
	    "&lt;type value='searchset'/>" +
	    "&lt;base value='http://example.org/fhir'/>" +
	    "&lt;total value='0'/>" +
	    "&lt;link>" +
	    "    &lt;relation value='self'/>" +
	    "    &lt;url value='http://example.org/fhir/Bundle/1234?search-offset=0&amp;_count=50'/>" +
	    "&lt;/link>" +
	    "&lt;/Bundle>");</code>

returns:
Exception in thread "main" ca.uhn.fhir.parser.DataFormatException: DataFormatException at [[row,col {unknown-source}]: [1,1]]: Expecting outer element called 'feed', found: Bundle

**Comment by wdebeau1** [comment]
This sounds suspiciously like the parser was created from a dstu1 FhirContext.
The default constructor for FhirContext will create a dstu1 context if the dstu structures are in your class path. There's a flavor of the constructor that takes an enum that lets you specify which version you really want.

**Comment by ahenket** [comment]
You were correct. Problem solved. Thanks
