### ISSUE TITLE
Instance Validator gives observation warnings

### ISSUE THREAD

**Issue by patrick-werner** [jamesagnew/hapi-fhir#942]
InstanceValidator throws various warnings in validateObservation, e.g.: "All observations should have a subject"

here:
https://github.com/jamesagnew/hapi-fhir/blob/23a01b5f18fc3d33aff39200fda459066d359b9f/hapi-fhir-validation/src/main/java/org/hl7/fhir/r4/validation/InstanceValidator.java#L3620-L3627

and here:
https://github.com/jamesagnew/hapi-fhir/blob/6468ca474a30a37b1747ea0cdb532fe680074bbf/hapi-fhir-validation/src/main/java/org/hl7/fhir/instance/validation/InstanceValidator.java#L1857-L1864

Looking at the FHIR spec these aren't mandatory and therefore we are confused why hapi is enforcing something out of spec.

**Comment by jamesagnew** [comment]
FWIW, these are "best practices" that are optional in InstanceValidator. As of the latest RI sync, these are no longer enabled by default.

We should probably have some documentation, and perhaps a link to what they actually refer to.

TBH I have no idea where (if at all) these best practices are documented

**Comment by patrick-werner** [comment]
Setting default to disable sounds good. I opened a GF Tracker item to add best practice documentation:
[GF 17147](https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=17147)
