### ISSUE TITLE
json parser of bundle creates incorrect logical id

### ISSUE THREAD

**Issue by brianreinhold** [jamesagnew/hapi-fhir#947]
Input logical id for resource M in JSON string is abcd
After the parse it becomes M/abcd

If one creates the Bundle using the HAPI FHIR API the generated JSON string has the logical id of resource M as just abcd.

But One cannot revert back to the original

**Comment by jamesagnew** [comment]
You can use `resource.getIdElement().getIdPart()` if you just want the logical id component of a resource ID. HAPI will always try to populate as many parts of the resource ID as it knows though as it's parsing (base URL, resource type, logical ID, version ID)

**Comment by jamesagnew** [comment]
Closing, please feel free to reopen if this did not work.
