### ISSUE TITLE
JsonParser.encodeResourceToString or XmlParser.parseResource ignores id

### ISSUE THREAD

**Issue by ahenket** [jamesagnew/hapi-fhir#95]
<code>IResource r = xmlp.parseResource("&lt;ValueSet xmlns='http://hl7.org/fhir'>&lt;id value='1234'/>&lt;/ValueSet>");</code>
<code>System.out.println(jsonp.encodeResourceToString(r));</code>

returns:
{"resourceType":"ValueSet"}

**Comment by jamesagnew** [comment]
Hi Alexander- You probably have your FhirContext in DSTU1 mode (which is the default at this point), and in DSTU1 the ID does not appear in the resource body.

Try it with the following context:
FhirContext ctx = FhirContext.forDev();

**Comment by ahenket** [comment]
I will do that. In the mean time Bill had pointed out that ditching the dstu structures jar helped too :-)
