### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.hl7.fhir.r4.utils.FHIRPathEngine$IEvaluationContext

### ISSUE THREAD

**Issue by ckan-user1** [jamesagnew/hapi-fhir#957]
Hello,
I am trying to run this validation code 
		 ctx.setParserErrorHandler(new StrictErrorHandler());
		 FhirValidator fhirValidator = ctx.newValidator();

		 FhirInstanceValidator fhirInstanceValidator = getFhirInstanceValidator();

		 fhirValidator.registerValidatorModule(fhirInstanceValidator);

		 ValidationResult validationResult = fhirValidator.validateWithResult(observation);

		 IGenericClient client = ctx.newRestfulGenericClient("http://localhost:8080/hapi/baseDstu3");
        Bundle resp = client.transaction().withBundle(bundle).execute();

// Log the response
        System.out.println(ctx.newXmlParser().setPrettyPrint(true).encodeResourceToString(resp));

    }

	private static FhirInstanceValidator getFhirInstanceValidator() {
		FhirInstanceValidator fhirInstanceValidator = null;

		StructureDefinition structureDefinition = getStructureDefinition();
		if (structureDefinition != null) {
			fhirInstanceValidator = new FhirInstanceValidator();
			fhirInstanceValidator.setStructureDefintion(structureDefinition);
		}
		return fhirInstanceValidator;
	}

	private static StructureDefinition getStructureDefinition() {
		FhirContext fhirContext = FhirContext.forDstu3();
		String profileText;
		try {
			String pathToProfile = "c:/profile/PoCObservationLength.xml";
			profileText = IOUtils.toString(new FileInputStream(pathToProfile), "UTF-8");
		} catch (IOException e) {
			return null;
		}
		return fhirContext.newXmlParser().parseResource(StructureDefinition.class, profileText);
	}

but I got this error  Caused by: java.lang.ClassNotFoundException: org.hl7.fhir.r4.utils.FHIRPathEngine$IEvaluationContext this

**Comment by jamesagnew** [comment]
Hi @ckan-user1, welcome to the HAPI FHIR project. Please see our FAQ for information on how to get help: http://hapifhir.io/hapi-fhir-faq.html#Getting_Help

With regards to this bug, do you have the class in question on your classpath? If not, please add it via the `hapi-fhir-structures-r4` JAR.
