### ISSUE TITLE
mvn validate fails on hapi-tinder-plugin:jar:0.9-SNAPSHOT

### ISSUE THREAD

**Issue by ahenket** [jamesagnew/hapi-fhir#96]
I cloned the full happy-api tree to disk and executed mvn validate on the base pom. This fails after many other downloads with:

[ERROR] Plugin ca.uhn.hapi.fhir:hapi-tinder-plugin:0.9-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact ca.uhn.hapi.fhir:hapi-tinder-plugin:jar:0.9-SNAPSHOT -> [Help 1]

How do I get around that?

**Comment by jamesagnew** [comment]
Have you tried an "mvn install" first? That HAPI build uses artifacts from
earlier modules in the later modules, so you actually probably can't
validate until you've built at least once.

Cheers,
James

**Comment by ahenket** [comment]
Made progress. Next hurdle is:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project hapi-fhir-structures-dstu: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process
[ERROR] java.lang.UnsupportedClassVersionError: javax/servlet/Servlet : Unsupported major.minor version 51.0

I'm running on Java 1.7.0 build 45

**Comment by jamesagnew** [comment]
Im thinking maven may be picking up an older java install?

What do you see if you do
mvn -v

-J

sent from my phone.

**Comment by ahenket** [comment]
Confusing... maven sees 1.6, but when I call java directly, it says 1.7 (I have 1.6, 1.7 and 1.8 installed)

mbp:hapi-fhir ahenket$ ~/Development/lib/apache-maven-3.2.5/bin/mvn -v
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T11:29:23-06:00)
Maven home: /Users/ahenket/Development/lib/apache-maven-3.2.5
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: nl_NL, platform encoding: MacRoman
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"
mbp:hapi-fhir ahenket$ java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

**Comment by wdebeau1** [comment]
Check your JAVA_HOME environment variable. Maven normally uses that to figure out which java it wants to run.

**Comment by ahenket** [comment]
It is empty on my machine. Can set it as java then fails to run. OSX has a different layout for Java. E.g. bin == Commands. So the error after setting it is:

mbp:loinc ahenket$ java -version
Unable to locate an executable at "/System/Library/Frameworks/JavaVM.framework/Versions/Current/bin/java" (-1)

**Comment by jamesagnew** [comment]
Boy that is weird.

It's probably worth trying to explicitly set JAVA_HOME and see if that
resolves it. I use the following:

export
JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home"

That path obviously may need to change depending on the specific version
(and I think /Library/Java/JavaVirtualMachines is only used by Oracle's
JDKs not the Apple ones) but something like that should do it.

Cheers,
James

**Comment by oliveregger** [comment]
thanks! I experienced the same error and with export the JAVA_HOME it works. another way to set in the terminal is

export JAVA_HOME=$(/usr/libexec/java_home)

and putting in .profile (see also http://www.mkyong.com/java/how-to-set-java_home-environment-variable-on-mac-os-x/)

**Comment by jamesagnew** [comment]
Closing this bug as it's been inactive for a while. Alexander, please feel free to reopen if you're still having this problem.
