### ISSUE TITLE
Practitioner specialty does not allow arbitrary CodeableConcept

### ISSUE THREAD

**Issue by jacksonjesse** [jamesagnew/hapi-fhir#98]
The API for Practitioner only allows a `BoundCodeableConceptDt<PractitionerSpecialtyEnum>` for each speciality. However, the schema allows for an arbitrary `CodeableConcept` to be used if your speciality doesn't fit into this list (which is very limited in this version of the spec).

http://hl7.org/implement/standards/FHIR-Develop/practitioner.html

The API should support adding of an arbitrary `CodeableConcept` in this slot.

**Comment by jacksonjesse** [comment]
The answer to #102 led me to understand that I was essentially reporting the same problem here. The solution for this one is similar, so apologies again for the misunderstanding. The solution is along the lines of:
```
practitioner.addSpecialty().getCodingFirstRep()
                .setDisplay("Custom speciality");
```

**Comment by steve1medix** [comment]
This seems to work in 0.9-SNAPSHOT:

practitioner.addSpecialty().addCoding().setSystem('urn:oid:2.16.840.1.113883.6.101').setCode('207Q00000X').setDisplay('Family Medicine')

**Comment by jacksonjesse** [comment]
Yep that definitely has the same effect, and probably a bit neater too :+1:
