### ISSUE TITLE
Composition: $document Operation

### ISSUE THREAD

**Issue by patrick-werner** [jamesagnew/hapi-fhir#982]
I just pushed the current state of my $document branch:
https://github.com/jamesagnew/hapi-fhir/commit/49bdff1862a58a52b4204442eafe450b7acf8ab1

Currently only in DSTU3 it is implemented properly.
I figured out how to return a Document Bundle instead of a SearchSet but i'm now stuck on writing the tests/ getting the Test to run: https://github.com/jamesagnew/hapi-fhir/blob/49bdff1862a58a52b4204442eafe450b7acf8ab1/hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/dstu3/CompositionDocumentDstu3Test.java#L103

I always end up with a 

> ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Exceeded maximum wait for connection: java.sql.SQLException: Cannot get a connection, pool error Timeout waiting for idle object

**Comment by jamesagnew** [comment]
Does this fail consistently, or just some of the time?

One thing to note, the tests randomize the size of the DB connection pool (size will be 1-4 iirc) just to make sure we don't have any processes that require more than one connection to complete (that's a recipe for deadlocks in production).

Actually, I guess re-reading what you wrote, you mean it happens consistently.

**Comment by jamesagnew** [comment]
Ok on more review, I'd be suspicious that this is a transaction boundary thing.

In [FhirResourceDaoCompositionDstu3.java](https://github.com/jamesagnew/hapi-fhir/blob/49bdff1862a58a52b4204442eafe450b7acf8ab1/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/dstu3/FhirResourceDaoCompositionDstu3.java) I think possibly you're loading the results outside of a transaction? What is the stack trace for that SQLException?
