### ISSUE TITLE
Travis & AppVeyor builds failing

### ISSUE THREAD

**Issue by patrick-werner** [jamesagnew/hapi-fhir#983]
Build is running without a problem locally.

**On travis the problem is:**
https://github.com/jamesagnew/hapi-fhir/blob/04f16294aa383176e9e331a0ddadfb8f44e5e52f/hapi-fhir-structures-dstu3/src/test/java/org/hl7/fhir/dstu3/hapi/rest/server/ServerCapabilityStatementProviderDstu3Test.java#L528

- [ ] setConformanceDate doesn't seem to work as the conformance statement returned always contains the live time/date instead of the set date

**Appveyor fails at:**
https://github.com/jamesagnew/hapi-fhir/blob/1ba00f6b11c0e71eda4cbd9f238584728f08c354/hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderInterceptorR4Test.java#L184

**Comment by jamesagnew** [comment]
Just looking into this now.

Man, I'm thrilled to have CI back to a state where failures are unexpected. :)
