### ISSUE TITLE
Pagination links should include the original resource type in the URL (or be configurable)

### ISSUE THREAD

**Issue by ohr** [jamesagnew/hapi-fhir#986]
I recently had the issue that pagination links created by HAPI are agnostic in terms of what type of resources have initially been queried. This is no problem as such, however, when you apply query authorization by resource type (based on the request URL), - e.g. when using OAuth2 with scopes reflecting these resource types - the agnostic paging links are not helpful at all.

I solved this locally by tweaking the paging URLs in the response using an IServerInterceptor (adding the resource type), and tweaking it back in the paging request using a Servlet Filter (removing the resource type again) and forwarding the modified request, so that normal processing can continue. This all works well, but it feels kind of "hacky"...

Is there are general need for paging links to contain the original resource type? Or should layout of paging links and their processing even be configurable? Comments welcome!

**Comment by jamesagnew** [comment]
In general the logic behind not providing that kind of thing in the URL (we did think about it) was that by FHIR's definition the URLs are supposed to be  opaque to the client.. so anything we added might become something that the client depended on and we couldn't change, which would be bad.

In your use case though, you don't need it to be non-opaque to the client, but rather to a different part of the server infrastructure. That seems reasonable to me.

I'd be opposed to making something like this be the default (I don't even really like the fact that the page number and size is a part of the URL but what can you do 😄 ) but certainly adding a callback hook wouldn't be a bad thing.

**Comment by ohr** [comment]
Well, it is still sort of transparent to the client - it's the server-side security infrastructure that usually depends on matching URLs to take authorization decisions... 
I could generalize this a bit, like having a strategy pattern that keeps the current behavior as default but leaves the choice to add your own implementation. Depending on a few "thumbs up" votes on this issue, though :-).
