### ISSUE TITLE
need help with getting the patient name in bundle

### ISSUE THREAD

**Issue by pnama** [jamesagnew/hapi-fhir#989]
hello, I'm also using org.hl7.fhir.r4.model now and trying to get the patient name but it's bundle type. So I'm trying to use the getEntry. But not sure how should I do after. I'm a beginner. If you could help me with getting the patient name, I'll be really appreciated. Providing codes would help a lot. I found example that might help you to understand what I'm trying to do... "http://hapifhir.io/doc_rest_client_examples.html" The bundle xml part(2nd one). Really really appreciate your hard work!

**Comment by patrick-werner** [comment]
Hi pnama,

Please use our Google Group to ask questions on how to use HAPI, the issue tracker is for reporting bugs and suggesting features.
https://groups.google.com/forum/#!forum/hapi-fhir

**Comment by pnama** [comment]
thank you so much!
