### ISSUE TITLE
Content type says xml ...

### ISSUE THREAD

**Issue by jkiddo** [jamesagnew/hapi-fhir#992]
By content says something else ...
![oh really](https://user-images.githubusercontent.com/211696/41154100-4b0d7c4e-6b19-11e8-89f2-b1baf8c6d1a7.PNG)

**Comment by patrick-werner** [comment]
can you provide the steps to reproduce the problem?

**Comment by jkiddo** [comment]
http://hapi.fhir.org/baseDstu3/Patient?_id=3991906 open that in a browser
