### ISSUE TITLE
Hapi-FHIR server is down

### ISSUE THREAD

**Issue by banivyom** [jamesagnew/hapi-fhir#998]
Server : http://fhirtest.uhn.ca/baseDstu2  ,   Is it the server or should I do something, because it was running last night and giving me errors today. If server is down then please fix that up asap.

**Comment by banivyom** [comment]
How long will it take for it start up again?

**Comment by jamesagnew** [comment]
The server is unreliable right now because the disk is almost full. Someone has uploaded a massive amount of data to it over the last few weeks.

I'm trying to get it under control right now.

**Comment by patrick-werner** [comment]
the server is up again.
